import { lazy, type ComponentType, type LazyExoticComponent } from 'react'


export interface ConceptEntry {
  id: string
  certId: string
  domain: number
  title: string
  description: string
  /** Loaded on demand: 309 figures must not ship in the initial chunk. */
  Component: LazyExoticComponent<ComponentType>
}

export const CONCEPTS: ConceptEntry[] = [
  {
    id: 'secplus-pki-lifecycle',
    certId: 'secplus',
    domain: 1,
    title: 'Certificate Lifecycle & Chain of Trust',
    description: 'Step through issuance, validation, deployment, and revocation (CRL vs OCSP).',
    Component: lazy(() => import('./secplus/PkiLifecycle')),
  },
  {
    id: 'secplus-cia-aaa-matrix',
    certId: 'secplus',
    domain: 1,
    title: 'CIA Triad × AAA Framework',
    description: 'Pick a CIA element and an AAA element to see how the two frameworks relate.',
    Component: lazy(() => import('./secplus/CiaAaaMatrix')),
  },
  {
    id: 'secplus-arp-spoofing',
    certId: 'secplus',
    domain: 2,
    title: 'ARP Spoofing & On-Path Attacks',
    description: 'Watch a poisoned ARP cache redirect a victim\'s traffic through an attacker.',
    Component: lazy(() => import('./secplus/ArpSpoofing')),
  },
  {
    id: 'secplus-social-engineering-ladder',
    certId: 'secplus',
    domain: 2,
    title: 'Social Engineering Ladder',
    description: 'Click a tier to see how sophistication and targeting escalate from mass phishing to BEC.',
    Component: lazy(() => import('./secplus/SocialEngineeringLadder')),
  },
  {
    id: 'secplus-malware-comparison-grid',
    certId: 'secplus',
    domain: 2,
    title: 'Malware Type Comparison',
    description: 'Pick a malware type to see its defining trait.',
    Component: lazy(() => import('./secplus/MalwareComparisonGrid')),
  },
  {
    id: 'secplus-dr-site-spectrum',
    certId: 'secplus',
    domain: 3,
    title: 'Disaster Recovery Site Spectrum',
    description: 'Slide across cold, pilot light, warm, hot, and multi-site tiers to compare RTO/RPO/cost.',
    Component: lazy(() => import('./secplus/DrSiteSpectrum')),
  },
  {
    id: 'secplus-zero-trust-diagram',
    certId: 'secplus',
    domain: 3,
    title: 'Zero Trust Architecture',
    description: 'Step through the shift from perimeter trust to per-request verification.',
    Component: lazy(() => import('./secplus/ZeroTrustDiagram')),
  },
  {
    id: 'secplus-order-of-volatility',
    certId: 'secplus',
    domain: 4,
    title: 'Order of Volatility',
    description: 'Click through evidence tiers from CPU cache to backups to see why collection order matters.',
    Component: lazy(() => import('./secplus/OrderOfVolatility')),
  },
  {
    id: 'secplus-log-source-siem-matrix',
    certId: 'secplus',
    domain: 4,
    title: 'Log Source Fit for SIEM Questions',
    description: 'Pick a security question and a log source to see how well they match.',
    Component: lazy(() => import('./secplus/LogSourceSiemMatrix')),
  },
  {
    id: 'secplus-ir-process-timeline',
    certId: 'secplus',
    domain: 4,
    title: 'Incident Response Process',
    description: 'Step through the six-stage incident response lifecycle.',
    Component: lazy(() => import('./secplus/IrProcessTimeline')),
  },
  {
    id: 'secplus-risk-calculator',
    certId: 'secplus',
    domain: 5,
    title: 'Quantitative Risk Calculator',
    description: 'Play with SLE/ARO/ALE inputs to see when a control is financially justified.',
    Component: lazy(() => import('./secplus/RiskCalculator')),
  },
  {
    id: 'secplus-risk-treatment-matrix',
    certId: 'secplus',
    domain: 5,
    title: 'Risk Treatment Matrix',
    description: 'Pick likelihood and impact to get the recommended risk treatment.',
    Component: lazy(() => import('./secplus/RiskTreatmentMatrix')),
  },
  {
    id: 'secplus-third-party-risk-spectrum',
    certId: 'secplus',
    domain: 5,
    title: 'Third-Party Risk Management Spectrum',
    description: 'Drag across the tiers to see how vendor oversight rigor trades off with cost.',
    Component: lazy(() => import('./secplus/ThirdPartyRiskSpectrum')),
  },
  {
    id: 'cysa-soc-alert-severity-ladder',
    certId: 'cysa',
    domain: 1,
    title: 'SOC Alert Severity Ladder',
    description: 'Click a severity tier to see its typical triage SLA and what drives an alert into that tier.',
    Component: lazy(() => import('./cysa/SocAlertSeverityLadder')),
  },
  {
    id: 'cysa-pyramid-of-pain',
    certId: 'cysa',
    domain: 1,
    title: 'The Pyramid of Pain',
    description: 'Click each indicator tier to see how costly it is for an attacker to change.',
    Component: lazy(() => import('./cysa/PyramidOfPain')),
  },
  {
    id: 'cysa-siem-rule-builder',
    certId: 'cysa',
    domain: 1,
    title: 'SIEM Correlation Rule Builder',
    description: 'Pick a logged condition and see whether it clears the bar for a correlation rule/alert.',
    Component: lazy(() => import('./cysa/SiemRuleBuilder')),
  },
  {
    id: 'cysa-vuln-scan-timeline',
    certId: 'cysa',
    domain: 2,
    title: 'Vulnerability Scanning Lifecycle',
    description: 'Step through a full scan-to-remediation cycle.',
    Component: lazy(() => import('./cysa/VulnScanTimeline')),
  },
  {
    id: 'cysa-cvss-calculator',
    certId: 'cysa',
    domain: 2,
    title: 'CVSS v3 Base Score Estimator',
    description: 'Adjust the four exploitability metrics to see how they drive an illustrative CVSS base score.',
    Component: lazy(() => import('./cysa/CvssCalculator')),
  },
  {
    id: 'cysa-patch-priority-matrix',
    certId: 'cysa',
    domain: 2,
    title: 'Patch Priority & SLA Matrix',
    description: 'Pick a vulnerability severity and an asset\'s exposure to get the recommended patch SLA.',
    Component: lazy(() => import('./cysa/PatchPriorityMatrix')),
  },
  {
    id: 'cysa-cyber-kill-chain',
    certId: 'cysa',
    domain: 3,
    title: 'Lockheed Martin Cyber Kill Chain',
    description: 'Step through the seven stages of an intrusion.',
    Component: lazy(() => import('./cysa/CyberKillChain')),
  },
  {
    id: 'cysa-nist-ir-lifecycle',
    certId: 'cysa',
    domain: 3,
    title: 'NIST SP 800-61 Incident Response Lifecycle',
    description: 'Step through the four phases of the NIST incident response lifecycle.',
    Component: lazy(() => import('./cysa/NistIrLifecycle')),
  },
  {
    id: 'cysa-containment-comparison',
    certId: 'cysa',
    domain: 3,
    title: 'Containment Strategy: Segment vs Shut Down',
    description: 'Two ways to contain a compromised host, and what each costs you.',
    Component: lazy(() => import('./cysa/ContainmentComparison')),
  },
  {
    id: 'cysa-report-severity-decision',
    certId: 'cysa',
    domain: 4,
    title: 'Who Needs to Know? Report Audience Selector',
    description: 'Pick the incident\'s scope and data sensitivity to see who the report should go to.',
    Component: lazy(() => import('./cysa/ReportSeverityDecision')),
  },
  {
    id: 'cysa-escalation-ladder',
    certId: 'cysa',
    domain: 4,
    title: 'Incident Escalation Ladder',
    description: 'Click a tier to see who owns it and how fast it must move.',
    Component: lazy(() => import('./cysa/EscalationLadder')),
  },
  {
    id: 'awssaa-iam-policy-evaluation',
    certId: 'awssaa',
    domain: 1,
    title: 'IAM Policy Evaluation Logic',
    description: 'Pick which explicit statements exist to see how IAM resolves the request.',
    Component: lazy(() => import('./awssaa/IamPolicyEvaluation')),
  },
  {
    id: 'awssaa-shared-responsibility-spectrum',
    certId: 'awssaa',
    domain: 1,
    title: 'Shared Responsibility Spectrum',
    description: 'Drag across service models to see the line move between what you manage and what AWS manages.',
    Component: lazy(() => import('./awssaa/SharedResponsibilitySpectrum')),
  },
  {
    id: 'awssaa-kms-key-comparison',
    certId: 'awssaa',
    domain: 1,
    title: 'AWS-Managed vs Customer-Managed KMS Keys',
    description: 'Compare the two key ownership models in AWS KMS.',
    Component: lazy(() => import('./awssaa/KmsKeyComparison')),
  },
  {
    id: 'awssaa-vpc-connectivity-scaling',
    certId: 'awssaa',
    domain: 2,
    title: 'VPC Peering vs Transit Gateway Scaling',
    description: 'Drag the VPC count slider to see peering connections grow quadratically vs Transit Gateway linearly.',
    Component: lazy(() => import('./awssaa/VpcConnectivityScaling')),
  },
  {
    id: 'awssaa-multi-az-vs-multi-region',
    certId: 'awssaa',
    domain: 2,
    title: 'Multi-AZ vs Multi-Region',
    description: 'Compare what each resilience pattern actually protects against.',
    Component: lazy(() => import('./awssaa/MultiAzVsMultiRegion')),
  },
  {
    id: 'awssaa-auto-scaling-timeline',
    certId: 'awssaa',
    domain: 2,
    title: 'Auto Scaling Group Timeline',
    description: 'Step through a scale-out and scale-in cycle.',
    Component: lazy(() => import('./awssaa/AutoScalingTimeline')),
  },
  {
    id: 'awssaa-storage-service-selector',
    certId: 'awssaa',
    domain: 3,
    title: 'AWS Storage Service Selector',
    description: 'Pick a workload to get the recommended storage service.',
    Component: lazy(() => import('./awssaa/StorageServiceSelector')),
  },
  {
    id: 'awssaa-database-selection-matrix',
    certId: 'awssaa',
    domain: 3,
    title: 'Database Selection Matrix',
    description: 'Pick a data-model need to get the recommended AWS database service.',
    Component: lazy(() => import('./awssaa/DatabaseSelectionMatrix')),
  },
  {
    id: 'awssaa-caching-decision-tree',
    certId: 'awssaa',
    domain: 3,
    title: 'Caching Service Decision Tree',
    description: 'Pick a caching need to get the recommended AWS service.',
    Component: lazy(() => import('./awssaa/CachingDecisionTree')),
  },
  {
    id: 'awssaa-purchase-option-spectrum',
    certId: 'awssaa',
    domain: 4,
    title: 'EC2 Purchase Option Spectrum',
    description: 'Slide across purchase options to see how discount, commitment, and interruption risk trade off.',
    Component: lazy(() => import('./awssaa/PurchaseOptionSpectrum')),
  },
  {
    id: 'awssaa-s3-storage-class-ladder',
    certId: 'awssaa',
    domain: 4,
    title: 'S3 Storage Class Ladder',
    description: 'Click a storage class to see its retrieval time and use case.',
    Component: lazy(() => import('./awssaa/S3StorageClassLadder')),
  },
  {
    id: 'awssaa-cost-calculator',
    certId: 'awssaa',
    domain: 4,
    title: 'On-Demand vs Committed Cost Calculator',
    description: 'Adjust usage and discount to compare On-Demand cost against a Savings Plan / Reserved Instance commitment.',
    Component: lazy(() => import('./awssaa/CostCalculator')),
  },
  {
    id: 'awsscs-guardduty-severity-ladder',
    certId: 'awsscs',
    domain: 1,
    title: 'GuardDuty Finding Severity Ladder',
    description: 'Click a severity tier to see example findings and the expected response urgency.',
    Component: lazy(() => import('./awsscs/GuardDutySeverityLadder')),
  },
  {
    id: 'awsscs-aws-ir-timeline',
    certId: 'awsscs',
    domain: 1,
    title: 'AWS Incident Response Lifecycle',
    description: 'Walk through an AWS-native incident from detection to lessons learned.',
    Component: lazy(() => import('./awsscs/AwsIrTimeline')),
  },
  {
    id: 'awsscs-cloudtrail-watch-config-comparison',
    certId: 'awsscs',
    domain: 2,
    title: 'CloudTrail vs CloudWatch vs AWS Config',
    description: 'Three different questions about your account, three different tools — pick a question to see which service answers it.',
    Component: lazy(() => import('./awsscs/CloudTrailWatchConfigComparison')),
  },
  {
    id: 'awsscs-log-pipeline-diagram',
    certId: 'awsscs',
    domain: 2,
    title: 'Anatomy of a Log & Alert Pipeline',
    description: 'From an API call to a security team alert.',
    Component: lazy(() => import('./awsscs/LogPipelineDiagram')),
  },
  {
    id: 'awsscs-sg-vs-nacl-comparison',
    certId: 'awsscs',
    domain: 3,
    title: 'Security Groups vs Network ACLs',
    description: 'Instance-level vs subnet-level filtering, and what "stateful" actually buys you.',
    Component: lazy(() => import('./awsscs/SgVsNaclComparison')),
  },
  {
    id: 'awsscs-vpc-endpoint-decision',
    certId: 'awsscs',
    domain: 3,
    title: 'Gateway vs Interface VPC Endpoint',
    description: 'Pick the service and where the request originates to find the right endpoint type.',
    Component: lazy(() => import('./awsscs/VpcEndpointDecision')),
  },
  {
    id: 'awsscs-waf-rule-flow',
    certId: 'awsscs',
    domain: 3,
    title: 'How a WAF Web ACL Evaluates a Request',
    description: 'Walk a request through Web ACL rule evaluation, in priority order.',
    Component: lazy(() => import('./awsscs/WafRuleFlow')),
  },
  {
    id: 'awsscs-cross-account-trust-evaluator',
    certId: 'awsscs',
    domain: 4,
    title: 'Cross-Account AssumeRole: Two Locks, Two Keys',
    description: 'sts:AssumeRole needs BOTH the role\'s trust policy and the caller\'s permission policy to agree.',
    Component: lazy(() => import('./awsscs/CrossAccountTrustEvaluator')),
  },
  {
    id: 'awsscs-permission-boundary-vs-scp',
    certId: 'awsscs',
    domain: 4,
    title: 'Permission Boundary vs Service Control Policy',
    description: 'Two different "guardrails" that both cap permissions without ever granting any.',
    Component: lazy(() => import('./awsscs/PermissionBoundaryVsScp')),
  },
  {
    id: 'awsscs-object-lock-modes',
    certId: 'awsscs',
    domain: 5,
    title: 'S3 Object Lock: Governance vs Compliance',
    description: 'Pick a retention mode and an actor, then try to delete a locked object to see who can override.',
    Component: lazy(() => import('./awsscs/ObjectLockModes')),
  },
  {
    id: 'awsscs-encryption-at-rest-comparison',
    certId: 'awsscs',
    domain: 5,
    title: 'S3 Server-Side Encryption: SSE-S3 vs SSE-KMS vs SSE-C',
    description: 'Same goal — encrypt at rest — but three very different key-management trade-offs.',
    Component: lazy(() => import('./awsscs/EncryptionAtRestComparison')),
  },
  {
    id: 'awsscs-scp-hierarchy-ladder',
    certId: 'awsscs',
    domain: 6,
    title: 'SCP Hierarchy: Scope Narrows, Restrictions Stack',
    description: 'Click a layer to see what it applies to — effective permission is the intersection of ALL of them.',
    Component: lazy(() => import('./awsscs/ScpHierarchyLadder')),
  },
  {
    id: 'awsscs-compliance-framework-mapping',
    certId: 'awsscs',
    domain: 6,
    title: 'Which Compliance Tool Do I Reach For?',
    description: 'Pick the requirement to find the AWS service built for it.',
    Component: lazy(() => import('./awsscs/ComplianceFrameworkMapping')),
  },
  {
    id: 'cissp-risk-management-timeline',
    certId: 'cissp',
    domain: 1,
    title: 'The Risk Management Lifecycle',
    description: 'Step through identifying, treating, and monitoring risk.',
    Component: lazy(() => import('./cissp/RiskManagementTimeline')),
  },
  {
    id: 'cissp-governance-comparison',
    certId: 'cissp',
    domain: 1,
    title: 'Policy vs Procedure',
    description: 'Compare two levels of the governance document hierarchy.',
    Component: lazy(() => import('./cissp/GovernanceComparison')),
  },
  {
    id: 'cissp-data-classification-ladder',
    certId: 'cissp',
    domain: 2,
    title: 'Data Classification Ladder',
    description: 'Click a tier to see how handling requirements escalate with classification.',
    Component: lazy(() => import('./cissp/DataClassificationLadder')),
  },
  {
    id: 'cissp-data-lifecycle-timeline',
    certId: 'cissp',
    domain: 2,
    title: 'The Data Lifecycle',
    description: 'Step through the controls that matter most at each stage.',
    Component: lazy(() => import('./cissp/DataLifecycleTimeline')),
  },
  {
    id: 'cissp-security-model-lattice',
    certId: 'cissp',
    domain: 3,
    title: 'Bell-LaPadula vs. Biba Access Rules',
    description: 'Pick a model, a clearance level, and an action to see whether the access rule allows or denies it.',
    Component: lazy(() => import('./cissp/SecurityModelLattice')),
  },
  {
    id: 'cissp-symmetric-vs-asymmetric-crypto',
    certId: 'cissp',
    domain: 3,
    title: 'Symmetric vs Asymmetric Cryptography',
    description: 'Compare the two fundamental encryption models.',
    Component: lazy(() => import('./cissp/SymmetricVsAsymmetricCrypto')),
  },
  {
    id: 'cissp-attack-mapping-ladder',
    certId: 'cissp',
    domain: 4,
    title: 'Network Attack Sophistication Ladder',
    description: 'Click a tier to see how complexity and impact escalate.',
    Component: lazy(() => import('./cissp/AttackMappingLadder')),
  },
  {
    id: 'cissp-secure-network-diagram',
    certId: 'cissp',
    domain: 4,
    title: 'Building a Segmented Network, Layer by Layer',
    description: 'Step through defense-in-depth network design.',
    Component: lazy(() => import('./cissp/SecureNetworkDiagram')),
  },
  {
    id: 'cissp-access-control-model-matrix',
    certId: 'cissp',
    domain: 5,
    title: 'Access Control Models',
    description: 'Pick a model to see who sets permissions and how it\'s used.',
    Component: lazy(() => import('./cissp/AccessControlModelMatrix')),
  },
  {
    id: 'cissp-sso-federation-timeline',
    certId: 'cissp',
    domain: 5,
    title: 'SSO via Federated Identity',
    description: 'Step through a SAML/OIDC single sign-on flow.',
    Component: lazy(() => import('./cissp/SsoFederationTimeline')),
  },
  {
    id: 'cissp-pen-test-timeline',
    certId: 'cissp',
    domain: 6,
    title: 'The Penetration Testing Process',
    description: 'Step through a full engagement from scoping to reporting.',
    Component: lazy(() => import('./cissp/PenTestTimeline')),
  },
  {
    id: 'cissp-audit-type-comparison',
    certId: 'cissp',
    domain: 6,
    title: 'Internal vs External Audit',
    description: 'Compare who performs each audit type and how much assurance it provides.',
    Component: lazy(() => import('./cissp/AuditTypeComparison')),
  },
  {
    id: 'cissp-ir-phase-ladder',
    certId: 'cissp',
    domain: 7,
    title: 'Incident Response Phases',
    description: 'Click a phase to see what happens and how time-critical it is.',
    Component: lazy(() => import('./cissp/IrPhaseLadder')),
  },
  {
    id: 'cissp-bcp-spectrum',
    certId: 'cissp',
    domain: 7,
    title: 'Business Continuity Test Maturity',
    description: 'Slide across BCP testing maturity to see how assurance, cost, and disruption trade off.',
    Component: lazy(() => import('./cissp/BcpSpectrum')),
  },
  {
    id: 'cissp-sdlc-timeline',
    certId: 'cissp',
    domain: 8,
    title: 'Secure SDLC',
    description: 'Step through security integrated at every phase of development.',
    Component: lazy(() => import('./cissp/SdlcTimeline')),
  },
  {
    id: 'cissp-owasp-10-ladder',
    certId: 'cissp',
    domain: 8,
    title: 'OWASP Top 10 (2021) — Leading Categories',
    description: 'Click a category to see how it manifests in real applications.',
    Component: lazy(() => import('./cissp/Owasp10Ladder')),
  },
  {
    id: 'aplus1-mobile-connectivity-comparison',
    certId: 'aplus1',
    domain: 1,
    title: 'Mobile Device Connectivity Trade-offs',
    description: 'Compare range, throughput, and power draw across the four short-range connection methods.',
    Component: lazy(() => import('./aplus1/MobileConnectivityComparison')),
  },
  {
    id: 'aplus1-fru-teardown-order',
    certId: 'aplus1',
    domain: 1,
    title: 'Laptop FRU Teardown Order',
    description: 'The field-replaceable-unit layers, outermost to innermost.',
    Component: lazy(() => import('./aplus1/FruTeardownOrder')),
  },
  {
    id: 'aplus1-cable-connector-comparison',
    certId: 'aplus1',
    domain: 2,
    title: 'Cable & Connector Comparison',
    description: 'Speed, distance, and connector type across the four media you\'ll be asked to pick between.',
    Component: lazy(() => import('./aplus1/CableConnectorComparison')),
  },
  {
    id: 'aplus1-wifi-standard-spectrum',
    certId: 'aplus1',
    domain: 2,
    title: '802.11 Wi-Fi Standard Spectrum',
    description: 'Slide across the standards to see how speed, frequency, and range trade off as Wi-Fi evolved.',
    Component: lazy(() => import('./aplus1/WifiStandardSpectrum')),
  },
  {
    id: 'aplus1-ports-protocols-matcher',
    certId: 'aplus1',
    domain: 2,
    title: 'Common Ports & Protocols Matcher',
    description: 'Pick a port number, then pick the protocol you think it maps to.',
    Component: lazy(() => import('./aplus1/PortsProtocolsMatcher')),
  },
  {
    id: 'aplus1-ram-compatibility-ladder',
    certId: 'aplus1',
    domain: 3,
    title: 'RAM Generation Compatibility Ladder',
    description: 'Click each generation to see why it\'s physically and electrically incompatible with the others.',
    Component: lazy(() => import('./aplus1/RamCompatibilityLadder')),
  },
  {
    id: 'aplus1-psu-wattage-calculator',
    certId: 'aplus1',
    domain: 3,
    title: 'PSU Wattage Calculator',
    description: 'Sum component draw against the PSU\'s rating to see if there\'s enough headroom.',
    Component: lazy(() => import('./aplus1/PsuWattageCalculator')),
  },
  {
    id: 'aplus1-raid-level-comparison',
    certId: 'aplus1',
    domain: 3,
    title: 'RAID 0 / 1 / 5 / 10 Comparison',
    description: 'Four identical drives, one shared size slider: see how striping, mirroring, and parity change usable capacity and fault tolerance.',
    Component: lazy(() => import('./aplus1/RaidLevelComparison')),
  },
  {
    id: 'aplus1-hypervisor-type-comparison',
    certId: 'aplus1',
    domain: 4,
    title: 'Type 1 vs Type 2 Hypervisors',
    description: 'Bare-metal vs hosted virtualization, stacked to show what sits between the VM and the hardware.',
    Component: lazy(() => import('./aplus1/HypervisorTypeComparison')),
  },
  {
    id: 'aplus1-cloud-service-responsibility-spectrum',
    certId: 'aplus1',
    domain: 4,
    title: 'IaaS / PaaS / SaaS Responsibility Spectrum',
    description: 'Drag across the service models to see the line move between what you manage and what the provider manages.',
    Component: lazy(() => import('./aplus1/CloudServiceResponsibilitySpectrum')),
  },
  {
    id: 'aplus1-troubleshooting-methodology',
    certId: 'aplus1',
    domain: 5,
    title: 'The CompTIA Troubleshooting Methodology',
    description: 'Step through the six-step process (also tested on Core 2) with a worked example at each stage.',
    Component: lazy(() => import('./aplus1/TroubleshootingMethodology')),
  },
  {
    id: 'aplus1-post-boot-troubleshooting-flow',
    certId: 'aplus1',
    domain: 5,
    title: 'POST / Boot Failure Troubleshooting Flow',
    description: 'Step through the boot sequence to see where a failure points you.',
    Component: lazy(() => import('./aplus1/PostBootTroubleshootingFlow')),
  },
  {
    id: 'aplus1-print-troubleshooting',
    certId: 'aplus1',
    domain: 5,
    title: 'Print Troubleshooting: Symptom to Cause',
    description: 'Click a symptom to see its most likely cause and the fix to try first.',
    Component: lazy(() => import('./aplus1/PrintTroubleshooting')),
  },
  {
    id: 'aplus2-windows-edition-picker',
    certId: 'aplus2',
    domain: 1,
    title: 'Windows Edition Feature Picker',
    description: 'Pick an edition and a feature to see whether it\'s unlocked.',
    Component: lazy(() => import('./aplus2/WindowsEditionPicker')),
  },
  {
    id: 'aplus2-file-system-comparison',
    certId: 'aplus2',
    domain: 1,
    title: 'File System Comparison',
    description: 'Pick two file systems to compare side by side.',
    Component: lazy(() => import('./aplus2/FileSystemComparison')),
  },
  {
    id: 'aplus2-boot-sequence-timeline',
    certId: 'aplus2',
    domain: 1,
    title: 'OS Boot Sequence Timeline',
    description: 'Walk through POST → bootloader → kernel → login.',
    Component: lazy(() => import('./aplus2/BootSequenceTimeline')),
  },
  {
    id: 'aplus2-social-engineering-picker',
    certId: 'aplus2',
    domain: 2,
    title: 'Social-Engineering Red-Flag Picker',
    description: 'Pick the channel and the attacker\'s technique to see the verdict.',
    Component: lazy(() => import('./aplus2/SocialEngineeringPicker')),
  },
  {
    id: 'aplus2-malware-severity-ladder',
    certId: 'aplus2',
    domain: 2,
    title: 'Malware Severity & Stealth Ladder',
    description: 'Click a tier to see how disruptive and how hidden each malware type tends to be.',
    Component: lazy(() => import('./aplus2/MalwareSeverityLadder')),
  },
  {
    id: 'aplus2-permission-calculator',
    certId: 'aplus2',
    domain: 2,
    title: 'NTFS vs Share Permission Calculator',
    description: 'Combine an NTFS permission with a share permission to find the effective access.',
    Component: lazy(() => import('./aplus2/PermissionCalculator')),
  },
  {
    id: 'aplus2-bsod-decision-tree',
    certId: 'aplus2',
    domain: 3,
    title: 'BSOD / Boot Error Decision Tree',
    description: 'Pick the symptom and when it happens to get the likely cause and fix path.',
    Component: lazy(() => import('./aplus2/BsodDecisionTree')),
  },
  {
    id: 'aplus2-mobile-troubleshooting-spectrum',
    certId: 'aplus2',
    domain: 3,
    title: 'Mobile App Troubleshooting Spectrum',
    description: 'Drag across common mobile OS symptoms to see the likely cause and fix.',
    Component: lazy(() => import('./aplus2/MobileTroubleshootingSpectrum')),
  },
  {
    id: 'aplus2-browser-hardening-walkthrough',
    certId: 'aplus2',
    domain: 3,
    title: 'Browser Hardening Walkthrough',
    description: 'Step through certificate warnings, extensions, pop-ups, and proxy settings.',
    Component: lazy(() => import('./aplus2/BrowserHardeningWalkthrough')),
  },
  {
    id: 'aplus2-change-management-timeline',
    certId: 'aplus2',
    domain: 4,
    title: 'Change Management Process',
    description: 'Step through the documented process every IT change should follow.',
    Component: lazy(() => import('./aplus2/ChangeManagementTimeline')),
  },
  {
    id: 'aplus2-documentation-lifecycle',
    certId: 'aplus2',
    domain: 4,
    title: 'IT Documentation Types',
    description: 'Click each document type to see what it captures and why it\'s maintained.',
    Component: lazy(() => import('./aplus2/DocumentationLifecycle')),
  },
  {
    id: 'aplus2-esd-safety-matrix',
    certId: 'aplus2',
    domain: 4,
    title: 'ESD & Component Safety',
    description: 'Pick a component and a precaution to see whether the handling is safe.',
    Component: lazy(() => import('./aplus2/EsdSafetyMatrix')),
  },
  {
    id: 'netplus-subnet-visualizer',
    certId: 'netplus',
    domain: 1,
    title: 'CIDR / Subnetting Visualizer',
    description: 'Enter a network address and drag the prefix length to see the mask, range, and host count live.',
    Component: lazy(() => import('./netplus/SubnetVisualizer')),
  },
  {
    id: 'netplus-osi-stack',
    certId: 'netplus',
    domain: 1,
    title: 'The OSI 7-Layer Model',
    description: 'Click any layer to see its PDU, protocols, and role in getting data across a network.',
    Component: lazy(() => import('./netplus/OsiStack')),
  },
  {
    id: 'netplus-tcp-vs-udp',
    certId: 'netplus',
    domain: 1,
    title: 'TCP vs. UDP',
    description: 'The two transport-layer protocols, and what happens to each when a segment goes missing.',
    Component: lazy(() => import('./netplus/TcpVsUdp')),
  },
  {
    id: 'netplus-switching-vs-routing',
    certId: 'netplus',
    domain: 2,
    title: 'Switching vs Routing',
    description: 'Compare how a Layer 2 switch and a Layer 3 router each decide where to forward traffic.',
    Component: lazy(() => import('./netplus/SwitchingVsRouting')),
  },
  {
    id: 'netplus-vlan-segmentation',
    certId: 'netplus',
    domain: 2,
    title: 'VLAN Segmentation',
    description: 'See how 802.1Q tagging splits one physical switch into isolated broadcast domains.',
    Component: lazy(() => import('./netplus/VlanSegmentation')),
  },
  {
    id: 'netplus-ap-channel-overlap-spectrum',
    certId: 'netplus',
    domain: 2,
    title: '2.4 GHz Channel Overlap',
    description: 'Slide across channel plans to see how spacing affects interference and throughput.',
    Component: lazy(() => import('./netplus/ApChannelOverlapSpectrum')),
  },
  {
    id: 'netplus-snmp-monitoring-flow',
    certId: 'netplus',
    domain: 3,
    title: 'SNMP Monitoring Flow',
    description: 'Step through polling, setting, and unsolicited traps.',
    Component: lazy(() => import('./netplus/SnmpMonitoringFlow')),
  },
  {
    id: 'netplus-backup-type-spectrum',
    certId: 'netplus',
    domain: 3,
    title: 'Backup Type Spectrum',
    description: 'Slide across backup types to see how each trades backup time, restore time, and storage.',
    Component: lazy(() => import('./netplus/BackupTypeSpectrum')),
  },
  {
    id: 'netplus-firewall-acl-evaluator',
    certId: 'netplus',
    domain: 4,
    title: 'Firewall ACL Evaluator',
    description: 'Pick a destination port and a rule set to see how top-down evaluation decides the outcome.',
    Component: lazy(() => import('./netplus/FirewallAclEvaluator')),
  },
  {
    id: 'netplus-vpn-tunnel-comparison',
    certId: 'netplus',
    domain: 4,
    title: 'VPN Tunnel Comparison',
    description: 'Contrast an always-on site-to-site tunnel with an on-demand client-to-site connection.',
    Component: lazy(() => import('./netplus/VpnTunnelComparison')),
  },
  {
    id: 'netplus-troubleshooting-methodology-timeline',
    certId: 'netplus',
    domain: 5,
    title: 'Network Troubleshooting Methodology',
    description: 'Step through CompTIA\'s seven-stage troubleshooting process.',
    Component: lazy(() => import('./netplus/TroubleshootingMethodologyTimeline')),
  },
  {
    id: 'netplus-cable-fault-decision-tree',
    certId: 'netplus',
    domain: 5,
    title: 'Cable Fault Decision Tree',
    description: 'Pick a symptom and a cable type to see the most likely root cause.',
    Component: lazy(() => import('./netplus/CableFaultDecisionTree')),
  },
  {
    id: 'netplus-db-loss-calculator',
    certId: 'netplus',
    domain: 5,
    title: 'Fiber Link Loss Calculator',
    description: 'Adjust fiber run length and connector/splice counts to estimate total loss against a link budget.',
    Component: lazy(() => import('./netplus/DbLossCalculator')),
  },
  {
    id: 'aplus1-laptop-battery-runtime-calculator',
    certId: 'aplus1',
    domain: 1,
    title: 'Laptop Battery Runtime Calculator',
    description: 'adjust battery capacity and power draw to see how estimated runtime responds.',
    Component: lazy(() => import('./aplus1/LaptopBatteryCalculator')),
  },
  {
    id: 'aplus1-laptop-display-panel-technologies',
    certId: 'aplus1',
    domain: 1,
    title: 'Laptop Display Panel Technologies',
    description: 'slide across panel types to see how viewing angle, color accuracy, and black level trade off.',
    Component: lazy(() => import('./aplus1/LaptopDisplayTechnologies')),
  },
  {
    id: 'aplus1-mobile-device-accessories',
    certId: 'aplus1',
    domain: 1,
    title: 'Mobile Device Accessories',
    description: 'click a card to flip between the accessory and what it\'s actually for.',
    Component: lazy(() => import('./aplus1/MobileAccessoriesMatcher')),
  },
  {
    id: 'aplus1-mobile-device-synchronization',
    certId: 'aplus1',
    domain: 1,
    title: 'Mobile Device Synchronization',
    description: 'pick a sync method and device environment to see the recommended approach.',
    Component: lazy(() => import('./aplus1/MobileSyncDecision')),
  },
  {
    id: 'aplus1-a-packet-s-journey-out-of-a-soho-network',
    certId: 'aplus1',
    domain: 2,
    title: 'A Packet\'s Journey Out of a SOHO Network',
    description: 'watch the token trace a request from a laptop out to the Internet.',
    Component: lazy(() => import('./aplus1/PacketJourneyThroughSoho')),
  },
  {
    id: 'aplus1-common-networking-hardware',
    certId: 'aplus1',
    domain: 2,
    title: 'Common Networking Hardware',
    description: 'click a card to flip between the device and what it actually does on the network.',
    Component: lazy(() => import('./aplus1/NetworkHardwareMatcher')),
  },
  {
    id: 'aplus1-dhcp-lease-process-dora',
    certId: 'aplus1',
    domain: 2,
    title: 'DHCP Lease Process (DORA)',
    description: 'step through how a client obtains an IP address automatically.',
    Component: lazy(() => import('./aplus1/DhcpLeaseProcess')),
  },
  {
    id: 'aplus1-internet-connection-types-ranked',
    certId: 'aplus1',
    domain: 2,
    title: 'Internet Connection Types, Ranked',
    description: 'click a connection type to compare typical speed, latency, and use case.',
    Component: lazy(() => import('./aplus1/InternetConnectionTypesRanking')),
  },
  {
    id: 'aplus1-network-type-spectrum',
    certId: 'aplus1',
    domain: 2,
    title: 'Network Type Spectrum',
    description: 'slide from the smallest to the largest network scope to compare range and typical technology.',
    Component: lazy(() => import('./aplus1/NetworkTypeSpectrum')),
  },
  {
    id: 'aplus1-soho-router-hardening',
    certId: 'aplus1',
    domain: 2,
    title: 'SOHO Router Hardening',
    description: 'toggle between an out-of-the-box configuration and a hardened one.',
    Component: lazy(() => import('./aplus1/SohoRouterHardening')),
  },
  {
    id: 'aplus1-cpu-socket-compatibility',
    certId: 'aplus1',
    domain: 3,
    title: 'CPU Socket Compatibility',
    description: 'pick a CPU brand and a motherboard socket to see whether they physically match.',
    Component: lazy(() => import('./aplus1/CpuSocketCompatibility')),
  },
  {
    id: 'aplus1-custom-pc-build-gaming-vs-cad-workstation',
    certId: 'aplus1',
    domain: 3,
    title: 'Custom PC Build: Gaming vs. CAD/Workstation',
    description: 'click a spec category to see how a custom build\'s priorities shift between the two scenarios.',
    Component: lazy(() => import('./aplus1/CustomPcBuildAdvisor')),
  },
  {
    id: 'aplus1-expansion-add-on-card-types',
    certId: 'aplus1',
    domain: 3,
    title: 'Expansion / Add-On Card Types',
    description: 'click a card to flip between the add-on card and the job it does.',
    Component: lazy(() => import('./aplus1/ExpansionCardMatcher')),
  },
  {
    id: 'aplus1-motherboard-component-layout',
    certId: 'aplus1',
    domain: 3,
    title: 'Motherboard Component Layout',
    description: 'step through the major zones of a typical ATX motherboard.',
    Component: lazy(() => import('./aplus1/MotherboardComponentDiagram')),
  },
  {
    id: 'aplus1-multifunction-device-setup-order',
    certId: 'aplus1',
    domain: 3,
    title: 'Multifunction Device Setup Order',
    description: 'use the arrows to put these deployment steps in order, then check your work.',
    Component: lazy(() => import('./aplus1/MultifunctionDeviceSetupOrder')),
  },
  {
    id: 'aplus1-storage-device-speed-tiers',
    certId: 'aplus1',
    domain: 3,
    title: 'Storage Device Speed Tiers',
    description: 'click a drive type to compare interface, sequential speed, and typical use case.',
    Component: lazy(() => import('./aplus1/StorageDeviceSpeedTiers')),
  },
  {
    id: 'aplus1-cloud-deployment-model-spectrum',
    certId: 'aplus1',
    domain: 4,
    title: 'Cloud Deployment Model Spectrum',
    description: 'slide from private to public to see how ownership, control, and cost predictability trade off.',
    Component: lazy(() => import('./aplus1/CloudDeploymentModelSpectrum')),
  },
  {
    id: 'aplus1-vdi-session-flow',
    certId: 'aplus1',
    domain: 4,
    title: 'VDI Session Flow',
    description: 'watch a virtual desktop infrastructure session travel from endpoint to host and back.',
    Component: lazy(() => import('./aplus1/VdiSessionFlow')),
  },
  {
    id: 'aplus1-virtual-switch-mode-picker',
    certId: 'aplus1',
    domain: 4,
    title: 'Virtual Switch Mode Picker',
    description: 'answer two questions about a VM\'s networking needs to see which virtual switch mode fits.',
    Component: lazy(() => import('./aplus1/VirtualNetworkModePicker')),
  },
  {
    id: 'aplus1-vm-resource-sizing-calculator',
    certId: 'aplus1',
    domain: 4,
    title: 'VM Resource Sizing Calculator',
    description: 'adjust host capacity and guest requirements to see whether the host can actually support the planned VMs.',
    Component: lazy(() => import('./aplus1/VmResourceSizingCalculator')),
  },
  {
    id: 'aplus1-component-swap-test-order',
    certId: 'aplus1',
    domain: 5,
    title: 'Component Swap-Test Order',
    description: 'for an unstable, no-POST, or randomly rebooting system, work from cheapest/fastest test down to most invasive.',
    Component: lazy(() => import('./aplus1/ComponentSwapTestOrder')),
  },
  {
    id: 'aplus1-display-signal-path',
    certId: 'aplus1',
    domain: 5,
    title: 'Display Signal Path',
    description: 'step through the video signal chain to see which symptom points to which stage.',
    Component: lazy(() => import('./aplus1/DisplaySignalPathDiagram')),
  },
  {
    id: 'aplus1-mobile-device-won-t-power-on-troubleshooting-order',
    certId: 'aplus1',
    domain: 5,
    title: 'Mobile Device Won\'t Power On — Troubleshooting Order',
    description: 'use the arrows to put these steps in the right order, least invasive first, then check.',
    Component: lazy(() => import('./aplus1/MobileDevicePowerTroubleshootingOrder')),
  },
  {
    id: 'aplus1-storage-and-raid-failure-symptom-matcher',
    certId: 'aplus1',
    domain: 5,
    title: 'Storage & RAID Failure Symptom Matcher',
    description: 'click a symptom card to reveal its likely cause and the right first response.',
    Component: lazy(() => import('./aplus1/StorageRaidFailureMatcher')),
  },
  {
    id: 'aplus1-wired-connectivity-troubleshooting',
    certId: 'aplus1',
    domain: 5,
    title: 'Wired Connectivity Troubleshooting',
    description: 'step through diagnosing a "no network" wired connection from the cable outward.',
    Component: lazy(() => import('./aplus1/WiredConnectivityTroubleshootingTimeline')),
  },
  {
    id: 'aplus1-wireless-connectivity-before-after',
    certId: 'aplus1',
    domain: 5,
    title: 'Wireless Connectivity: Before / After',
    description: 'toggle between a misconfigured access point and the same AP after standard troubleshooting fixes.',
    Component: lazy(() => import('./aplus1/WirelessConnectivityBeforeAfter')),
  },
  {
    id: 'aplus2-control-panel-applet-router',
    certId: 'aplus2',
    domain: 1,
    title: 'Control Panel Applet Router',
    description: 'pick a symptom, then pick the applet that fixes it.',
    Component: lazy(() => import('./aplus2/ControlPanelAppletRouter')),
  },
  {
    id: 'aplus2-linux-disk-full-troubleshooting-sequence',
    certId: 'aplus2',
    domain: 1,
    title: 'Linux Disk-Full Troubleshooting Sequence',
    description: 'a Linux workstation is nearly out of disk space. Use the arrows to put these commands in the order you\'d actually run them, then check.',
    Component: lazy(() => import('./aplus2/LinuxCommandSequence')),
  },
  {
    id: 'aplus2-mac-os-tool-spectrum',
    certId: 'aplus2',
    domain: 1,
    title: 'macOS Tool Spectrum',
    description: 'slide across core macOS features to see what each one is for.',
    Component: lazy(() => import('./aplus2/MacOsToolSpectrum')),
  },
  {
    id: 'aplus2-mbr-vs-gpt-partition-styles',
    certId: 'aplus2',
    domain: 1,
    title: 'MBR vs GPT Partition Styles',
    description: 'pick a scenario to see which partition table style Disk Management should use.',
    Component: lazy(() => import('./aplus2/DiskPartitionStyleComparison')),
  },
  {
    id: 'aplus2-windows-command-line-tool-matcher',
    certId: 'aplus2',
    domain: 1,
    title: 'Windows Command-Line Tool Matcher',
    description: 'click a command to flip it and reveal what it actually does.',
    Component: lazy(() => import('./aplus2/WindowsCliToolMatcher')),
  },
  {
    id: 'aplus2-workgroup-to-domain-join',
    certId: 'aplus2',
    domain: 1,
    title: 'Workgroup to Domain Join',
    description: 'watch a workstation move from a local workgroup into an Active Directory domain.',
    Component: lazy(() => import('./aplus2/DomainJoinFlow')),
  },
  {
    id: 'aplus2-authentication-method-matcher',
    certId: 'aplus2',
    domain: 2,
    title: 'Authentication Method Matcher',
    description: 'click a term to flip it and reveal what it actually authenticates with.',
    Component: lazy(() => import('./aplus2/AuthenticationMethodMatcher')),
  },
  {
    id: 'aplus2-data-destruction-and-disposal-workflow',
    certId: 'aplus2',
    domain: 2,
    title: 'Data Destruction & Disposal Workflow',
    description: 'walk through choosing and documenting the right disposal method for a drive.',
    Component: lazy(() => import('./aplus2/DataDestructionTimeline')),
  },
  {
    id: 'aplus2-lost-mobile-device-response',
    certId: 'aplus2',
    domain: 2,
    title: 'Lost Mobile Device Response',
    description: 'watch the response escalate from a screen lock to a full remote wipe.',
    Component: lazy(() => import('./aplus2/MobileDeviceSecurityFlow')),
  },
  {
    id: 'aplus2-physical-security-control-ladder',
    certId: 'aplus2',
    domain: 2,
    title: 'Physical Security Control Ladder',
    description: 'click a control to see how strong a physical barrier it really is.',
    Component: lazy(() => import('./aplus2/PhysicalSecurityLayers')),
  },
  {
    id: 'aplus2-workstation-hardening-before-after',
    certId: 'aplus2',
    domain: 2,
    title: 'Workstation Hardening: Before / After',
    description: 'toggle to see an unhardened workstation next to one configured with security best practices.',
    Component: lazy(() => import('./aplus2/WindowsSecurityHardeningToggle')),
  },
  {
    id: 'aplus2-workstation-port-exposure-calculator',
    certId: 'aplus2',
    domain: 2,
    title: 'Workstation Port Exposure Calculator',
    description: 'adjust firewall and port settings to see how workstation exposure changes.',
    Component: lazy(() => import('./aplus2/PortSecurityRiskCalculator')),
  },
  {
    id: 'aplus2-application-crash-and-slow-performance-triage',
    certId: 'aplus2',
    domain: 3,
    title: 'Application Crash & Slow Performance Triage',
    description: 'pick the symptom and when it happens to get the likely cause and fix path.',
    Component: lazy(() => import('./aplus2/ApplicationCrashDecisionMatrix')),
  },
  {
    id: 'aplus2-best-practice-malware-removal-process',
    certId: 'aplus2',
    domain: 3,
    title: 'Best Practice Malware Removal Process',
    description: 'step through CompTIA\'s 7-step malware removal procedure in order.',
    Component: lazy(() => import('./aplus2/MalwareRemovalProcess')),
  },
  {
    id: 'aplus2-general-troubleshooting-methodology',
    certId: 'aplus2',
    domain: 3,
    title: 'General Troubleshooting Methodology',
    description: 'use the arrows to put CompTIA\'s six troubleshooting steps in the correct order, then check.',
    Component: lazy(() => import('./aplus2/TroubleshootingMethodologySequence')),
  },
  {
    id: 'aplus2-mobile-security-symptom-spectrum',
    certId: 'aplus2',
    domain: 3,
    title: 'Mobile Security Symptom Spectrum',
    description: 'drag across mobile security symptoms to see how private and how obvious each one is.',
    Component: lazy(() => import('./aplus2/MobileSecuritySymptomSpectrum')),
  },
  {
    id: 'aplus2-pc-security-symptom-matcher',
    certId: 'aplus2',
    domain: 3,
    title: 'PC Security Symptom Matcher',
    description: 'click a symptom to reveal the likely security issue and next step.',
    Component: lazy(() => import('./aplus2/PcSecuritySymptomMatcher')),
  },
  {
    id: 'aplus2-windows-update-failure-resolution-path',
    certId: 'aplus2',
    domain: 3,
    title: 'Windows Update Failure Resolution Path',
    description: 'watch the token move through the escalating fix path for a failed Windows Update.',
    Component: lazy(() => import('./aplus2/WindowsUpdateFailureFlow')),
  },
  {
    id: 'aplus2-backup-strategy-storage-calculator',
    certId: 'aplus2',
    domain: 4,
    title: 'Backup Strategy Storage Calculator',
    description: 'adjust data size, daily change rate, and retention to compare full, incremental, and differential backup storage.',
    Component: lazy(() => import('./aplus2/BackupRecoveryCalculator')),
  },
  {
    id: 'aplus2-customer-communication-and-professionalism',
    certId: 'aplus2',
    domain: 4,
    title: 'Customer Communication & Professionalism',
    description: 'toggle to compare an unprofessional response with a professional one for the same scenario.',
    Component: lazy(() => import('./aplus2/CustomerCommunicationToggle')),
  },
  {
    id: 'aplus2-incident-response-and-chain-of-custody',
    certId: 'aplus2',
    domain: 4,
    title: 'Incident Response & Chain of Custody',
    description: 'use the arrows to order the first-response steps for handling prohibited content or activity, then check.',
    Component: lazy(() => import('./aplus2/IncidentResponseSequence')),
  },
  {
    id: 'aplus2-remote-access-technology-ladder',
    certId: 'aplus2',
    domain: 4,
    title: 'Remote Access Technology Ladder',
    description: 'click a tier to compare remote access technologies from simple screen sharing to a full network tunnel.',
    Component: lazy(() => import('./aplus2/RemoteAccessLadder')),
  },
  {
    id: 'aplus2-scripting-basics-windows-native-vs-cross-platform',
    certId: 'aplus2',
    domain: 4,
    title: 'Scripting Basics: Windows-Native vs Cross-Platform',
    description: 'compare the two broad scripting families a technician runs into.',
    Component: lazy(() => import('./aplus2/ScriptingLanguageComparison')),
  },
  {
    id: 'aplus2-server-room-environmental-controls',
    certId: 'aplus2',
    domain: 4,
    title: 'Server Room Environmental Controls',
    description: 'step through the environmental controls that protect an equipment room.',
    Component: lazy(() => import('./aplus2/EnvironmentalControlsDiagram')),
  },
  {
    id: 'netplus-ipv4-vs-ipv6-addressing',
    certId: 'netplus',
    domain: 1,
    title: 'IPv4 vs IPv6 Addressing',
    description: 'compare how the two addressing schemes represent, resolve, and conserve addresses.',
    Component: lazy(() => import('./netplus/Ipv4VsIpv6Addressing')),
  },
  {
    id: 'netplus-network-topology-types',
    certId: 'netplus',
    domain: 1,
    title: 'Network Topology Types',
    description: 'step through physical topologies to see how devices are wired together and what each buys you.',
    Component: lazy(() => import('./netplus/NetworkTopologyDiagram')),
  },
  {
    id: 'netplus-traditional-control-plane-vs-sdn',
    certId: 'netplus',
    domain: 1,
    title: 'Traditional Control Plane vs SDN',
    description: 'toggle to see where forwarding decisions get made, before and after centralizing control.',
    Component: lazy(() => import('./netplus/SdnControlPlaneToggle')),
  },
  {
    id: 'netplus-traffic-delivery-types',
    certId: 'netplus',
    domain: 1,
    title: 'Traffic Delivery Types',
    description: 'click a traffic type to see how many hosts actually receive each packet.',
    Component: lazy(() => import('./netplus/TrafficDeliveryStack')),
  },
  {
    id: 'netplus-wan-connection-types',
    certId: 'netplus',
    domain: 1,
    title: 'WAN Connection Types',
    description: 'slide across WAN link types to compare cost, speed, and latency trade-offs.',
    Component: lazy(() => import('./netplus/WanConnectionSpectrum')),
  },
  {
    id: 'netplus-well-known-port-numbers',
    certId: 'netplus',
    domain: 1,
    title: 'Well-Known Port Numbers',
    description: 'click a card to flip between the port number and the service it belongs to.',
    Component: lazy(() => import('./netplus/WellKnownPortsMatcher')),
  },
  {
    id: 'netplus-dhcp-lease-process-dora',
    certId: 'netplus',
    domain: 2,
    title: 'DHCP Lease Process (DORA)',
    description: 'step through Discover, Offer, Request, Acknowledge, and the later renewal.',
    Component: lazy(() => import('./netplus/DhcpLeaseTimeline')),
  },
  {
    id: 'netplus-dns-record-types',
    certId: 'netplus',
    domain: 2,
    title: 'DNS Record Types',
    description: 'click a card to flip between the record type and what it resolves.',
    Component: lazy(() => import('./netplus/DnsRecordMatcher')),
  },
  {
    id: 'netplus-nat-pat-translation-flow',
    certId: 'netplus',
    domain: 2,
    title: 'NAT / PAT Translation Flow',
    description: 'watch a packet\'s address get translated out to the internet, and back.',
    Component: lazy(() => import('./netplus/NatPatFlowTrace')),
  },
  {
    id: 'netplus-redundant-links-stp-blocking-vs-lacp-aggregation',
    certId: 'netplus',
    domain: 2,
    title: 'Redundant Links: STP Blocking vs LACP Aggregation',
    description: 'toggle to see what happens to a second physical link between two switches.',
    Component: lazy(() => import('./netplus/RedundantLinkToggle')),
  },
  {
    id: 'netplus-routing-protocols-by-administrative-distance',
    certId: 'netplus',
    domain: 2,
    title: 'Routing Protocols by Administrative Distance',
    description: 'click a source to see why a router trusts it more or less than the others when routes conflict.',
    Component: lazy(() => import('./netplus/RoutingProtocolStack')),
  },
  {
    id: 'netplus-wireless-security-standards',
    certId: 'netplus',
    domain: 2,
    title: 'Wireless Security Standards',
    description: 'slide across Wi-Fi security generations to compare encryption and key management.',
    Component: lazy(() => import('./netplus/WirelessSecuritySpectrum')),
  },
  {
    id: 'netplus-choosing-a-monitoring-tool',
    certId: 'netplus',
    domain: 3,
    title: 'Choosing a Monitoring Tool',
    description: 'pick what you need to see and when you need to see it.',
    Component: lazy(() => import('./netplus/MonitoringToolMatrix')),
  },
  {
    id: 'netplus-disaster-recovery-site-types',
    certId: 'netplus',
    domain: 3,
    title: 'Disaster Recovery Site Types',
    description: 'use the arrows to order these sites from fastest to slowest recovery, then check.',
    Component: lazy(() => import('./netplus/DrSiteReorder')),
  },
  {
    id: 'netplus-network-change-management-process',
    certId: 'netplus',
    domain: 3,
    title: 'Network Change Management Process',
    description: 'step through how a network change moves from request to documented reality.',
    Component: lazy(() => import('./netplus/ChangeManagementTimeline')),
  },
  {
    id: 'netplus-physical-vs-logical-network-diagrams',
    certId: 'netplus',
    domain: 3,
    title: 'Physical vs Logical Network Diagrams',
    description: 'compare what each documentation type shows and when you would reach for it.',
    Component: lazy(() => import('./netplus/DocumentationTypeComparison')),
  },
  {
    id: 'netplus-device-hardening-checklist',
    certId: 'netplus',
    domain: 4,
    title: 'Device Hardening Checklist',
    description: 'toggle between an out-of-the-box device and one that has gone through standard hardening steps.',
    Component: lazy(() => import('./netplus/DeviceHardeningToggle')),
  },
  {
    id: 'netplus-ids-vs-ips',
    certId: 'netplus',
    domain: 4,
    title: 'IDS vs IPS',
    description: 'watch the same malicious packet take the out-of-band IDS path versus the inline IPS path.',
    Component: lazy(() => import('./netplus/IdsVsIpsDiagram')),
  },
  {
    id: 'netplus-physical-security-controls',
    certId: 'netplus',
    domain: 4,
    title: 'Physical Security Controls',
    description: 'click a card to flip between the control\'s name and what it actually does.',
    Component: lazy(() => import('./netplus/PhysicalSecurityControls')),
  },
  {
    id: 'netplus-radius-vs-tacacs',
    certId: 'netplus',
    domain: 4,
    title: 'RADIUS vs TACACS+',
    description: 'compare the two dominant AAA (authentication, authorization, accounting) protocols used to centralize network logins.',
    Component: lazy(() => import('./netplus/AaaProtocolComparison')),
  },
  {
    id: 'netplus-dns-troubleshooting-with-nslookup-dig',
    certId: 'netplus',
    domain: 5,
    title: 'DNS Troubleshooting with nslookup/dig',
    description: 'step through isolating a name-resolution failure to the internal or upstream DNS server.',
    Component: lazy(() => import('./netplus/DnsTroubleshootingFlow')),
  },
  {
    id: 'netplus-duplicate-ip-address-conflict',
    certId: 'netplus',
    domain: 5,
    title: 'Duplicate IP Address Conflict',
    description: 'trace how a stray static IP collides with an address already in use.',
    Component: lazy(() => import('./netplus/DuplicateIpConflictTrace')),
  },
  {
    id: 'netplus-interface-error-counters-ranked-by-severity',
    certId: 'netplus',
    domain: 5,
    title: 'Interface Error Counters, Ranked by Severity',
    description: 'click a counter to see what it means and how urgently it should be investigated.',
    Component: lazy(() => import('./netplus/InterfaceErrorCounters')),
  },
  {
    id: 'netplus-latency-jitter-and-packet-loss',
    certId: 'netplus',
    domain: 5,
    title: 'Latency, Jitter & Packet Loss',
    description: 'drag the sliders to see how the three core performance metrics combine into an overall verdict for real-time traffic.',
    Component: lazy(() => import('./netplus/NetworkPerformanceCalculator')),
  },
  {
    id: 'netplus-which-hardware-tool-do-i-need',
    certId: 'netplus',
    domain: 5,
    title: 'Which Hardware Tool Do I Need?',
    description: 'pick the symptom and cable media to see which physical-layer tool actually fits the job.',
    Component: lazy(() => import('./netplus/NetworkToolSelector')),
  },
  {
    id: 'netplus-wireless-signal-strength-troubleshooting',
    certId: 'netplus',
    domain: 5,
    title: 'Wireless Signal Strength Troubleshooting',
    description: 'drag the slider across RSSI tiers to see what a client actually experiences at each signal level.',
    Component: lazy(() => import('./netplus/WirelessSignalSpectrum')),
  },
  {
    id: 'secplus-change-management-process',
    certId: 'secplus',
    domain: 1,
    title: 'Change Management Process',
    description: 'step through a well-governed change from request to review.',
    Component: lazy(() => import('./secplus/ChangeManagementTimeline')),
  },
  {
    id: 'secplus-deception-and-disruption-technology',
    certId: 'secplus',
    domain: 1,
    title: 'Deception & Disruption Technology',
    description: 'toggle to see how honeypots and decoys change an attacker\'s path after the perimeter is breached.',
    Component: lazy(() => import('./secplus/DeceptionTechnologyToggle')),
  },
  {
    id: 'secplus-encryption-across-the-data-lifecycle',
    certId: 'secplus',
    domain: 1,
    title: 'Encryption Across the Data Lifecycle',
    description: 'drag across the data lifecycle to see how the right cryptographic control changes by state.',
    Component: lazy(() => import('./secplus/DataStateEncryptionSpectrum')),
  },
  {
    id: 'secplus-security-control-types-matrix',
    certId: 'secplus',
    domain: 1,
    title: 'Security Control Types Matrix',
    description: 'pick a control category and a control function to see a matching real-world example.',
    Component: lazy(() => import('./secplus/SecurityControlTypeMatrix')),
  },
  {
    id: 'secplus-attack-surface-reduction-calculator',
    certId: 'secplus',
    domain: 2,
    title: 'Attack Surface Reduction Calculator',
    description: 'adjust common mitigation techniques and watch the estimated residual risk score respond.',
    Component: lazy(() => import('./secplus/AttackSurfaceReductionCalculator')),
  },
  {
    id: 'secplus-physical-intrusion-attempt-sequence',
    certId: 'secplus',
    domain: 2,
    title: 'Physical Intrusion Attempt Sequence',
    description: 'use the arrows to put a physical social-engineering intrusion in the order it typically unfolds, then check.',
    Component: lazy(() => import('./secplus/PhysicalIntrusionSequence')),
  },
  {
    id: 'secplus-sql-injection-attack-trace',
    certId: 'secplus',
    domain: 2,
    title: 'SQL Injection Attack Trace',
    description: 'watch an unsanitized input field turn into a full data breach.',
    Component: lazy(() => import('./secplus/SqlInjectionAttackTrace')),
  },
  {
    id: 'secplus-threat-actor-sophistication-tiers',
    certId: 'secplus',
    domain: 2,
    title: 'Threat Actor Sophistication Tiers',
    description: 'click each tier to compare threat actors by resources, sophistication, and motivation.',
    Component: lazy(() => import('./secplus/ThreatActorSophisticationStack')),
  },
  {
    id: 'secplus-threat-vectors-and-attack-surfaces',
    certId: 'secplus',
    domain: 2,
    title: 'Threat Vectors & Attack Surfaces',
    description: 'click a card to flip between the vector name and how it is used.',
    Component: lazy(() => import('./secplus/ThreatVectorFlipCards')),
  },
  {
    id: 'secplus-vulnerability-types-across-the-stack',
    certId: 'secplus',
    domain: 2,
    title: 'Vulnerability Types Across the Stack',
    description: 'step through where each vulnerability type actually lives.',
    Component: lazy(() => import('./secplus/VulnerabilityStackDiagram')),
  },
  {
    id: 'secplus-cloud-shared-responsibility-model',
    certId: 'secplus',
    domain: 3,
    title: 'Cloud Shared Responsibility Model',
    description: 'pick a service model to see how security responsibility shifts between provider and customer.',
    Component: lazy(() => import('./secplus/CloudResponsibilityComparison')),
  },
  {
    id: 'secplus-high-availability-failover',
    certId: 'secplus',
    domain: 3,
    title: 'High Availability Failover',
    description: 'watch load balancing and clustering absorb a node failure.',
    Component: lazy(() => import('./secplus/HighAvailabilityFailoverTrace')),
  },
  {
    id: 'secplus-ics-scada-and-embedded-device-security-priority',
    certId: 'secplus',
    domain: 3,
    title: 'ICS/SCADA & Embedded Device Security Priority',
    description: 'since these devices often cannot be patched, use the arrows to rank these controls in the order you should apply them, then check.',
    Component: lazy(() => import('./secplus/IcsCompensatingControlPriority')),
  },
  {
    id: 'secplus-screened-subnet-dmz-segmentation',
    certId: 'secplus',
    domain: 3,
    title: 'Screened Subnet (DMZ) Segmentation',
    description: 'step through how a screened subnet keeps public services separate from the internal network.',
    Component: lazy(() => import('./secplus/ScreenedSubnetDiagram')),
  },
  {
    id: 'secplus-alerting-and-monitoring-tool-matcher',
    certId: 'secplus',
    domain: 4,
    title: 'Alerting & Monitoring Tool Matcher',
    description: 'click a card to flip between the acronym and what the tool actually does.',
    Component: lazy(() => import('./secplus/MonitoringToolMatcher')),
  },
  {
    id: 'secplus-asset-management-lifecycle',
    certId: 'secplus',
    domain: 4,
    title: 'Asset Management Lifecycle',
    description: 'step through a hardware/software asset from procurement to disposal.',
    Component: lazy(() => import('./secplus/AssetManagementLifecycle')),
  },
  {
    id: 'secplus-credentialed-vs-non-credentialed-scanning',
    certId: 'secplus',
    domain: 4,
    title: 'Credentialed vs. Non-Credentialed Scanning',
    description: 'compare what each vulnerability scan type can see and where it fits.',
    Component: lazy(() => import('./secplus/VulnerabilityScanTypes')),
  },
  {
    id: 'secplus-layered-network-defenses',
    certId: 'secplus',
    domain: 4,
    title: 'Layered Network Defenses',
    description: 'step through how a single connection is checked at each defensive layer.',
    Component: lazy(() => import('./secplus/NetworkDefenseLayers')),
  },
  {
    id: 'secplus-patch-management-sequence',
    certId: 'secplus',
    domain: 4,
    title: 'Patch Management Sequence',
    description: 'use the arrows to put the patch management process in order, then check.',
    Component: lazy(() => import('./secplus/PatchManagementSequence')),
  },
  {
    id: 'secplus-secure-baseline-hardening',
    certId: 'secplus',
    domain: 4,
    title: 'Secure Baseline Hardening',
    description: 'toggle between a default configuration and a hardened secure baseline.',
    Component: lazy(() => import('./secplus/SecureBaselineToggle')),
  },
  {
    id: 'secplus-audit-and-assessment-type-picker',
    certId: 'secplus',
    domain: 5,
    title: 'Audit & Assessment Type Picker',
    description: 'pick who performs the review and why, to see which audit type it is.',
    Component: lazy(() => import('./secplus/AuditTypeDecision')),
  },
  {
    id: 'secplus-business-impact-analysis-calculator',
    certId: 'secplus',
    domain: 5,
    title: 'Business Impact Analysis Calculator',
    description: 'adjust outage inputs to see estimated impact and whether it exceeds the process\'s Maximum Tolerable Downtime.',
    Component: lazy(() => import('./secplus/BusinessImpactCalculator')),
  },
  {
    id: 'secplus-compliance-reporting-flow',
    certId: 'secplus',
    domain: 5,
    title: 'Compliance Reporting Flow',
    description: 'watch a finding move from internal review to external disclosure and closure.',
    Component: lazy(() => import('./secplus/ComplianceReportingTrace')),
  },
  {
    id: 'secplus-governance-model-spectrum',
    certId: 'secplus',
    domain: 5,
    title: 'Governance Model Spectrum',
    description: 'drag across the tiers to see how centralized and decentralized governance trade off.',
    Component: lazy(() => import('./secplus/GovernanceModelSpectrum')),
  },
  {
    id: 'secplus-security-awareness-training-cycle',
    certId: 'secplus',
    domain: 5,
    title: 'Security Awareness Training Cycle',
    description: 'step through how an awareness program is built, delivered, and measured.',
    Component: lazy(() => import('./secplus/AwarenessTrainingTimeline')),
  },
  {
    id: 'secplus-security-documentation-hierarchy',
    certId: 'secplus',
    domain: 5,
    title: 'Security Documentation Hierarchy',
    description: 'click a tier to see how governance flows down into policies, standards, procedures, and guidelines.',
    Component: lazy(() => import('./secplus/PolicyHierarchyStack')),
  },
  {
    id: 'cysa-cloud-shared-responsibility-finder',
    certId: 'cysa',
    domain: 1,
    title: 'Cloud Shared Responsibility Finder',
    description: 'pick a service model and a layer to see who is on the hook for securing it.',
    Component: lazy(() => import('./cysa/CloudSecOpsDecision')),
  },
  {
    id: 'cysa-flat-network-vs-zero-trust-segmentation',
    certId: 'cysa',
    domain: 1,
    title: 'Flat Network vs. Zero-Trust Segmentation',
    description: 'toggle to compare a flat, perimeter-only network with a segmented, zero-trust design.',
    Component: lazy(() => import('./cysa/NetworkSegmentationToggle')),
  },
  {
    id: 'cysa-log-ingestion-pipeline',
    certId: 'cysa',
    domain: 1,
    title: 'Log Ingestion Pipeline',
    description: 'watch a raw event travel from source to a correlated alert.',
    Component: lazy(() => import('./cysa/LogIngestionPipeline')),
  },
  {
    id: 'cysa-privileged-access-tiering',
    certId: 'cysa',
    domain: 1,
    title: 'Privileged Access Tiering',
    description: 'click a tier to see why identity infrastructure sits above everyday user accounts.',
    Component: lazy(() => import('./cysa/IdentityAccessSocTiers')),
  },
  {
    id: 'cysa-threat-intelligence-source-matcher',
    certId: 'cysa',
    domain: 1,
    title: 'Threat Intelligence Source Matcher',
    description: 'click a card to reveal what each threat-intel source is best (and worst) for.',
    Component: lazy(() => import('./cysa/ThreatIntelSourceMatcher')),
  },
  {
    id: 'cysa-transport-encryption-protocol-spectrum',
    certId: 'cysa',
    domain: 1,
    title: 'Transport Encryption Protocol Spectrum',
    description: 'slide across the protocol generations to compare strength, forward secrecy, and real-world exposure.',
    Component: lazy(() => import('./cysa/EncryptionProtocolSpectrum')),
  },
  {
    id: 'cysa-dread-risk-score-calculator',
    certId: 'cysa',
    domain: 2,
    title: 'DREAD Risk Score Calculator',
    description: 'rate each DREAD factor 0-10 to see how a threat model converts qualitative judgment into a comparable score.',
    Component: lazy(() => import('./cysa/DreadRiskCalculator')),
  },
  {
    id: 'cysa-mapping-the-attack-surface',
    certId: 'cysa',
    domain: 2,
    title: 'Mapping the Attack Surface',
    description: 'reveal, one category at a time, everything an attacker could try before you even start scanning.',
    Component: lazy(() => import('./cysa/AttackSurfaceManagement')),
  },
  {
    id: 'cysa-prioritizing-beyond-cvss-epss-and-kev',
    certId: 'cysa',
    domain: 2,
    title: 'Prioritizing Beyond CVSS: EPSS & KEV',
    description: 'use the arrows to rank these findings from highest to lowest real-world remediation priority, then check.',
    Component: lazy(() => import('./cysa/EpssKevPrioritization')),
  },
  {
    id: 'cysa-reading-a-vulnerability-scan-finding',
    certId: 'cysa',
    domain: 2,
    title: 'Reading a Vulnerability Scan Finding',
    description: 'walk through how an analyst turns one raw scan finding into a prioritized ticket.',
    Component: lazy(() => import('./cysa/ScanReportWalkthrough')),
  },
  {
    id: 'cysa-sql-injection-vs-cross-site-scripting',
    certId: 'cysa',
    domain: 2,
    title: 'SQL Injection vs. Cross-Site Scripting',
    description: 'two of the most common web application vulnerability classes, compared side by side.',
    Component: lazy(() => import('./cysa/OwaspWebVulnTypes')),
  },
  {
    id: 'cysa-true-false-positive-and-negative-finder',
    certId: 'cysa',
    domain: 2,
    title: 'True/False Positive & Negative Finder',
    description: 'pick a scanner result and a manual validation result to see which outcome you are dealing with.',
    Component: lazy(() => import('./cysa/FalsePositiveNegativeDecision')),
  },
  {
    id: 'cysa-chain-of-custody-flow',
    certId: 'cysa',
    domain: 3,
    title: 'Chain of Custody Flow',
    description: 'step through how evidence moves, and what gets logged, at each handoff.',
    Component: lazy(() => import('./cysa/ChainOfCustodyFlow')),
  },
  {
    id: 'cysa-eradication-vs-remediation',
    certId: 'cysa',
    domain: 3,
    title: 'Eradication vs. Remediation',
    description: 'two phases that sound similar but answer different questions.',
    Component: lazy(() => import('./cysa/EradicationVsRemediation')),
  },
  {
    id: 'cysa-mitre-attand-ck-tactic-trace',
    certId: 'cysa',
    domain: 3,
    title: 'MITRE ATT&CK Tactic Trace',
    description: 'watch a token move across ATT&CK tactics in a typical intrusion path.',
    Component: lazy(() => import('./cysa/MitreAttackTacticTrace')),
  },
  {
    id: 'cysa-order-of-volatility',
    certId: 'cysa',
    domain: 3,
    title: 'Order of Volatility',
    description: 'use the arrows to sequence evidence collection from most to least volatile, then check.',
    Component: lazy(() => import('./cysa/OrderOfVolatility')),
  },
  {
    id: 'cysa-playbook-runbook-and-friends',
    certId: 'cysa',
    domain: 3,
    title: 'Playbook, Runbook & Friends',
    description: 'click a card to flip between the term and what it actually means in an IR program.',
    Component: lazy(() => import('./cysa/PlaybookRunbookMatcher')),
  },
  {
    id: 'cysa-root-cause-analysis-technique-selector',
    certId: 'cysa',
    domain: 3,
    title: 'Root Cause Analysis Technique Selector',
    description: 'describe the incident and get the RCA technique best suited to it.',
    Component: lazy(() => import('./cysa/RootCauseAnalysisSelector')),
  },
  {
    id: 'cysa-executive-summary-vs-technical-report',
    certId: 'cysa',
    domain: 4,
    title: 'Executive Summary vs. Technical Report',
    description: 'toggle between the two audiences a single vulnerability finding gets written for.',
    Component: lazy(() => import('./cysa/ExecutiveVsTechnicalReport')),
  },
  {
    id: 'cysa-incident-communication-cadence',
    certId: 'cysa',
    domain: 4,
    title: 'Incident Communication Cadence',
    description: 'slide across severity to see how often, and to whom, updates should go out.',
    Component: lazy(() => import('./cysa/CommunicationCadenceSpectrum')),
  },
  {
    id: 'cysa-post-incident-review-meeting',
    certId: 'cysa',
    domain: 4,
    title: 'Post-Incident Review Meeting',
    description: 'step through the agenda a lessons-learned meeting should follow.',
    Component: lazy(() => import('./cysa/PostIncidentReviewAgenda')),
  },
  {
    id: 'cysa-vulnerability-management-kpi-calculator',
    certId: 'cysa',
    domain: 4,
    title: 'Vulnerability Management KPI Calculator',
    description: 'adjust scan and remediation figures to see the KPIs a vulnerability report would surface.',
    Component: lazy(() => import('./cysa/VulnManagementKpiCalculator')),
  },
  {
    id: 'awssaa-cross-account-assume-role-flow',
    certId: 'awssaa',
    domain: 1,
    title: 'Cross-Account AssumeRole Flow',
    description: 'watch a caller in one account assume a role in another.',
    Component: lazy(() => import('./awssaa/CrossAccountAssumeRoleFlow')),
  },
  {
    id: 'awssaa-iam-users-vs-groups-vs-roles',
    certId: 'awssaa',
    domain: 1,
    title: 'IAM Users vs Groups vs Roles',
    description: 'compare the three ways IAM represents "who" is making a request.',
    Component: lazy(() => import('./awssaa/IamRolesUsersGroups')),
  },
  {
    id: 'awssaa-public-private-subnet-design',
    certId: 'awssaa',
    domain: 1,
    title: 'Public/Private Subnet Design',
    description: 'step through how a VPC routes traffic between tiers.',
    Component: lazy(() => import('./awssaa/VpcPublicPrivateSubnetDesign')),
  },
  {
    id: 'awssaa-secrets-manager-vs-parameter-store',
    certId: 'awssaa',
    domain: 1,
    title: 'Secrets Manager vs Parameter Store',
    description: 'click a card to reveal which service the trait belongs to.',
    Component: lazy(() => import('./awssaa/SecretsManagerVsParameterStore')),
  },
  {
    id: 'awssaa-security-groups-vs-network-acls',
    certId: 'awssaa',
    domain: 1,
    title: 'Security Groups vs Network ACLs',
    description: 'pick a scope and rule type to see which network control fits.',
    Component: lazy(() => import('./awssaa/NaclVsSecurityGroupDecision')),
  },
  {
    id: 'awssaa-waf-shield-and-firewall-manager',
    certId: 'awssaa',
    domain: 1,
    title: 'WAF, Shield & Firewall Manager',
    description: 'click a layer of AWS edge protection to see its scope.',
    Component: lazy(() => import('./awssaa/WafShieldEdgeProtection')),
  },
  {
    id: 'awssaa-disaster-recovery-failover-sequence',
    certId: 'awssaa',
    domain: 2,
    title: 'Disaster Recovery Failover Sequence',
    description: 'step through a regional failover from outage to recovery.',
    Component: lazy(() => import('./awssaa/BackupDrFailoverSequence')),
  },
  {
    id: 'awssaa-elastic-load-balancer-types',
    certId: 'awssaa',
    domain: 2,
    title: 'Elastic Load Balancer Types',
    description: 'slide across ELB types to compare OSI layer, throughput, and routing flexibility.',
    Component: lazy(() => import('./awssaa/LoadBalancerTypeSpectrum')),
  },
  {
    id: 'awssaa-order-the-dr-strategies',
    certId: 'awssaa',
    domain: 2,
    title: 'Order the DR Strategies',
    description: 'use the arrows to rank the four DR strategies from lowest cost/slowest recovery to highest cost/fastest recovery, then check.',
    Component: lazy(() => import('./awssaa/DrStrategyOrderChallenge')),
  },
  {
    id: 'awssaa-rds-single-az-vs-multi-az',
    certId: 'awssaa',
    domain: 2,
    title: 'RDS Single-AZ vs Multi-AZ',
    description: 'toggle to see how a standby replica changes failure behavior.',
    Component: lazy(() => import('./awssaa/RdsMultiAzToggle')),
  },
  {
    id: 'awssaa-read-replica-scaling-calculator',
    certId: 'awssaa',
    domain: 2,
    title: 'Read Replica Scaling Calculator',
    description: 'adjust query load to see how many read replicas an RDS primary needs.',
    Component: lazy(() => import('./awssaa/ReadReplicaScalingCalculator')),
  },
  {
    id: 'awssaa-sqs-vs-sns-messaging-patterns',
    certId: 'awssaa',
    domain: 2,
    title: 'SQS vs SNS Messaging Patterns',
    description: 'compare queue-based and topic-based decoupling.',
    Component: lazy(() => import('./awssaa/SqsVsSnsDecoupling')),
  },
  {
    id: 'awssaa-api-gateway-rest-api-vs-http-api',
    certId: 'awssaa',
    domain: 3,
    title: 'API Gateway: REST API vs HTTP API',
    description: 'compare the two API Gateway types for building a high-performing front door to your backend.',
    Component: lazy(() => import('./awssaa/ApiGatewayTypeComparison')),
  },
  {
    id: 'awssaa-cloud-front-cache-request-trace',
    certId: 'awssaa',
    domain: 3,
    title: 'CloudFront Cache Request Trace',
    description: 'watch a request travel from viewer to edge to origin and back.',
    Component: lazy(() => import('./awssaa/CloudFrontCacheTrace')),
  },
  {
    id: 'awssaa-compute-service-selection',
    certId: 'awssaa',
    domain: 3,
    title: 'Compute Service Selection',
    description: 'pick your operational preference and workload shape to see which compute service fits.',
    Component: lazy(() => import('./awssaa/ComputeServiceDecisionMatrix')),
  },
  {
    id: 'awssaa-dynamo-db-partition-key-design',
    certId: 'awssaa',
    domain: 3,
    title: 'DynamoDB Partition Key Design',
    description: 'toggle between a low-cardinality key and a well-distributed one to see why hot partitions happen.',
    Component: lazy(() => import('./awssaa/DynamoDbPartitionKeyToggle')),
  },
  {
    id: 'awssaa-ebs-volume-type-spectrum',
    certId: 'awssaa',
    domain: 3,
    title: 'EBS Volume Type Spectrum',
    description: 'slide across EBS volume types to compare IOPS, throughput, and relative cost.',
    Component: lazy(() => import('./awssaa/EbsVolumeTypeSpectrum')),
  },
  {
    id: 'awssaa-serverless-event-driven-pipeline',
    certId: 'awssaa',
    domain: 3,
    title: 'Serverless Event-Driven Pipeline',
    description: 'step through a decoupled S3 → Lambda → DynamoDB → SNS ingestion pipeline.',
    Component: lazy(() => import('./awssaa/ServerlessEventPipeline')),
  },
  {
    id: 'awssaa-compute-sp-vs-ec2-instance-sp-vs-reserved-instances',
    certId: 'awssaa',
    domain: 4,
    title: 'Compute SP vs EC2 Instance SP vs Reserved Instances',
    description: 'compare the three ways to commit spend for a discount, from most to least flexible.',
    Component: lazy(() => import('./awssaa/SavingsPlansComparison')),
  },
  {
    id: 'awssaa-cost-explorer-vs-budgets-vs-trusted-advisor',
    certId: 'awssaa',
    domain: 4,
    title: 'Cost Explorer vs Budgets vs Trusted Advisor',
    description: 'pick what you\'re trying to accomplish to see which AWS cost management tool fits.',
    Component: lazy(() => import('./awssaa/CostManagementToolComparison')),
  },
  {
    id: 'awssaa-data-transfer-cost-spectrum',
    certId: 'awssaa',
    domain: 4,
    title: 'Data Transfer Cost Spectrum',
    description: 'slide across traffic paths to see how cost and latency change as data crosses more boundaries.',
    Component: lazy(() => import('./awssaa/DataTransferCostSpectrum')),
  },
  {
    id: 'awssaa-ec2-right-sizing-calculator',
    certId: 'awssaa',
    domain: 4,
    title: 'EC2 Right-Sizing Calculator',
    description: 'set a running instance size and its average CPU utilization to see the right-sizing recommendation.',
    Component: lazy(() => import('./awssaa/Ec2RightSizingCalculator')),
  },
  {
    id: 'awssaa-lambda-cost-model-calculator',
    certId: 'awssaa',
    domain: 4,
    title: 'Lambda Cost Model Calculator',
    description: 'adjust monthly invocations, duration, and memory to see how Lambda\'s two-part pricing (requests + GB-seconds) plays out.',
    Component: lazy(() => import('./awssaa/LambdaCostModelCalculator')),
  },
  {
    id: 'awssaa-order-the-s3-lifecycle-transitions',
    certId: 'awssaa',
    domain: 4,
    title: 'Order the S3 Lifecycle Transitions',
    description: 'use the arrows to put a single object\'s lifecycle policy transitions in chronological order, then check.',
    Component: lazy(() => import('./awssaa/S3LifecycleTransitionChallenge')),
  },
  {
    id: 'awsscs-automated-remediation-event-bridge-lambda',
    certId: 'awsscs',
    domain: 1,
    title: 'Automated Remediation: EventBridge + Lambda',
    description: 'watch a GuardDuty finding travel through an automated response pipeline.',
    Component: lazy(() => import('./awsscs/AutomatedRemediationFlowTrace')),
  },
  {
    id: 'awsscs-guard-duty-finding-type-matcher',
    certId: 'awsscs',
    domain: 1,
    title: 'GuardDuty Finding Type Matcher',
    description: 'GuardDuty finding type names encode threat, resource, and behavior. Click a card to reveal what it actually means.',
    Component: lazy(() => import('./awsscs/GuardDutyFindingTypeMatcher')),
  },
  {
    id: 'awsscs-guard-duty-to-security-hub-to-detective-pipeline',
    certId: 'awsscs',
    domain: 1,
    title: 'GuardDuty to Security Hub to Detective Pipeline',
    description: 'step through how a raw signal becomes an investigated finding across the three detection services.',
    Component: lazy(() => import('./awsscs/ThreatDetectionServicePipeline')),
  },
  {
    id: 'awsscs-macie-sensitive-data-discovery-coverage-vs-cost',
    certId: 'awsscs',
    domain: 1,
    title: 'Macie Sensitive Data Discovery: Coverage vs. Cost',
    description: 'adjust bucket size, sampling depth, and enabled identifiers to see the coverage/cost tradeoff of a classification job.',
    Component: lazy(() => import('./awsscs/MacieDiscoveryCostCalculator')),
  },
  {
    id: 'awsscs-cloud-trail-log-file-integrity-validation',
    certId: 'awsscs',
    domain: 2,
    title: 'CloudTrail Log File Integrity Validation',
    description: 'step through how CloudTrail\'s digest hash chain makes tampering detectable.',
    Component: lazy(() => import('./awsscs/CloudTrailDigestChainTimeline')),
  },
  {
    id: 'awsscs-cloud-watch-logs-insights-query-commands',
    certId: 'awsscs',
    domain: 2,
    title: 'CloudWatch Logs Insights: Query Commands',
    description: 'click a command to reveal what it does in a Logs Insights query pipeline.',
    Component: lazy(() => import('./awsscs/LogsInsightsCommandMatcher')),
  },
  {
    id: 'awsscs-s3-server-access-logging-vs-cloud-trail-data-events',
    certId: 'awsscs',
    domain: 2,
    title: 'S3 Server Access Logging vs. CloudTrail Data Events',
    description: 'two different ways to log S3 object activity, each with different reliability, cost, and automation implications.',
    Component: lazy(() => import('./awsscs/S3AccessLogsVsDataEvents')),
  },
  {
    id: 'awsscs-vpc-flow-log-record-field-order',
    certId: 'awsscs',
    domain: 2,
    title: 'VPC Flow Log Record: Field Order',
    description: 'a representative subset of the default flow log record\'s fields, scrambled. Use the arrows to put them back in their real left-to-right order, then check.',
    Component: lazy(() => import('./awsscs/VpcFlowLogFieldOrder')),
  },
  {
    id: 'awsscs-bastion-host-vs-systems-manager-session-manager',
    certId: 'awsscs',
    domain: 3,
    title: 'Bastion Host vs. Systems Manager Session Manager',
    description: 'toggle between the legacy SSH bastion pattern and Session Manager.',
    Component: lazy(() => import('./awsscs/SessionManagerVsBastionToggle')),
  },
  {
    id: 'awsscs-container-workload-security-scanning-task-role-scope',
    certId: 'awsscs',
    domain: 3,
    title: 'Container Workload Security: Scanning + Task Role Scope',
    description: 'pick an ECR scanning level and a task role scope to see the resulting posture.',
    Component: lazy(() => import('./awsscs/ContainerWorkloadSecurityMatrix')),
  },
  {
    id: 'awsscs-ddo-s-protection-tiers-shield-standard-to-full-edge-stack',
    certId: 'awsscs',
    domain: 3,
    title: 'DDoS Protection Tiers: Shield Standard to Full Edge Stack',
    description: 'slide across tiers to see how coverage, cost, and DRT access scale.',
    Component: lazy(() => import('./awsscs/DdosProtectionTierSlider')),
  },
  {
    id: 'awsscs-network-firewall-waf-and-security-groups-layered-defense',
    certId: 'awsscs',
    domain: 3,
    title: 'Network Firewall, WAF, and Security Groups: Layered Defense',
    description: 'step through the order in which each layer inspects inbound traffic.',
    Component: lazy(() => import('./awsscs/EdgeDefenseLayerDiagram')),
  },
  {
    id: 'awsscs-patch-management-with-systems-manager',
    certId: 'awsscs',
    domain: 3,
    title: 'Patch Management with Systems Manager',
    description: 'step through the Patch Manager workflow from baseline to compliance report.',
    Component: lazy(() => import('./awsscs/PatchManagerWorkflowTimeline')),
  },
  {
    id: 'awsscs-vpc-peering-vs-transit-gateway-vs-private-link',
    certId: 'awsscs',
    domain: 3,
    title: 'VPC Peering vs. Transit Gateway vs. PrivateLink',
    description: 'pick your connectivity goal to see which private connectivity option fits.',
    Component: lazy(() => import('./awsscs/ConnectivityChoiceMatrix')),
  },
  {
    id: 'awsscs-enforcing-mfa-optional-vs-conditionally-required',
    certId: 'awsscs',
    domain: 4,
    title: 'Enforcing MFA: Optional vs Conditionally Required',
    description: 'toggle to compare an unenforced setup with a policy that actually requires MFA.',
    Component: lazy(() => import('./awsscs/MfaEnforcementApproaches')),
  },
  {
    id: 'awsscs-federated-access-via-iam-identity-center',
    certId: 'awsscs',
    domain: 4,
    title: 'Federated Access via IAM Identity Center',
    description: 'trace a workforce sign-in from the external IdP to a live AWS session.',
    Component: lazy(() => import('./awsscs/FederatedAccessWithIdentityCenter')),
  },
  {
    id: 'awsscs-identity-based-vs-resource-based-policy-evaluation',
    certId: 'awsscs',
    domain: 4,
    title: 'Identity-Based vs Resource-Based Policy Evaluation',
    description: 'pick each policy\'s stance and the account scope to see whether the request is allowed.',
    Component: lazy(() => import('./awsscs/IamPolicyEvaluationLogic')),
  },
  {
    id: 'awsscs-lifecycle-of-sts-temporary-credentials',
    certId: 'awsscs',
    domain: 4,
    title: 'Lifecycle of STS Temporary Credentials',
    description: 'follow a role assumption from request to automatic expiry.',
    Component: lazy(() => import('./awsscs/StsTemporaryCredentialsLifecycle')),
  },
  {
    id: 'awsscs-data-classification-tiers-for-aws-workloads',
    certId: 'awsscs',
    domain: 5,
    title: 'Data Classification Tiers for AWS Workloads',
    description: 'slide across the classification levels to see the controls each one demands.',
    Component: lazy(() => import('./awsscs/DataClassificationForAwsWorkloads')),
  },
  {
    id: 'awsscs-envelope-encryption-with-kms',
    certId: 'awsscs',
    domain: 5,
    title: 'Envelope Encryption with KMS',
    description: 'watch the data key travel through generation, local use, and decryption.',
    Component: lazy(() => import('./awsscs/EnvelopeEncryptionConcept')),
  },
  {
    id: 'awsscs-kms-key-policy-vs-iam-policy-who-actually-grants-access',
    certId: 'awsscs',
    domain: 5,
    title: 'KMS Key Policy vs IAM Policy: Who Actually Grants Access',
    description: 'the key policy is the root of trust; IAM policies only help once the key policy delegates to them.',
    Component: lazy(() => import('./awsscs/KmsKeyPolicyVsIamPolicy')),
  },
  {
    id: 'awsscs-secrets-manager-rotation-lifecycle',
    certId: 'awsscs',
    domain: 5,
    title: 'Secrets Manager Rotation Lifecycle',
    description: 'step through the AWSPENDING/AWSCURRENT dance behind automatic secret rotation.',
    Component: lazy(() => import('./awsscs/SecretsManagerRotationLifecycle')),
  },
  {
    id: 'awsscs-aws-organizations-a-typical-account-structure',
    certId: 'awsscs',
    domain: 6,
    title: 'AWS Organizations: A Typical Account Structure',
    description: 'click a tier to see why that account or OU exists and what it should (and shouldn\'t) run.',
    Component: lazy(() => import('./awsscs/OrganizationsAccountStructure')),
  },
  {
    id: 'awsscs-building-a-multi-account-security-strategy',
    certId: 'awsscs',
    domain: 6,
    title: 'Building a Multi-Account Security Strategy',
    description: 'use the arrows to put these landing-zone steps in order, then check.',
    Component: lazy(() => import('./awsscs/MultiAccountSecurityStrategy')),
  },
  {
    id: 'awsscs-control-tower-guardrail-types',
    certId: 'awsscs',
    domain: 6,
    title: 'Control Tower Guardrail Types',
    description: 'click a card to reveal what each guardrail category actually does.',
    Component: lazy(() => import('./awsscs/ControlTowerGuardrails')),
  },
  {
    id: 'awsscs-cost-allocation-tags-as-a-governance-signal',
    certId: 'awsscs',
    domain: 6,
    title: 'Cost Allocation Tags as a Governance Signal',
    description: 'adjust tag coverage to see how it drives a governance visibility score.',
    Component: lazy(() => import('./awsscs/CostAllocationTagsForGovernance')),
  },
  {
    id: 'cissp-choosing-a-threat-modeling-methodology',
    certId: 'cissp',
    domain: 1,
    title: 'Choosing a Threat Modeling Methodology',
    description: 'pick the scenario driving your threat model and see which methodology fits.',
    Component: lazy(() => import('./cissp/ThreatModelingMethods')),
  },
  {
    id: 'cissp-due-diligence-vs-due-care',
    certId: 'cissp',
    domain: 1,
    title: 'Due Diligence vs Due Care',
    description: 'toggle between the research step and the action step of the prudent-person rule.',
    Component: lazy(() => import('./cissp/DueCareVsDueDiligence')),
  },
  {
    id: 'cissp-security-control-categories-by-timing',
    certId: 'cissp',
    domain: 1,
    title: 'Security Control Categories by Timing',
    description: 'click a tier to see where it sits in the incident timeline, from deterring an attacker to recovering from one.',
    Component: lazy(() => import('./cissp/SecurityControlCategories')),
  },
  {
    id: 'cissp-world-legal-system-families',
    certId: 'cissp',
    domain: 1,
    title: 'World Legal System Families',
    description: 'slide across the major legal system types recognized for cross-border compliance work.',
    Component: lazy(() => import('./cissp/LegalSystemSpectrum')),
  },
  {
    id: 'cissp-asset-and-data-ownership-roles',
    certId: 'cissp',
    domain: 2,
    title: 'Asset & Data Ownership Roles',
    description: 'click a role to see where it sits in the chain of accountability, from executive owner down to end user.',
    Component: lazy(() => import('./cissp/AssetOwnershipHierarchy')),
  },
  {
    id: 'cissp-clear-purge-or-destroy',
    certId: 'cissp',
    domain: 2,
    title: 'Clear, Purge, or Destroy?',
    description: 'pick a media type and disposition to see the NIST 800-88 sanitization category it demands.',
    Component: lazy(() => import('./cissp/DataSanitizationDecision')),
  },
  {
    id: 'cissp-core-privacy-principles',
    certId: 'cissp',
    domain: 2,
    title: 'Core Privacy Principles',
    description: 'click a principle to flip it and reveal what it actually requires.',
    Component: lazy(() => import('./cissp/PrivacyPrinciplesMatcher')),
  },
  {
    id: 'cissp-the-three-states-of-data',
    certId: 'cissp',
    domain: 2,
    title: 'The Three States of Data',
    description: 'step through at rest, in transit, and in use to see which control applies where.',
    Component: lazy(() => import('./cissp/DataStateControls')),
  },
  {
    id: 'cissp-casb-the-four-pillars',
    certId: 'cissp',
    domain: 3,
    title: 'CASB: The Four Pillars',
    description: 'watch a cloud request pass through a Cloud Access Security Broker\'s core functions.',
    Component: lazy(() => import('./cissp/CloudAccessSecurityBroker')),
  },
  {
    id: 'cissp-clark-wilson-vs-brewer-nash',
    certId: 'cissp',
    domain: 3,
    title: 'Clark-Wilson vs. Brewer-Nash',
    description: 'compare an integrity model against a conflict-of-interest model side by side.',
    Component: lazy(() => import('./cissp/SecurityModelsComparison')),
  },
  {
    id: 'cissp-defense-in-depth-layered-detection',
    certId: 'cissp',
    domain: 3,
    title: 'Defense in Depth: Layered Detection',
    description: 'adjust the number of independent layers and each layer\'s detection rate to see why redundant, independent controls compound.',
    Component: lazy(() => import('./cissp/DefenseInDepthCalculator')),
  },
  {
    id: 'cissp-layered-physical-defense',
    certId: 'cissp',
    domain: 3,
    title: 'Layered Physical Defense',
    description: 'step through the five stages of physical security, from discouraging an attacker to responding to one.',
    Component: lazy(() => import('./cissp/PhysicalSecurityLayers')),
  },
  {
    id: 'cissp-802-1-x-port-based-nac-sequence',
    certId: 'cissp',
    domain: 4,
    title: '802.1X Port-Based NAC Sequence',
    description: 'use the arrows to put the 802.1X authentication handshake in order, then check.',
    Component: lazy(() => import('./cissp/NetworkAccessControl8021X')),
  },
  {
    id: 'cissp-securing-converged-voice-vo-ip-sip',
    certId: 'cissp',
    domain: 4,
    title: 'Securing Converged Voice (VoIP/SIP)',
    description: 'toggle between an unsecured and a hardened SIP/VoIP deployment.',
    Component: lazy(() => import('./cissp/ConvergedProtocolsRisk')),
  },
  {
    id: 'cissp-which-secure-protocol-fits',
    certId: 'cissp',
    domain: 4,
    title: 'Which Secure Protocol Fits?',
    description: 'pick a use case to see which secure channel protocol it calls for and why.',
    Component: lazy(() => import('./cissp/SecureProtocolComparison')),
  },
  {
    id: 'cissp-wireless-security-standards',
    certId: 'cissp',
    domain: 4,
    title: 'Wireless Security Standards',
    description: 'slide across the Wi-Fi security generations to see how encryption, key management, and attack resistance improved.',
    Component: lazy(() => import('./cissp/WirelessSecurityArchitecture')),
  },
  {
    id: 'cissp-biometric-sensitivity-far-vs-frr-trade-off',
    certId: 'cissp',
    domain: 5,
    title: 'Biometric Sensitivity: FAR vs. FRR Trade-off',
    description: 'slide the sensor threshold and watch false acceptance and false rejection trade off.',
    Component: lazy(() => import('./cissp/BiometricThresholdSpectrum')),
  },
  {
    id: 'cissp-kerberos-authentication-flow',
    certId: 'cissp',
    domain: 5,
    title: 'Kerberos Authentication Flow',
    description: 'watch the ticket-granting handshake between client, KDC, and service.',
    Component: lazy(() => import('./cissp/KerberosAuthFlow')),
  },
  {
    id: 'cissp-standing-privileged-access-vs-just-in-time-jit',
    certId: 'cissp',
    domain: 5,
    title: 'Standing Privileged Access vs. Just-in-Time (JIT)',
    description: 'toggle to compare always-on admin rights with time-bound, brokered elevation.',
    Component: lazy(() => import('./cissp/JitPrivilegedAccessToggle')),
  },
  {
    id: 'cissp-the-identity-and-access-provisioning-lifecycle',
    certId: 'cissp',
    domain: 5,
    title: 'The Identity & Access Provisioning Lifecycle',
    description: 'step through an identity from hire to deprovisioning.',
    Component: lazy(() => import('./cissp/IdentityLifecycleTimeline')),
  },
  {
    id: 'cissp-choosing-a-code-review-method',
    certId: 'cissp',
    domain: 6,
    title: 'Choosing a Code Review Method',
    description: 'pick your access level and goal to see which review technique fits.',
    Component: lazy(() => import('./cissp/CodeReviewMethodMatrix')),
  },
  {
    id: 'cissp-security-control-testing-techniques',
    certId: 'cissp',
    domain: 6,
    title: 'Security Control Testing Techniques',
    description: 'click a card to reveal how each control-testing technique actually works.',
    Component: lazy(() => import('./cissp/ControlTestingMethodMatcher')),
  },
  {
    id: 'cissp-test-coverage-strategies-weakest-to-strongest',
    certId: 'cissp',
    domain: 6,
    title: 'Test Coverage Strategies, Weakest to Strongest',
    description: 'use the arrows to order these from weakest to strongest rigor, then check.',
    Component: lazy(() => import('./cissp/CoverageStrategyOrdering')),
  },
  {
    id: 'cissp-vulnerability-assessment-vs-penetration-test-vs-red-team',
    certId: 'cissp',
    domain: 6,
    title: 'Vulnerability Assessment vs. Penetration Test vs. Red Team',
    description: 'click a tier to see how scope, stealth, and realism escalate.',
    Component: lazy(() => import('./cissp/AssessmentIntensityStack')),
  },
  {
    id: 'cissp-disaster-recovery-plan-test-types',
    certId: 'cissp',
    domain: 7,
    title: 'Disaster Recovery Plan Test Types',
    description: 'order these DR test types from least to most disruptive, then check.',
    Component: lazy(() => import('./cissp/DrTestTypeOrdering')),
  },
  {
    id: 'cissp-risk-based-patch-priority-calculator',
    certId: 'cissp',
    domain: 7,
    title: 'Risk-Based Patch Priority Calculator',
    description: 'adjust the inputs to see how a patch\'s priority and SLA are derived.',
    Component: lazy(() => import('./cissp/PatchPriorityCalculator')),
  },
  {
    id: 'cissp-the-digital-forensics-investigation-process',
    certId: 'cissp',
    domain: 7,
    title: 'The Digital Forensics Investigation Process',
    description: 'step through evidence handling from first response to presentation.',
    Component: lazy(() => import('./cissp/ForensicsInvestigationTimeline')),
  },
  {
    id: 'cissp-the-logging-and-monitoring-pipeline',
    certId: 'cissp',
    domain: 7,
    title: 'The Logging & Monitoring Pipeline',
    description: 'step through how a raw log event becomes an analyst\'s alert.',
    Component: lazy(() => import('./cissp/LogMonitoringPipelineDiagram')),
  },
  {
    id: 'cissp-application-security-testing-tools-across-the-sdlc',
    certId: 'cissp',
    domain: 8,
    title: 'Application Security Testing Tools Across the SDLC',
    description: 'slide across SAST, SCA, IAST, and DAST to compare where and how each runs.',
    Component: lazy(() => import('./cissp/AppSecTestingToolsSpectrum')),
  },
  {
    id: 'cissp-common-software-weakness-categories-cwe-style',
    certId: 'cissp',
    domain: 8,
    title: 'Common Software Weakness Categories (CWE-style)',
    description: 'click a category to see how it shows up at the source-code level.',
    Component: lazy(() => import('./cissp/SecureCodingWeaknessStack')),
  },
  {
    id: 'cissp-database-security-aggregation-and-inference',
    certId: 'cissp',
    domain: 8,
    title: 'Database Security: Aggregation & Inference',
    description: 'toggle to compare a database exposed to aggregation/inference with one hardened against it.',
    Component: lazy(() => import('./cissp/DatabaseSecurityToggle')),
  },
  {
    id: 'cissp-waterfall-vs-agile-dev-sec-ops',
    certId: 'cissp',
    domain: 8,
    title: 'Waterfall vs. Agile / DevSecOps',
    description: 'compare how each development methodology integrates (or bolts on) security.',
    Component: lazy(() => import('./cissp/DevMethodologyComparison')),
  },
]

export function conceptsForCert(certId: string): ConceptEntry[] {
  return CONCEPTS.filter((c) => c.certId === certId)
}
