-- AWS Security Specialty (SCS-C02) Domain 5 (Data Protection) expansion: 5.1 data-at-rest (S3 SSE variants/Bucket Keys/default encryption, EBS/RDS/DynamoDB/EFS/Redshift/Secrets Manager encryption-at-rest mechanics, encrypted AMI cross-account sharing, Macie custom vs managed identifiers and automated discovery, S3 Block Public Access's four settings), 5.2 data-in-transit (ACM, ACM Private CA, ALB/NLB/CloudFront TLS policies and SNI, mutual TLS, Site-to-Site VPN, Direct Connect's lack of default encryption plus MACsec, RDS/OpenSearch in-transit enforcement, S3 TLS-version enforcement) largely from scratch, and 5.3 key management (multi-Region KMS keys, KMS grant tokens, KMS scheduled-deletion waiting period) as a small non-duplicating addition.

insert into public.flashcards (id, cert, deck, domain, objective, front, back) values
-- 5.1 Data at Rest: core flashcards
('sc-f-600','awsscs','core',5,'5.1',$$What are the three S3 server-side encryption options and who manages the key in each?$$,$$SSE-S3 uses S3-managed keys (fully automatic, no KMS visibility/audit); SSE-KMS uses a KMS key you control with CloudTrail auditing, key policies, and grants; SSE-C uses a customer-supplied key sent with each request that AWS never stores.$$),
('sc-f-601','awsscs','core',5,'5.1',$$What problem do S3 Bucket Keys solve for SSE-KMS?$$,$$Without them, every SSE-KMS object request calls KMS individually, which is costly at scale; a bucket key is a short-lived, bucket-level key derived from the KMS key that S3 uses to encrypt many objects, sharply cutting KMS API call volume and cost.$$),
('sc-f-602','awsscs','core',5,'5.1',$$What does enabling default encryption on an S3 bucket do?$$,$$Automatically encrypts every new object with the chosen method (SSE-S3 or SSE-KMS) even if the PUT request specifies no encryption header, so applications don't need code changes to get encryption at rest.$$),
('sc-f-603','awsscs','core',5,'5.1',$$What does the "EBS encryption by default" account setting do, and what happens to copies?$$,$$Once enabled per Region, every new EBS volume and snapshot is encrypted automatically; a snapshot or AMI created from an already-encrypted volume stays encrypted, and copying a snapshot lets you re-encrypt it under a different KMS key.$$),
('sc-f-604','awsscs','core',5,'5.1',$$When can you enable encryption at rest on an existing RDS or Aurora database?$$,$$Never in place - encryption is set only at creation time. To encrypt an existing unencrypted instance, you take a snapshot, copy that snapshot with encryption enabled, and restore a new encrypted instance from the copy.$$),
('sc-f-605','awsscs','core',5,'5.1',$$What are DynamoDB's three encryption-at-rest key options?$$,$$AWS owned key (default, free, not visible in your account), AWS managed key (aws/dynamodb in your KMS, some visibility/audit), and a customer managed KMS key (full control over policy, rotation, and grants).$$),
('sc-f-606','awsscs','core',5,'5.1',$$When must you enable encryption at rest for an EFS file system?$$,$$At creation time only - EFS encryption at rest cannot be turned on for an existing unencrypted file system; you must create a new encrypted file system and migrate the data (e.g., with AWS DataSync).$$),
('sc-f-607','awsscs','core',5,'5.1',$$Unlike RDS, when can you enable encryption on an existing Amazon Redshift cluster?$$,$$Redshift lets you modify an existing unencrypted cluster to enable KMS encryption; it automatically creates an encrypted copy behind the scenes and migrates to it, unlike RDS which requires a manual snapshot-and-restore.$$),
('sc-f-608','awsscs','core',5,'5.1',$$How are Secrets Manager secrets and SSM Parameter Store SecureString parameters encrypted at rest?$$,$$Both encrypt their values using a KMS key (an AWS managed key by default, or a customer managed key you specify) - plaintext is only ever exposed to a caller with the matching KMS decrypt permission and the appropriate service permission.$$),
('sc-f-609','awsscs','core',5,'5.1',$$What are the four individual S3 Block Public Access settings?$$,$$BlockPublicAcls (rejects new public ACLs), IgnorePublicAcls (ignores existing public ACLs), BlockPublicPolicy (rejects bucket policies granting public access), and RestrictPublicBuckets (restricts access for buckets with a public policy to AWS services/authorized users only) - settable at the account or bucket level.$$),
-- 5.2 Data in Transit: core flashcards
('sc-f-610','awsscs','core',5,'5.2',$$What does AWS Certificate Manager (ACM) provide, and how are public certificates renewed?$$,$$ACM issues and manages free public TLS/SSL certificates for use with integrated services (ALB/NLB, CloudFront, API Gateway) and handles automatic renewal via DNS or email validation - eliminating manual certificate tracking and expiry risk.$$),
('sc-f-611','awsscs','core',5,'5.2',$$What is AWS Private Certificate Authority (Private CA) used for?$$,$$Issuing private TLS certificates for internal resources (internal load balancers, IoT devices, service-to-service mTLS) that don't need a publicly trusted certificate - your organization becomes its own certificate authority, trusted only within your infrastructure.$$),
('sc-f-612','awsscs','core',5,'5.2',$$What does a load balancer's TLS security policy control?$$,$$The minimum TLS protocol version and the set of allowed cipher suites for HTTPS/TLS listeners on an ALB or NLB - choosing a modern policy (e.g., requiring TLS 1.2+) blocks clients that only support outdated, weaker protocols.$$),
('sc-f-613','awsscs','core',5,'5.2',$$What is the difference between CloudFront's viewer protocol policy and origin protocol policy?$$,$$Viewer protocol policy controls how end users connect to CloudFront (e.g., "Redirect HTTP to HTTPS" or "HTTPS only"); origin protocol policy separately controls how CloudFront itself connects back to your origin server - both hops must be configured for end-to-end encryption.$$),
('sc-f-614','awsscs','core',5,'5.2',$$How does CloudFront let you use a custom domain with a modern minimum TLS version?$$,$$Attach an ACM certificate for the custom domain and choose a security policy specifying the minimum TLS protocol version; CloudFront uses SNI to serve the correct certificate for each domain sharing the same edge infrastructure.$$),
('sc-f-615','awsscs','core',5,'5.2',$$What does mutual TLS (mTLS) add on top of standard TLS for an API Gateway endpoint?$$,$$Standard TLS only proves the server's identity to the client; mTLS additionally requires the client to present a trusted certificate, so API Gateway also verifies who is calling - used for high-assurance service-to-service or B2B integrations.$$),
('sc-f-616','awsscs','core',5,'5.2',$$What protects data in transit over an AWS Site-to-Site VPN connection?$$,$$IPsec tunnels encrypt traffic between the on-premises gateway and the AWS Virtual Private Gateway/Transit Gateway, providing confidentiality and integrity over the underlying public internet path.$$),
('sc-f-617','awsscs','core',5,'5.2',$$Is traffic over an AWS Direct Connect connection encrypted by default?$$,$$No - Direct Connect provides a private, dedicated network path but does NOT encrypt traffic by default; to add encryption you must run a VPN over Direct Connect or use MACsec on supported connections.$$),
('sc-f-618','awsscs','core',5,'5.2',$$What is MACsec on AWS Direct Connect?$$,$$A native Layer 2 encryption standard available on certain Direct Connect connections (dedicated 10/100 Gbps ports) that encrypts traffic point-to-point on the physical link, without the overhead of an IPsec VPN tunnel.$$),
('sc-f-619','awsscs','core',5,'5.2',$$How do you enforce that clients only connect to an RDS/Aurora database over an encrypted connection?$$,$$Set the engine's SSL-enforcement parameter (e.g., rds.force_ssl for PostgreSQL) in the DB parameter group, or require SSL/TLS in the database user's grants - unencrypted connection attempts are then rejected.$$),
('sc-f-620','awsscs','core',5,'5.2',$$What are the two separate in-transit encryption settings for an Amazon OpenSearch Service domain?$$,$$Node-to-node encryption (TLS between the cluster's own data nodes) and enforced HTTPS (TLS between clients and the domain's endpoint) - both must be enabled to fully protect traffic, since they cover different hops.$$),
('sc-f-621','awsscs','core',5,'5.2',$$How can an S3 bucket policy reject requests that use TLS versions older than 1.2?$$,$$A Deny statement conditioned on the aws:TlsVersion key (using NumericLessThan on the version), alongside aws:SecureTransport, blocks any request that connects with HTTP or with an outdated TLS version.$$),
-- 5.3 Key Management + Immutability: core flashcards
('sc-f-622','awsscs','core',5,'5.3',$$What are KMS multi-Region keys and what problem do they solve?$$,$$A multi-Region key is a set of KMS keys in different Regions that share the same key material and key ID, letting you encrypt in one Region and decrypt in another without re-encrypting the data - useful for global applications and disaster recovery, though each replica is still managed independently for policy/rotation.$$),
('sc-f-623','awsscs','core',5,'5.3',$$What happens when you schedule deletion of a KMS customer managed key?$$,$$KMS enforces a mandatory waiting period of 7 to 30 days (you choose) before permanently destroying the key; during that window the key is disabled and unusable, but deletion can still be canceled - protecting against accidental, irreversible loss of access to encrypted data.$$),
-- acronyms
('sc-a-180','awsscs','acronym',5,'5.1',$$SSE$$,$$Server-Side Encryption - S3 encrypts objects at rest using S3-managed (SSE-S3), KMS (SSE-KMS), or customer-provided (SSE-C) keys.$$),
('sc-a-181','awsscs','acronym',5,'5.1',$$PII$$,$$Personally Identifiable Information - sensitive data type (names, SSNs, card numbers) that Amazon Macie's managed data identifiers are built to discover in S3.$$),
('sc-a-182','awsscs','acronym',5,'5.2',$$ACM$$,$$AWS Certificate Manager - provisions, manages, and auto-renews public or private TLS certificates for integrated AWS services.$$),
('sc-a-183','awsscs','acronym',5,'5.2',$$mTLS$$,$$Mutual TLS - both client and server present certificates, so each verifies the other's identity, not just the server's.$$),
('sc-a-184','awsscs','acronym',5,'5.2',$$SNI$$,$$Server Name Indication - a TLS extension letting a server present the correct certificate when multiple domains share one IP/listener.$$),
('sc-a-185','awsscs','acronym',5,'5.2',$$MACsec$$,$$Media Access Control Security - IEEE Layer 2 encryption standard supported on certain AWS Direct Connect connections.$$),
('sc-a-186','awsscs','acronym',5,'5.3',$$MRK$$,$$Multi-Region Key - a KMS key replicated across Regions with shared key material and ID, letting ciphertext be decrypted in another Region without re-encryption.$$),
-- feynman
('sc-y-090','awsscs','feynman',5,'5.1',$$Explain why enabling encryption on an existing RDS database requires a snapshot-and-restore, while Redshift lets you just modify the cluster.$$,$$Model answer: RDS treats the storage encryption setting as fixed at creation - the underlying encrypted storage volume and the way RDS wires the KMS key into replication and backups can't be swapped in place, so the only path is to snapshot the database, copy that snapshot with encryption turned on, and restore a brand-new instance from the encrypted copy, then cut the application over. Redshift built a live migration path instead: when you modify an existing cluster to enable encryption, Redshift transparently creates a fully encrypted copy of the cluster in the background and switches over to it once it's ready, so you request it as a simple modification instead of doing the snapshot dance yourself. Same underlying constraint - you can't encrypt existing blocks without rewriting them - just different services chose to expose or hide that plumbing.$$),
('sc-y-091','awsscs','feynman',5,'5.1',$$Explain the difference between Amazon Macie's managed data identifiers and custom data identifiers.$$,$$Model answer: Managed data identifiers are AWS-built detectors for common sensitive data types - credit card numbers, SSNs, passport numbers, credentials - that come ready to use with no configuration, covering the patterns most organizations care about. Custom data identifiers are regex patterns you define yourself for data that's sensitive to your specific business but not a standard type - like an internal employee ID format or a proprietary account number scheme. You typically run both together: managed identifiers catch the universal categories, and custom identifiers catch the organization-specific ones regex can't guess for you.$$),
('sc-y-092','awsscs','feynman',5,'5.2',$$Explain why CloudFront needs both a viewer protocol policy and an origin protocol policy to achieve full end-to-end encryption.$$,$$Model answer: CloudFront sits in the middle of two separate network hops - the "viewer" hop from the end user's browser to the CloudFront edge, and the "origin" hop from that edge back to your actual server. Each hop is configured independently. The viewer protocol policy only decides whether users connecting to CloudFront must use HTTPS - it says nothing about what CloudFront does next. If you stop there, CloudFront might still fetch content from your origin over plain HTTP, leaving that second hop exposed. The origin protocol policy is what forces CloudFront itself to speak HTTPS when it goes to fetch or refresh content from your server. You need both set to HTTPS-only for genuinely end-to-end encrypted delivery; setting just one leaves half the path in the clear.$$),
('sc-y-093','awsscs','feynman',5,'5.2',$$Explain why AWS Direct Connect is often mistakenly assumed to be encrypted, and how to actually add encryption to it.$$,$$Model answer: Direct Connect gives you a dedicated, private physical network path from your data center into AWS, bypassing the public internet entirely - and "private" gets confused with "encrypted," but they're different properties. Nothing about that dedicated link scrambles the bits traveling over it; anyone with physical access to the link's path could theoretically read the data. If you need confidentiality, you have two real options: run a Site-to-Site VPN (IPsec) on top of the Direct Connect connection, which re-adds the encryption layer at the cost of some throughput and complexity, or use MACsec, which is native Layer 2 encryption available on qualifying dedicated Direct Connect ports and adds negligible overhead. The private path solves exposure to the internet at large; encryption is a separate control you have to add deliberately on top of it.$$);

insert into public.questions (id, cert, domain, objective, qtype, difficulty, stem, choices, answer, explanation) values
-- 5.1 Data at Rest
('sc-q-600','awsscs',5,'5.1','mcq',2,$q$A team wants S3 objects encrypted at rest with full CloudTrail visibility into every key usage, a key policy they control, and the ability to issue temporary grants. Which S3 encryption option fits?$q$,$q$["SSE-S3 with S3-managed keys","SSE-KMS with a customer managed KMS key","SSE-C with a customer-supplied key","Client-side encryption with no S3 configuration"]$q$::jsonb,'1'::jsonb,$q$SSE-KMS with a customer managed key gives CloudTrail-logged key usage, a key policy you author, and grant-based delegation. SSE-S3 keys are fully managed by S3 with no visibility into individual key operations; SSE-C requires sending the key with every request and AWS never stores it, so KMS auditing/grants don't apply; unmanaged client-side encryption bypasses S3-integrated key management entirely.$q$),
('sc-q-601','awsscs',5,'5.1','mcq',2,$q$An application encrypts millions of objects per day with SSE-KMS and is hitting high KMS request charges. What reduces this cost without switching away from KMS-backed encryption?$q$,$q$["Enabling S3 Bucket Keys","Switching every object to SSE-C","Disabling default encryption","Increasing the KMS key's rotation frequency"]$q$::jsonb,'0'::jsonb,$q$S3 Bucket Keys generate a short-lived, bucket-level key from the KMS key that S3 reuses to encrypt many objects, dramatically cutting the number of individual KMS API calls and their cost. SSE-C shifts key handling to the client rather than reducing KMS calls, disabling default encryption removes protection rather than cutting cost safely, and rotation frequency doesn't affect per-request API costs.$q$),
('sc-q-602','awsscs',5,'5.1','mcq',1,$q$Developers frequently forget to set the encryption header when uploading to an S3 bucket, leaving some objects unencrypted. What setting guarantees every new object is encrypted regardless of the request?$q$,$q$["S3 Transfer Acceleration","S3 default encryption on the bucket","S3 Requester Pays","S3 Intelligent-Tiering"]$q$::jsonb,'1'::jsonb,$q$Default encryption applies the configured method (SSE-S3 or SSE-KMS) to every new object automatically, even when the PUT request omits the encryption header - no application changes required. The other settings control transfer speed, billing, and storage-class automation, not encryption.$q$),
('sc-q-603','awsscs',5,'5.1','mcq',2,$q$An account enables the "EBS encryption by default" setting in us-east-1. What is the effect?$q$,$q$["Every existing unencrypted volume in us-east-1 is immediately re-encrypted","Every new EBS volume and snapshot created in us-east-1 from that point on is encrypted automatically","It encrypts volumes in all Regions simultaneously","It only affects volumes attached to instances launched via Auto Scaling"]$q$::jsonb,'1'::jsonb,$q$The setting is per-Region and forward-looking: new volumes and snapshots created after enabling it are automatically encrypted, but existing unencrypted volumes are untouched and must be migrated manually (e.g., snapshot, copy encrypted, create new volume). It does not apply retroactively, globally, or only to Auto Scaling launches.$q$),
('sc-q-604','awsscs',5,'5.1','matching',3,$q$Match each AWS data store to how its encryption-at-rest setting behaves.$q$,$q${"left":["Amazon RDS","Amazon Redshift","Amazon DynamoDB","Amazon EFS"],"right":["Always encrypted at rest with a choice of AWS owned, AWS managed, or customer managed key","Fixed at creation - an existing unencrypted file system must be replaced and data migrated","Can be enabled on an existing cluster via a modify operation that migrates data behind the scenes","Fixed at creation - encrypting an existing instance requires snapshot, encrypted copy, and restore"]}$q$::jsonb,$q$[3,2,0,1]$q$::jsonb,$q$RDS and EFS both lock in the encryption setting at creation and require building a new encrypted resource and migrating data; Redshift instead offers a live modify path that migrates in the background; DynamoDB is always encrypted, only the key tier changes. Recognizing which services allow in-place changes versus which force a rebuild is a common exam distinction.$q$),
('sc-q-605','awsscs',5,'5.1','mcq',3,$q$A team wants to share an AMI backed by a KMS-encrypted snapshot with another AWS account so that account can launch instances from it. Sharing the AMI itself is not enough. What else is required?$q$,$q$["Nothing else - AMI sharing alone grants full access to the underlying encrypted snapshot","The target account must be granted permission to use the KMS key (via the key policy or a grant), since AMI sharing alone doesn't include key access","The KMS key must be deleted before sharing","The snapshot must first be decrypted"]$q$::jsonb,'1'::jsonb,$q$Sharing an encrypted AMI shares the AMI metadata and snapshot reference, but the receiving account still needs explicit permission on the KMS key itself (via the key policy or a grant) to decrypt the snapshot and launch instances - key access and resource sharing are separate steps. Deleting the key or decrypting the snapshot would break the very encryption being relied on.$q$),
('sc-q-606','awsscs',5,'5.1','mcq',1,$q$A table is created in DynamoDB without specifying any encryption key. Which key protects it at rest, and what is the cost implication?$q$,$q$["No encryption is applied by default","The AWS owned key, at no additional cost","A customer managed key is created automatically and billed hourly","Data remains in plaintext until a key is manually attached"]$q$::jsonb,'1'::jsonb,$q$DynamoDB tables are always encrypted at rest; if you don't choose otherwise, the AWS owned key is used, which is free and has no visible key resource in your account. Choosing the AWS managed or a customer managed key trades that transparency for auditability, policy control, or (for customer managed) an hourly KMS charge.$q$),
('sc-q-607','awsscs',5,'5.1','mcq',2,$q$A team realizes their production EFS file system was created without encryption at rest enabled. What is required to fix this?$q$,$q$["Enable an EFS setting to turn on encryption in place","Create a new encrypted EFS file system and migrate the data to it, then cut over","Encryption cannot ever be added to EFS data","Attach a KMS key to the existing file system's properties"]$q$::jsonb,'1'::jsonb,$q$EFS encryption at rest is fixed at creation and cannot be toggled on for an existing file system; the standard fix is to create a new encrypted file system, migrate the data (e.g., via AWS DataSync), and repoint workloads to it. There is no in-place toggle or key-attachment option after creation.$q$),
('sc-q-608','awsscs',5,'5.1','multi',2,$q$Which of the following are among S3 Block Public Access's four individually configurable settings? (Select all that apply.)$q$,$q$["BlockPublicAcls","RestrictPublicBuckets","EnableVersioning","IgnorePublicAcls"]$q$::jsonb,$q$[0,1,3]$q$::jsonb,$q$BlockPublicAcls, IgnorePublicAcls, BlockPublicPolicy, and RestrictPublicBuckets are the four Block Public Access settings; EnableVersioning is an unrelated S3 feature governing object version history, not public access.$q$),
('sc-q-609','awsscs',5,'5.1','mcq',2,$q$A company needs Macie to flag a proprietary internal account-number format that isn't a standard PII type. What should they configure?$q$,$q$["A managed data identifier, since it already covers every possible format","A custom data identifier using a regex pattern matching the internal format","Disable Macie and review manually","An S3 lifecycle rule"]$q$::jsonb,'1'::jsonb,$q$Custom data identifiers let you define your own regex pattern for organization-specific sensitive data that managed (built-in) identifiers, which target common standard PII types, don't recognize. Managed identifiers alone would miss a proprietary format; lifecycle rules and manual review don't perform content classification.$q$),
('sc-q-610','awsscs',5,'5.1','mcq',1,$q$A security team wants Macie to continuously and automatically sample S3 buckets over time for newly appearing sensitive data, without manually scheduling each scan. What should they enable?$q$,$q$["A one-time classification job run manually each week","Macie's automated sensitive data discovery","S3 Inventory reports","GuardDuty S3 Protection"]$q$::jsonb,'1'::jsonb,$q$Automated sensitive data discovery continuously and automatically evaluates buckets over time, prioritizing based on prior findings, without requiring a manually scheduled job. A one-time job only covers a single point-in-time scan, S3 Inventory only lists objects without classifying content, and GuardDuty S3 Protection detects anomalous access rather than classifying data.$q$),
('sc-q-611','awsscs',5,'5.1','ordering',3,$q$Order the steps to add encryption at rest to an existing unencrypted RDS database.$q$,$q$["Restore a new DB instance from the encrypted snapshot copy","Create a snapshot of the unencrypted DB instance","Redirect the application to the new encrypted instance and decommission the old one","Copy the snapshot, enabling encryption on the copy"]$q$::jsonb,$q$[1,3,0,2]$q$::jsonb,$q$You must first capture the current state as a snapshot, then create an encrypted copy of that snapshot (encryption can't be toggled on the original), restore a new instance from the encrypted copy, and finally cut the application over before retiring the old unencrypted instance.$q$),
-- 5.2 Data in Transit
('sc-q-612','awsscs',5,'5.2','mcq',1,$q$Which AWS service issues free public TLS certificates and automatically renews them for use with an Application Load Balancer?$q$,$q$["AWS Certificate Manager (ACM)","AWS Secrets Manager","AWS KMS","AWS Config"]$q$::jsonb,'0'::jsonb,$q$ACM issues and auto-renews public TLS certificates at no additional charge for integrated services like ALB, CloudFront, and API Gateway. Secrets Manager stores secrets, KMS manages encryption keys (not certificates), and Config tracks resource configuration.$q$),
('sc-q-613','awsscs',5,'5.2','mcq',3,$q$An internal microservice mesh needs TLS certificates for service-to-service traffic that never leaves the company's own infrastructure and doesn't need public browser trust. What should be used to issue these certificates?$q$,$q$["A public ACM certificate","AWS Private Certificate Authority (Private CA)","A self-signed certificate generated ad hoc on each host","S3 default encryption"]$q$::jsonb,'1'::jsonb,$q$Private CA lets you run your own internal certificate authority, issuing trusted-within-your-org certificates for internal-only services - exactly this use case. Public ACM certificates are meant for publicly resolvable domains, ad hoc self-signed certs create unmanageable trust and rotation problems at scale, and S3 default encryption is unrelated to TLS certificates.$q$),
('sc-q-614','awsscs',5,'5.2','mcq',1,$q$A compliance requirement mandates that an Application Load Balancer reject any client connection attempting to negotiate TLS 1.0 or 1.1. How is this enforced?$q$,$q$["Selecting a TLS security policy on the HTTPS listener that sets a TLS 1.2+ minimum","Adding a WAF rule blocking old browsers","Enabling S3 Block Public Access","Rotating the ACM certificate more frequently"]$q$::jsonb,'0'::jsonb,$q$The listener's TLS security policy defines the minimum protocol version and cipher suites accepted; choosing a policy with a 1.2+ minimum causes the ALB to refuse the TLS handshake for older protocol attempts. WAF rules filter HTTP content, not protocol negotiation; Block Public Access is an S3 feature; certificate rotation doesn't affect protocol version enforcement.$q$),
('sc-q-615','awsscs',5,'5.2','matching',2,$q$Match each CloudFront setting to the connection hop it protects.$q$,$q${"left":["Viewer protocol policy","Origin protocol policy"],"right":["Encryption between the CloudFront edge location and your origin server","Encryption between the end user's browser and the CloudFront edge location"]}$q$::jsonb,$q$[1,0]$q$::jsonb,$q$The viewer protocol policy governs the client-to-edge hop (e.g., forcing HTTPS from browsers), while the origin protocol policy independently governs the edge-to-origin hop; both must be set to HTTPS to achieve full end-to-end encryption, since misconfiguring either leaves one hop exposed.$q$),
('sc-q-616','awsscs',5,'5.2','mcq',3,$q$A B2B partner integration requires that an API Gateway endpoint verify the calling client's identity via a certificate, not just present its own certificate to the caller. What should be configured?$q$,$q$["Standard one-way TLS with an ACM certificate","Mutual TLS (mTLS), requiring the client to present a trusted certificate","An API key in the request header","IAM resource policies on the API"]$q$::jsonb,'1'::jsonb,$q$mTLS requires both sides to present certificates, letting API Gateway cryptographically verify the client's identity in addition to the client verifying the server - standard one-way TLS only does the latter. API keys and IAM resource policies can restrict access but don't perform certificate-based mutual authentication at the TLS layer.$q$),
('sc-q-617','awsscs',5,'5.2','mcq',1,$q$What protocol provides the encryption for an AWS Site-to-Site VPN connection between an on-premises network and a VPC?$q$,$q$["IPsec","TLS 1.3 only","SSH","MACsec"]$q$::jsonb,'0'::jsonb,$q$Site-to-Site VPN establishes IPsec tunnels to encrypt and authenticate traffic between the customer gateway and AWS. TLS secures application-layer HTTP traffic rather than whole-network VPN tunnels, SSH secures remote shell sessions, and MACsec is a Direct Connect Layer 2 feature, not VPN.$q$),
('sc-q-618','awsscs',5,'5.2','mcq',2,$q$A company assumes their AWS Direct Connect connection is automatically encrypting all traffic because it bypasses the public internet. Is this assumption correct?$q$,$q$["Yes, Direct Connect encrypts all traffic by default","No - Direct Connect provides a private dedicated path but no encryption by default; a VPN overlay or MACsec must be added","No - Direct Connect cannot carry encrypted traffic at all","Yes, but only for traffic to S3"]$q$::jsonb,'1'::jsonb,$q$Direct Connect's privacy comes from bypassing the shared public internet, not from encrypting the bits on the wire; achieving confidentiality requires layering a VPN (IPsec) over the connection or using MACsec on qualifying ports. It's not that encrypted traffic is impossible - it's simply not automatic, and it's not scoped only to S3.$q$),
('sc-q-619','awsscs',5,'5.2','mcq',3,$q$A company wants native Layer 2 encryption on a dedicated 10 Gbps Direct Connect port, without the throughput overhead of an IPsec VPN tunnel. What should they use?$q$,$q$["MACsec","Site-to-Site VPN over Direct Connect","TLS termination at the Direct Connect router","S3 Transfer Acceleration"]$q$::jsonb,'0'::jsonb,$q$MACsec provides native, low-overhead Layer 2 encryption directly on qualifying dedicated Direct Connect connections. A VPN overlay works but adds IPsec tunneling overhead; Direct Connect routers don't terminate application-layer TLS, and Transfer Acceleration is an unrelated S3 upload feature.$q$),
('sc-q-620','awsscs',5,'5.2','mcq',2,$q$A security review requires that a PostgreSQL RDS instance reject any client connection that isn't using SSL/TLS. What enforces this?$q$,$q$["Setting the rds.force_ssl parameter to enabled in the DB parameter group","Enabling S3 Block Public Access","Rotating the master password","Enabling Multi-AZ"]$q$::jsonb,'0'::jsonb,$q$The rds.force_ssl parameter (in the relevant parameter group) makes the PostgreSQL engine reject non-SSL connection attempts outright. Block Public Access is an S3 feature, password rotation doesn't affect transport encryption, and Multi-AZ addresses availability, not encryption in transit.$q$),
('sc-q-621','awsscs',5,'5.2','multi',2,$q$Which statements about Amazon OpenSearch Service in-transit encryption are TRUE? (Select all that apply.)$q$,$q$["Node-to-node encryption protects traffic between the domain's own data nodes","Enforcing HTTPS protects traffic between clients and the domain endpoint","Enabling one of node-to-node encryption or enforced HTTPS automatically enables the other","Both settings are independently configurable and address different hops"]$q$::jsonb,$q$[0,1,3]$q$::jsonb,$q$Node-to-node encryption and enforced HTTPS are genuinely separate settings covering different traffic hops (inter-node vs. client-to-endpoint) and must each be turned on deliberately - enabling one does not automatically enable the other.$q$),
('sc-q-622','awsscs',5,'5.2','mcq',3,$q$A team wants to install an ACM-issued public certificate's private key directly onto a self-managed NGINX server running on an EC2 instance, outside of any AWS-integrated service. Why does this fail?$q$,$q$["ACM-issued certificate private keys cannot be exported; ACM certificates are only usable with integrated services like ELB, CloudFront, and API Gateway","EC2 instances cannot use TLS at all","ACM only issues certificates for S3 buckets","NGINX cannot be run on EC2"]$q$::jsonb,'0'::jsonb,$q$ACM manages the private key internally and only exposes the certificate for use through its integrated services - it never lets you export the private key to install elsewhere. To run TLS on a self-managed server, you'd need a certificate from another CA (e.g., issued by ACM Private CA and exported, or a third-party cert) whose private key you can install directly.$q$),
('sc-q-623','awsscs',5,'5.2','ordering',2,$q$A request flows from a browser through CloudFront, to an Application Load Balancer, and finally to backend EC2 instances, with encryption enforced at every hop. Order the encryption boundaries from the segment CLOSEST to the end user to the segment CLOSEST to the backend.$q$,$q$["Application Load Balancer to backend EC2 instances (re-encrypted TLS)","Browser to CloudFront edge (TLS terminated at the edge)","CloudFront edge to Application Load Balancer (re-encrypted TLS)"]$q$::jsonb,$q$[1,2,0]$q$::jsonb,$q$Each hop terminates and re-establishes its own TLS session: the browser-to-edge leg is closest to the user, the edge-to-ALB leg carries the request into the AWS network, and the ALB-to-backend leg is the final segment - full end-to-end encryption requires deliberately re-encrypting at each boundary rather than assuming one certificate covers the whole path.$q$),
('sc-q-624','awsscs',5,'5.2','mcq',3,$q$A team wants a Network Load Balancer to terminate TLS using an ACM certificate so backend instances receive decrypted traffic, reducing CPU load on those instances. What NLB listener type achieves this?$q$,$q$["A TCP listener with pass-through TLS","A TLS listener performing TLS termination at the load balancer","A UDP listener","An HTTP listener"]$q$::jsonb,'1'::jsonb,$q$An NLB TLS listener terminates the TLS session at the load balancer using an attached ACM (or imported) certificate, forwarding plaintext to targets and offloading the TLS handshake/decryption cost from the backend instances. A TCP pass-through listener forwards the encrypted stream unmodified, requiring backends to terminate TLS themselves; NLB has no HTTP listener type (that's an ALB feature) and UDP listeners don't perform TLS termination at all.$q$),
('sc-q-625','awsscs',5,'5.2','mcq',1,$q$A bucket policy denies requests where aws:SecureTransport is false AND where the connecting TLS version is below 1.2. What is the combined effect?$q$,$q$["It blocks plaintext HTTP requests only, allowing any TLS version","It blocks both plaintext HTTP requests and HTTPS requests using outdated TLS versions below 1.2","It blocks all requests to the bucket","It has no effect because S3 does not support TLS version conditions"]$q$::jsonb,'1'::jsonb,$q$Combining a deny on aws:SecureTransport=false with a deny on TLS versions below 1.2 closes both gaps at once - unencrypted HTTP is rejected, and so is HTTPS negotiated with a weak, outdated TLS version. S3 does support a TLS version condition key, and the policy doesn't block all requests, only the two specifically denied cases.$q$),
-- 5.3 Key Management + Immutability
('sc-q-626','awsscs',5,'5.3','mcq',2,$q$A global application encrypts data in one Region and needs to decrypt that same ciphertext after replicating it to a second Region, without re-encrypting anything. What KMS feature enables this?$q$,$q$["A KMS multi-Region key, with a replica created in the second Region","A single-Region customer managed key shared via a resource policy","AWS Certificate Manager","S3 cross-region replication alone"]$q$::jsonb,'0'::jsonb,$q$Multi-Region keys share the same key material and key ID across Regions, so ciphertext encrypted under the primary key can be decrypted directly using its replica in another Region with no re-encryption step. A single-Region key can't be used for decryption in a Region it doesn't exist in via a resource policy alone, ACM manages certificates rather than data keys, and S3 replication copies objects but doesn't solve cross-Region key availability.$q$),
('sc-q-627','awsscs',5,'5.3','mcq',3,$q$An application creates a KMS grant and immediately tries to use the permission it just delegated, but the call fails because the grant hasn't yet propagated everywhere. What lets the application use the grant right away?$q$,$q$["Passing the grant token returned when the grant was created, on the subsequent API call","Waiting exactly 24 hours before use","Recreating the KMS key","Switching to an AWS managed key"]$q$::jsonb,'0'::jsonb,$q$KMS grants are eventually consistent, so a brand-new grant may not yet be visible everywhere; passing the grant token returned at creation time on the next call proves the grant's validity immediately, bypassing the propagation delay. Waiting arbitrarily, recreating the key, or switching key types don't address the specific consistency gap the grant token is designed to solve.$q$),
('sc-q-628','awsscs',5,'5.3','mcq',1,$q$A customer managed KMS key is scheduled for deletion with a 14-day waiting period. What can happen during those 14 days?$q$,$q$["The key remains fully usable for encrypt/decrypt operations as normal","The key is disabled and unusable, but the deletion can still be canceled before the period ends","The key is immediately and irreversibly destroyed","The waiting period can be shortened to zero at any time"]$q$::jsonb,'1'::jsonb,$q$During the scheduled waiting period (7-30 days, chosen at deletion request), the key is disabled and cannot be used for cryptographic operations, but administrators can still cancel the deletion to restore it - the mandatory window exists precisely to prevent irreversible mistakes. Permanent destruction only happens once the full waiting period elapses.$q$);
