-- AWS Security Specialty (SCS-C02) Domain 2 (Security Logging & Monitoring)
-- expansion across its three real task-statement objectives (2.2 and 2.4 do
-- not exist in SCS-C02): 2.1 monitoring/alerting design gets 25 new items
-- (11 questions + 14 flashcards); 2.3 logging solution design gets 14 new
-- items (6 questions + 8 flashcards); 2.5 log data analysis (CloudWatch Logs
-- Insights), which had almost no prior coverage, gets 32 new items (14
-- questions + 18 flashcards). New topics not previously covered in the
-- awsscs bank: CloudWatch composite alarms, CloudWatch anomaly detection,
-- Logs subscription filters, JSON metric-filter patterns, AWS Config
-- aggregators/custom rules/auto-remediation/recorder scope, CloudTrail
-- Insights anomaly types, VPC Traffic Mirroring components, CloudWatch
-- cross-account observability, CloudTrail multi-region trails and
-- CloudTrail Lake, VPC Flow Logs custom formats, CloudTrail digest-file
-- chaining, Route 53 Resolver query logs, and a full pass on CloudWatch
-- Logs Insights (fields/filter/stats/sort/limit/parse/dedup/bin, cross-log-
-- group queries, JSON field auto-discovery, saved queries, cost model, and
-- data protection policies/unmask). Adds questions sc-q-300..sc-q-330 (31)
-- and flashcards sc-f-300..sc-f-327 (core, 28), sc-a-120..sc-a-126
-- (acronym, 7), sc-y-060..sc-y-064 (feynman, 5). Purely additive: no
-- existing rows are modified or deleted.

insert into public.questions (id, cert, domain, objective, qtype, difficulty, stem, choices, answer, explanation) values
-- Objective 2.1: monitoring/alerting design
('sc-q-300','awsscs',2,'2.1','mcq',2,$q$A CIS AWS Foundations Benchmark control requires an alert whenever a principal attempts an API call that IAM denies. Which design correctly implements this using CloudWatch?$q$,$q$["A CloudWatch Logs metric filter on the CloudTrail log group matching errorCode values of AccessDenied and UnauthorizedOperation, driving an alarm and SNS topic","An AWS Config rule that evaluates IAM policies for overly permissive statements","A VPC Flow Logs REJECT record filter","A GuardDuty finding type filter in Security Hub"]$q$::jsonb,'0'::jsonb,$q$A metric filter matching the CloudTrail errorCode field for AccessDenied/UnauthorizedOperation values, tied to an alarm and SNS, surfaces every denied API call in near real time - the CIS-recommended pattern. A Config rule evaluates policy documents rather than individual API call outcomes, VPC Flow Logs REJECT records are network-layer, not IAM-layer, and Security Hub aggregates findings rather than raw CloudTrail error codes.$q$),
('sc-q-301','awsscs',2,'2.1','mcq',1,$q$A security team wants an immediate CloudWatch alarm whenever any IAM policy is created, changed, or deleted anywhere in the account. What should they build?$q$,$q$["A CloudWatch Logs metric filter on the CloudTrail log group matching IAM policy API calls (e.g., PutUserPolicy, CreatePolicy, DeletePolicy), tied to an alarm and SNS topic","An AWS Config recorder scoped only to EC2 resources","A VPC Flow Logs filter for IAM traffic","AWS Trusted Advisor's weekly email digest"]$q$::jsonb,'0'::jsonb,$q$A metric filter matching the CloudTrail event names for IAM policy mutation calls, wired to an alarm and SNS, gives near-real-time notification of policy changes - another CIS Foundations Benchmark control. Config's recorder tracks resource state rather than firing a real-time alarm feed by itself, Flow Logs never see IAM API calls since they only capture network traffic, and Trusted Advisor's digest is periodic, not event-driven.$q$),
('sc-q-302','awsscs',2,'2.1','mcq',1,$q$An application's CPU alarm alone pages the on-call engineer during normal traffic spikes that cause no real problem, creating alert fatigue. The team wants a page to fire only when CPU is high AND the error rate is also elevated. What CloudWatch feature should they use?$q$,$q$["A composite alarm combining the CPU alarm and the error-rate alarm with an AND rule","A single alarm with two metrics averaged together","Two separate SNS topics for the same alarm","A CloudWatch dashboard widget"]$q$::jsonb,'0'::jsonb,$q$A composite alarm evaluates the alarm states of multiple underlying alarms with AND/OR logic, so it can require both the CPU alarm and the error-rate alarm to be in ALARM before it notifies - directly reducing noise from either condition alone. Averaging two unrelated metrics together loses the meaning of each individually, duplicating SNS topics doesn't add any logic, and a dashboard widget only visualizes data, it doesn't evaluate conditions or send notifications.$q$),
('sc-q-303','awsscs',2,'2.1','mcq',2,$q$A retail application's request volume triples every weekend and fluctuates predictably by time of day, making a single static alarm threshold either too sensitive on weekdays or too lax on weekends. Which CloudWatch capability adapts to this pattern automatically?$q$,$q$["CloudWatch anomaly detection, which models expected value bands from historical metric behavior","A single static-threshold alarm set to the highest expected value","A CloudWatch Logs metric filter","AWS Config drift detection"]$q$::jsonb,'0'::jsonb,$q$Anomaly detection builds a model of expected metric behavior from historical data, producing a dynamic band that widens or narrows with normal patterns like weekday/weekend cycles, and alarms only when the metric falls outside that band. A static threshold set high enough to survive weekends would miss real weekday problems, metric filters operate on log text rather than statistical modeling of a metric, and Config drift detection tracks resource configuration, not metric values.$q$),
('sc-q-304','awsscs',2,'2.1','mcq',2,$q$A security team manages 40 AWS accounts across 3 regions and wants a single, centralized place to view configuration compliance and drift across all of them, without logging into each account individually. What should they set up?$q$,$q$["An AWS Config aggregator collecting configuration and compliance data from all source accounts and regions","A separate AWS Config recorder manually checked in each account","A CloudTrail organization trail","An IAM role assumed sequentially into each account"]$q$::jsonb,'0'::jsonb,$q$A Config aggregator pulls configuration items and rule compliance data from many accounts and regions into one authorizing account, giving a single centralized view - exactly this design need. Checking each account's recorder individually doesn't scale to 40 accounts, an organization trail centralizes API activity logs rather than Config compliance data, and manually assuming roles account-by-account is exactly the manual toil an aggregator eliminates.$q$),
('sc-q-305','awsscs',2,'2.1','mcq',3,$q$A company needs an AWS Config rule that checks a condition specific to its internal naming and tagging conventions, for which no AWS managed rule exists. How should they implement this?$q$,$q$["A custom Config rule backed by a Lambda function containing the organization-specific evaluation logic","Wait for AWS to release a matching managed rule","An SCP that blocks the noncompliant naming pattern","A CloudWatch alarm on resource creation events"]$q$::jsonb,'0'::jsonb,$q$Custom Config rules invoke a Lambda function you write, so any evaluation logic - including organization-specific naming/tagging conventions - can be expressed even without a matching managed rule. Waiting for AWS leaves the requirement unmet indefinitely, an SCP can block certain API calls but can't express Config's flexible per-resource evaluation logic, and a CloudWatch alarm doesn't evaluate configuration compliance at all.$q$),
('sc-q-306','awsscs',2,'2.1','mcq',2,$q$A Config rule flags any S3 bucket that becomes publicly readable as NON_COMPLIANT. The security team wants the bucket's public access automatically blocked within minutes, with no analyst action required. What should they attach to the rule?$q$,$q$["An automatic remediation action that runs an SSM Automation document to enable S3 Block Public Access on the noncompliant bucket","A manual ticket routed to the security team's queue","A CloudWatch dashboard widget showing the finding","Deleting the Config rule so the finding stops appearing"]$q$::jsonb,'0'::jsonb,$q$Config rules can be associated with an automatic remediation action - typically an SSM Automation document - that runs as soon as a resource is evaluated as NON_COMPLIANT, closing the gap without waiting on a human. A manual ticket and a dashboard widget both still require an analyst to act, and deleting the rule removes visibility instead of fixing the underlying exposure.$q$),
('sc-q-307','awsscs',2,'2.1','ordering',3,$q$Order the sequence of events in an AWS Config auto-remediation pipeline that responds to an unencrypted EBS volume being created.$q$,$q$["A new unencrypted EBS volume is created, changing the account's resource configuration","AWS Config records the new configuration item and evaluates it against the encryption rule","The rule evaluation returns NON_COMPLIANT for the volume","The associated SSM Automation remediation action runs to bring the volume into compliance"]$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$The pipeline starts with the actual resource change; Config then records that change as a configuration item and runs the applicable rule against it; a failing check produces a NON_COMPLIANT evaluation; and only then does the attached remediation action execute to correct the resource. Remediation is reactive to a specific NON_COMPLIANT evaluation, so it cannot run before that evaluation exists.$q$),
('sc-q-308','awsscs',2,'2.1','matching',1,$q$Match each VPC Traffic Mirroring component to its role.$q$,$q${"left":["Mirror source","Mirror target","Mirror filter","Mirror session"],"right":["The ENI whose traffic is being copied","The ENI or Network Load Balancer that receives the copied traffic","Rules defining which traffic (protocol, port, direction) is copied","The configuration binding a source, target, and filter together"]}$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$The mirror source is the network interface being observed; the mirror target is where the copied packets are delivered for inspection; the mirror filter narrows which traffic is actually copied, by protocol, port, or direction, to control volume and relevance; and the mirror session ties a specific source, target, and filter into one active mirroring configuration.$q$),
('sc-q-309','awsscs',2,'2.1','mcq',1,$q$Besides unusual API call volume, what other type of anomaly can CloudTrail Insights automatically detect and surface as an insight event?$q$,$q$["Unusual API error rates, such as a spike in failed calls to a specific API","Unusual EC2 CPU utilization","Unusual S3 storage class transitions","Unusual Route 53 DNS query latency"]$q$::jsonb,'0'::jsonb,$q$CloudTrail Insights analyzes both unusual call volume and unusual error rates for management API activity, surfacing either as an insight event without the team needing to define a threshold in advance. EC2 CPU, S3 storage-class transitions, and DNS latency are metrics tracked by other services (CloudWatch, S3, Route 53), not CloudTrail Insights.$q$),
('sc-q-310','awsscs',2,'2.1','multi',3,$q$A central security operations team wants to view CloudWatch metrics, dashboards, and alarms from 25 member accounts in one monitoring account, without copying the underlying data or granting broad cross-account IAM access. Which TWO statements about CloudWatch cross-account observability are correct?$q$,$q$["A monitoring account can view and query metrics, logs, and traces from source accounts that have shared them, without duplicating the underlying data","Source accounts explicitly opt in by creating a sink and a link that authorizes the monitoring account to view their observability data","The monitoring account automatically gains full administrative IAM access to every source account","Cross-account observability requires exporting all logs to S3 first before they can be viewed centrally"]$q$::jsonb,$q$[0,1]$q$::jsonb,$q$Cross-account observability lets an appointed monitoring account query metrics, logs, and traces live from source accounts that have explicitly linked to it via a sink, without copying data around or exporting to S3 first. It grants only observability visibility, not broad administrative IAM access - the two are unrelated, and source accounts must opt in rather than being enrolled automatically.$q$),
-- Objective 2.3: logging solution design
('sc-q-311','awsscs',2,'2.3','mcq',1,$q$By default, an AWS account creates a single trail intended to capture management events. What must be enabled on that trail to ensure API activity is logged no matter which AWS region it occurs in?$q$,$q$["Multi-region trail, so events from every region are delivered to the trail's single S3 destination","CloudTrail Insights","VPC Flow Logs in every region","A Config aggregator"]$q$::jsonb,'0'::jsonb,$q$Enabling the multi-region option on a trail (the console default when creating one) ensures API activity from every AWS region is captured and delivered to the trail's destination, so a region-specific gap can't be silently missed. Insights adds anomaly detection on top of an existing trail, Flow Logs capture network traffic rather than API calls, and a Config aggregator centralizes configuration data, not CloudTrail events.$q$),
('sc-q-312','awsscs',2,'2.3','mcq',2,$q$An investigations team needs to run ad hoc SQL queries against two years of CloudTrail event history without first exporting anything to S3 and setting up Athena tables. Which CloudTrail capability fits?$q$,$q$["CloudTrail Lake, which stores events in a managed, queryable event data store","CloudTrail Insights","A CloudTrail organization trail","VPC Flow Logs"]$q$::jsonb,'0'::jsonb,$q$CloudTrail Lake ingests events into a managed event data store that supports SQL-based queries directly, with configurable long-term retention, avoiding the extra step of exporting to S3 and defining Athena tables. Insights only flags statistical anomalies, an organization trail is about which accounts are logged rather than how the data is queried, and Flow Logs are unrelated to API event history.$q$),
('sc-q-313','awsscs',2,'2.3','mcq',2,$q$An investigator needs the TCP flags field for each flow log record to distinguish SYN packets from established connections, but the account's flow logs were created with the default format. What should they do?$q$,$q$["Create a new flow log using a custom format that includes the tcp-flags field","Nothing - the default format already includes TCP flags","Enable CloudTrail data events instead","Switch the flow log destination from S3 to CloudWatch Logs"]$q$::jsonb,'0'::jsonb,$q$The default VPC Flow Logs format does not include every available field; fields like tcp-flags must be requested explicitly via a custom log format when creating the flow log. CloudTrail data events record API-level object access, not TCP handshake details, and changing the destination changes where records land, not which fields they contain.$q$),
('sc-q-314','awsscs',2,'2.3','ordering',3,$q$Order the steps of verifying that a set of delivered CloudTrail log files have not been tampered with, using log file validation.$q$,$q$["Enable log file validation on the trail so CloudTrail begins generating digest files alongside log files","CloudTrail periodically delivers a digest file that includes a hash of each log file and a reference to the previous digest file's hash","An investigator retrieves the log files and their corresponding digest file chain from the S3 bucket","The investigator runs the CloudTrail validate-logs command, which recomputes hashes and follows the digest chain to confirm nothing was altered or removed"]$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$Validation only produces evidence once it's turned on, so enabling it comes first; from then on CloudTrail chains each digest file to the previous one's hash, creating a tamper-evident sequence; an investigator later pulls both the log files and the matching digests; and running validate-logs recomputes the hashes and walks the chain, which fails loudly if any file was altered or a digest is missing - revealing gaps as well as edits.$q$),
('sc-q-315','awsscs',2,'2.3','mcq',1,$q$A security team suspects a compromised instance is using DNS queries to communicate with a command-and-control domain. Which log source specifically captures the DNS queries made by resources in a VPC?$q$,$q$["Route 53 Resolver query logs","VPC Flow Logs","CloudTrail management events","S3 server access logs"]$q$::jsonb,'0'::jsonb,$q$Route 53 Resolver query logging records the DNS queries made from within a VPC, including the query name and the resolved response, making it the direct source for detecting suspicious domains. VPC Flow Logs show only IP/port traffic metadata after resolution, CloudTrail records AWS API calls, and S3 server access logs record S3 request activity - none of them capture DNS query content.$q$),
('sc-q-316','awsscs',2,'2.3','matching',2,$q$Match each log source to the type of evidence it primarily provides during an investigation.$q$,$q${"left":["CloudTrail management events","CloudTrail data events","VPC Flow Logs","SSM Session Manager session logs"],"right":["Control-plane API calls, such as creating or deleting a resource","Data-plane object access, such as which S3 object was read","Network traffic metadata between IP addresses and ports","The interactive commands an administrator typed during a shell session"]}$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$Management events cover control-plane actions like resource creation; data events cover the higher-volume, opt-in data-plane actions like object reads; VPC Flow Logs capture network-layer metadata rather than any API or command content; and Session Manager session logs capture the literal commands and output of an interactive administrative session - each source answers a different investigative question, and a complete picture typically needs more than one.$q$),
-- Objective 2.5: log data analysis (CloudWatch Logs Insights)
('sc-q-317','awsscs',2,'2.5','mcq',1,$q$Using CloudWatch Logs Insights on a log group containing ALB access logs, which query approach finds the ten client IP addresses generating the most 5xx errors?$q$,$q$["filter status >= 500 | stats count() as errorCount by client_ip | sort errorCount desc | limit 10","fields @timestamp, @message | sort @timestamp desc | limit 10","parse @message \"* * *\" as a, b, c","dedup client_ip"]$q$::jsonb,'0'::jsonb,$q$Filtering to error status codes, aggregating a count per client IP with stats, sorting descending, and limiting to 10 rows is exactly the pipeline needed to surface the top offending IPs. Sorting raw events by timestamp doesn't aggregate anything, a bare parse only extracts fields without counting, and dedup alone just removes duplicate rows without any counting or ranking.$q$),
('sc-q-318','awsscs',2,'2.5','mcq',2,$q$A log group contains unstructured text lines like "user=alice action=login result=failed". Which Logs Insights command extracts the result value into its own field named outcome for further filtering?$q$,$q$["parse @message \"result=*\" as outcome","fields @message","stats count() by @message","sort @message desc"]$q$::jsonb,'0'::jsonb,$q$The parse command extracts a substring matching the given pattern into a named field, so parse @message "result=*" as outcome pulls the value after result= into outcome for later filtering or aggregation. fields alone just selects existing fields, stats aggregates rather than extracts, and sort only reorders rows.$q$),
('sc-q-319','awsscs',2,'2.5','mcq',2,$q$A log group logs the same alert multiple times per minute due to retries. Before counting distinct alert types, an analyst wants to keep only the first occurrence of each unique alertId in the query result. Which command achieves this?$q$,$q$["dedup alertId","sort alertId","limit 1","fields alertId"]$q$::jsonb,'0'::jsonb,$q$dedup removes subsequent rows that share the same value for the specified field, keeping only the first occurrence - exactly what's needed before counting distinct alerts without retries inflating the total. Sorting only reorders results, limit caps the total row count rather than deduplicating, and fields just selects which columns to display.$q$),
('sc-q-320','awsscs',2,'2.5','mcq',2,$q$A team wants a time series chart of request counts bucketed into 5-minute intervals from CloudWatch Logs Insights query results. Which function creates those time buckets?$q$,$q$["stats count() by bin(5m)","filter @timestamp like /5m/","parse @timestamp \"5m\"","sort @timestamp by 5m"]$q$::jsonb,'0'::jsonb,$q$bin() groups the query's time range into fixed-size buckets, so stats count() by bin(5m) produces a count for each 5-minute interval, which the console can render as a time series. The other options misuse filter/parse/sort syntax and don't perform any time-bucketing.$q$),
('sc-q-321','awsscs',2,'2.5','mcq',1,$q$During an incident, an analyst needs to correlate log entries across the log groups of five different Lambda functions in the same account and region within one query, without exporting or copying any data. What CloudWatch Logs Insights capability allows this?$q$,$q$["Running a single query against multiple selected log groups at once","Exporting each log group to S3 and joining them in Athena","Creating a CloudWatch Logs subscription filter for each function","Enabling CloudTrail data events for the Lambda functions"]$q$::jsonb,'0'::jsonb,$q$Logs Insights supports selecting multiple log groups for a single query, letting an analyst search and correlate across them directly with no export step. Exporting to S3 and joining in Athena works but requires the extra step the question says to avoid, subscription filters stream data to a target rather than support ad hoc querying, and CloudTrail data events are unrelated to a Lambda function's own application logs.$q$),
('sc-q-322','awsscs',2,'2.5','mcq',1,$q$An application logs structured JSON events like {"level":"error","user":{"id":42}}. In CloudWatch Logs Insights, how can an analyst filter on the nested user id without writing a custom parse expression?$q$,$q$["Reference the nested field directly using dot notation, such as user.id, since Logs Insights auto-discovers JSON fields","It is impossible to query nested JSON fields","Flatten the JSON manually in the console before querying","Only the top-level level field can ever be queried"]$q$::jsonb,'0'::jsonb,$q$When log events are valid JSON, Logs Insights automatically discovers fields, including nested ones, which can be referenced with dot notation like user.id directly in filter or stats clauses - no manual parse needed. Nested fields are fully queryable, no manual flattening step exists in the console, and top-level fields are not the only ones accessible.$q$),
('sc-q-323','awsscs',2,'2.5','mcq',1,$q$A SOC analyst runs the same CloudWatch Logs Insights query to check for failed console logins every time they start a shift. How can they avoid retyping the query each time?$q$,$q$["Save the query so it can be reloaded and rerun later","Recreate a new log group for it every day","Export the query text to CloudTrail","Disable log retention so old queries auto-restore"]$q$::jsonb,'0'::jsonb,$q$Logs Insights lets you save a query definition for later reuse, so the analyst can reload the exact same query on demand instead of retyping it each shift. Creating a new log group has nothing to do with reusing a query, CloudTrail has no concept of storing Logs Insights query text, and retention settings control how long log data is kept, not query reuse.$q$),
('sc-q-324','awsscs',2,'2.5','mcq',2,$q$A team's monthly bill shows a large charge from CloudWatch Logs Insights after they ran broad queries across a full year of high-volume logs. What primarily drives this cost?$q$,$q$["The amount of log data scanned by each query, regardless of how many results are returned","A flat fee per query regardless of data size","The number of dashboards displaying the results","The number of IAM users who ran queries"]$q$::jsonb,'0'::jsonb,$q$Logs Insights bills based on the volume of log data scanned to satisfy a query, so widening the time range or querying a huge log group directly increases cost even if the final result set is small; narrowing the time range or log group scope reduces the bill. It isn't a flat per-query fee, dashboard count is unrelated to query billing, and the number of users running queries doesn't itself change how much data any single query scans.$q$),
('sc-q-325','awsscs',2,'2.5','mcq',2,$q$A company wants CloudWatch Logs to automatically detect and mask credit card numbers that accidentally appear in application log events, before most viewers can see them. What should they configure?$q$,$q$["A CloudWatch Logs data protection policy on the log group","A metric filter matching credit card number patterns","S3 Object Lock on the exported logs","A resource-based policy on the log group"]$q$::jsonb,'0'::jsonb,$q$A data protection policy scans incoming log events for configured sensitive-data patterns, such as credit card numbers, and masks matches so most readers see a redacted value instead of the raw sensitive data. A metric filter only counts pattern matches for alarms, it doesn't redact anything; Object Lock provides immutability, not masking; and a resource-based policy controls access, not content transformation.$q$),
('sc-q-326','awsscs',2,'2.5','mcq',3,$q$A log group has a data protection policy masking Social Security numbers. An authorized fraud investigator needs to see the original, unmasked values while running a CloudWatch Logs Insights query. What must be true for this to work?$q$,$q$["The investigator's IAM identity must have the logs:Unmask permission, and the query must include the unmask command","Data protection policies cannot ever be reversed once applied","Any user who can view the log group can automatically see unmasked values","The log group's retention period must first be extended"]$q$::jsonb,'0'::jsonb,$q$Unmasking requires both an explicit unmask command in the query and the caller having the logs:Unmask IAM permission - a deliberate two-part control so only specifically authorized users see the original sensitive values. Masking is reversible for authorized queries, not permanent; ordinary viewers without the permission continue to see masked data even if they can read the log group; and retention period is unrelated to unmasking rights.$q$),
('sc-q-327','awsscs',2,'2.5','multi',2,$q$Which TWO statements about CloudWatch Logs Insights are correct?$q$,$q$["Query results and cost are driven by the volume of log data scanned within the specified time range","It provides a purpose-built query language for ad hoc analysis of data already stored in CloudWatch Logs","It performs SQL joins across unrelated log groups from different AWS accounts","It requires first streaming all log data into Amazon OpenSearch Service before it can be queried"]$q$::jsonb,$q$[0,1]$q$::jsonb,$q$Logs Insights is billed by data scanned and gives a dedicated query language for interactively analyzing logs that are already sitting in CloudWatch Logs - no separate indexing step required. It does not perform cross-account SQL joins, and it queries CloudWatch Logs data directly; it has no dependency on first moving data into OpenSearch.$q$),
('sc-q-328','awsscs',2,'2.5','ordering',2,$q$Order the pipeline of a CloudWatch Logs Insights query that finds the count of failed login attempts per source IP address in the last hour, sorted from highest to lowest.$q$,$q$["filter eventName = \"ConsoleLogin\" and responseElements.ConsoleLogin = \"Failure\"","stats count() as failures by sourceIPAddress","sort failures desc","limit 20"]$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$The query pipeline narrows to the relevant failed login events first, then aggregates a count per source IP, then orders the aggregated results from most to least failures, and finally caps how many rows are returned - each stage operating on the output of the one before it, which is why filtering must precede aggregation and sorting must follow it.$q$),
('sc-q-329','awsscs',2,'2.5','matching',1,$q$Match each CloudWatch Logs Insights command to its purpose.$q$,$q${"left":["fields","filter","stats","parse"],"right":["Selects or computes which fields appear in the results","Narrows results to events matching a condition","Aggregates values, such as counts or averages, across matching events","Extracts a new field from unstructured text using a pattern"]}$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$fields chooses or derives which columns appear; filter restricts which log events are considered; stats performs aggregations like count(), avg(), or count_distinct() over the filtered set; and parse pulls a new named field out of free-text log lines using a glob or regex-style pattern - together these commands form the building blocks of most Logs Insights queries.$q$),
('sc-q-330','awsscs',2,'2.5','mcq',3,$q$A team already archives two years of VPC Flow Logs as Parquet files in S3 and regularly needs to run complex SQL joins against multiple large historical tables. Which analysis approach is a better fit than CloudWatch Logs Insights for this specific need?$q$,$q$["Amazon Athena querying the S3-based Parquet files directly with standard SQL, including joins","CloudWatch Logs Insights, since it also supports SQL joins across S3 data","AWS Config, since it can run ad hoc queries over historical logs","CloudTrail Insights, since it processes VPC Flow Log data as well"]$q$::jsonb,'0'::jsonb,$q$Athena is built for SQL-based analysis, including joins, directly over data already living in S3, such as archived Parquet-formatted Flow Logs - a better fit once the data has left CloudWatch Logs and complex joins are required. Logs Insights queries CloudWatch Logs specifically and doesn't support cross-table SQL joins, Config evaluates resource configuration rather than running log queries, and CloudTrail Insights only analyzes CloudTrail management/data event anomalies, not VPC Flow Log content.$q$);

insert into public.flashcards (id, cert, deck, domain, objective, front, back) values
-- Objective 2.1: monitoring/alerting design
('sc-f-300','awsscs','core',2,'2.1',$$What is a CloudWatch composite alarm?$$,$$An alarm whose trigger condition is a logical AND/OR expression over the ALARM/OK states of other alarms, letting you require multiple conditions (e.g., high CPU AND elevated error rate) before notifying - reducing noise from any single flapping metric.$$),
('sc-f-301','awsscs','core',2,'2.1',$$What does CloudWatch anomaly detection do?$$,$$Applies machine learning to a metric's historical values to build an expected value band that adapts to trends and cyclical patterns (like weekday/weekend traffic); an alarm can then trigger only when the metric falls outside that dynamic band, instead of a fixed static threshold.$$),
('sc-f-302','awsscs','core',2,'2.1',$$CloudWatch Logs metric filter vs subscription filter - what's the difference?$$,$$A metric filter counts pattern matches and turns them into a CloudWatch metric for alarming (e.g., alert when root logins > 0). A subscription filter instead streams matching log events in near real time to a destination like Kinesis Data Streams, Firehose, or Lambda for further processing - one produces a number, the other forwards the raw events.$$),
('sc-f-303','awsscs','core',2,'2.1',$$How do CloudWatch Logs metric filter patterns match structured JSON log events?$$,$$For JSON-formatted logs, a pattern can reference fields directly, e.g. { $.errorCode = "AccessDenied" }, letting the filter match on a specific field's value rather than searching the whole line as unstructured text.$$),
('sc-f-304','awsscs','core',2,'2.1',$$What is an AWS Config aggregator?$$,$$A Config resource in a designated account that collects configuration and compliance data from many source accounts and regions (via an Organization or individual authorizations), providing one centralized view of drift and compliance without logging into each account.$$),
('sc-f-305','awsscs','core',2,'2.1',$$AWS Config managed rule vs custom rule - when do you need a custom rule?$$,$$Managed rules are pre-built AWS checks (e.g., s3-bucket-public-read-prohibited) covering common cases. A custom rule invokes your own Lambda function, needed when the check reflects organization-specific logic (naming conventions, internal tagging policy) that no managed rule expresses.$$),
('sc-f-306','awsscs','core',2,'2.1',$$How does AWS Config automatic remediation work?$$,$$A remediation action, usually an SSM Automation document, is associated with a Config rule; when a resource evaluates as NON_COMPLIANT, the action runs automatically (optionally after a retry/wait period) to correct the resource - e.g., re-enabling S3 Block Public Access - without waiting for an analyst.$$),
('sc-f-307','awsscs','core',2,'2.1',$$What determines which resources the AWS Config recorder tracks?$$,$$The configuration recorder's settings define whether it records all supported resource types or only a specified list, and whether it includes global resources (like IAM); global resource recording should typically be enabled in only one region to avoid duplicate configuration items.$$),
('sc-f-308','awsscs','core',2,'2.1',$$What two types of anomalies does CloudTrail Insights detect?$$,$$Unusual API call volume (a spike or drop in how often an API is called) and unusual API error rates - both are flagged automatically as insight events based on CloudTrail's own baseline of normal activity, without the team defining a threshold.$$),
('sc-f-309','awsscs','core',2,'2.1',$$What does CloudWatch cross-account observability let a monitoring account do?$$,$$After a source account creates a sink and links to it, the monitoring account can search, visualize, and query that source account's metrics, logs, and traces directly - without copying the data or being granted broad IAM access into the source account.$$),
('sc-a-120','awsscs','acronym',2,'2.1',$$SNS$$,$$Simple Notification Service - delivers alarm and finding notifications (email, SMS, Lambda, etc.) as the action end of most CloudWatch/Config alerting pipelines.$$),
('sc-a-121','awsscs','acronym',2,'2.1',$$CIS$$,$$Center for Internet Security - publishes the AWS Foundations Benchmark whose controls (root login alerts, unauthorized API call alerts, IAM/security-group change alerts) are commonly implemented with CloudWatch Logs metric filters.$$),
('sc-y-060','awsscs','feynman',2,'2.1',$$Explain how you would design a CloudWatch-based alerting pipeline that satisfies several CIS AWS Foundations Benchmark controls at once, such as alerting on root logins, unauthorized API calls, IAM policy changes, and security group changes.$$,$$Model answer: All four controls follow the same shape, so you build the pipeline once and repeat the pattern. First, make sure a multi-region CloudTrail trail is also delivered to a CloudWatch Logs log group - that log group is the raw material every metric filter reads. Then, for each control, define a metric filter with a pattern matching the relevant CloudTrail fields: root login matches userIdentity.type = Root plus a console sign-in event; unauthorized API calls match errorCode values like AccessDenied or UnauthorizedOperation; IAM policy changes match event names like PutUserPolicy or CreatePolicy; security group changes match AuthorizeSecurityGroupIngress and similar. Each metric filter increments its own CloudWatch metric, and each metric gets its own alarm with a threshold of one occurrence, wired to an SNS topic the security team is subscribed to. Optionally, a composite alarm groups several of these into one paging rule if you want a single high-priority page when multiple controls fire together. The result is near-real-time notification for each control, built entirely from one shared log group and a handful of parallel metric filter/alarm pairs.$$),
('sc-y-061','awsscs','feynman',2,'2.1',$$Explain when you would choose AWS Config drift detection over a CloudWatch alarm for security monitoring, and when you'd want both.$$,$$Model answer: CloudWatch alarms are built for continuous, real-time signals - a metric crosses a threshold right now, so notify right now. AWS Config is built for configuration state over time - it snapshots a resource's settings whenever they change, evaluates that snapshot against a rule, and keeps a full history you can browse later, even for a change that happened last month before anyone was watching. If the question is "did an S3 bucket become public a moment ago and I need to know within seconds," that's arguably better served by an EventBridge rule reacting to the API call itself, or a CloudWatch alarm on a related metric. If the question is "is this bucket compliant right now, and can I show what its configuration looked like on any date, and can I automatically remediate the very next time it drifts," that's Config's job. In practice you use both together: Config continuously tracks and can auto-remediate configuration drift, while CloudWatch alarms and metric filters give you the fastest possible notification for the specific event patterns you care about most, such as a root login or a security group opened to the world.$$),
-- Objective 2.3: logging solution design
('sc-f-310','awsscs','core',2,'2.3',$$CloudTrail multi-region trail vs organization trail - what's the difference?$$,$$A multi-region trail solves the "which regions" problem: it captures events from every AWS region within a single account into one destination. An organization trail solves the "which accounts" problem: it captures events from every member account in an AWS Organization. A trail can be both multi-region and an organization trail at the same time for full account and region coverage.$$),
('sc-f-311','awsscs','core',2,'2.3',$$What is CloudTrail Lake?$$,$$A managed, immutable event data store for CloudTrail events that supports SQL-based queries directly against it, with configurable retention up to years - an alternative to exporting logs to S3 and querying them with Athena when you need ad hoc SQL analysis of historical API activity.$$),
('sc-f-312','awsscs','core',2,'2.3',$$What controls which fields appear in a VPC Flow Log record?$$,$$The log format: the default format includes a fixed set of fields, but a custom format lets you choose additional fields such as tcp-flags, pkt-srcaddr, or flow-direction - useful when an investigation needs details the default format omits.$$),
('sc-f-313','awsscs','core',2,'2.3',$$How does CloudTrail's digest file chain make tampering detectable?$$,$$Each digest file (delivered roughly every hour when log file validation is enabled) contains hashes of the log files it covers plus a reference to the hash of the previous digest file. Running the validate-logs command walks this chain and recomputes hashes, so it can detect not just an altered log file but also a deleted or missing digest in the sequence.$$),
('sc-f-314','awsscs','core',2,'2.3',$$What does Route 53 Resolver query logging capture?$$,$$The DNS queries made by resources inside a VPC (or on-premises via a Resolver endpoint) and the responses returned, giving visibility that VPC Flow Logs and CloudTrail cannot - useful for detecting DNS-based command-and-control or data exfiltration.$$),
('sc-a-122','awsscs','acronym',2,'2.3',$$DNS$$,$$Domain Name System - the queries Route 53 Resolver query logging records, often analyzed for command-and-control beaconing or data exfiltration over DNS.$$),
('sc-a-123','awsscs','acronym',2,'2.3',$$ENI$$,$$Elastic Network Interface - the finest granularity at which VPC Flow Logs (and a Traffic Mirroring source) can be enabled, below the subnet and VPC levels.$$),
('sc-y-062','awsscs','feynman',2,'2.3',$$Explain which log source you'd reach for to answer each of these forensic questions: what API calls did an attacker make, what network connections did a compromised instance open, and what commands did an administrator type during a remote session?$$,$$Model answer: Each question has a purpose-built log source, and mixing them up wastes investigation time. "What API calls did the attacker make" is CloudTrail's job - management events show control-plane actions like creating resources or changing IAM, and data events add the higher-volume object-level actions like S3 reads if they're enabled for the resource in question. "What network connections did a compromised instance open" is VPC Flow Logs - source/destination IP, port, and byte counts, though not packet contents (Traffic Mirroring would be needed for that level of detail). "What commands did an administrator type in a session" is Systems Manager Session Manager's session logging - if it's configured to log to S3 or CloudWatch Logs, it captures the literal interactive commands and output of that shell session, something neither CloudTrail nor Flow Logs record at all, since it happens inside the instance rather than at the API or network layer. A complete incident reconstruction almost always needs more than one of these together, because none of them alone sees the whole picture.$$),
-- Objective 2.5: log data analysis (CloudWatch Logs Insights)
('sc-f-315','awsscs','core',2,'2.5',$$What does the CloudWatch Logs Insights fields command do?$$,$$Selects which fields appear in the query results, and can also compute new fields from expressions - e.g., fields @timestamp, @message, ispresent(errorCode) as hasError - without altering the underlying log data.$$),
('sc-f-316','awsscs','core',2,'2.5',$$What does the CloudWatch Logs Insights filter command do?$$,$$Narrows the events considered by the rest of the query to those matching a boolean condition, e.g. filter status >= 500 or filter @message like /ERROR/ - conceptually a WHERE clause applied to log events.$$),
('sc-f-317','awsscs','core',2,'2.5',$$What does the CloudWatch Logs Insights stats command do?$$,$$Aggregates values across the matching events, with functions like count(), sum(), avg(), min(), max(), and count_distinct(), optionally grouped by one or more fields - e.g., stats count() by sourceIPAddress to rank activity per IP.$$),
('sc-f-318','awsscs','core',2,'2.5',$$What do the CloudWatch Logs Insights sort and limit commands do?$$,$$sort orders the result rows by one or more fields (ascending or descending); limit caps how many rows are returned, defaulting to 1,000 and capped at 10,000 per query - typically used together, e.g. sort count desc | limit 10, to surface only the top results.$$),
('sc-f-319','awsscs','core',2,'2.5',$$What does the CloudWatch Logs Insights parse command do?$$,$$Extracts a new named field from unstructured log text using a glob-style or regex pattern, e.g. parse @message "user=* action=*" as user, action - turning free-text log lines into structured fields you can then filter or aggregate on.$$),
('sc-f-320','awsscs','core',2,'2.5',$$What does the CloudWatch Logs Insights dedup command do?$$,$$Removes result rows that duplicate an earlier row's value(s) for the specified field(s), keeping only the first occurrence - useful for collapsing retried or repeated log entries before counting distinct events.$$),
('sc-f-321','awsscs','core',2,'2.5',$$What does the bin() function do in a CloudWatch Logs Insights query?$$,$$Groups the query's time range into fixed-size time buckets (e.g., bin(5m) for 5-minute buckets), typically used with stats count() by bin(...) to produce the data behind a time series visualization.$$),
('sc-f-322','awsscs','core',2,'2.5',$$Can a single CloudWatch Logs Insights query span multiple log groups?$$,$$Yes - a query can target multiple log groups in the same account and region at once, letting you correlate events (e.g., across several Lambda functions' log groups) in one query instead of running separate queries and merging results manually.$$),
('sc-f-323','awsscs','core',2,'2.5',$$How does CloudWatch Logs Insights handle JSON-formatted log events?$$,$$It automatically discovers fields in valid JSON log events, including nested ones, which can be referenced directly with dot notation (e.g., user.id) in filter, fields, or stats - no manual parse expression is needed the way it would be for unstructured text.$$),
('sc-f-324','awsscs','core',2,'2.5',$$What is a saved query in CloudWatch Logs Insights?$$,$$A stored query definition that can be reloaded and rerun later from the console, letting an analyst reuse a standard investigative query (e.g., "failed console logins in the last hour") without retyping it every time.$$),
('sc-f-325','awsscs','core',2,'2.5',$$How is CloudWatch Logs Insights billed?$$,$$By the amount of log data scanned to run each query within its specified time range and log group scope - not by a flat per-query fee, number of results, or number of users - so narrowing the time range or log groups queried directly reduces cost.$$),
('sc-f-326','awsscs','core',2,'2.5',$$What is a CloudWatch Logs data protection policy?$$,$$A policy attached to a log group that scans incoming events for configured sensitive-data patterns (credit card numbers, SSNs, AWS credentials, etc.) and automatically masks matches, so most viewers of the log group see redacted values instead of the raw sensitive data.$$),
('sc-f-327','awsscs','core',2,'2.5',$$What does the unmask command do in CloudWatch Logs Insights?$$,$$Reveals the original value of data that a data protection policy has masked, but only for callers whose IAM identity has the logs:Unmask permission - everyone else's query results (with or without unmask in the query) still show the masked value.$$),
('sc-a-124','awsscs','acronym',2,'2.5',$$PII$$,$$Personally Identifiable Information - a common target of CloudWatch Logs data protection policies, which detect and mask it in log events.$$),
('sc-a-125','awsscs','acronym',2,'2.5',$$JSON$$,$$JavaScript Object Notation - the structured log format that CloudWatch Logs Insights auto-discovers fields from, including nested fields via dot notation.$$),
('sc-a-126','awsscs','acronym',2,'2.5',$$SIEM$$,$$Security Information and Event Management - a full-featured log aggregation/correlation platform; CloudWatch Logs Insights offers lightweight ad hoc query analysis directly on CloudWatch Logs without standing one up.$$),
('sc-y-063','awsscs','feynman',2,'2.5',$$Explain how you would use CloudWatch Logs Insights to investigate a suspected credential-compromise incident, given that CloudTrail and VPC Flow Logs are both delivered into CloudWatch Logs.$$,$$Model answer: Start from what you already know - a specific IAM principal or access key is suspected. Run a Logs Insights query against the CloudTrail log group filtering for that principal's userIdentity, using stats count() by eventName to see, at a glance, which APIs it called and how often, which quickly surfaces anything unusual like new IAM users being created or GuardDuty being disabled. Then pivot to the network side: query the VPC Flow Logs log group for the instance or ENI associated with that principal's activity, filtering by time window and looking at destination IPs and rejected connections to see if the compromised credential was used to reach unexpected external hosts. Because Logs Insights can query multiple log groups, or you can run them as two focused queries and compare timestamps by hand, you're able to build a timeline: which API call happened, and what network activity surrounded it, without exporting anything to a separate SIEM or waiting for a batch export to Athena. The key idea is that Logs Insights turns already-centralized log data into an interactive investigation tool instead of a write-only archive.$$),
('sc-y-064','awsscs','feynman',2,'2.5',$$Explain the difference in purpose between a CloudWatch Logs metric filter and a CloudWatch Logs Insights query.$$,$$Model answer: A metric filter is a standing, forward-looking rule - you define a pattern once, and from that point forward every matching log event increments a CloudWatch metric in near real time, which an alarm can watch and act on immediately. It only sees events that arrive after it's created; it has no concept of history. A Logs Insights query is the opposite: it's an ad hoc, backward-looking tool you run on demand against log data that's already stored, whether that's the last hour or the last month, and it can slice, aggregate, and reshape that historical data in whatever way the current investigation needs. In short, metric filters are how you get alerted the moment something happens going forward; Logs Insights is how you dig through what already happened. A mature monitoring design uses metric filters for the handful of patterns you always want to know about immediately, and reaches for Logs Insights for the open-ended, retroactive questions that come up during an actual investigation.$$);
