-- A+ Core 1 (220-1101) Domain 1 expansion: Mobile Devices.
-- Tops objectives 1.1 (laptop hardware & components), 1.2 (laptop/mobile display
-- components), 1.3 (mobile accessories & ports) and 1.4 (mobile network
-- connectivity & application support) up to 33 items each.
--   questions   a1-q-200 .. a1-q-251  (52: 37 mcq, 10 multi, 3 ordering, 2 matching)
--   flashcards  a1-f-200 .. a1-f-261  (62: 57 core, 5 acronym)
-- Acronym decks: IPS, NFC, MAM, IMEI, PRL. OLED and MDM were skipped because
-- acronym cards for them already exist in the aplus1 bank.
-- Text uses dollar-quoting, matching every other seed and expansion file.

insert into public.questions (id, cert, domain, objective, qtype, difficulty, stem, choices, answer, explanation) values

-- ---------- 1.1 Laptop hardware and components (14) ----------

('a1-q-200','aplus1',1,'1.1','mcq',1,$q$A customer brings in a thin ultrabook and asks a technician to double its memory. The technician opens the service manual and finds no memory compartment and no SO-DIMM sockets listed in the parts diagram. What is the most likely situation?$q$,$q$["The laptop uses full-size DIMMs that mount vertically behind the display hinge", "Memory can still be added by inserting a USB flash drive and enabling it as extra RAM", "The memory is soldered directly to the system board and cannot be upgraded", "The SO-DIMM sockets are hidden beneath the keyboard and are reached by removing it"]$q$::jsonb,'2'::jsonb,$q$Many thin-and-light laptops solder the DRAM packages to the board to save height, so the only way to get more memory is to buy a higher-capacity configuration up front or replace the machine. Hidden sockets under the keyboard is the tempting answer because some older business laptops genuinely do place one socket there - but the service manual parts diagram would still list the socket and the module, and here it lists neither. A USB flash drive provides caching at best and is never a substitute for physical RAM.$q$),

('a1-q-201','aplus1',1,'1.1','mcq',2,$q$A user reports that the trackpad on a three-year-old laptop has become stiff and no longer clicks, and that the machine now rocks because the bottom cover bulges outward. What should the technician do FIRST?$q$,$q$["Power the laptop off, stop charging it, and arrange replacement of the swollen battery", "Order and fit a new trackpad assembly, since the click mechanism has worn out", "Run a battery calibration cycle to restore the pack to its rated capacity", "Tighten the bottom-cover screws so the palm rest seats flat against the chassis again"]$q$::jsonb,'0'::jsonb,$q$A bulging bottom cover with a trackpad that will not depress is the classic signature of a swollen lithium-ion battery pushing upward from underneath - a fire and rupture hazard, so charging stops and the pack is replaced with a manufacturer-approved part and recycled through an approved battery programme. Replacing the trackpad is the tempting answer because that is where the user notices the symptom, but the trackpad is intact and merely obstructed; fitting a new one leaves a swelling pack in the chassis. Tightening screws actively compresses the cell, which is exactly what must not happen.$q$),

('a1-q-202','aplus1',1,'1.1','mcq',2,$q$A small drink spill has left five keys on a laptop keyboard completely unresponsive while the rest of the keyboard, the trackpad and the display all work normally. What is the correct field repair?$q$,$q$["Pull and replace the five affected keycaps, which contain the failed switches", "Remap the five dead keys to unused keys through the operating system", "Replace the system board, since the keyboard controller lives on it", "Replace the keyboard assembly, which on most laptops is the field-replaceable unit"]$q$::jsonb,'3'::jsonb,$q$Laptop keys sit on a single shared membrane or scissor matrix on one flex circuit, so liquid damage to part of that matrix kills a group of keys and the whole keyboard assembly is the part that gets swapped - on many current designs it is riveted into the top case, making the top case the replaceable unit. Replacing keycaps is the tempting answer because a keycap is the visible part a user can pop off, but a keycap is just plastic; it carries no switch and replacing it does nothing for a dead contact underneath.$q$),

('a1-q-203','aplus1',1,'1.1','mcq',3,$q$A technician must move a laptop from its 2.5-inch SATA hard drive to a new M.2 NVMe SSD. The installed operating system, applications and user data must all survive, and the laptop has only one internal drive position available at a time. Which approach best meets the requirement?$q$,$q$["Convert the hard drive to a dynamic disk and extend its volume onto the new SSD", "Fit the SSD in an external USB enclosure, clone the hard drive to it, then swap the SSD into the laptop", "Copy the user profile folders to a USB stick, install the SSD, and perform a clean operating-system install", "Install the SSD first and let the UEFI firmware copy the old drive across automatically"]$q$::jsonb,'1'::jsonb,$q$Cloning through a USB enclosure works around the single-bay limitation: the new drive is visible at the same time as the old one, the clone copies the operating system, applications and data intact, and only then is the SSD moved inside. Copying the profile and reinstalling is the tempting answer because it does preserve user files, but it discards the installed applications and settings and turns a 30-minute swap into a full rebuild. UEFI firmware has no drive-copy function, and spanning a volume across two disks is not a migration at all - it would leave the system dependent on both drives.$q$),

('a1-q-204','aplus1',1,'1.1','mcq',2,$q$After a technician replaces the M.2 wireless card in a laptop, the adapter appears normally in Device Manager with no errors, but the laptop now sees only the access point in the same room and connects at a very low rate. What was most likely missed during reassembly?$q$,$q$["The card was installed in the storage socket rather than the wireless socket", "The antenna leads were not reattached to the wireless card connectors", "The wireless driver was not installed for the new card model", "Airplane mode was left switched on after the repair"]$q$::jsonb,'1'::jsonb,$q$Detecting only the nearest access point at a poor rate is a signal-path symptom, and the signal path for a laptop runs from the card through two hair-thin u.FL/MHF leads, through the hinge, to the antenna elements in the lid. If the leads are unplugged or pinched, the card still works electrically - which is exactly why it enumerates cleanly. A missing driver is the reflex answer for a newly fitted card, but a card with no driver shows a warning in Device Manager and lists no networks at all rather than a short list of very close ones. Airplane mode would disable the radio entirely, and the M.2 keying physically prevents a wireless card from entering a storage socket.$q$),

('a1-q-205','aplus1',1,'1.1','mcq',1,$q$An insurance assessor works on a laptop in busy waiting rooms and on trains, and is worried that people beside and behind her can read customer records off the screen. Which physical component addresses this?$q$,$q$["A shorter screen-lock timeout enforced by group policy", "Full-disk encryption on the laptop storage", "A cable lock anchoring the laptop to the desk", "A privacy screen filter fitted over the display"]$q$::jsonb,'3'::jsonb,$q$A privacy filter is a polarising film or snap-on panel that narrows the display viewing angle so the image looks black from the side - the direct countermeasure to shoulder surfing, and the only option here that protects the screen while the user is actively working. A shorter lock timeout is the tempting answer because it is the standard laptop-privacy control, but it only protects an unattended machine; it does nothing while the assessor is typing. Encryption protects data at rest on a stolen device, and a cable lock protects the hardware, not what is displayed on it.$q$),

('a1-q-206','aplus1',1,'1.1','mcq',2,$q$A hospital wants clinicians to authenticate at shared bedside laptops by touching their existing contactless staff badge against the palm rest, without typing a password each time. Which laptop component provides this?$q$,$q$["A near-field scanner built into the palm rest", "A fingerprint reader integrated with the power button", "An infrared camera for facial recognition", "A Trusted Platform Module on the system board"]$q$::jsonb,'0'::jsonb,$q$A near-field (NFC) scanner reads the contactless badge the clinicians already carry at a few centimetres, which is precisely the tap-to-log-on workflow described. A fingerprint reader is the tempting answer because it is the most common laptop biometric, but it authenticates the person directly and makes no use of the badge the hospital has already issued - and gloved clinical hands read poorly. An IR camera has the same problem behind a mask, and a TPM stores keys; it has no way to sense anything presented to the outside of the machine.$q$),

('a1-q-207','aplus1',1,'1.1','mcq',2,$q$A field engineer carries a laptop in a backpack over rough sites and has already lost one drive to physical shock. Which replacement drive best addresses the problem, and for what reason?$q$,$q$["A 2.5-inch hard drive with a larger cache, because caching reduces head movement", "An external USB hard drive, because it is not mounted inside the chassis", "An M.2 NVMe SSD, because it has no moving parts to be damaged by shock", "A 7,200 RPM hard drive, because the higher spindle speed resists vibration"]$q$::jsonb,'2'::jsonb,$q$Solid-state drives store data in NAND flash with no platters or heads, so an impact that would crash a hard-drive head onto a spinning platter does nothing mechanical to them - and they also draw less power and run cooler and quieter. The larger-cache hard drive is the plausible-sounding distractor because a cache genuinely does reduce head activity, but it does nothing while the drive is being jolted in a backpack, and a faster 7,200 RPM spindle makes a shock event worse rather than better. Moving the data to an external drive just puts the same fragile mechanism in the same bag.$q$),

('a1-q-208','aplus1',1,'1.1','mcq',3,$q$A technician tries to fit an M.2 2280 NVMe SSD into the only free M.2 socket on a laptop board. The socket is much shorter than the drive and the notch in the drive does not line up with the socket key. What is the most likely explanation?$q$,$q$["The SSD is a SATA M.2 drive and this socket accepts only NVMe drives", "The socket must be enabled in UEFI setup before a card will physically seat in it", "The mounting standoff screw is missing, which is preventing the card from seating", "The free socket is the short A/E-keyed 2230 socket intended for the wireless card"]$q$::jsonb,'3'::jsonb,$q$M.2 sockets are keyed and sized on purpose: storage cards are M-keyed (or B+M) and are usually 2280 long, while the wireless card uses a short 2230 socket with an A/E key. A physically shorter socket with a mismatched notch is the board telling the technician this is the Wi-Fi position, not a spare storage slot. Confusing SATA and NVMe is the tempting answer because both do exist in M.2 form, but that mismatch is electrical - such a drive still slides into the socket and simply is not detected. A firmware setting can never change a connector's shape, and a missing standoff would let the card seat and then sit at an angle rather than block it.$q$),

('a1-q-209','aplus1',1,'1.1','mcq',1,$q$An office moves to unassigned hot desks. Management wants a low-cost way to stop someone walking off with a laptop that a user has stepped away from for a few minutes. What should be issued?$q$,$q$["An asset tag with the organisation name etched into the lid", "A cable lock threaded through the laptop security slot and anchored to the desk", "A UEFI supervisor password on every laptop", "Full-disk encryption with a pre-boot PIN"]$q$::jsonb,'1'::jsonb,$q$A cable lock is the physical security control for exactly this scenario: it tethers the chassis to the furniture so the machine cannot simply be lifted and carried out. A UEFI password is the tempting answer because it is a genuine laptop security measure, but it only stops the thief from changing firmware settings or booting - it does not stop them taking the hardware. Encryption likewise protects the data after the theft, and an asset tag only helps identify the machine if it is later recovered.$q$),

('a1-q-210','aplus1',1,'1.1','multi',2,$q$A technician is about to replace the keyboard in a business laptop. Select the TWO practices that apply. (Choose two.)$q$,$q$["Disconnect the internal battery connector from the board, not merely shut the operating system down","Release the ZIF connector latch before withdrawing the keyboard ribbon cable","Puncture the old battery pack to discharge it safely before disposal","Replace only the individual keycaps, because the key matrix is not part of the keyboard assembly","Blow compressed air into the socket to reset the keyboard controller after installation"]$q$::jsonb,'[0,1]'::jsonb,$q$Shutting down is not enough on a laptop with an internal battery - the board stays live, so the battery connector comes off before any component is disturbed. Ribbon cables terminate in zero-insertion-force connectors whose latch must be lifted or slid back first; pulling against a closed latch tears the flex circuit and is one of the most common self-inflicted repair failures. Puncturing a lithium-ion pack causes a violent thermal runaway and is never a disposal method. The keycap option is the tempting wrong answer because keycaps are removable, but the key matrix is exactly what the keyboard assembly is, and compressed air resets nothing.$q$),

('a1-q-211','aplus1',1,'1.1','multi',3,$q$A technician is migrating a user from an ageing laptop hard drive to a new SSD. Select the THREE actions that belong in the migration. (Choose three.)$q$,$q$["Verify that a current, complete backup of the user data exists before starting","Confirm the SSD capacity is at least as large as the data in use on the source drive","Boot the migrated system and have the user open their data before the old drive is wiped","Convert the source drive to a dynamic disk so that cloning software can read it","Permanently disable UEFI Secure Boot so the cloned drive will start"]$q$::jsonb,'[0,1,2]'::jsonb,$q$A migration is a copy operation performed on hardware that is already suspect, so a verified backup comes first, the destination has to be able to hold what is being copied, and the old drive is kept intact until the user has confirmed the new one boots and their files open. Converting to a dynamic disk is the tempting distractor because it sounds like a legitimate disk-preparation step, but it changes the on-disk layout for no benefit and complicates cloning. Secure Boot does not block a cloned installation that keeps its original boot loader, and switching it off permanently weakens the machine for no reason.$q$),

('a1-q-212','aplus1',1,'1.1','multi',2,$q$Select the TWO items that are physical privacy or security components of a laptop rather than software or firmware controls. (Choose two.)$q$,$q$["A privacy screen filter","A fingerprint reader in the palm rest","Full-disk encryption of the system volume","A screen-saver lock timeout enforced by policy","A UEFI supervisor password"]$q$::jsonb,'[0,1]'::jsonb,$q$The objective calls out physical privacy and security components - parts you can hold. A privacy filter is a physical film limiting the viewing angle and a fingerprint reader is a hardware biometric sensor. Encryption, lock timeouts and UEFI passwords are all real and useful controls, and the UEFI password is the most tempting of them because firmware feels like hardware, but it is a setting stored in firmware, not a component fitted to the machine.$q$),

('a1-q-213','aplus1',1,'1.1','ordering',2,$q$Place the steps for replacing a SO-DIMM in a laptop into the correct order.$q$,$q$["Insert the new SO-DIMM into the socket at roughly a 45-degree angle until the gold contacts disappear into the slot","Power the laptop down, unplug the AC adapter and disconnect the battery","Reassemble the cover, power on, and confirm the new memory total in UEFI setup or the operating system","Put on an anti-static wrist strap and work on a hard, grounded surface","Press the module flat until the side retaining clips latch over its notches","Open the memory compartment and spread the retaining clips so the existing module lifts"]$q$::jsonb,'[1,3,5,0,4,2]'::jsonb,$q$Electrical safety comes first: with an internal battery still connected the board remains live, so power down, unplug and disconnect the battery before anything else. Anti-static protection is put on next, before any component is touched. Only then is the compartment opened and the old module released by spreading the clips. Installation is the reverse of removal - the module enters at an angle so the contacts seat fully, then is pressed flat until the clips latch, and pressing flat before the contacts are seated is what cracks modules. Verifying the reported total last is what proves the module is genuinely seated rather than merely clipped in place.$q$),

-- ---------- 1.2 Display components of mobile devices (14) ----------

('a1-q-214','aplus1',1,'1.2','mcq',1,$q$Which statement correctly describes how an OLED laptop panel differs from an LED-backlit LCD?$q$,$q$["OLED is a variety of IPS panel driven by a faster backlight inverter", "OLED requires a CCFL lamp and a high-voltage inverter to illuminate the panel", "OLED pixels emit their own light, so there is no backlight and black pixels are switched fully off", "OLED uses a brighter LED backlight behind the same liquid-crystal matrix"]$q$::jsonb,'2'::jsonb,$q$OLED is emissive: each subpixel generates its own light, so the panel needs no backlight layer at all and a black pixel is simply switched off, which is why OLED contrast is effectively unlimited and the panel can be made thinner. The brighter-backlight option is the tempting one because it explains OLED's reputation for vivid images, but any backlight, however bright, leaks through a black LCD pixel and prevents true black. Inverters belong only to older CCFL-backlit LCDs and appear on no OLED panel.$q$),

('a1-q-215','aplus1',1,'1.2','mcq',2,$q$A user reports that their laptop screen is black. A technician shines a bright torch at an angle across the panel and can just make out the desktop and mouse pointer. An external monitor attached to the laptop displays normally. Which component has failed?$q$,$q$["The display backlight, or on an older CCFL panel its inverter", "The LCD panel itself, which is no longer forming an image", "The graphics processor on the system board", "The display data cable running through the hinge"]$q$::jsonb,'0'::jsonb,$q$The torch test is the discriminator on this objective: if a faint image is visible under external light, the panel is still receiving video and forming a picture, so the only thing missing is illumination - the backlight or, on a CCFL panel, the inverter that drives it. Blaming the panel is the tempting answer because the user's complaint is a black screen, but a failed panel would show nothing under a torch. A working external monitor rules the GPU out, and a broken display cable produces no image, garbage or lid-angle-dependent flicker rather than a clean but unlit picture.$q$),

('a1-q-216','aplus1',1,'1.2','mcq',3,$q$An older laptop with a CCFL-backlit display shows a dim, pinkish image that flickers for a few seconds after power-on and then goes dark, while an external monitor stays perfect. Which component converts the laptop DC supply into the high-voltage AC that the backlight lamp requires?$q$,$q$["The AC adapter", "The display data cable", "The inverter", "The digitizer"]$q$::jsonb,'2'::jsonb,$q$The inverter steps the laptop internal DC rail up to the high-voltage alternating current a cold-cathode fluorescent lamp needs to strike and stay lit; a dying inverter or lamp gives exactly this pattern of a brief pink flicker followed by darkness. The AC adapter is the tempting choice because it is the obvious high-voltage part of the system, but it does the opposite job - converting mains AC down to low-voltage DC - and it sits outside the machine. Note that LED-backlit and OLED panels have no inverter at all, so this answer never applies to a modern laptop.$q$),

('a1-q-217','aplus1',1,'1.2','mcq',2,$q$A 2-in-1 laptop was dropped. The image is bright, sharp and undistorted across the whole screen, the keyboard and trackpad work, but touch input is ignored in the lower-right region of the display while the rest of the screen responds normally. Which component should be replaced?$q$,$q$["The digitizer (touch layer) bonded over the panel", "The LCD panel", "The graphics processor", "The display data cable"]$q$::jsonb,'0'::jsonb,$q$The digitizer is the transparent touch-sensing layer laminated over the display glass, and impact damage to part of that grid produces a dead zone while the panel underneath keeps showing a perfect image. On many bonded assemblies this means ordering the complete display assembly. Reinstalling or blaming the touch driver is the usual wrong instinct, but a software or driver fault kills touch across the entire screen uniformly - a localised dead area is physical damage. An intact image rules out the panel and the cable.$q$),

('a1-q-218','aplus1',1,'1.2','mcq',2,$q$Why are the Wi-Fi antennas in a laptop routed up the sides of the display bezel rather than mounted next to the wireless card in the base?$q$,$q$["The lid position gives the shortest possible cable run to the wireless card", "The lid keeps the antennas away from the heat produced by the CPU", "Radio regulations require antennas to be at least 30 cm from the keyboard", "The lid is the highest point and is clear of the metal shielding, board and battery in the base"]$q$::jsonb,'3'::jsonb,$q$Antenna elements need clear space and height; the display lid raises them above the desk and away from the shielding cans, battery pack and ground planes crowded into the base, which is why the leads accept a long, awkward route through the hinge. The shortest-cable-run option is the tempting one because it sounds like good engineering practice, but the lid placement deliberately gives the longest run in the machine - signal quality is worth the extra loss. Heat is irrelevant to antenna performance here, and the regulatory figure is invented.$q$),

('a1-q-219','aplus1',1,'1.2','mcq',3,$q$A laptop returns from a screen replacement. The image is perfect, but the user now has to sit next to the access point to stay connected, where before the laptop worked across the whole building. What is the most likely cause?$q$,$q$["The laptop must be re-authenticated to the wireless network after any hardware change", "The antenna leads in the lid were left disconnected or pinched during reassembly", "The new panel draws power that the wireless card can no longer obtain", "The wireless driver was corrupted when the display assembly was removed"]$q$::jsonb,'1'::jsonb,$q$The Wi-Fi antenna elements live in the display bezel and their leads pass through the hinge to the card in the base, so any lid or panel service puts them at risk - unplugged from the card, trapped in the hinge, or torn off the element. A range collapse immediately after display work is that fault until proven otherwise. Driver corruption is the tempting distractor because reinstalling a driver is easy to try, but removing a display assembly does not touch software, and a broken driver would stop the adapter working entirely rather than shortening its range. Panels and wireless cards are on separate power rails, and no wireless network requires reauthentication because a screen was changed.$q$),

('a1-q-220','aplus1',1,'1.2','mcq',1,$q$A laptop's built-in webcam has failed and the user wants it repaired rather than replaced with an external one. Which statement about the repair is correct?$q$,$q$["The camera is soldered to the trackpad controller and cannot be serviced at all", "The camera module sits in the display bezel with its cable running through the hinge, so the display assembly must be opened", "The camera is mounted on the system board and is reached by removing the palm rest", "The camera is a removable M.2 card fitted alongside the wireless card"]$q$::jsonb,'1'::jsonb,$q$The webcam, its microphone array, the status LED and often an ambient-light sensor are all built into the display bezel above the screen, sharing a cable that runs down through the hinge to the board - so servicing any of them means opening or replacing the display assembly, which is why many organisations simply issue a USB webcam instead. Locating it on the system board is the tempting answer because that is where most laptop electronics live, but the camera has to look at the user, and the only part of the machine facing them is the lid.$q$),

('a1-q-221','aplus1',1,'1.2','mcq',3,$q$A user comparing laptops wants the LCD panel type with the deepest contrast and darkest blacks, and is willing to accept slower pixel response and some colour shift when viewed off-axis. Which panel type fits?$q$,$q$["TN", "IPS", "A TN panel with an IPS backlight", "VA"]$q$::jsonb,'3'::jsonb,$q$Among LCD types, vertical alignment gives the highest native contrast ratio and the deepest blacks, at the cost of slower response and noticeable colour shift away from centre - exactly the trade-off the user accepted. IPS is the tempting answer because it is the panel most often recommended, but IPS is chosen for colour accuracy and viewing angle, not for contrast, where it typically trails VA. TN gives the fastest response and the worst contrast and angles of the three, and "a TN panel with an IPS backlight" describes a product that does not exist, since the backlight is not a panel technology at all.$q$),

('a1-q-222','aplus1',1,'1.2','mcq',2,$q$A laptop display flickers and shows shifting horizontal lines. Opening or closing the lid a few degrees makes the lines appear or disappear. An external monitor connected at the same time is completely clean. What is the most likely cause?$q$,$q$["The display data cable running through the hinge is chafed or loose", "The panel backlight is failing", "The graphics processor is overheating", "The digitizer is short-circuiting against the panel"]$q$::jsonb,'0'::jsonb,$q$Symptoms that change with lid angle point at something that flexes with the lid, and the eDP or LVDS video cable is the part that bends through the hinge every time the laptop is opened - insulation wears, conductors break intermittently, and the picture corrupts. A failing backlight is the tempting alternative because it is the most common lid-related fault, but a backlight problem changes brightness, not image content, and would not paint lines. A GPU fault would corrupt the external monitor too, and the digitizer carries touch input, not video.$q$),

('a1-q-223','aplus1',1,'1.2','mcq',2,$q$A user with an 18-month-old laptop reports that on a plain white background they can faintly see the outline of the taskbar and of a chat window they keep open all day. The image is otherwise sharp and evenly lit. What is this?$q$,$q$["Backlight bleed at the panel edges", "A failing display data cable", "Image persistence (burn-in) on an OLED panel", "A cluster of stuck subpixels"]$q$::jsonb,'2'::jsonb,$q$Burn-in is uneven ageing of the organic emitters: elements that display the same bright static content for thousands of hours dim relative to their neighbours, leaving a permanent ghost of that content on plain backgrounds. It is specific to OLED and is why those panels ship with pixel-shift and taskbar auto-hide mitigations. Stuck pixels are the tempting answer because both are permanent display defects, but a stuck pixel is a single dot locked to one colour, not a recognisable shape matching the user interface. Backlight bleed shows at panel edges on dark content and cannot exist on a backlightless OLED, and a cable fault produces flicker or lines rather than a stable ghost.$q$),

('a1-q-224','aplus1',1,'1.2','mcq',3,$q$A laptop wireless card has two antenna connectors, labelled MAIN and AUX. During a repair only the MAIN lead is reconnected. What is the most likely result?$q$,$q$["The card is not detected by the operating system until both leads are attached", "Wi-Fi works normally but the card's Bluetooth radio stops functioning", "There is no effect, because the second connector is a spare for a future upgrade", "The card still associates with networks, but range and throughput are noticeably reduced"]$q$::jsonb,'3'::jsonb,$q$Modern 802.11n/ac/ax cards use multiple antennas for MIMO spatial streams and receive diversity, so with one lead attached the radio still transmits and receives and the connection looks healthy - it simply loses a stream and the ability to pick the better signal path, which shows up as lower rates and shorter usable range. Non-detection is the tempting answer because a missing connection feels fatal, but enumeration on the M.2 bus has nothing to do with the RF leads. Bluetooth shares the card and the 2.4 GHz path and keeps working over the remaining antenna, and no laptop ships a purely decorative antenna connector.$q$),

('a1-q-225','aplus1',1,'1.2','multi',2,$q$Select the TWO observations that point to a failed backlight rather than a failed LCD panel. (Choose two.)$q$,$q$["A faint but complete image is visible when a bright torch is held close to the screen","An external monitor attached to the laptop displays normally","A large black blotch with radiating cracks covers part of the screen","Touch input is ignored across the entire screen","Vertical coloured lines appear on the laptop screen and on the external monitor"]$q$::jsonb,'[0,1]'::jsonb,$q$A visible image under a torch proves the panel is still receiving video and rendering it, so only illumination is missing, and a clean external monitor proves the graphics processor and its output are healthy - together they isolate the fault to the backlight or its inverter. Cracks with a spreading black blotch are physical liquid-crystal damage to the panel itself, the strongest distractor because it is also a lid fault. Dead touch is a digitizer symptom, and corruption that follows onto the external monitor points to the GPU or system board rather than anything in the lid.$q$),

('a1-q-226','aplus1',1,'1.2','multi',3,$q$Select the TWO statements that are true of OLED laptop displays compared with LED-backlit LCDs. (Choose two.)$q$,$q$["OLED needs no backlight layer and no inverter, because each pixel is its own light source","OLED can render true black by switching individual pixels completely off","OLED is immune to image retention because there is no backlight to age","OLED requires a CCFL lamp driven by a high-voltage inverter","OLED places an emissive layer behind a conventional TN liquid-crystal matrix"]$q$::jsonb,'[0,1]'::jsonb,$q$Self-emissive pixels are the whole point of OLED: no backlight assembly, no inverter, and per-pixel control that makes true black possible. Immunity to image retention is the most tempting distractor because it sounds like a logical consequence of removing the backlight, but it is backwards - burn-in is caused by the organic emitters themselves ageing unevenly, so removing the backlight is exactly what introduces the risk. CCFL lamps and inverters belong to older LCDs, and OLED has no liquid-crystal matrix of any kind.$q$),

('a1-q-227','aplus1',1,'1.2','matching',2,$q$Match each laptop display symptom to the component most likely responsible.$q$,$q${"left":["A faint image is visible only under a bright torch; an external monitor is fine","The picture is perfect but one corner of the touchscreen ignores input","Wi-Fi range collapsed immediately after the display assembly was serviced","Lines and flicker appear and disappear as the lid is moved through certain angles"],"right":["The display data cable passing through the hinge","The backlight, or its inverter on a CCFL panel","An antenna lead in the display bezel","The digitizer layer over the panel"]}$q$::jsonb,'[1,3,2,0]'::jsonb,$q$Each symptom maps to the part of the lid that produces it. Illumination missing but image present is the backlight or inverter; a perfect image with localised dead touch is the digitizer, since a driver fault would kill touch everywhere; a range collapse straight after lid service is a disconnected or pinched antenna lead, not a driver; and corruption that tracks lid angle is the flexing video cable. The common trap is answering the last one with the backlight because the fault is in the lid - but brightness faults never draw lines.$q$),

-- ---------- 1.3 Accessories and ports of mobile devices (12) ----------

('a1-q-228','aplus1',1,'1.3','mcq',2,$q$Which statement about the USB-C connector is correct?$q$,$q$["It defines a fixed transfer rate that is the same on every device that uses it", "It is a reversible connector that can carry data, video via Alternate Mode and power in either direction", "It is a data-only connector, so charging always requires a separate barrel jack", "It is Apple's proprietary connector, licensed to other manufacturers"]$q$::jsonb,'1'::jsonb,$q$USB-C is a connector form factor, not a speed or a feature set: the same reversible plug can carry USB data at anything from USB 2.0 rates up to USB4 and Thunderbolt, DisplayPort or HDMI video through Alternate Mode, and power in either direction through USB Power Delivery. The fixed-transfer-rate option is the tempting one because people talk about USB-C as though it were a performance class, but two identical-looking ports can differ enormously - which is why a dock may fail to drive a monitor on one laptop and work on another.$q$),

('a1-q-229','aplus1',1,'1.3','mcq',1,$q$A helpdesk stocks charging cables for a mixed fleet. Which statement about the Lightning connector is correct?$q$,$q$["It is a 24-pin reversible connector that also carries DisplayPort video natively", "It is a legacy 30-pin connector superseded by micro-USB", "It is Apple's proprietary reversible 8-pin connector used on older iPhones and iPads", "It is the industry-standard connector that replaced micro-USB on Android phones"]$q$::jsonb,'2'::jsonb,$q$Lightning is Apple's own small reversible 8-pin connector, introduced to replace Apple's earlier 30-pin dock connector and used on iPhones and iPads until those product lines moved to USB-C. The industry-standard option is the tempting one because Lightning and USB-C look similar and serve the same role, but Lightning was never licensed as an industry standard and never appeared on Android hardware - USB-C is the connector that unified the market. The 24-pin reversible description belongs to USB-C.$q$),

('a1-q-230','aplus1',1,'1.3','mcq',2,$q$A technician needs to reach the console of a managed switch in a wiring closet using a modern laptop that has only USB-C and USB-A ports. Which connection method should be used?$q$,$q$["A USB-to-serial (RS-232) console adapter with terminal software on the laptop", "An HDMI cable from the laptop to the switch management port", "An NFC tap between the laptop and the switch", "A Bluetooth pairing between the laptop and the switch"]$q$::jsonb,'0'::jsonb,$q$Console access on network hardware is a serial interface: the switch presents an RS-232 console port, and because laptops no longer ship a DB-9 port the technician uses a USB-to-serial adapter with a terminal application, typically at 9600 8-N-1. HDMI is the tempting answer because it is the connector the laptop actually has and it is used for out-of-band screens on some appliances, but HDMI is a one-way video interface and cannot carry a command-line session. Switches expose no NFC or Bluetooth console interface.$q$),

('a1-q-231','aplus1',1,'1.3','mcq',2,$q$A user needs two extra USB-A ports and a wired Ethernet connection added to their laptop when they sit at their desk. They need no additional displays and the laptop already has its own charger. Which accessory is the most appropriate and lowest-cost fit?$q$,$q$["A KVM switch", "An unpowered USB-A hub", "A port replicator", "A Thunderbolt docking station with dual DisplayPort outputs and 90 W charging"]$q$::jsonb,'2'::jsonb,$q$A port replicator is precisely this product: a single-connector accessory that duplicates ports the laptop already supports - USB and Ethernet - with no additional display capability and no power delivery. The Thunderbolt dock is the tempting answer because it would certainly do the job, but it pays for dual video outputs and 90 W charging the user explicitly does not need. A KVM shares one keyboard, monitor and mouse between several computers rather than expanding one, and an unpowered hub adds USB ports but no Ethernet at all.$q$),

('a1-q-232','aplus1',1,'1.3','mcq',2,$q$A user bought a rubber-tipped stylus for their tablet and complains that it has no pressure sensitivity and that resting a hand on the screen makes stray marks. What should the technician explain?$q$,$q$["A passive stylus only mimics a finger; pressure and palm rejection require an active pen the device supports", "The digitizer has failed and the display assembly must be replaced", "Pressure sensitivity is enabled by pairing the stylus over Bluetooth tethering", "A screen protector is blocking the capacitive layer and must be removed"]$q$::jsonb,'0'::jsonb,$q$A passive stylus is nothing more than a conductive tip that the capacitive touchscreen reads exactly as it would read a fingertip, so there is no channel to report pressure or tilt and no way for the device to know a palm is not another finger. Those features need an active pen with its own power and a supported protocol talking to a compatible digitizer. Blaming the digitizer is the tempting answer because the symptom is touch-related, but the screen is behaving exactly as designed - the accessory, not the hardware, is the limitation.$q$),

('a1-q-233','aplus1',1,'1.3','mcq',3,$q$A user plugs a headset with a single 3.5 mm plug into a laptop combo audio jack. Audio plays through the earpieces correctly, but the laptop offers no input device for the headset microphone. What is the most likely cause?$q$,$q$["The combo jack is wired as line-level output only and cannot accept a headset", "The audio driver must be reinstalled before the microphone will enumerate", "The headset must first be paired over Bluetooth to enable its microphone", "The headset uses a 3-pole TRS plug, so it carries no microphone conductor"]$q$::jsonb,'3'::jsonb,$q$A laptop combo jack expects a 4-pole TRRS plug: tip and first ring carry left and right audio, and the remaining contacts carry ground and the microphone. A 3-pole TRS plug physically has no conductor for the microphone, so headphones work and the mic never appears - the fix is a TRRS headset, a TRS-to-TRRS splitter or a USB headset. The line-output option is the tempting one because it also explains a missing microphone, but a jack that were output-only would not be described as a combo jack, and audio in this scenario is already working through it.$q$),

('a1-q-234','aplus1',1,'1.3','mcq',2,$q$A graphic artist needs pressure-sensitive freehand drawing and handwriting on a laptop that has no touchscreen and cannot be replaced this year. Which accessory should be specified?$q$,$q$["A Thunderbolt docking station with an extra display output", "An external drawing pad (graphics tablet) with an active pen", "A larger external precision trackpad", "A passive touch pen used on the laptop's existing trackpad"]$q$::jsonb,'1'::jsonb,$q$A drawing pad provides an absolute-position surface with an active pen that reports pressure and usually tilt, which is what freehand illustration and handwriting need, and it works with any laptop over USB regardless of whether the laptop screen is touch-capable. The external trackpad is the tempting answer because it is also a pointing surface, but a trackpad reports relative movement with no pressure levels and no pen tracking, so it cannot produce a varying-width stroke. A dock adds ports, not input capability.$q$),

('a1-q-235','aplus1',1,'1.3','mcq',2,$q$A user holds their phone against a Bluetooth speaker and the two connect immediately, without opening the phone's Bluetooth settings and choosing the device. Which statement explains what happened?$q$,$q$["The phone tethered to the speaker, sharing its cellular connection", "NFC carried the pairing handshake at tap range, and the audio then streamed over Bluetooth", "NFC carried the audio stream, so Bluetooth was never used", "The speaker joined the phone's Wi-Fi hotspot and streamed over the local network"]$q$::jsonb,'1'::jsonb,$q$Tap-to-pair uses NFC only for the handshake: at a few centimetres the two devices exchange the Bluetooth address and pairing information, then hand the session straight over to Bluetooth, which supplies the range and bandwidth the audio needs. The idea that NFC carries the audio is the tempting misreading because the tap is what the user actually did, but NFC works over a couple of centimetres at low data rates and could not sustain a music stream while the phone sits in a pocket.$q$),

('a1-q-236','aplus1',1,'1.3','multi',3,$q$A user wants one USB-C cable from their laptop to a dock that will drive two external monitors, charge the laptop and provide Ethernet. Select the TWO things the technician must verify beforehand. (Choose two.)$q$,$q$["That the laptop's USB-C port supports DisplayPort Alternate Mode or Thunderbolt","That the dock's Power Delivery output meets or exceeds the laptop's charger rating","That the laptop contains a discrete GPU, because USB-C video requires one","That the cable supplied is a charge-only cable, to protect the high-speed lanes","That the dock and the laptop are running the same operating system version"]$q$::jsonb,'[0,1]'::jsonb,$q$Not every USB-C port carries video - some are data and charge only - so the port specification has to be checked before promising dual monitors, and a dock rated below the laptop's charger will let the battery drain under load even though the laptop reports it is connected to power. The charge-only cable option is the most tempting trap because it sounds like a protective measure, but such cables omit the high-speed pairs entirely and would break both video and data. Integrated graphics drive USB-C displays perfectly well, and a dock has no operating system to match.$q$),

('a1-q-237','aplus1',1,'1.3','multi',2,$q$Select the TWO capabilities that a full docking station typically adds but a basic port replicator does not. (Choose two.)$q$,$q$["Charging the laptop over the same single connection","Driving multiple independent external displays","Providing additional USB ports","Providing a wired Ethernet connection","Giving the laptop a raised place to sit on the desk"]$q$::jsonb,'[0,1]'::jsonb,$q$Extra USB ports and Ethernet are exactly what a port replicator exists to provide, so they cannot be what distinguishes the two products - that is the trap in this item. The dock's differentiators are power delivery to charge the laptop over the same cable and enough video bandwidth to run several independent displays, and higher-end docks add storage or graphics expansion as well. A physical stand is a stand, not a capability of either device.$q$),

('a1-q-238','aplus1',1,'1.3','ordering',2,$q$Place the steps for setting up a USB-C docking station at a new desk into the correct order.$q$,$q$["Connect the external monitors, keyboard, mouse and Ethernet cable to the dock","Confirm the laptop's USB-C port supports DisplayPort Alternate Mode and note the charger wattage it needs","Plug the dock's own power supply into the mains and switch the dock on","Attach the single USB-C cable between the dock and the laptop","Arrange the displays in the operating system and confirm the laptop reports that it is charging"]$q$::jsonb,'[1,2,0,3,4]'::jsonb,$q$Compatibility is confirmed first, because a port without Alternate Mode or a dock that cannot supply the laptop's wattage makes every later step pointless. The dock is then powered, since an unpowered dock cannot enumerate its downstream devices or deliver charge. Peripherals are attached to the dock before the laptop is connected so that everything appears in one enumeration pass rather than in a sequence of hot-plug events, and the single cable to the laptop is what brings the whole arrangement live. Verifying display layout and charging status last is what proves both the video and power paths actually work rather than merely being connected.$q$),

('a1-q-239','aplus1',1,'1.3','matching',2,$q$Match each mobile connection method or accessory to what it provides.$q$,$q${"left":["Lightning","NFC","Port replicator","Active touch pen"],"right":["Duplicates ports the laptop already has at the desk, without adding displays or charging","Apple proprietary reversible 8-pin connector used on older iPhones and iPads","Pressure sensitivity, tilt and palm rejection when writing on a compatible digitizer","Tap-range wireless used for contactless payment and for pairing handshakes"]}$q$::jsonb,'[1,3,0,2]'::jsonb,$q$Lightning is Apple's own 8-pin reversible connector, distinct from the industry-standard USB-C that replaced it. NFC operates over a couple of centimetres and is used for payments, badges and tap-to-pair handshakes that then hand the session to Bluetooth. A port replicator only duplicates existing ports - adding displays and charging over one cable is what makes an accessory a docking station instead. An active pen is powered and communicates with the digitizer, which is what gives it pressure and palm rejection that a passive stylus can never provide. The usual error is pairing NFC with the docking-style description because both are desk conveniences.$q$),

-- ---------- 1.4 Mobile network connectivity and application support (12) ----------

('a1-q-240','aplus1',1,'1.4','mcq',2,$q$A user on a rural site reports that their new 5G phone shows an LTE indicator most of the working day and only shows 5G when they drive into town. What should the technician tell them?$q$,$q$["The SIM is a 4G SIM and must be exchanged for a 5G SIM", "The phone needs a PRL update before it will use 5G", "5G has been disabled in the phone's developer settings", "This is expected behaviour: the phone falls back to 4G LTE where there is no 5G coverage"]$q$::jsonb,'3'::jsonb,$q$Cellular generations coexist, and handsets are built to select the best available technology and drop back automatically - 5G coverage is still concentrated in built-up areas, so an LTE indicator in the countryside means the network, not the phone, is the limit. The PRL suggestion is the tempting one because a roaming list genuinely does control which networks a handset prefers, but it cannot conjure a 5G signal where no 5G radio has been deployed. SIMs are not generation-locked in the way the SIM-exchange answer implies, and a developer setting that silently disables 5G is not a normal cause.$q$),

('a1-q-241','aplus1',1,'1.4','mcq',2,$q$An employee is travelling abroad for six weeks and wants to keep using their own handset while paying local rates rather than international roaming charges. What is the standard approach?$q$,$q$["Confirm the handset is carrier-unlocked, then fit a local SIM or activate a local eSIM profile", "Have the carrier push a PRL update so the phone uses the foreign network at local rates", "Enrol the device in MDM so the roaming charges are billed to the corporate account", "Enable Wi-Fi calling, which removes cellular charges of every kind"]$q$::jsonb,'0'::jsonb,$q$On a SIM-based network the subscriber identity lives on the SIM rather than in the handset, so an unlocked phone can simply take a local operator's SIM or download a local eSIM profile and be billed as a domestic customer. The PRL option is the tempting distractor because a roaming list really does steer the handset between networks, but it only reorders preferences within the home carrier's roaming agreements - the billing relationship is unchanged. MDM manages policy and applications and has nothing to do with tariffs, and Wi-Fi calling helps only when Wi-Fi is available and does not remove cellular charges elsewhere.$q$),

('a1-q-242','aplus1',1,'1.4','mcq',3,$q$After a carrier reorganises its towers and roaming partners in a region, users of older handsets on that carrier report dropped calls and long periods with no service, while newer handsets are unaffected. Which maintenance action refreshes the list of networks and frequencies the handset should prefer?$q$,$q$["An IMEI re-registration", "A factory reset of the handset", "A PRL update", "An APN reset"]$q$::jsonb,'2'::jsonb,$q$The Preferred Roaming List is the carrier-supplied table telling the handset which systems, bands and roaming partners to look for and in what order; when the carrier changes its network the list has to be refreshed or the phone keeps hunting for arrangements that no longer exist. Resetting the APN is the tempting answer because it is the other carrier-side setting technicians know, but the APN governs the data connection to the packet network and has no effect on which tower the phone camps on for voice. The IMEI identifies the handset for blocking and provisioning and is not a service-selection setting, and a factory reset erases the user's data while leaving the same stale roaming list in place.$q$),

('a1-q-243','aplus1',1,'1.4','mcq',2,$q$Four colleagues in a meeting room with no usable Wi-Fi need internet access on their laptops through one person's phone. Which method should be used?$q$,$q$["Use USB tethering from the phone to each laptop in turn", "Use Bluetooth PAN tethering, which supports the largest number of simultaneous clients", "Use NFC to share the phone's connection with each laptop", "Enable the phone's Wi-Fi mobile hotspot and have each laptop join it"]$q$::jsonb,'3'::jsonb,$q$A Wi-Fi hotspot turns the phone into an access point, so several clients associate at once at Wi-Fi rates - the only option here that serves four laptops simultaneously. USB tethering is the tempting alternative because it is the fastest and most reliable method and it charges the phone at the same time, but a phone has one USB port and therefore one tethered client. Bluetooth PAN works but is the slowest of the three and supports few clients, and NFC has neither the range nor the throughput to share a connection at all. Warn the user about data allowance and battery drain.$q$),

('a1-q-244','aplus1',1,'1.4','mcq',1,$q$A user says the new Bluetooth speaker they were issued never appears in the list of available devices on their phone, although the phone finds their car and their headphones normally. What should be checked first?$q$,$q$["Whether the phone and the speaker are on the same Wi-Fi network", "Whether the speaker has been put into discoverable (pairing) mode", "Whether the phone's mobile hotspot has been enabled", "Whether the speaker needs a PRL update from the carrier"]$q$::jsonb,'1'::jsonb,$q$Bluetooth accessories are not permanently discoverable - a button is normally held until an indicator flashes, and the accessory drops back out of pairing mode after a minute or two, which is why a speaker that was never put into that state simply never appears. The fact that the phone discovers other devices already proves the phone's radio and scanning are working. The Wi-Fi option is the tempting one because both are wireless and users conflate them, but Bluetooth pairing is entirely independent of any Wi-Fi network, and a PRL is a cellular roaming list that has nothing to do with an accessory.$q$),

('a1-q-245','aplus1',1,'1.4','mcq',2,$q$A user reports that a mapping application says it cannot determine their position and asks the helpdesk to repair the phone's GPS. Outdoors, other applications show the correct location. What should the technician check first?$q$,$q$["Whether the carrier has pushed a PRL update that re-enables GPS", "Whether airplane mode has disabled the satellite receiver permanently", "Whether location services are enabled and whether that specific app has been granted location permission", "Whether the phone's GPS antenna has become detached and needs replacement"]$q$::jsonb,'2'::jsonb,$q$Location on a modern phone is a permission-gated service: the system-wide toggle must be on and the individual application must hold the permission, and mobile operating systems increasingly default new apps to no access or to while-in-use only. Other apps reporting the correct position proves the receiver itself is fine, which is exactly why the antenna option is wrong even though it is the tempting hardware answer the user has already suggested. A PRL governs cellular roaming, not positioning, and airplane mode affects the whole device rather than one application - and is never permanent.$q$),

('a1-q-246','aplus1',1,'1.4','mcq',3,$q$A technician is configuring corporate mail on staff phones. The organisation requires that mail, calendar and contacts all stay in sync across the user's devices and that IT can enforce a passcode policy and remotely wipe only the corporate mailbox. Which account type should be configured?$q$,$q$["An Exchange / Microsoft 365 account using Exchange ActiveSync", "A POP3 account with SMTP for outgoing mail", "An IMAP account with SMTP for outgoing mail", "A forwarding rule that copies corporate mail into the user's personal account"]$q$::jsonb,'0'::jsonb,$q$Exchange ActiveSync is the only option here that carries calendar and contact data alongside mail and that lets the server push device policy and perform a targeted wipe of the corporate account. IMAP is the tempting near-miss because it does keep mail synchronised across devices and is often confused with a full corporate configuration, but it transports mail only - no calendar, no contacts, and no policy or remote-wipe channel. POP3 is weaker still, downloading messages to one device and typically removing them from the server, and forwarding to a personal account puts corporate data outside every control the organisation has.$q$),

('a1-q-247','aplus1',1,'1.4','mcq',2,$q$A company requires that access to corporate applications on mobile devices use something the user knows plus something the user has. Which configuration meets the requirement?$q$,$q$["A fingerprint plus facial recognition on the same handset", "A longer password combined with a 30-day expiry policy", "The account password plus a time-based code from an authenticator app on the enrolled device", "The account password plus an answer to a personal security question"]$q$::jsonb,'2'::jsonb,$q$Two-factor authentication requires two different categories of factor, and a password (knowledge) combined with a code generated on a device the user physically holds (possession) satisfies exactly that. The security-question option is the classic trap: it feels like a second step, but a memorised answer is another piece of knowledge, so the pair remains single-factor. A fingerprint and a face are both inherence factors and likewise fall in one category, and password length and expiry are strength rules that add no factor at all.$q$),

('a1-q-248','aplus1',1,'1.4','multi',2,$q$A user replaces their phone and signs in to the same cloud account on the new handset. Select the THREE items that are typically restored by that sign-in. (Choose three.)$q$,$q$["Contacts","Calendar entries","Email","The handset's IMEI","The carrier's preferred roaming list"]$q$::jsonb,'[0,1,2]'::jsonb,$q$Account synchronisation through Microsoft 365, a Google account or iCloud carries the user's personal data - contacts, calendar, mail, and usually photos, app lists, bookmarks and settings - which is what makes signing in the standard first step on a replacement device. The IMEI is the most tempting distractor because it does move with the user's service, but it is the unique identity of the handset hardware itself and is burned into the new phone, not restored onto it. The PRL is likewise supplied by the carrier to that specific handset and has nothing to do with a user account.$q$),

('a1-q-249','aplus1',1,'1.4','multi',2,$q$A user asks to turn on their phone's Wi-Fi hotspot for a colleague's laptop. Select the TWO consequences they should be warned about. (Choose two.)$q$,$q$["Hotspot traffic is counted against the phone's cellular data allowance","Running the hotspot noticeably increases battery drain","The phone cannot receive voice calls while the hotspot is active","Connected laptops receive addresses from the corporate DHCP server","The hotspot requires the handset to be rooted or jailbroken first"]$q$::jsonb,'[0,1]'::jsonb,$q$Everything the connected laptop downloads travels over the phone's cellular link, so it consumes the phone owner's allowance and can trigger throttling or overage, and running a Wi-Fi radio as an access point on top of the cellular radio is one of the heaviest continuous loads a phone can carry, so the phone should stay on charge. Losing voice service is the most tempting distractor because older data behaviour worked that way, but on LTE and 5G voice and data run together. The hotspot hands out addresses from its own private range, and it is a standard operating-system feature that needs no rooting.$q$),

('a1-q-250','aplus1',1,'1.4','multi',3,$q$Select the TWO statements that correctly contrast MDM with MAM. (Choose two.)$q$,$q$["MDM enrols and controls the whole device, including passcode policy and full-device remote wipe","MAM controls only the corporate applications and their data, allowing a selective wipe that leaves personal content intact","MAM can only be used on corporate-owned devices that have been factory reset before enrolment","MDM can be applied to only one mobile operating system per organisation","MAM removes the need for authentication on corporate applications"]$q$::jsonb,'[0,1]'::jsonb,$q$Mobile device management takes ownership of the device as a whole - passcode and encryption policy, restrictions, and a wipe that erases everything - while mobile application management confines itself to the managed apps and their container, so leaving the company removes corporate mail and files and leaves personal photos and messages untouched. The corporate-ownership claim is the most tempting distractor because it inverts the real position: it is precisely MAM's limited reach that makes it the usual choice for personally owned BYOD handsets. MDM platforms manage mixed iOS and Android fleets routinely, and MAM strengthens rather than removes app authentication.$q$),

('a1-q-251','aplus1',1,'1.4','ordering',1,$q$Place the steps for pairing a Bluetooth headset with a phone into the correct order.$q$,$q$["Select the discovered headset from the list on the phone","Enable Bluetooth on the phone and put the headset into discoverable (pairing) mode","Test the connection by playing audio and speaking into the microphone","Enter or confirm the PIN or passkey if the headset requests one","Wait for the phone to finish scanning and show the headset as a discovered device"]$q$::jsonb,'[1,4,0,3,2]'::jsonb,$q$Nothing can be found until both radios are ready, so Bluetooth is switched on and the accessory is put into pairing mode first - accessories are not permanently discoverable and time out of that state. The phone then scans and lists what it finds, the user selects the intended device, and any PIN or passkey is entered to complete the bond. Testing is deliberately last: a device can appear paired in the list yet still fail to carry audio if it connected on the wrong profile, so the pairing is only proven once sound and microphone are confirmed working.$q$);

insert into public.flashcards (id, cert, deck, domain, objective, front, back) values

-- ---------- 1.1 Laptop hardware and components (17) ----------

('a1-f-200','aplus1','core',1,'1.1',$$A customer asks whether the RAM in their thin ultrabook can be upgraded later. What do you check, and what is the usual answer?$$,$$Check the manufacturer service manual or parts diagram for SO-DIMM sockets. Many thin-and-light laptops solder the DRAM to the board to save height, so the only upgrade path is buying a higher-capacity configuration up front. Never promise an upgrade before checking the specific model.$$),

('a1-f-201','aplus1','core',1,'1.1',$$What does a bulging bottom cover, a trackpad that will not click, or a lid that no longer closes flat indicate on a laptop?$$,$$A swollen lithium-ion battery pressing outward from inside the chassis. Stop charging, power the machine down, never puncture or compress the pack, fit a manufacturer-approved replacement, and dispose of the old pack through an approved battery or e-waste recycling programme.$$),

('a1-f-202','aplus1','core',1,'1.1',$$In what order do you remove power before opening a laptop?$$,$$Shut the operating system down, unplug the AC adapter, remove the external battery or disconnect the internal battery connector from the board, then hold the power button a few seconds to drain residual charge. Fit an anti-static strap before touching any component.$$),

('a1-f-203','aplus1','core',1,'1.1',$$How is a SO-DIMM physically removed and installed?$$,$$Removal: push the two side retaining clips outward and the module springs up to roughly 45 degrees. Installation: insert at about 45 degrees until the gold contacts disappear into the socket, then press flat until both clips latch. Pressing flat before the contacts seat is what cracks modules.$$),

('a1-f-204','aplus1','core',1,'1.1',$$Why do laptops use SO-DIMM rather than DIMM, and what else has to match?$$,$$SO-DIMM (Small Outline DIMM) is the short form factor that fits a laptop chassis. Generation (DDR4 versus DDR5), supported speed, and whether the board has one or two sockets must all match the machine. The contact notch is keyed differently per generation, so a DDR4 module physically will not enter a DDR5 socket.$$),

('a1-f-205','aplus1','core',1,'1.1',$$What do M.2 key types and card lengths tell you about which card fits a socket?$$,$$M key (usually 2280 long) is PCIe/NVMe storage; B+M key is SATA or PCIe x2 storage; A+E key in a short 2230 socket is the Wi-Fi/Bluetooth card. Notch position and socket length physically prevent putting a storage card into a wireless socket, so a card that will not seat is usually in the wrong socket.$$),

('a1-f-206','aplus1','core',1,'1.1',$$What are the two standard ways to move a laptop operating system and its data onto a new drive?$$,$$1) Clone: attach the new drive (spare bay or USB/M.2 enclosure) and copy it sector by sector, then swap. 2) Image and restore: capture an image of the old drive to external or network storage, fit the new drive, restore the image. Back up first either way, and keep the old drive until the new one is verified.$$),

('a1-f-207','aplus1','core',1,'1.1',$$What must you verify about capacity before cloning a laptop drive?$$,$$The destination must hold the data actually in use on the source, and many tools additionally require it to be as large as the source partition unless they can shrink partitions during the copy. A 1 TB drive with 200 GB used clones to a 500 GB SSD only if the tool resizes partitions.$$),

('a1-f-208','aplus1','core',1,'1.1',$$What is a privacy screen filter and which threat does it counter?$$,$$A polarising film or snap-on panel that narrows the display viewing angle so the image reads as black from the side. It counters shoulder surfing and visual eavesdropping in open offices, aircraft and waiting rooms - and it is the only control that works while the user is actively typing. It does nothing against malware or theft.$$),

('a1-f-209','aplus1','core',1,'1.1',$$What is a near-field scanner on a laptop used for?$$,$$A built-in NFC reader in the palm rest that authenticates a user when they tap an NFC staff badge or token against it. Common on shared clinical and retail workstations where repeatedly typing a password is impractical and gloved hands defeat fingerprint readers.$$),

('a1-f-210','aplus1','core',1,'1.1',$$Which biometric readers appear on business laptops, and what do they actually do?$$,$$A fingerprint reader (palm rest or power button) and an infrared camera for facial recognition, which works in darkness and resists a printed-photo spoof. Both are inherence factors and normally release a credential held in the TPM rather than replacing the account password itself.$$),

('a1-f-211','aplus1','core',1,'1.1',$$What physically prevents a laptop from being carried off a hot desk?$$,$$A cable lock threaded through the laptop security slot and anchored to the furniture. It is a theft deterrent for the hardware only - full-disk encryption is what protects the data if the machine is taken anyway, and a UEFI password only stops firmware changes.$$),

('a1-f-212','aplus1','core',1,'1.1',$$What is easiest to forget when replacing a laptop M.2 wireless card?$$,$$Reattaching both hair-thin antenna leads (usually labelled MAIN/1 and AUX/2) to the u.FL/MHF connectors and routing them back into the lid without pinching them in the hinge. Symptom of a missed lead: the adapter enumerates cleanly and connects, but only to very close access points and at poor rates.$$),

('a1-f-213','aplus1','core',1,'1.1',$$Why is an SSD the default replacement drive in a laptop?$$,$$No moving platters or heads, so it survives the shock and vibration of being carried; lower power draw and heat, so better battery life; silent; and far lower access latency. Hard drives still win only on cost per terabyte for bulk storage.$$),

('a1-f-214','aplus1','core',1,'1.1',$$How do you release a ZIF ribbon-cable connector?$$,$$Zero Insertion Force connectors have a small hinged latch or sliding bar that must be lifted or drawn back before the ribbon will slide out, and closed again after the new ribbon is inserted square and fully home. Pulling a ribbon against a closed latch tears the flex circuit and is a common way to destroy a keyboard or trackpad mid-repair.$$),

('a1-f-215','aplus1','core',1,'1.1',$$When one key on a laptop keyboard stops registering (not merely a lost keycap), what is replaced?$$,$$The whole keyboard assembly. Keys share a single membrane or scissor matrix on one flex circuit, and on many current designs the keyboard is riveted into the top case, making the top case the field-replaceable unit. A keycap is plastic only and carries no switch.$$),

('a1-f-216','aplus1','core',1,'1.1',$$A laptop works fine after a repair except that the trackpad, keyboard or camera is now dead. What is the first thing to suspect?$$,$$An internal ribbon or flex cable left unseated in its ZIF connector, or pinched during reassembly. Reopen and reseat before ordering parts - a component that worked before the service and not after is almost never the component that failed.$$),

-- ---------- 1.2 Display components of mobile devices (17) ----------

('a1-f-217','aplus1','core',1,'1.2',$$How does an OLED panel differ from an LED-backlit LCD?$$,$$OLED pixels emit their own light, so there is no backlight layer and no inverter: a black pixel is switched off, giving true blacks, very high contrast and a thinner, lighter panel. The trade-offs are image persistence (burn-in) from static content and faster ageing of the blue emitters.$$),

('a1-f-218','aplus1','core',1,'1.2',$$Compare the three LCD panel types found in laptops.$$,$$TN: cheapest, fastest response, worst colour and viewing angles. IPS: best colour accuracy and widest viewing angles, moderate response, the choice for design work. VA: deepest contrast and blacks of the three, slower response and some off-axis colour shift. All three need a backlight.$$),

('a1-f-219','aplus1','core',1,'1.2',$$The screen looks black but a faint image is visible under a torch, and an external monitor is fine. What failed?$$,$$The backlight, or on an older CCFL panel the inverter that drives it. A visible image under external light proves the panel is still receiving video and forming a picture, and a clean external monitor rules out the GPU. A truly dead panel shows nothing under a torch.$$),

('a1-f-220','aplus1','core',1,'1.2',$$What does a display inverter do, and which laptops have one?$$,$$It converts the laptop low-voltage DC rail into the high-voltage AC that a cold-cathode fluorescent (CCFL) backlight lamp needs. Only older CCFL-backlit LCDs contain one - LED-backlit and OLED panels have none, so replacing the inverter is never the answer on a modern laptop.$$),

('a1-f-221','aplus1','core',1,'1.2',$$What is a digitizer, and which symptom points at it?$$,$$The transparent touch-sensing layer bonded over the display glass. Symptom: the image is perfect but touch or pen input is dead, erratic or wrong in part of the screen. A driver or software fault kills touch across the whole display uniformly; a localised dead zone is physical digitizer damage.$$),

('a1-f-222','aplus1','core',1,'1.2',$$Why are laptop Wi-Fi antennas run up the sides of the display bezel?$$,$$The lid is the highest point of the machine and is clear of the shielding cans, battery and ground planes packed into the base, so the antenna elements get the cleanest path to access points. The leads run from the card in the base, through the hinge, into the lid - which is why lid service so often breaks Wi-Fi.$$),

('a1-f-223','aplus1','core',1,'1.2',$$Wi-Fi range collapsed immediately after a screen replacement. What do you check?$$,$$The antenna leads in the lid: unplugged from the wireless card, pinched in the hinge, or detached from the elements in the bezel. Reconnect both MAIN and AUX and re-route them clear of the hinge. Reinstalling the driver will not help - the adapter was never the problem.$$),

('a1-f-224','aplus1','core',1,'1.2',$$Why does a laptop wireless card have two antenna connectors?$$,$$For MIMO spatial streams and receive diversity on 802.11n/ac/ax. With only one lead connected the card still associates and looks healthy, but it loses a stream and the ability to pick the better signal path, so throughput and usable range drop - a subtle and easily missed post-repair fault.$$),

('a1-f-225','aplus1','core',1,'1.2',$$Where do the webcam and microphone live in a laptop, and what does that mean for repairs?$$,$$In the display bezel above the screen, together with the activity LED and often an ambient-light sensor, sharing one cable that runs through the hinge to the board. Replacing either usually means opening or replacing the display assembly, which is why many organisations issue an external USB webcam instead.$$),

('a1-f-226','aplus1','core',1,'1.2',$$The image flickers or shows lines that change as the lid is moved, but an external monitor is clean. What is wrong?$$,$$The display data cable (eDP/LVDS) that flexes through the hinge is chafed, broken or loose. Dependence on lid angle is the tell. Lines that also appear on the external monitor would point instead at the GPU or system board.$$),

('a1-f-227','aplus1','core',1,'1.2',$$How do you tell burn-in from a stuck pixel and from backlight bleed?$$,$$Burn-in / image persistence: a faint ghost of static content such as a taskbar, visible on plain backgrounds - an OLED ageing symptom. Stuck or dead pixel: a single dot locked to one colour or black. Backlight bleed: brighter patches at the edges of an LCD, visible only on dark content and impossible on a backlightless OLED.$$),

('a1-f-228','aplus1','core',1,'1.2',$$Which display technologies need a backlight and which do not?$$,$$Every LCD subtype (TN, IPS, VA) needs one - modern panels use LED, older ones a CCFL lamp plus an inverter. OLED needs none because each pixel is its own light source. This is why "image but no light" and "light but no image" are different faults on an LCD and why the first cannot occur on OLED.$$),

('a1-f-229','aplus1','core',1,'1.2',$$An external monitor shows the same corruption as the laptop screen. What does that rule out?$$,$$The panel, the backlight, the inverter and the display cable - everything inside the lid. Corruption that follows the signal onto a second display points at the GPU, its driver or the system board, so replacing lid parts would waste both the part and the labour.$$),

('a1-f-230','aplus1','core',1,'1.2',$$What is the practical difference between a touchscreen and an active pen digitizer?$$,$$A capacitive touchscreen senses finger-sized conductive contact only. An active digitizer additionally tracks a powered pen, giving pressure levels, tilt, barrel buttons and palm rejection. A passive rubber-tipped stylus works on any touchscreen but gets none of those capabilities.$$),

('a1-f-231','aplus1','core',1,'1.2',$$Why do OLED and LCD panels dim differently?$$,$$An LCD dims by reducing backlight output across the whole panel, so black never becomes truly black and contrast falls at low brightness. An OLED dims per pixel and can switch a pixel off completely, which is why its contrast is effectively unlimited - and also why a bright static interface wears those pixels unevenly.$$),

('a1-f-232','aplus1','core',1,'1.2',$$Half the screen is dark, bounded by a jagged line with radiating cracks. Which part is replaced?$$,$$The LCD panel itself - this is physical liquid-crystal damage from impact or pressure. It is not a backlight, cable or GPU fault and no software step helps. On a 2-in-1 where the digitizer is bonded to the panel, the whole display assembly is the replaceable unit.$$),

('a1-f-233','aplus1','acronym',1,'1.2',$$IPS$$,$$In-Plane Switching - an LCD panel technology giving accurate colour and wide viewing angles. It is the panel to specify for photo, design and shared-screen work, versus the faster but washed-out TN and the high-contrast but slower VA.$$),

-- ---------- 1.3 Accessories and ports of mobile devices (14) ----------

('a1-f-234','aplus1','core',1,'1.3',$$What can travel over a single USB-C connection?$$,$$Data at anything from USB 2.0 rates up to USB4 and Thunderbolt, video through DisplayPort or HDMI Alternate Mode, and power in either direction through USB Power Delivery. USB-C is only the connector shape - the speed and the features depend on the host port, the cable and the device.$$),

('a1-f-235','aplus1','core',1,'1.3',$$Why does a USB-C cable sometimes charge a device but refuse to carry video?$$,$$Because charge-only cables omit the high-speed wire pairs, and because some laptop USB-C ports never implemented DisplayPort Alternate Mode at all. Two identical-looking ports can differ enormously, so check the port specification and the cable rating before blaming the dock or the monitor.$$),

('a1-f-236','aplus1','core',1,'1.3',$$What is the Lightning connector?$$,$$Apple's proprietary reversible 8-pin connector, used on iPhones, iPads and accessories after it replaced Apple's 30-pin dock connector and before those lines moved to USB-C. It carries power and data; video output requires an Apple AV adapter that does the conversion in the adapter itself.$$),

('a1-f-237','aplus1','core',1,'1.3',$$What does "serial interface" mean when connecting a laptop to network equipment?$$,$$An RS-232 console connection. Modern laptops have no DB-9 port, so you use a USB-to-serial console adapter (or a USB-C console cable) plus terminal software, typically at 9600 8-N-1, to reach the command line of a switch, router or firewall out of band.$$),

('a1-f-238','aplus1','core',1,'1.3',$$Docking station versus port replicator - what actually separates them?$$,$$A port replicator duplicates ports the laptop already has - USB, Ethernet, usually one display - over a single connector. A docking station adds desktop-class expansion: multiple independent displays, power delivery that charges the laptop over the same cable, and sometimes extra storage or graphics.$$),

('a1-f-239','aplus1','core',1,'1.3',$$What two things must be checked before a USB-C dock will drive dual monitors and charge a laptop?$$,$$1) That the laptop USB-C port supports DisplayPort Alternate Mode or Thunderbolt - some ports are data and charge only. 2) That the dock Power Delivery output meets or exceeds the laptop charger rating, or the battery will still drain under load even though the laptop reports it is plugged in.$$),

('a1-f-240','aplus1','core',1,'1.3',$$Passive stylus versus active touch pen?$$,$$A passive stylus is a conductive tip the capacitive screen reads exactly like a fingertip - no pressure, no tilt, no palm rejection, but it works on anything. An active pen is powered and talks to a compatible digitizer, providing pressure levels, tilt, buttons and palm rejection. The device must support the pen's protocol.$$),

('a1-f-241','aplus1','core',1,'1.3',$$Why might a headset plugged into a laptop combo jack play audio but capture no voice?$$,$$Because the headset has a 3-pole TRS plug (left, right, ground) with no conductor for a microphone. A combo jack expects a 4-pole TRRS plug that carries the microphone on the extra ring. Fix with a TRRS headset, a TRS-to-TRRS splitter, or a USB headset.$$),

('a1-f-242','aplus1','core',1,'1.3',$$When is a drawing pad the right accessory rather than a trackpad?$$,$$When the user needs pressure-sensitive freehand input - illustration, handwriting, photo masking - on a machine with no touchscreen. A drawing pad maps absolute pen position with pressure and tilt; a trackpad only reports relative finger movement and can never produce a varying-width stroke.$$),

('a1-f-243','aplus1','core',1,'1.3',$$A Bluetooth speaker is paired and connected but the laptop still plays through its internal speakers. What is wrong?$$,$$The default audio output device has not been changed. Pairing only creates the link; the output must be selected in the sound settings. Also check that the device connected on the stereo audio profile rather than the low-quality hands-free/headset profile, which some systems select when a microphone is present.$$),

('a1-f-244','aplus1','core',1,'1.3',$$Which methods can share a phone's internet connection, and how do they compare?$$,$$USB tethering: one device, fastest and most reliable, and it charges the phone. Bluetooth PAN tethering: one or two devices, slowest, lowest battery cost. Wi-Fi hotspot: several devices at once and the highest throughput, but the heaviest battery drain. All three consume the phone's cellular data allowance.$$),

('a1-f-245','aplus1','core',1,'1.3',$$What does a KVM switch do, and why is it not a docking station?$$,$$A KVM shares one keyboard, video display and mouse between several computers. A dock expands the ports of a single computer. Two PCs and one monitor is a KVM problem; one laptop needing more ports and displays is a dock problem.$$),

('a1-f-246','aplus1','core',1,'1.3',$$A USB accessory works on one laptop port but not another. What explains it?$$,$$Ports on the same machine differ: USB 2.0 versus 3.x versus Thunderbolt, always-on charging ports, and data-limited downstream ports on cheap hubs. Test the accessory directly on the laptop to rule out an unpowered hub that cannot supply enough current for the device.$$),

('a1-f-247','aplus1','acronym',1,'1.3',$$NFC$$,$$Near Field Communication - two-way wireless over a couple of centimetres. Used for contactless payment, transit and door badges, and tap-to-pair handshakes that exchange Bluetooth pairing details and then hand the session over to Bluetooth for the actual data or audio.$$),

-- ---------- 1.4 Mobile network connectivity and application support (14) ----------

('a1-f-248','aplus1','core',1,'1.4',$$What do 3G, 4G LTE and 5G mean in practice on a handset?$$,$$Successive cellular generations, each faster with lower latency. 3G is legacy voice and basic data, 4G LTE is the widely deployed data baseline, 5G adds much higher throughput and lower latency but with patchier coverage. Handsets fall back automatically, so a 5G phone showing LTE in a rural area is behaving normally.$$),

('a1-f-249','aplus1','core',1,'1.4',$$GSM versus CDMA - what is the practical difference for a technician?$$,$$GSM identifies the subscriber on a removable SIM (or a downloadable eSIM profile), so an unlocked handset can take a local SIM abroad and be billed at local rates. CDMA historically tied the subscriber to the handset, programmed by the carrier, with no SIM to swap. Modern LTE and 5G networks are SIM-based worldwide.$$),

('a1-f-250','aplus1','core',1,'1.4',$$When does a PRL update actually fix a service problem?$$,$$On carrier networks that use a preferred roaming list, after the carrier changes towers, bands or roaming partners and the handset keeps hunting for arrangements that no longer exist. It affects which cellular system the phone camps on - not Wi-Fi, not Bluetooth, and not the APN used for the data connection.$$),

('a1-f-251','aplus1','core',1,'1.4',$$What are the trade-offs of running a phone's Wi-Fi hotspot?$$,$$It serves several devices at once at Wi-Fi rates, but every byte counts against the cellular data allowance, running two radios continuously drains the battery fast (keep the phone charging), and the hotspot must be secured with WPA2/WPA3 and a strong passphrase rather than left open.$$),

('a1-f-252','aplus1','core',1,'1.4',$$List the Bluetooth pairing steps in order.$$,$$1) Enable Bluetooth and put the accessory into discoverable/pairing mode. 2) Let the phone scan and discover the device. 3) Select the device from the discovered list. 4) Enter or confirm the PIN or passkey if prompted. 5) Test - play audio, type, or speak - to verify the connection actually works.$$),

('a1-f-253','aplus1','core',1,'1.4',$$A Bluetooth accessory never appears in the phone's device list. What is the usual cause?$$,$$It is not in discoverable/pairing mode - most accessories need a button held until an indicator flashes and drop out of that state after a minute or two. Other causes: it is already connected to another nearby device, it is out of range, or its battery is flat. If the phone finds other devices, the phone is fine.$$),

('a1-f-254','aplus1','core',1,'1.4',$$Which three sources do phones combine for location services?$$,$$GPS/GNSS satellites (most accurate, needs a view of the sky), cellular tower triangulation (coarse, works wherever there is signal), and Wi-Fi positioning against a database of known access points (best indoors). The operating system blends all three, which is why "the GPS is broken" is usually a disabled permission.$$),

('a1-f-255','aplus1','core',1,'1.4',$$A mapping app cannot find the user's position. What do you check before suspecting hardware?$$,$$Whether location services are enabled system-wide, whether that specific app holds the location permission and at what level (never / while using / always), and whether battery-saver or airplane mode is restricting it. If other apps report the correct position, the receiver and antenna are proven good.$$),

('a1-f-256','aplus1','core',1,'1.4',$$Which mail account type do you configure for corporate mail that must sync calendar and contacts and accept device policy?$$,$$Exchange / Microsoft 365 via Exchange ActiveSync. IMAP synchronises mail across devices but carries no calendar or contacts and offers no policy or remote-wipe channel. POP3 is weaker still, downloading to one device and typically removing messages from the server.$$),

('a1-f-257','aplus1','core',1,'1.4',$$What counts as two-factor authentication on a mobile device?$$,$$Two different categories: something you know (password, PIN), something you have (the enrolled phone with an authenticator app, a push approval, a hardware token), something you are (fingerprint, face). A password plus a security question is still one factor - both are knowledge. A fingerprint plus a face is also one factor.$$),

('a1-f-258','aplus1','core',1,'1.4',$$What typically transfers when a user signs in to their account on a replacement phone?$$,$$Contacts, calendar, mail, photos, the app list and much app data, browser bookmarks and passwords, and device settings - through Microsoft 365, a Google account or iCloud. Hardware and carrier identifiers such as the IMEI and the preferred roaming list belong to the handset and never transfer with the account.$$),

('a1-f-259','aplus1','acronym',1,'1.4',$$MAM$$,$$Mobile Application Management - policy control over corporate applications and their data only, not the whole device. It supports a selective wipe that removes company mail and files while leaving personal photos and messages untouched, which is why it is the usual choice for personally owned BYOD handsets.$$),

('a1-f-260','aplus1','acronym',1,'1.4',$$IMEI$$,$$International Mobile Equipment Identity - the unique serial number of the handset hardware itself. Carriers use it to block a stolen device from the network. It identifies the phone, not the subscriber; the subscriber identity (IMSI) lives on the SIM.$$),

('a1-f-261','aplus1','acronym',1,'1.4',$$PRL$$,$$Preferred Roaming List - the carrier-supplied table of systems, bands and roaming partners a handset should prefer and in what order. Updating it restores service after a carrier changes its tower layout or roaming agreements; it has no effect on Wi-Fi, Bluetooth or app data.$$);
