-- Acronym drill deck: 100 cards. Front asks for expansion + one-line meaning.
insert into public.flashcards (id, deck, domain, objective, front, back) values
('a-001','acronym',1,'1.2',$$CIA$$,$$Confidentiality, Integrity, Availability - the three pillars of information security.$$),
('a-002','acronym',1,'1.2',$$AAA$$,$$Authentication, Authorization, Accounting - verifying identity, granting rights, logging use.$$),
('a-003','acronym',1,'1.4',$$PKI$$,$$Public Key Infrastructure - the system of CAs, certificates, and keys enabling trusted asymmetric crypto.$$),
('a-004','acronym',1,'1.4',$$CA$$,$$Certificate Authority - trusted entity that issues and signs digital certificates.$$),
('a-005','acronym',1,'1.4',$$CSR$$,$$Certificate Signing Request - data sent to a CA (incl. public key) to request a certificate.$$),
('a-006','acronym',1,'1.4',$$CRL$$,$$Certificate Revocation List - CA-published list of revoked certificates.$$),
('a-007','acronym',1,'1.4',$$OCSP$$,$$Online Certificate Status Protocol - real-time certificate revocation checking.$$),
('a-008','acronym',1,'1.4',$$HSM$$,$$Hardware Security Module - dedicated tamper-resistant device for key storage and crypto operations.$$),
('a-009','acronym',1,'1.4',$$TPM$$,$$Trusted Platform Module - chip on a motherboard providing hardware root of trust and key storage.$$),
('a-010','acronym',1,'1.4',$$FDE$$,$$Full Disk Encryption - encrypting an entire drive (e.g., BitLocker).$$),
('a-011','acronym',1,'1.4',$$ECC$$,$$Elliptic Curve Cryptography - asymmetric crypto with small keys, ideal for mobile/IoT.$$),
('a-012','acronym',1,'1.4',$$AES$$,$$Advanced Encryption Standard - the standard symmetric block cipher (128/192/256-bit keys).$$),
('a-013','acronym',1,'1.4',$$RSA$$,$$Rivest-Shamir-Adleman - widely used asymmetric algorithm based on factoring large primes.$$),
('a-014','acronym',1,'1.2',$$PDCA$$,$$Plan-Do-Check-Act - continuous improvement cycle often applied to security programs.$$),
('a-015','acronym',2,'2.1',$$APT$$,$$Advanced Persistent Threat - well-resourced (often nation-state) actor maintaining long-term stealthy access.$$),
('a-016','acronym',2,'2.4',$$RAT$$,$$Remote Access Trojan - malware giving an attacker covert remote control of a host.$$),
('a-017','acronym',2,'2.4',$$DDoS$$,$$Distributed Denial of Service - flooding a target from many sources to exhaust resources.$$),
('a-018','acronym',2,'2.4',$$XSS$$,$$Cross-Site Scripting - injecting malicious script into pages viewed by other users.$$),
('a-019','acronym',2,'2.4',$$SQLi$$,$$SQL Injection - inserting SQL into inputs to manipulate database queries.$$),
('a-020','acronym',2,'2.4',$$CSRF$$,$$Cross-Site Request Forgery - tricking a logged-in user's browser into sending unwanted requests.$$),
('a-021','acronym',2,'2.2',$$BEC$$,$$Business Email Compromise - impersonating executives/vendors by email to redirect payments or data.$$),
('a-022','acronym',2,'2.3',$$CVE$$,$$Common Vulnerabilities and Exposures - standardized IDs for publicly known vulnerabilities.$$),
('a-023','acronym',4,'4.3',$$CVSS$$,$$Common Vulnerability Scoring System - 0-10 severity score for vulnerabilities.$$),
('a-024','acronym',2,'2.3',$$RCE$$,$$Remote Code Execution - vulnerability allowing an attacker to run arbitrary code remotely.$$),
('a-025','acronym',2,'2.2',$$MitM$$,$$Man/Adversary-in-the-Middle - attacker secretly relays or alters traffic between two parties (on-path attack).$$),
('a-026','acronym',3,'3.1',$$IaC$$,$$Infrastructure as Code - defining infrastructure in versioned code/templates (e.g., Terraform).$$),
('a-027','acronym',3,'3.1',$$SDN$$,$$Software-Defined Networking - separating the network control plane from the data plane.$$),
('a-028','acronym',3,'3.1',$$ICS$$,$$Industrial Control System - hardware/software controlling industrial processes.$$),
('a-029','acronym',3,'3.1',$$SCADA$$,$$Supervisory Control and Data Acquisition - ICS architecture for monitoring/controlling distributed industrial equipment.$$),
('a-030','acronym',3,'3.1',$$RTOS$$,$$Real-Time Operating System - OS with deterministic timing, used in embedded/industrial devices.$$),
('a-031','acronym',3,'3.2',$$VPN$$,$$Virtual Private Network - encrypted tunnel over an untrusted network.$$),
('a-032','acronym',3,'3.2',$$IPSec$$,$$Internet Protocol Security - suite for authenticating/encrypting IP traffic (AH, ESP; tunnel/transport modes).$$),
('a-033','acronym',3,'3.2',$$TLS$$,$$Transport Layer Security - protocol securing traffic in transit (successor to SSL).$$),
('a-034','acronym',3,'3.2',$$SASE$$,$$Secure Access Service Edge - cloud-delivered networking + security (SD-WAN, ZTNA, CASB, FWaaS) as one service.$$),
('a-035','acronym',3,'3.2',$$SD-WAN$$,$$Software-Defined Wide Area Network - centrally managed, policy-driven WAN over mixed transport links.$$),
('a-036','acronym',3,'3.3',$$DLP$$,$$Data Loss Prevention - controls that detect/block exfiltration of sensitive data.$$),
('a-037','acronym',3,'3.4',$$RAID$$,$$Redundant Array of Independent Disks - disk redundancy/striping schemes for availability.$$),
('a-038','acronym',3,'3.4',$$UPS$$,$$Uninterruptible Power Supply - battery backup power for graceful ride-through/shutdown.$$),
('a-039','acronym',5,'5.2',$$RTO$$,$$Recovery Time Objective - maximum tolerable time to restore a service after disruption.$$),
('a-040','acronym',5,'5.2',$$RPO$$,$$Recovery Point Objective - maximum tolerable data loss measured in time (how old restored data may be).$$),
('a-041','acronym',5,'5.2',$$MTTR$$,$$Mean Time To Repair/Recover - average time to fix a failed component.$$),
('a-042','acronym',5,'5.2',$$MTBF$$,$$Mean Time Between Failures - average operating time between failures of a repairable system.$$),
('a-043','acronym',5,'5.2',$$BIA$$,$$Business Impact Analysis - identifies critical functions and impact of their disruption (feeds RTO/RPO).$$),
('a-044','acronym',5,'5.2',$$ALE$$,$$Annualized Loss Expectancy - SLE x ARO; expected yearly loss from a risk.$$),
('a-045','acronym',5,'5.2',$$SLE$$,$$Single Loss Expectancy - expected loss from one occurrence (asset value x exposure factor).$$),
('a-046','acronym',5,'5.2',$$ARO$$,$$Annualized Rate of Occurrence - expected number of occurrences per year.$$),
('a-047','acronym',4,'4.4',$$SIEM$$,$$Security Information and Event Management - central log aggregation, correlation, and alerting.$$),
('a-048','acronym',4,'4.7',$$SOAR$$,$$Security Orchestration, Automation and Response - automating incident response playbooks.$$),
('a-049','acronym',4,'4.5',$$EDR$$,$$Endpoint Detection and Response - endpoint agent for detection, investigation, and response.$$),
('a-050','acronym',4,'4.5',$$XDR$$,$$Extended Detection and Response - detection/response correlated across endpoint, network, cloud, email.$$),
('a-051','acronym',4,'4.5',$$NAC$$,$$Network Access Control - admits devices to the network based on identity/posture (e.g., 802.1X).$$),
('a-052','acronym',4,'4.5',$$IDS$$,$$Intrusion Detection System - monitors traffic/hosts and alerts on malicious activity (detective).$$),
('a-053','acronym',4,'4.5',$$IPS$$,$$Intrusion Prevention System - inline IDS that can block malicious traffic (preventive).$$),
('a-054','acronym',4,'4.5',$$WAF$$,$$Web Application Firewall - filters HTTP(S) to protect web apps (XSS, SQLi, etc.).$$),
('a-055','acronym',4,'4.5',$$UTM$$,$$Unified Threat Management - all-in-one firewall/IPS/AV/web-filter appliance.$$),
('a-056','acronym',4,'4.6',$$IAM$$,$$Identity and Access Management - lifecycle of identities and their access rights.$$),
('a-057','acronym',4,'4.6',$$SSO$$,$$Single Sign-On - one authentication grants access to multiple applications.$$),
('a-058','acronym',4,'4.6',$$MFA$$,$$Multi-Factor Authentication - authentication using 2+ factor categories (know/have/are).$$),
('a-059','acronym',4,'4.6',$$SAML$$,$$Security Assertion Markup Language - XML standard for exchanging authN/authZ between IdP and SP (federation/SSO).$$),
('a-060','acronym',4,'4.6',$$OIDC$$,$$OpenID Connect - identity layer on top of OAuth 2.0 for federated login.$$),
('a-061','acronym',4,'4.6',$$LDAP$$,$$Lightweight Directory Access Protocol - protocol for querying directory services (e.g., AD).$$),
('a-062','acronym',4,'4.6',$$PAM$$,$$Privileged Access Management - vaulting, brokering, and monitoring of privileged accounts.$$),
('a-063','acronym',4,'4.6',$$RBAC$$,$$Role-Based Access Control - permissions assigned via roles, not individuals.$$),
('a-064','acronym',4,'4.6',$$ABAC$$,$$Attribute-Based Access Control - access decisions from attributes (user, resource, environment).$$),
('a-065','acronym',4,'4.6',$$DAC$$,$$Discretionary Access Control - resource owner decides who gets access.$$),
('a-066','acronym',4,'4.6',$$MAC$$,$$Mandatory Access Control - system-enforced labels/clearances control access (also: Message Authentication Code, media access control - context matters).$$),
('a-067','acronym',4,'4.6',$$TOTP$$,$$Time-based One-Time Password - OTP derived from a shared secret + current time.$$),
('a-068','acronym',4,'4.6',$$HOTP$$,$$HMAC-based One-Time Password - OTP derived from a shared secret + counter.$$),
('a-069','acronym',4,'4.1',$$WPA3$$,$$Wi-Fi Protected Access 3 - current wireless security standard (SAE handshake replaces PSK 4-way).$$),
('a-070','acronym',4,'4.1',$$SAE$$,$$Simultaneous Authentication of Equals - WPA3 password-authenticated key exchange resistant to offline dictionary attacks.$$),
('a-071','acronym',4,'4.1',$$MDM$$,$$Mobile Device Management - central policy enforcement on mobile devices.$$),
('a-072','acronym',4,'4.1',$$BYOD$$,$$Bring Your Own Device - personally owned devices used for work.$$),
('a-073','acronym',4,'4.1',$$COPE$$,$$Corporate-Owned, Personally Enabled - company device allowing personal use.$$),
('a-074','acronym',4,'4.1',$$CYOD$$,$$Choose Your Own Device - employee picks from an approved corporate device list.$$),
('a-075','acronym',4,'4.4',$$SCAP$$,$$Security Content Automation Protocol - standards suite for automated configuration/vulnerability checking.$$),
('a-076','acronym',4,'4.4',$$SNMP$$,$$Simple Network Management Protocol - monitors/manages network devices (v3 adds auth+encryption).$$),
('a-077','acronym',4,'4.5',$$DMARC$$,$$Domain-based Message Authentication, Reporting and Conformance - email policy telling receivers how to treat SPF/DKIM failures.$$),
('a-078','acronym',4,'4.5',$$DKIM$$,$$DomainKeys Identified Mail - cryptographic signature proving mail came from the domain and was not altered.$$),
('a-079','acronym',4,'4.5',$$SPF$$,$$Sender Policy Framework - DNS record listing servers authorized to send mail for a domain.$$),
('a-080','acronym',4,'4.5',$$DNSSEC$$,$$DNS Security Extensions - signs DNS records to prevent spoofing/cache poisoning.$$),
('a-081','acronym',4,'4.9',$$NetFlow$$,$$Network flow metadata (who talked to whom, when, how much) - traffic analysis without payloads.$$),
('a-082','acronym',4,'4.8',$$IR$$,$$Incident Response - Preparation, Detection/Analysis, Containment, Eradication, Recovery, Lessons Learned.$$),
('a-083','acronym',5,'5.1',$$AUP$$,$$Acceptable Use Policy - rules for appropriate use of company systems.$$),
('a-084','acronym',5,'5.3',$$SLA$$,$$Service Level Agreement - contract defining measurable service commitments (uptime, response).$$),
('a-085','acronym',5,'5.3',$$MOU$$,$$Memorandum of Understanding - non-binding statement of intent between parties.$$),
('a-086','acronym',5,'5.3',$$MSA$$,$$Master Service Agreement - umbrella contract governing future work orders/SOWs.$$),
('a-087','acronym',5,'5.3',$$SOW$$,$$Statement of Work - defines specific deliverables, timeline, and scope for an engagement.$$),
('a-088','acronym',5,'5.3',$$NDA$$,$$Non-Disclosure Agreement - legally binds parties to confidentiality.$$),
('a-089','acronym',5,'5.4',$$GDPR$$,$$General Data Protection Regulation - EU privacy law governing personal data.$$),
('a-090','acronym',5,'5.4',$$PCI DSS$$,$$Payment Card Industry Data Security Standard - contractual security standard for cardholder data.$$),
('a-091','acronym',5,'5.4',$$PII$$,$$Personally Identifiable Information - data that can identify an individual.$$),
('a-092','acronym',5,'5.4',$$PHI$$,$$Protected Health Information - health data protected under HIPAA.$$),
('a-093','acronym',3,'3.3',$$PGP/GPG$$,$$Pretty Good Privacy / GNU Privacy Guard - encryption for files and email using hybrid crypto.$$),
('a-094','acronym',3,'3.1',$$CASB$$,$$Cloud Access Security Broker - enforcement point between users and cloud services (visibility, DLP, policy).$$),
('a-095','acronym',3,'3.1',$$VPC$$,$$Virtual Private Cloud - isolated virtual network within a public cloud.$$),
('a-096','acronym',1,'1.2',$$ZTNA$$,$$Zero Trust Network Access - per-session, identity- and posture-based access to specific apps (never trust, always verify).$$),
('a-097','acronym',2,'2.4',$$IoC$$,$$Indicator of Compromise - artifact (hash, IP, domain, behavior) suggesting an intrusion.$$),
('a-098','acronym',4,'4.3',$$CPE$$,$$Common Platform Enumeration - standard naming for platforms/software in vulnerability data.$$),
('a-099','acronym',5,'5.5',$$SOC 2$$,$$Service Organization Control 2 - attestation report on a provider's security/availability/confidentiality controls.$$),
('a-100','acronym',1,'1.3',$$CAB$$,$$Change Advisory Board - body that reviews and approves changes in change management.$$);
