-- Security+ Domain 1 expansion (General Security Concepts, 12%): adds
-- flashcards f1-046..055 and questions q1-031..055, filling coverage gaps
-- identified in review (change management depth, blockchain models, cipher
-- suites, key escrow, PFS, cert chain of trust) and adding PBQ-style items.

insert into public.flashcards (id, deck, domain, objective, front, back) values
('f1-046','core',1,'1.1',$$Name three physical security controls beyond guards and cameras.$$,$$Fencing (deters/delays), lighting (deters, aids detection), locks (preventive), bollards (vehicle barrier), alarms (detective).$$),
('f1-047','core',1,'1.1',$$Does a compensating control eliminate the underlying risk?$$,$$No - it reduces risk to an acceptable level by an alternate means while the primary control is infeasible; the vulnerability itself still exists until that primary fix lands.$$),
('f1-048','core',1,'1.2',$$What is the "assume breach" principle in Zero Trust?$$,$$Design and operate as though an attacker is already inside the network - minimizing blast radius via segmentation, least privilege, and continuous verification rather than relying on a hardened perimeter.$$),
('f1-049','core',1,'1.2',$$What is a distributed deception platform?$$,$$A coordinated network of many honeypots, honeytokens, and honeyfiles deployed at scale across an environment - not just one decoy - to raise the odds an attacker touches something that alerts.$$),
('f1-050','core',1,'1.3',$$What is stakeholder analysis in change management?$$,$$Identifying everyone affected by a change (owners, users, dependent teams) before approval, so impact is understood and the right people can approve or object.$$),
('f1-051','core',1,'1.3',$$What role does version control play in change management?$$,$$It tracks every change to configuration/code with who/when/why, enables review before merge, and provides an exact rollback point - foundational to auditable, reversible change.$$),
('f1-052','core',1,'1.3',$$Standard vs normal vs emergency change - what''s the difference?$$,$$Standard: pre-approved, low-risk, repeatable (e.g., routine patching). Normal: goes through full CAB review. Emergency: expedited approval for urgent fixes (e.g., active exploitation), documented after the fact.$$),
('f1-053','core',1,'1.4',$$What is key escrow and its trade-off?$$,$$Storing a copy of an encryption key with a trusted third party for recovery (lost keys, legal access); the trade-off is a new point of compromise - if the escrow is breached, so is the key.$$),
('f1-054','core',1,'1.4',$$Public vs permissioned blockchain?$$,$$Public: anyone can join/validate (Bitcoin) - maximum decentralization, slower. Permissioned: only approved participants validate (enterprise/consortium use) - faster, less decentralized, more control over who writes.$$),
('f1-055','core',1,'1.4',$$What is a cipher suite and what does it negotiate?$$,$$A named bundle of algorithms a TLS session agrees on: key exchange (e.g., ECDHE), authentication (e.g., RSA), bulk encryption (e.g., AES-256-GCM), and a MAC/hash - negotiated during the TLS handshake.$$);

insert into public.questions (id, domain, objective, qtype, difficulty, stem, choices, answer, explanation) values
('q1-031',1,'1.1','mcq',2,$q$A company installs fencing and bright motion-activated lighting around its data center perimeter. What control category and type do these BEST represent?$q$,$q$["Physical category; deterrent and preventive","Technical category; detective","Administrative category; corrective","Physical category; corrective only"]$q$::jsonb,'0'::jsonb,$q$Fencing and lighting are physical (real-world barriers) that primarily deter attackers, with fencing also physically impeding access. They are not system-enforced (technical) or purely after-the-fact (corrective).$q$),
('q1-032',1,'1.1','mcq',2,$q$A compensating control has been running for eight months for a vulnerability that was supposed to be patched within 30 days. What is the correct interpretation?$q$,$q$["The risk has been fully eliminated","The underlying risk still exists; the compensating control is a temporary reduction, not a permanent fix","Compensating controls never expire and need no follow-up","The vulnerability no longer needs to be tracked"]$q$::jsonb,'1'::jsonb,$q$A compensating control reduces risk while the primary control is infeasible - it does not eliminate the vulnerability. Letting one run indefinitely without revisiting the real fix is a classic audit finding, not a resolved item.$q$),
('q1-033',1,'1.1','matching',2,$q$Match each physical control to its primary type(s).$q$,$q${"left":["Fencing","Motion-activated floodlight","Door lock","Security guard patrol"],"right":["Preventive/deterrent","Deterrent/detective","Preventive","Detective/deterrent"]}$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$Fencing delays/deters intrusion; a motion floodlight deters and alerts anyone watching; a lock physically prevents entry; a patrolling guard detects and deters simultaneously.$q$),
('q1-034',1,'1.1','mcq',3,$q$An organization cannot immediately replace an unpatchable legacy point-of-sale system, so it isolates it on its own VLAN, disables unnecessary services, and adds enhanced logging. Which BEST describes this approach?$q$,$q$["A single preventive control","Layered compensating and detective measures (defense in depth) around an infeasible primary fix","A directive control","No real control, since PCI DSS does not apply here"]$q$::jsonb,'1'::jsonb,$q$Combining segmentation (compensating), service reduction (hardening), and logging (detective) is layered defense in depth working around a patch that can't be applied. It's not one control, isn't directive (no policy document here), and payment systems are exactly where this compliance scope applies.$q$),
('q1-035',1,'1.2','mcq',2,$q$A company''s public status page falsely shows "All systems operational" during a real outage because the monitoring feed was tampered with. Which CIA element was violated by the tampering itself, separate from the outage?$q$,$q$["Confidentiality","Integrity","Availability","Non-repudiation"]$q$::jsonb,'1'::jsonb,$q$Unauthorized alteration of the monitoring data is an integrity violation, distinct from the outage itself, which is an availability issue. Confidentiality would involve unauthorized disclosure, not tampering.$q$),
('q1-036',1,'1.2','mcq',2,$q$An employee''s laptop is fully patched, off the corporate network, and connecting via VPN from home. Under Zero Trust, should it receive more trust because it is a known corporate asset?$q$,$q$["Yes, corporate-owned assets are always trusted","No - every request is authenticated and authorized regardless of device ownership or network location","Only if it uses a wired connection","Yes, but only for the first login of the day"]$q$::jsonb,'1'::jsonb,$q$Zero Trust means never trust, always verify - per request, regardless of whose asset it is or where it connects from. Device ownership does not grant standing trust; continuous verification replaces implicit trust.$q$),
('q1-037',1,'1.2','mcq',2,$q$A security team deploys dozens of fake credentials, decoy file shares, and simulated database servers throughout the network, all feeding one alerting pipeline. What is this coordinated approach called?$q$,$q$["A single honeypot","A distributed deception platform","An access control vestibule","A screened subnet"]$q$::jsonb,'1'::jsonb,$q$Deploying many coordinated decoys at scale - not just one honeypot - is a distributed deception platform, maximizing the odds an attacker touches a trap. A vestibule is a physical mantrap; a screened subnet is a DMZ.$q$),
('q1-038',1,'1.2','mcq',1,$q$Which AAA function is responsible for recording that a user accessed a specific file at 3:14 PM?$q$,$q$["Authentication","Authorization","Accounting","Availability"]$q$::jsonb,'2'::jsonb,$q$Accounting logs what was done and when. Authentication proves identity, authorization grants rights, and availability is not part of AAA.$q$),
('q1-039',1,'1.3','mcq',2,$q$A proposed database schema change is submitted for approval. Before the CAB votes, someone must identify every team whose application queries that database. What activity is this?$q$,$q$["Backout planning","Stakeholder analysis / impact analysis","Maintenance window scheduling","Version control tagging"]$q$::jsonb,'1'::jsonb,$q$Identifying affected parties before approval is stakeholder/impact analysis - distinct from backout planning (recovery), scheduling (timing), or tagging (versioning).$q$),
('q1-040',1,'1.3','mcq',1,$q$Which change type is pre-approved, low-risk, and repeatable, such as monthly antivirus signature updates?$q$,$q$["Emergency change","Standard change","Normal change","Unauthorized change"]$q$::jsonb,'1'::jsonb,$q$Standard changes are pre-approved because their risk and process are well understood and repeatable. Normal changes need full CAB review; emergency changes are expedited for urgent fixes.$q$),
('q1-041',1,'1.3','mcq',2,$q$A zero-day is being actively exploited against a public-facing server. The team patches within the hour without waiting for the next CAB meeting, then documents the change afterward. What change type was this?$q$,$q$["Standard change","Normal change","Emergency change","No change was needed"]$q$::jsonb,'2'::jsonb,$q$An urgent, actively-exploited risk justifies an emergency change: act fast, document after the fact. Standard changes are pre-approved routine work; normal changes wait for full review.$q$),
('q1-042',1,'1.3','mcq',2,$q$A developer commits a configuration change directly to production without review, breaking a dependent service. Which practice, if enforced, would most directly have prevented this?$q$,$q$["A backout plan","Version control with mandatory review before merge","A maintenance window","An application allow list"]$q$::jsonb,'1'::jsonb,$q$Version control with required review catches dependency-breaking changes before they reach production. A backout plan only helps after the damage is done; a maintenance window controls timing, not review.$q$),
('q1-043',1,'1.3','mcq',3,$q$A network change was approved, but the technician implements it two weeks after the approved maintenance window without re-confirming impact. What is the most likely risk?$q$,$q$["None - approval never expires","The environment may have changed since approval, invalidating the original impact analysis","Maintenance windows are only suggestions","Version control prevents this automatically"]$q$::jsonb,'1'::jsonb,$q$Systems and dependencies can shift in two weeks; implementing a stale approval without re-checking impact risks unforeseen breakage. Approvals are tied to a point-in-time analysis, not an indefinite license.$q$),
('q1-044',1,'1.4','mcq',2,$q$A law firm needs the ability to recover an employee''s encrypted files if that employee becomes unreachable, without weakening the encryption used day to day. Which capability supports this?$q$,$q$["Key escrow with a trusted recovery agent","Steganography","Salting","Certificate pinning"]$q$::jsonb,'0'::jsonb,$q$Key escrow stores a recoverable copy of the encryption key with a trusted party for exactly this scenario. Steganography hides data, salting strengthens password hashing, and pinning locks a client to an expected certificate.$q$),
('q1-045',1,'1.4','mcq',3,$q$A consortium of banks wants a shared ledger where only approved member institutions can validate transactions, not the general public. Which blockchain model fits?$q$,$q$["Public blockchain","Permissioned (private/consortium) blockchain","A single centralized database only","Steganographic ledger"]$q$::jsonb,'1'::jsonb,$q$A permissioned blockchain restricts validation to approved participants - faster and more controlled than a public chain, while still distributed among the consortium members. Public blockchains allow anyone to validate.$q$),
('q1-046',1,'1.4','mcq',2,$q$During a TLS handshake, the client and server agree on ECDHE for key exchange, RSA for authentication, and AES-256-GCM for bulk encryption. What is this negotiated bundle called?$q$,$q$["A certificate chain","A cipher suite","A key escrow agreement","A CRL"]$q$::jsonb,'1'::jsonb,$q$A cipher suite is the named bundle of algorithms negotiated for a TLS session: key exchange, authentication, bulk encryption, and MAC/hash. A certificate chain is about trust validation, not algorithm negotiation.$q$),
('q1-047',1,'1.4','mcq',2,$q$Which property ensures that even if a server''s long-term private key is stolen next year, an attacker cannot decrypt THIS year''s already-recorded TLS sessions?$q$,$q$["Key stretching","Perfect forward secrecy (ephemeral session keys)","Certificate pinning","Data masking"]$q$::jsonb,'1'::jsonb,$q$Perfect forward secrecy uses ephemeral, session-unique keys that are never derivable from the long-term key, so a later key compromise can't unlock past traffic. Key stretching slows password guessing; pinning and masking address different problems.$q$),
('q1-048',1,'1.4','mcq',2,$q$Which property of a cryptographic hash function means a single-character change in the input completely changes the output?$q$,$q$["Collision resistance","The avalanche effect","Salting","Key stretching"]$q$::jsonb,'1'::jsonb,$q$The avalanche effect describes how a tiny input change cascades into a drastically different digest. Collision resistance is about two different inputs not sharing an output; salting and stretching are password-hashing hardening techniques.$q$),
('q1-049',1,'1.4','matching',2,$q$Match each cryptographic concept to what it primarily protects or achieves.$q$,$q${"left":["Hashing","Symmetric encryption","Digital signature","Salting"],"right":["Integrity (one-way fingerprint)","Confidentiality of bulk data","Authenticity and non-repudiation","Defeats rainbow tables on password hashes"]}$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$Hashing fingerprints data for integrity checks; symmetric encryption protects bulk data confidentiality; a digital signature proves authenticity and non-repudiation; salting defeats precomputed rainbow-table attacks on stored password hashes.$q$),
('q1-050',1,'1.4','ordering',3,$q$Order the steps of verifying a received digital signature.$q$,$q$["Receiver decrypts the signature with the sender''s public key to recover the original hash","Receiver independently hashes the received message","Receiver compares the two hash values","If the hashes match, the message is verified as authentic and unaltered"]$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$The receiver first recovers the sender's original hash by decrypting the signature with the sender's public key, then computes their own hash of the received message, compares the two, and treats a match as proof of authenticity and integrity.$q$),
('q1-051',1,'1.4','mcq',2,$q$A mobile banking app must verify it is talking to the real bank server even if a compromised CA issues a fraudulent certificate for the bank''s domain. What should the app implement?$q$,$q$["OCSP stapling","Certificate pinning","A wildcard certificate","Key escrow"]$q$::jsonb,'1'::jsonb,$q$Certificate pinning hard-codes the expected certificate/key in the app, so even a validly-signed fraudulent certificate from a compromised CA is rejected. OCSP stapling speeds revocation checks but still trusts any validly-signed cert.$q$),
('q1-052',1,'1.4','mcq',2,$q$A browser trusts a website''s certificate because it was signed by an intermediate CA, which was itself signed by a root CA already trusted by the operating system. What is this called?$q$,$q$["Certificate pinning","Chain of trust / certificate chaining","Key escrow","OCSP stapling"]$q$::jsonb,'1'::jsonb,$q$Trust flows from a trusted root CA through intermediate CAs to the leaf certificate - validating a certificate means validating the whole chain to a trusted root. Pinning is a client-side override of this default trust model.$q$),
('q1-053',1,'1.4','mcq',3,$q$A company wants full-disk encryption where losing the encryption key makes recovery cryptographically impossible, even for the company itself. Which practice conflicts with this goal?$q$,$q$["Using AES-256","Enabling key escrow with a recovery agent","Enabling a TPM","Using a strong passphrase"]$q$::jsonb,'1'::jsonb,$q$Key escrow deliberately creates a recovery path by storing a copy of the key with a trusted party - the opposite of "unrecoverable without the key." AES-256, a TPM, and a strong passphrase are all compatible with that no-recovery goal.$q$),
('q1-054',1,'1.4','mcq',2,$q$A customer support screen shows "Card ending in 4821" instead of the full card number, while the full number remains stored securely elsewhere for processing. What technique is this?$q$,$q$["Tokenization","Masking","Hashing","Key stretching"]$q$::jsonb,'1'::jsonb,$q$Masking obscures part of a value for display while the full value exists underneath - exactly this partial-reveal pattern. Tokenization would replace the number with an unrelated token; hashing would make the original unrecoverable.$q$),
('q1-055',1,'1.4','mcq',2,$q$Why is a self-signed certificate generally unsuitable for a public-facing e-commerce website?$q$,$q$["It cannot encrypt traffic at all","Browsers won''t trust it by default since no recognized CA vouches for its identity, triggering warnings that erode customer confidence","Self-signed certificates expire immediately","It requires OCSP stapling to function"]$q$::jsonb,'1'::jsonb,$q$A self-signed certificate still encrypts traffic, but without a trusted CA's signature, browsers show trust warnings that scare away customers - fine for internal tools, unacceptable for a public storefront.$q$);
