-- CySA+ CS0-003 Domain 4 (Reporting & Communication) expansion: adds flashcards
-- cy-f-500..513 / cy-a-160..164 / cy-y-080..082 and questions cy-q-500..518,
-- covering vulnerability-report content fields, mitigation vs remediation vs
-- recommendation, action-plan categories (config mgmt/patching/compensating
-- controls/awareness), MOU and POA&M, organizational-governance inhibitors
-- (4.1), and incident-report structure (scope/impact/findings/recommendations),
-- SITREPs and the ambiguity of "MTTR", trusted-distribution limits, inadvertent
-- disclosure, authenticated out-of-band channels, RACI, and TLP (4.2).

insert into public.flashcards (id, cert, deck, domain, objective, front, back) values
('cy-f-500','cysa','core',4,'4.1',$$What must a vulnerability report include beyond just the CVE/finding name?$$,$$The affected hosts or assets, a plain-language impact statement, and a recommended remediation timeline - a bare CVE ID tells no one what is actually at risk or what to do next.$$),
('cy-f-501','cysa','core',4,'4.1',$$What is the difference between mitigation, remediation, and a recommendation in a vulnerability report?$$,$$Mitigation reduces risk temporarily without removing the flaw (e.g., a WAF rule); remediation actually fixes the underlying issue (e.g., the patch); a recommendation is the suggested future action a stakeholder must still approve and schedule.$$),
('cy-f-502','cysa','core',4,'4.1',$$What are the four common categories of items in a vulnerability action plan?$$,$$Configuration management (harden the baseline), patching (apply the vendor fix), compensating controls (temporary risk reduction when patching isn't possible), and awareness/education/training (address the human factor behind the flaw).$$),
('cy-f-503','cysa','core',4,'4.1',$$When is a compensating control used instead of remediation in an action plan?$$,$$When the real fix (patch or upgrade) can't be applied immediately - due to a legacy dependency, vendor timeline, or change freeze - a compensating control such as segmentation or a WAF rule reduces risk in the meantime without touching the vulnerable system itself.$$),
('cy-f-504','cysa','core',4,'4.1',$$Why does an action plan sometimes need an awareness/training component, not just a technical fix?$$,$$Some vulnerabilities exist because of user behavior, such as falling for phishing or reusing credentials; patching the technical flaw alone leaves the behavioral root cause untouched, so the action plan must include training to close that gap.$$),
('cy-f-505','cysa','core',4,'4.1',$$How does organizational governance act as a remediation inhibitor?$$,$$Multiple approval layers, cross-team sign-off, and change-control bureaucracy can slow a fix even when the technical patch itself is trivial - reporting should flag governance delay as an inhibitor distinct from technical difficulty.$$),
('cy-f-506','cysa','core',4,'4.2',$$What does the "scope" section of an incident report define?$$,$$Which systems, data, accounts, and business units were actually affected - and, just as importantly, confirmed NOT affected - bounding the incident so readers know exactly what the rest of the report covers.$$),
('cy-f-507','cysa','core',4,'4.2',$$What does the "impact" section of an incident report quantify?$$,$$The real-world business consequences - downtime hours, records exposed, financial cost, and affected customers - translating technical severity into terms stakeholders can act on.$$),
('cy-f-508','cysa','core',4,'4.2',$$What is the difference between "findings" and "recommendations" in an incident report?$$,$$Findings are the factual discoveries from the investigation (what happened, how the attacker got in); recommendations are the specific proposed actions to prevent recurrence - findings describe the past, recommendations shape the future.$$),
('cy-f-509','cysa','core',4,'4.2',$$What is a SITREP in incident communication, and how does it differ from a post-incident executive briefing?$$,$$A SITREP (situation report) is a brief, recurring status update issued at set intervals WHILE an incident is still ongoing, so stakeholders aren't left guessing mid-crisis; the executive briefing is a single summary delivered once after containment, not a repeating series.$$),
('cy-f-510','cysa','core',4,'4.2',$$Why is the acronym "MTTR" ambiguous in incident response reporting?$$,$$MTTR is used inconsistently to mean Mean Time To Respond, Mean Time To Remediate, and Mean Time To Recover - three different measurements. A well-written report spells out which meaning is intended each time so metrics aren't compared as if they were the same thing.$$),
('cy-f-511','cysa','core',4,'4.2',$$Why should incident communications be limited to a defined, trusted distribution list rather than broadcast widely?$$,$$Over-sharing incident details, even internally, increases the chance information reaches the attacker, the press, or panicked employees before it's verified - a need-to-know list keeps sensitive facts controlled until the communication plan authorizes wider release.$$),
('cy-f-512','cysa','core',4,'4.2',$$What is the risk of documenting sensitive incident details inside a broadly-visible ticketing system?$$,$$Helpdesk or ticketing platforms are often viewable by many employees or even customers by default; pasting exploit details, credentials, or victim data into a routine ticket can leak the very information the response is trying to contain.$$),
('cy-f-513','cysa','core',4,'4.2',$$Why must an alternate ("out-of-band") communication channel be authenticated before a team relies on it during an incident?$$,$$Simply moving to a different channel isn't enough - if participants aren't verified, an attacker could join or spoof a hastily-created group chat or call and monitor the very response coordination the out-of-band channel was meant to protect.$$),
('cy-a-160','cysa','acronym',4,'4.1',$$MOU$$,$$Memorandum of Understanding - a non-binding agreement with a vendor or partner that can restrict when and how a system may be changed, acting as a remediation inhibitor.$$),
('cy-a-161','cysa','acronym',4,'4.1',$$POA&M$$,$$Plan of Action and Milestones - a formal tracking document listing each open finding with its corrective steps, an assigned owner, and target completion dates.$$),
('cy-a-162','cysa','acronym',4,'4.2',$$SITREP$$,$$Situation Report - a brief, recurring status update issued at set intervals throughout an ongoing incident, distinct from the one-time post-incident executive briefing or the final technical report.$$),
('cy-a-163','cysa','acronym',4,'4.2',$$RACI$$,$$Responsible, Accountable, Consulted, Informed - a chart used in an incident communication plan to define exactly who acts, who decides, who is asked, and who is merely notified.$$),
('cy-a-164','cysa','acronym',4,'4.2',$$TLP$$,$$Traffic Light Protocol - a labeling scheme (RED/AMBER/GREEN/CLEAR) that tells recipients of incident information how far they are allowed to share it further.$$),
('cy-y-080','cysa','feynman',4,'4.1',$$Explain why a vulnerability action plan usually needs more than one type of control, using a real example.$$,$$Model answer: Say a legacy billing server has a critical flaw but can't be patched until a vendor-certified update ships in six months. Patching isn't available yet, so you add a compensating control now - isolate it on its own segment, add extra monitoring. Meanwhile configuration management tightens whatever's already exposed, and if the root cause involved a misconfigured default password, awareness training addresses why that happened. One control type covers one angle - real remediation stacks several until the actual patch lands.$$),
('cy-y-081','cysa','feynman',4,'4.2',$$Explain why calling every incident-response time measurement "MTTR" causes confusion, and how you'd fix it in a report.$$,$$Model answer: MTTR gets used for Respond, Remediate, and Recover - three different clocks measuring different things. If one report says "MTTR improved 20%" without saying which one, a reader can't tell if detection-to-response got faster or if full recovery got faster - very different stories. Fix it by never using the bare acronym alone: label each metric explicitly, like "mean time to contain" and "mean time to recover," so every chart and comparison is unambiguous.$$),
('cy-y-082','cysa','feynman',4,'4.2',$$Explain to a new analyst why an incident report keeps "findings" and "recommendations" in separate sections instead of blending them together.$$,$$Model answer: Findings are what the investigation actually proved happened - facts a reader should be able to trust and verify. Recommendations are judgment calls about what to do next, which reasonable people could debate. Blend them and a reader can't tell whether a statement is established fact or a suggested opinion - it makes the facts look like they're being spun, and it makes recommendations look like they're already proven necessary rather than a call the business still has to make.$$);

insert into public.questions (id, cert, domain, objective, qtype, difficulty, stem, choices, answer, explanation) values
('cy-q-500','cysa',4,'4.1','mcq',1,$q$A vulnerability report lists only a CVE identifier and a CVSS score for a finding. What is missing that a reader would need to actually act on it?$q$,$q$["Nothing - the CVE and CVSS score are sufficient on their own","The affected hosts, an impact statement, and a recommended remediation timeline","The vulnerability's discovery date only","A list of every vulnerability ever found in the organization"]$q$::jsonb,'1'::jsonb,$q$A CVE ID and CVSS score describe the flaw in the abstract; a reader needs to know which specific hosts are affected, what the real-world impact is, and by when it should be fixed to actually act on the finding.$q$),
('cy-q-501','cysa',4,'4.1','mcq',2,$q$While waiting for a vendor patch to become available, a team deploys a temporary WAF rule that blocks the known exploit pattern. What does this WAF rule represent in the vulnerability report?$q$,$q$["A remediation","A mitigation","A recommendation awaiting approval","A compliance report"]$q$::jsonb,'1'::jsonb,$q$The WAF rule reduces risk without removing the underlying flaw - that is a mitigation. Remediation would be the actual patch; a recommendation is a proposed future action, not something already deployed.$q$),
('cy-q-502','cysa',4,'4.1','mcq',2,$q$A legacy medical device cannot be patched without vendor recertification, so the team instead isolates it on its own restricted network segment with additional monitoring. Which action-plan category does this represent?$q$,$q$["Patching","Awareness and training","A compensating control","A compliance report"]$q$::jsonb,'2'::jsonb,$q$When the real fix cannot be applied, a compensating control - here, segmentation plus monitoring - reduces risk in the meantime. It is not patching, since nothing was fixed, nor training, since no behavior was addressed.$q$),
('cy-q-503','cysa',4,'4.1','mcq',1,$q$A vulnerability finding traces back to an employee reusing a personal password after falling for a phishing email. The team resets the password and also schedules a mandatory phishing-awareness session. Why include the training in the action plan rather than stopping at the password reset?$q$,$q$["Training is required by every action plan regardless of cause","The password reset fixes the immediate exposure, but the behavioral root cause remains unless addressed","Training replaces the need for a password reset","Training has no real effect on recurrence"]$q$::jsonb,'1'::jsonb,$q$Resetting the password closes the specific exposure, but the underlying behavior that created it is untouched - the action plan must address the human root cause, not just its technical symptom, or the same pattern recurs.$q$),
('cy-q-504','cysa',4,'4.1','mcq',3,$q$A critical fix requires sign-off from three separate business units, each with its own change-approval board, adding weeks before the technically-ready patch can even be scheduled. Which remediation inhibitor does this scenario illustrate?$q$,$q$["A technical incompatibility with the patch itself","Organizational governance - approval layers slowing remediation independent of technical readiness","A missing CVE identifier","An inaccurate CVSS score"]$q$::jsonb,'1'::jsonb,$q$The patch is technically ready; what is slow is bureaucratic approval across multiple governance structures. Reporting should distinguish this governance delay from technical inhibitors so stakeholders know where to intervene.$q$),
('cy-q-505','cysa',4,'4.1','multi',2,$q$Which of the following belong in a formal vulnerability management report sent to stakeholders? (Choose three.)$q$,$q$["A list of affected hosts or systems","A plain-language statement of business impact","A recommended remediation timeline","An unrelated product marketing announcement","The personal performance review of the analyst who found it","A screenshot of an unrelated department's org chart"]$q$::jsonb,$q$[0,1,2]$q$::jsonb,$q$A vulnerability report documents what is affected, what it means for the business, and by when it should be fixed. Marketing content, personnel reviews, and unrelated org charts have no place in a security finding report.$q$),
('cy-q-506','cysa',4,'4.1','matching',2,$q$Match each vulnerability action-plan category to the example that illustrates it.$q$,$q${"left":["Configuration management","Patching","Compensating control","Awareness and training"],"right":["Tightening a hardened baseline setting that was left at its insecure default","Applying the vendor-released fix that removes the flaw entirely","Adding network segmentation while a permanent fix is pending","Running a workshop after a credential-reuse incident"]}$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$Configuration management corrects baseline settings; patching applies the actual fix; a compensating control reduces risk when the fix is not yet possible; awareness and training addresses the human behavior behind a finding. Each action-plan category targets a different kind of gap.$q$),
('cy-q-507','cysa',4,'4.1','ordering',3,$q$Place these steps of turning a raw vulnerability scan finding into a tracked, reported remediation in the correct order.$q$,$q$["Validate the finding and identify affected hosts","Calculate a risk score from severity, exposure, and asset value","Assign an owner and a remediation SLA","Build an action plan of remediation, mitigation, or compensating controls","Track progress to closure and report the resulting metrics"]$q$::jsonb,$q$[0,1,2,3,4]$q$::jsonb,$q$You first confirm what was actually found and where, then score its risk, then assign accountability and a deadline, then decide how it will actually be addressed, and finally track that work to completion and reflect it in reporting metrics.$q$),
('cy-q-508','cysa',4,'4.2','mcq',1,$q$An incident report states that only the finance department's file share and 40 associated user accounts were affected, and explicitly confirms the production payment system was not touched. Which section of the report does this represent?$q$,$q$["The scope","The lessons-learned summary","The regulatory notification checklist","The evidence chain of custody"]$q$::jsonb,'0'::jsonb,$q$The scope section bounds the incident - what was affected and, just as importantly, what was confirmed unaffected - so every other section of the report has a clear boundary to work within.$q$),
('cy-q-509','cysa',4,'4.2','mcq',3,$q$Rather than stating "the server had a critical vulnerability exploited," an incident report's impact section states "18 hours of downtime, 12,000 customer records exposed, and an estimated $85,000 in recovery cost." What does this rewording accomplish?$q$,$q$["Nothing - both statements convey identical information","It translates technical severity into quantified business consequences stakeholders can act on","It replaces the need for a technical root-cause section","It satisfies a legal requirement that technical terms never appear in a report"]$q$::jsonb,'1'::jsonb,$q$The impact section's job is to quantify real business consequences - downtime, records exposed, cost - so leadership can weigh the incident in terms they can act on, distinct from a technical severity rating.$q$),
('cy-q-510','cysa',4,'4.2','mcq',2,$q$An incident report states, "The attacker gained access through a reused administrator password," and separately states, "We recommend enforcing multi-factor authentication on all administrator accounts." Which statement is a finding, and which is a recommendation?$q$,$q$["Both are findings; the report has no recommendations","The first is a finding, a factual discovery; the second is a recommendation, a proposed future action","The first is a recommendation; the second is a finding","Both are recommendations; nothing in the report is a factual finding"]$q$::jsonb,'1'::jsonb,$q$A finding documents what the investigation actually established happened; a recommendation proposes what should be done about it going forward. Keeping them distinct lets readers tell established fact from proposed action.$q$),
('cy-q-511','cysa',4,'4.2','mcq',1,$q$Every two hours during a still-unfolding ransomware incident, the response lead sends a short update on current status, actions taken, and next steps to leadership. What is this recurring update called, and how does it differ from the executive briefing sent after containment?$q$,$q$["A SITREP - a brief, recurring status update issued while the incident is still active, unlike the one-time executive briefing sent after containment","A root cause analysis, identical in purpose to the executive briefing","A regulatory notification, required only after the incident closes","A holding statement intended solely for external media"]$q$::jsonb,'0'::jsonb,$q$A SITREP is a short, recurring update delivered at intervals throughout an active incident, keeping stakeholders current before anything is fully resolved. The executive briefing is different - a single summary delivered once containment is achieved, not a repeating series.$q$),
('cy-q-512','cysa',4,'4.2','mcq',3,$q$One quarterly report states "MTTR improved by 20%" without further detail, and a reviewer cannot tell whether this means incidents were acknowledged faster, actually fixed faster, or fully recovered from faster. What is the BEST fix for this ambiguity in future reports?$q$,$q$["Stop reporting any time-based metrics at all","Explicitly label which meaning is intended each time, such as 'mean time to contain' or 'mean time to recover', instead of using the bare acronym alone","Always assume MTTR means 'remediate' in every context","Replace MTTR with MTTD in every report"]$q$::jsonb,'1'::jsonb,$q$MTTR is genuinely overloaded across Respond, Remediate, and Recover. The fix is not to drop metrics or guess a default meaning - it is to spell out explicitly which time measurement each figure represents.$q$),
('cy-q-513','cysa',4,'4.2','mcq',1,$q$During an active incident, an analyst wants to post updates in a company-wide chat channel visible to all 2,000 employees "so everyone stays informed." What does the incident communication plan's principle of limiting distribution suggest instead?$q$,$q$["Post to the company-wide channel as requested; wider awareness is always better during an incident","Restrict updates to a defined, trusted, need-to-know list until the plan authorizes wider release","Send no updates to anyone until the incident is fully closed","Only the CEO may ever see any incident update"]$q$::jsonb,'1'::jsonb,$q$Broadcasting unverified details incident-wide risks reaching the attacker, the press, or causing panic before facts are confirmed. Updates should go to a defined, trusted, need-to-know list, expanding only as the communication plan authorizes.$q$),
('cy-q-514','cysa',4,'4.2','mcq',2,$q$A support technician documents exploit details and a customer's exposed data directly inside a helpdesk ticket that is visible by default to that customer's entire organization. What principle did this violate?$q$,$q$["Nothing - ticketing systems are always appropriately private","Preventing inadvertent disclosure of sensitive incident information through broadly-visible channels","The requirement to notify regulators within 72 hours","Chain-of-custody requirements for digital evidence"]$q$::jsonb,'1'::jsonb,$q$Ticketing systems are often more broadly visible than responders assume. Pasting exploit and victim-data details into one exposed the very information the response was trying to contain - a classic inadvertent-disclosure failure.$q$),
('cy-q-515','cysa',4,'4.2','mcq',2,$q$A response team quickly spins up a new group chat as an "out-of-band" channel after suspecting email compromise, but adds members by phone number without verifying anyone's identity first. What risk remains even though the team moved off the compromised network?$q$,$q$["None - simply using a different channel eliminates all risk","An unverified participant, or the attacker, could join or spoof the new channel, defeating the purpose of moving off-network","Group chats are inherently more secure than email in every case","The new channel automatically inherits the security of the old one"]$q$::jsonb,'1'::jsonb,$q$Moving to a separate channel only helps if that channel is itself trustworthy - without verifying who is actually on it, an attacker could join or spoof the "secure" channel just as easily as reading the compromised email.$q$),
('cy-q-516','cysa',4,'4.2','multi',2,$q$Which of the following are standard sections of a formal incident response report? (Choose three.)$q$,$q$["Executive summary","Scope and impact","Findings and recommendations","The organization's unrelated marketing calendar","A list of employees' personal social media accounts","The vendor's general product brochure"]$q$::jsonb,$q$[0,1,2]$q$::jsonb,$q$A formal IR report centers on an executive summary, a scope/impact statement, and findings with recommendations. Marketing calendars, personal social accounts, and vendor brochures are unrelated to documenting the incident.$q$),
('cy-q-517','cysa',4,'4.2','ordering',2,$q$Place these sections in the order a reader would typically encounter them in a formal incident response report, from first to last.$q$,$q$["Executive summary","Scope and timeline of events","Impact (business consequences)","Findings and root cause","Recommendations for prevention"]$q$::jsonb,$q$[0,1,2,3,4]$q$::jsonb,$q$The executive summary orients the reader first; scope and timeline establish what happened and when; impact translates that into business terms; findings explain the root cause; recommendations close the report by proposing what to do next.$q$),
('cy-q-518','cysa',4,'4.2','matching',3,$q$Match each incident-response reporting term to its definition.$q$,$q${"left":["SITREP","TLP","RACI","Scope statement"],"right":["A brief, recurring status update issued while an incident is still ongoing","A labeling scheme controlling how far shared incident information may be redistributed","A chart defining who is responsible, accountable, consulted, and informed during response","The boundary of which systems, data, and users were and were not affected"]}$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$A SITREP keeps stakeholders current throughout an active incident; TLP labels how far information can travel; RACI assigns communication roles; the scope statement bounds what the incident report actually covers. Each term serves a distinct reporting function.$q$);
