-- Expand CySA+ (CS0-003) Domain 3 (Incident Response & Management): new
-- questions and flashcards for 3.1 (attack methodology frameworks), 3.2
-- (perform IR activities: containment/eradication/recovery), and 3.3
-- (preparation & post-incident activities), distinct from content already
-- seeded in 20260711000002_seed_cysa_flashcards.sql, 20260711000003/4_seed_cysa_questions_*.sql,
-- and 20260714000006_expand_cysa.sql.

insert into public.questions (id, cert, domain, objective, qtype, difficulty, stem, choices, answer, explanation) values
-- ===================== 3.1 attack methodology frameworks (13) =====================
('cy-q-400','cysa',3,'3.1','ordering',2,$q$Place these MITRE ATT&CK Enterprise tactics in the order they appear across the matrix.$q$,$q$["Reconnaissance","Initial Access","Execution","Persistence","Lateral Movement","Exfiltration"]$q$::jsonb,$q$[0,1,2,3,4,5]$q$::jsonb,$q$These are 6 of the ATT&CK Enterprise matrix's 14 tactic columns in matrix order: Reconnaissance, Resource Development, Initial Access, Execution, Persistence, Privilege Escalation, Defense Evasion, Credential Access, Discovery, Lateral Movement, Collection, Command and Control, Exfiltration, and Impact. Each column groups techniques that share the same adversary goal.$q$),
('cy-q-401','cysa',3,'3.1','mcq',1,$q$What is the primary purpose of the MITRE ATT&CK Navigator?$q$,$q$["To assign CVSS scores to vulnerabilities","To visualize ATT&CK technique coverage as an interactive heat map, such as detections, gaps, or a specific group's known TTPs","To automatically patch systems against known techniques","To generate compliance reports for auditors"]$q$::jsonb,'1'::jsonb,$q$Navigator renders the ATT&CK matrix as a color-codable heat map so analysts can overlay what's detected, what's missing, or what a named threat group is known to use - a visualization tool, not a scoring, patching, or compliance tool.$q$),
('cy-q-402','cysa',3,'3.1','mcq',1,$q$In MITRE ATT&CK, what does the sub-technique identifier T1055.012 represent?$q$,$q$["A completely unrelated technique that happens to share a similar number","A specific implementation (Process Hollowing) of the parent technique T1055 (Process Injection)","The 12th tactic column in the Enterprise matrix","A CVE identifier cross-referenced to the technique"]$q$::jsonb,'1'::jsonb,$q$Sub-techniques refine a parent technique into more specific implementations, numbered technique.sub-technique. T1055.012 is Process Hollowing, one way of achieving the broader T1055 Process Injection technique. It is unrelated to tactic numbering or CVE IDs.$q$),
('cy-q-403','cysa',3,'3.1','mcq',1,$q$What does the MITRE D3FEND framework catalog?$q$,$q$["Offensive techniques used by nation-state actors","Defensive countermeasure techniques mapped against the ATT&CK offensive techniques they counter","Vulnerability severity ratings","Legal requirements for breach notification"]$q$::jsonb,'1'::jsonb,$q$D3FEND is a knowledge base of defensive techniques - like DNS traffic analysis or process spawn analysis - each linked to the specific ATT&CK offensive techniques it helps counter. It is a defender-side complement to ATT&CK, not a severity or legal framework.$q$),
('cy-q-404','cysa',3,'3.1','mcq',2,$q$What problem does the Unified Kill Chain address that the original Lockheed Martin Cyber Kill Chain does not model well?$q$,$q$["It ignores phishing as an initial access vector entirely","The looping, in-network stages of persistence, pivoting, and lateral movement after initial compromise","It cannot be used for any web application attacks","It replaces the need for the Diamond Model entirely"]$q$::jsonb,'1'::jsonb,$q$The Unified Kill Chain (Pols and Bakker) merges the original chain's linear stages with ATT&CK's granular techniques into 18 phases that loop, capturing the repeated pivoting and lateral movement real intrusions involve after the attacker is already inside - something the original chain's single post-compromise box glosses over.$q$),
('cy-q-405','cysa',3,'3.1','mcq',3,$q$An analyst notes that a framework built around a single linear breach-and-malware narrative struggles to represent an attacker who compromised cloud identity credentials and pivoted between SaaS tenants without ever crossing a network perimeter. Which framework's limitation does this describe?$q$,$q$["MITRE ATT&CK","The original Cyber Kill Chain","The Diamond Model","OSSTMM"]$q$::jsonb,'1'::jsonb,$q$The original Kill Chain assumes a perimeter-breach, malware-delivery narrative. Cloud identity attacks that never touch a traditional perimeter or drop malware don't map cleanly onto its stages - a well-known critique that motivated broader, more granular models like the Unified Kill Chain and ATT&CK.$q$),
('cy-q-406','cysa',3,'3.1','matching',2,$q$Match each Diamond Model meta-feature to what it captures about an intrusion event.$q$,$q${"left":["Phase","Result","Direction","Methodology"],"right":["Which kill-chain-like stage the event represents","The outcome of the event, such as success, failure, or unknown","The direction of the connection, such as victim-to-infrastructure","The general class of activity used, such as phishing or exploit"]}$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$Beyond the four core vertices (adversary, capability, infrastructure, victim), the Diamond Model attaches meta-features to every event - Phase, Result, Direction, Methodology, Resources, and Timestamp - adding the context needed to correlate individual events into a full campaign picture.$q$),
('cy-q-407','cysa',3,'3.1','mcq',2,$q$What is an "activity-attack graph" (activity thread) in the Diamond Model used for?$q$,$q$["Scoring a vulnerability's exploitability","Chaining multiple linked Diamond events that share a vertex, such as the same infrastructure or adversary, to reconstruct a full multi-stage campaign","Calculating mean time to detect","Assigning CVSS environmental scores"]$q$::jsonb,'1'::jsonb,$q$An activity-attack graph strings together separate Diamond events that share a common vertex, letting analysts trace a campaign's full sequence of activity rather than viewing each event in isolation. It has nothing to do with CVSS scoring or detection metrics.$q$),
('cy-q-408','cysa',3,'3.1','mcq',3,$q$During incident analysis, evidence shows a phishing email was delivered and opened, but its payload never executed because endpoint protection blocked it. Mapping this to the Cyber Kill Chain, at which stage was the attack interrupted, and what does that imply for response scope?$q$,$q$["Actions on Objectives - full data exfiltration must be assumed and recovery is extensive","Delivery/Exploitation - the attacker never gained execution, so eradication and recovery scope is minimal compared to a fully installed foothold","Reconnaissance - no incident occurred at all","Command and Control - a full network-wide isolation is automatically required"]$q$::jsonb,'1'::jsonb,$q$Identifying the last stage reached tells responders how much cleanup is actually needed. Here the payload was blocked at delivery/exploitation, before installation or C2 - so unlike a fully installed foothold, eradication and recovery scope is small: confirm no execution occurred and address the delivery vector.$q$),
('cy-q-409','cysa',3,'3.1','mcq',1,$q$What is an ATT&CK Group profile?$q$,$q$["A list of an organization's own internal security team members","A catalog entry for a named threat-actor group listing its historically observed tactics and techniques","A vulnerability disclosure timeline","A list of approved software vendors"]$q$::jsonb,'1'::jsonb,$q$ATT&CK catalogs named groups, such as APT29, along with the techniques they have historically been observed using. Analysts compare an incident's TTPs against these profiles to support attribution and anticipate what the actor might do next.$q$),
('cy-q-410','cysa',3,'3.1','mcq',2,$q$Both OSSTMM and the OWASP Testing Guide are security testing methodology frameworks. What distinguishes the OWASP Testing Guide's scope from OSSTMM's?$q$,$q$["OWASP Testing Guide focuses specifically on web application security testing, while OSSTMM covers general operational security testing across physical, human, and network domains","OWASP Testing Guide only applies to legal contracts, not testing","OSSTMM is exclusively for wireless network testing","There is no meaningful difference - they are the same document under two names"]$q$::jsonb,'0'::jsonb,$q$OSSTMM (Open Source Security Testing Methodology Manual) is a broad, peer-reviewed methodology covering physical, human, wireless, telecom, and network security testing with measurable Risk Assessment Values. The OWASP Testing Guide narrows in specifically on web application security testing.$q$),
('cy-q-411','cysa',3,'3.1','multi',2,$q$Select the TWO examples of external partnership/collaboration models an organization might rely on for incident response support. (Choose two.)$q$,$q$["An ISAC providing peer threat-intelligence sharing within the industry","A contracted MSSP performing outsourced monitoring and response","The organization's internal password complexity policy","A vulnerability's CVSS base score"]$q$::jsonb,'[0,1]'::jsonb,$q$ISACs and MSSPs are both external collaboration models: an ISAC is a peer community for sharing threat intelligence, and an MSSP is a contracted provider delivering monitoring or response services. An internal password policy and a CVSS score are internal/technical artifacts, not partnership models.$q$),
('cy-q-412','cysa',3,'3.1','mcq',3,$q$An organization wants ongoing 24/7 security monitoring performed by a specialized outside team under a service contract, rather than exchanging threat intelligence with industry peers. Which collaboration model fits, and how does it differ from an ISAC?$q$,$q$["An MSSP - a contracted provider performing the monitoring service, versus an ISAC's role of peer intelligence-sharing rather than service delivery","An ISAC - both are identical to MSSPs","A CSIRT - this describes internal team roles, not the arrangement","OSSTMM - a testing methodology, not a monitoring service"]$q$::jsonb,'0'::jsonb,$q$An MSSP is contracted to actually perform monitoring or response as a service; an ISAC is a community where peer organizations share intelligence, not a service provider. Choosing between them depends on whether the organization needs delivered service or shared information.$q$),
-- ===================== 3.2 perform IR activities (16) =====================
('cy-q-413','cysa',3,'3.2','mcq',1,$q$Which containment approach blocks a compromised host's network access using firewall rules, ACLs, or VLAN reassignment, without necessarily touching the host itself?$q$,$q$["Account-based containment","Network-based containment","Data carving","Legal hold"]$q$::jsonb,'1'::jsonb,$q$Network-based containment restricts a host's connectivity from outside the host - firewall rules, ACL changes, or VLAN reassignment - stopping lateral movement and C2 traffic without requiring agent access to the endpoint.$q$),
('cy-q-414','cysa',3,'3.2','mcq',1,$q$What does EDR-based host isolation (network quarantine) allow that fully powering off the host would not?$q$,$q$["The host keeps full production network access","Analysts can still reach the isolated host through the EDR management channel for live remote investigation","The host automatically re-images itself","The malware is guaranteed to self-delete"]$q$::jsonb,'1'::jsonb,$q$EDR network quarantine cuts a host off from the rest of the network while keeping its connection to the EDR console alive, so responders can keep investigating live instead of losing all access the way a full power-off would.$q$),
('cy-q-415','cysa',3,'3.2','mcq',1,$q$A user's credentials were compromised. Beyond resetting the password, what MUST containment also address?$q$,$q$["Nothing further is needed once the password changes","Revoking active sessions and any issued tokens, since a password reset alone does not invalidate them","Reinstalling the operating system on the user's laptop","Filing a legal hold notice"]$q$::jsonb,'1'::jsonb,$q$A password reset does not kill sessions or tokens already issued before the reset. Full account-based containment must also explicitly revoke active sessions and tokens, or the attacker's existing access survives the reset.$q$),
('cy-q-416','cysa',3,'3.2','mcq',2,$q$Before terminating a compromised cloud instance, what should responders do to preserve the ability to investigate later?$q$,$q$["Nothing - termination is sufficient for containment","Snapshot the affected volume/instance for forensic preservation before terminating it, in addition to revoking exposed credentials","Immediately delete all cloud logs to save storage cost","Disable billing alerts"]$q$::jsonb,'1'::jsonb,$q$Terminating a cloud instance without first snapshotting it destroys forensic evidence permanently. Responders should revoke exposed API keys/IAM credentials AND capture a snapshot before termination, preserving the ability to investigate afterward.$q$),
('cy-q-417','cysa',3,'3.2','mcq',2,$q$A host is confirmed to have a kernel-level rootkit. Why would responders reimage it from a known-good gold image rather than manually deleting the identified malicious files?$q$,$q$["Manual deletion is always faster and equally thorough","A rootkit may hide additional persistence mechanisms that manual cleanup misses, so reimaging guarantees a clean, trusted baseline","Reimaging is required by law for every incident","Gold images cannot be used on previously compromised systems"]$q$::jsonb,'1'::jsonb,$q$Rootkits are specifically designed to hide their own presence and any additional footholds from normal inspection. Manual file deletion trusts incomplete detection; reimaging from a trusted baseline eliminates that risk entirely.$q$),
('cy-q-418','cysa',3,'3.2','mcq',1,$q$The team removes an attacker's scheduled task, deletes a rogue Windows service, and disables an unauthorized account created during the intrusion. Which IR sub-phase are these actions part of?$q$,$q$["Recovery","Eradication - removing the persistence mechanisms the attacker left behind","Preparation","Post-incident reporting"]$q$::jsonb,'1'::jsonb,$q$Scheduled tasks, rogue services, and unauthorized accounts are persistence mechanisms an attacker uses to regain access even after the original malware is removed. Clearing them out is core eradication work, distinct from later recovery or reporting.$q$),
('cy-q-419','cysa',3,'3.2','mcq',1,$q$What does sinkholing a malicious command-and-control domain accomplish during containment?$q$,$q$["It permanently deletes the domain from the internet","It redirects the domain's DNS resolution to a controlled server, cutting off C2 traffic and optionally revealing which internal hosts still try to reach it","It patches the vulnerability the malware exploited","It restores the affected system to production"]$q$::jsonb,'1'::jsonb,$q$Sinkholing points a malicious domain's DNS at a server defenders control, severing the malware's C2 channel while letting the defender optionally observe which internal hosts keep trying to beacon out - useful both for containment and scoping.$q$),
('cy-q-420','cysa',3,'3.2','mcq',3,$q$Investigators determine the attacker had access for three weeks before detection. The most recent backup was taken five days ago. What must responders confirm before using that backup for recovery?$q$,$q$["Nothing - the most recent backup is always safe to restore from","That the backup predates the attacker's initial access, or it may already contain the compromise and reintroduce the threat on restore","That the backup file size matches the previous backup exactly","That the backup was encrypted with AES-256"]$q$::jsonb,'1'::jsonb,$q$If the attacker had a three-week foothold and the backup is only five days old, that backup was taken WHILE the attacker was already present - restoring it could reintroduce the same compromise. Responders must select a restore point that predates initial access.$q$),
('cy-q-421','cysa',3,'3.2','mcq',2,$q$What is a hyper-care monitoring period?$q$,$q$["A permanent doubling of an organization's security budget","A period of heightened, focused monitoring on systems immediately after they are restored to production, watching for signs of reinfection","A legal requirement to notify customers within 72 hours","A synonym for chain of custody"]$q$::jsonb,'1'::jsonb,$q$Hyper-care is the closely watched window right after recovery, applying extra monitoring attention to freshly restored systems so any sign of reinfection is caught quickly, before the incident is declared fully closed.$q$),
('cy-q-422','cysa',3,'3.2','ordering',2,$q$Order these steps of a phased recovery after a multi-system compromise.$q$,$q$["Confirm eradication is complete via re-scanning affected systems","Restore the most business-critical systems first under heightened (hyper-care) monitoring","Restore remaining lower-priority systems once critical systems are stable","Return to normal monitoring levels once no reinfection signs appear"]$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$Recovery should not begin until eradication is verified complete. Then the most critical systems come back first under close watch, followed by lower-priority systems, with normal monitoring resuming only once no reinfection signs have appeared.$q$),
('cy-q-423','cysa',3,'3.2','mcq',3,$q$The scope of a compromise across a network segment is still unclear, with new affected hosts being discovered every hour. What is the MOST appropriate immediate containment action?$q$,$q$["Isolate hosts one at a time only after each is individually confirmed compromised","Isolate the entire affected segment/VLAN while scoping continues, rather than chasing hosts one at a time","Take no action until scoping is 100% complete","Shut down the entire company network permanently"]$q$::jsonb,'1'::jsonb,$q$When new affected hosts keep surfacing, isolating them one at a time always lags behind the spread. Isolating the whole segment stops further lateral movement immediately while scoping continues in parallel.$q$),
('cy-q-424','cysa',3,'3.2','mcq',2,$q$Why might a response team choose to monitor a compromised host quietly for a short additional period instead of containing it the instant it's discovered?$q$,$q$["Neglecting containment is always the correct default","To gather intelligence on the attacker's scope, tools, and objectives before acting, weighed deliberately against the risk of the attacker noticing and reacting first","Because containment is technically impossible once a host is compromised","To avoid having to write an incident report"]$q$::jsonb,'1'::jsonb,$q$Immediate containment can tip an attacker off, causing them to destroy evidence or scatter to unknown footholds. A deliberate, risk-weighed delay - not neglect - can let responders learn more about scope and tools before shutting the door on all of it at once.$q$),
('cy-q-425','cysa',3,'3.2','mcq',1,$q$When would a Continuity of Operations Plan (COOP) be invoked during incident response?$q$,$q$["When containment actions will disrupt critical business operations, so essential functions can continue on alternate means","Only during scheduled system maintenance","Whenever a single phishing email is reported","Only when writing the final lessons-learned report"]$q$::jsonb,'0'::jsonb,$q$COOP defines how essential business functions keep running through alternate means when a primary system must be taken offline or isolated for containment - it's invoked specifically when response actions threaten operational continuity.$q$),
('cy-q-426','cysa',3,'3.2','mcq',1,$q$Which set of containment options is appropriate for an ACTIVE distributed denial-of-service (DDoS) attack, as opposed to a malware intrusion?$q$,$q$["Reimaging affected servers from a gold image","Rate limiting, blackhole/null routing of attack traffic, or traffic scrubbing via an upstream provider or CDN","Revoking OAuth tokens","Sinkholing the attacker's DNS domain"]$q$::jsonb,'1'::jsonb,$q$A DDoS attack is a flood, not an exploit-based intrusion, so containment focuses on absorbing or filtering traffic - rate limiting, blackhole routing, or scrubbing via an upstream provider - rather than reimaging hosts or revoking credentials.$q$),
('cy-q-427','cysa',3,'3.2','mcq',3,$q$A vulnerability in a third-party software component embedded in the organization's product is being actively exploited, and the vendor has not yet released a patch. What is the MOST appropriate immediate action?$q$,$q$["Wait indefinitely for the vendor's patch with no interim action","Disable or isolate the affected component's functionality until a vendor fix is available, since the organization cannot patch code it doesn't own","Ignore the issue since it is entirely the vendor's responsibility","Immediately rewrite and redistribute the vendor's code without their involvement"]$q$::jsonb,'1'::jsonb,$q$Supply-chain compromises are hard to eradicate because the affected code isn't the organization's to patch. Until the vendor ships a fix, the practical containment/eradication step is disabling or isolating that component's functionality.$q$),
('cy-q-428','cysa',3,'3.2','multi',2,$q$Select the TWO actions that specifically validate eradication was complete before systems return to full production. (Choose two.)$q$,$q$["Re-scanning previously affected systems for the same indicators of compromise","Monitoring restored systems closely during a hyper-care period for signs of reinfection","Immediately deleting all incident-related logs","Filing the annual compliance audit report"]$q$::jsonb,'[0,1]'::jsonb,$q$Confirming eradication worked means actively checking for evidence it didn't: re-scanning for the same IOCs and watching restored systems closely during hyper-care. Deleting logs destroys the ability to check, and a compliance audit is unrelated to this specific incident's cleanup.$q$),
-- ===================== 3.3 preparation & post-incident (6) =====================
('cy-q-429','cysa',3,'3.3','multi',2,$q$Select the events that SHOULD trigger a review of the incident response plan outside its normal review cycle. (Choose three.)$q$,$q$["A merger/acquisition or major new cloud/system migration","Significant regulatory changes affecting notification obligations","Immediately following any real incident, to fold in what was learned","Every time a single low-severity phishing email is reported"]$q$::jsonb,'[0,1,2]'::jsonb,$q$Major organizational or regulatory changes and real incidents can invalidate the assumptions an IR plan was built on, so each should trigger an out-of-cycle review. A single routine low-severity phishing report doesn't warrant reopening the whole plan.$q$),
('cy-q-430','cysa',3,'3.3','mcq',2,$q$An analyst applies the "five whys" technique to a phishing incident and finds the terminal answer is "no one owns reviewing the email allowlist." What is the value of asking "why" repeatedly instead of stopping at "a user clicked a malicious link"?$q$,$q$["It assigns blame to the specific user who clicked the link","It surfaces the systemic, fixable condition (an unowned process) instead of stopping at a symptom that would simply repeat with the next user","It has no real value beyond the first answer","It replaces the need for a lessons-learned meeting"]$q$::jsonb,'1'::jsonb,$q$Stopping at "the user clicked the link" blames a symptom that will recur with any user. Repeatedly asking why traces back to the actual systemic gap - an unowned allowlist review process - which is the fixable root cause.$q$),
('cy-q-431','cysa',3,'3.3','matching',2,$q$Match each root-cause finding to its category.$q$,$q${"left":["A firewall rule that should have blocked the traffic was never configured","The IR runbook for this scenario was never written","An employee reused a personal password on a corporate account after falling for a lookalike login page"],"right":["Technical - a missing or misconfigured control","Process - a procedure that was never defined or followed","Human factor - a mistake or susceptibility"]}$q$::jsonb,$q$[0,1,2]$q$::jsonb,$q$Root causes are commonly sorted into technical (missing/misconfigured controls), process (undefined or unfollowed procedures), and human-factor (mistakes or susceptibilities) categories. Naming the right one determines what actually needs to change to prevent recurrence.$q$),
('cy-q-432','cysa',3,'3.3','mcq',1,$q$What distinguishes a corrective action from a preventive action in a post-incident CAPA tracker?$q$,$q$["Corrective and preventive are two names for the same thing","Corrective fixes the specific problem that already occurred; preventive reduces the risk of similar problems occurring elsewhere in the organization","Preventive actions are only ever technical, corrective actions only ever procedural","Corrective actions require no owner or deadline"]$q$::jsonb,'1'::jsonb,$q$A corrective action directly remedies the specific issue that caused this incident; a preventive action looks broader, addressing conditions that could let a similar issue occur somewhere else. Both still need an owner and deadline to actually get done.$q$),
('cy-q-433','cysa',3,'3.3','mcq',3,$q$Litigation related to a breach concluded eighteen months ago, but preserved evidence images are still being held indefinitely. What must happen before that legal hold can be released?$q$,$q$["The evidence can be deleted automatically after any fixed time period with no further review","Legal counsel must confirm the litigation/investigatory need has genuinely passed before the hold is released and normal retention resumes","The original incident commander must personally delete the files","Legal holds never expire once created, under any circumstances"]$q$::jsonb,'1'::jsonb,$q$A legal hold overrides normal retention only for as long as the litigation or investigatory need exists. Releasing it prematurely risks destroying evidence that turns out still to be needed, so legal counsel must sign off that the need has passed before normal retention/deletion resumes.$q$),
('cy-q-434','cysa',3,'3.3','mcq',2,$q$How do MTTC (mean time to contain) and MTTD (mean time to detect) differ as post-incident metrics?$q$,$q$["They measure the exact same interval and are interchangeable","MTTD measures time from compromise to detection; MTTC measures time from detection to the incident being brought under control - together they reveal where the response pipeline is slow","MTTC only applies to phishing incidents","MTTD can only be calculated after MTTC is known"]$q$::jsonb,'1'::jsonb,$q$MTTD covers the gap between compromise and detection; MTTC covers the gap between detection and containment. Tracking both separately shows whether an organization's weakness is spotting incidents or acting on them fast enough once spotted.$q$);

insert into public.flashcards (id, cert, deck, domain, objective, front, back) values
-- ===================== 3.1 core (10) =====================
('cy-f-400','cysa','core',3,'3.1',$$What are the 14 tactics in the MITRE ATT&CK Enterprise matrix, in order?$$,$$Reconnaissance, Resource Development, Initial Access, Execution, Persistence, Privilege Escalation, Defense Evasion, Credential Access, Discovery, Lateral Movement, Collection, Command and Control, Exfiltration, Impact - the columns of the matrix, left to right.$$),
('cy-f-401','cysa','core',3,'3.1',$$What is the MITRE ATT&CK Navigator?$$,$$A free web tool that renders the ATT&CK matrix as an interactive heat map, letting analysts overlay detections, gaps, or a specific threat group's known techniques to visualize defensive coverage.$$),
('cy-f-402','cysa','core',3,'3.1',$$How are ATT&CK sub-techniques structured and numbered?$$,$$A technique (e.g., T1055 Process Injection) can have sub-techniques (T1055.001 DLL Injection, T1055.012 Process Hollowing) describing more specific implementations - written as technique.sub-technique.$$),
('cy-f-403','cysa','core',3,'3.1',$$What is MITRE D3FEND?$$,$$A knowledge base of defensive countermeasure techniques (e.g., DNS traffic analysis, process spawn analysis) mapped against the offensive ATT&CK techniques they counter - a defender's complement to ATT&CK.$$),
('cy-f-404','cysa','core',3,'3.1',$$What is the Unified Kill Chain?$$,$$A model (Pols and Bakker) that merges Lockheed Martin's linear Cyber Kill Chain with ATT&CK's granular techniques into 18 phases, looping to model persistence, pivoting, and lateral movement that the original chain treats as a single endpoint.$$),
('cy-f-405','cysa','core',3,'3.1',$$What is a key limitation of the original Cyber Kill Chain?$$,$$It was built around a single, linear, perimeter-breach-and-malware narrative, so it under-represents insider threats, cloud/identity attacks, and the repeated lateral-movement loops seen in real intrusions.$$),
('cy-f-406','cysa','core',3,'3.1',$$What are the Diamond Model's meta-features?$$,$$Attributes attached to every event beyond the four core vertices - Timestamp, Phase, Result, Direction, Methodology, and Resources - adding context (when, what stage, outcome, which way, how, with what) for correlating intrusions.$$),
('cy-f-407','cysa','core',3,'3.1',$$What is an activity-attack graph (activity thread) in the Diamond Model?$$,$$A chain of linked Diamond events that share a vertex, such as the same infrastructure or adversary, strung together to reconstruct the full sequence of a multi-stage campaign rather than one isolated event.$$),
('cy-f-408','cysa','core',3,'3.1',$$How does mapping an incident to Cyber Kill Chain stages help scope the response?$$,$$Identifying the LAST stage the attacker reached (e.g., stopped at Delivery vs. reaching Actions on Objectives) tells responders how much eradication and recovery work is needed - an attacker stopped early left far less to clean up.$$),
('cy-f-409','cysa','core',3,'3.1',$$What is an ATT&CK Group profile used for?$$,$$ATT&CK catalogs named threat-actor groups (e.g., APT29) with their historically observed techniques, letting analysts compare an incident's TTPs against known adversaries to support attribution and anticipate next moves.$$),
-- ===================== 3.2 core (18) =====================
('cy-f-410','cysa','core',3,'3.2',$$What does network-based containment typically involve?$$,$$Blocking or restricting a compromised host's connectivity using firewall rules, ACL changes, or VLAN reassignment - stopping lateral movement and C2 traffic without necessarily touching the host itself.$$),
('cy-f-411','cysa','core',3,'3.2',$$What is EDR-based host isolation (network quarantine)?$$,$$The EDR agent cuts the host off from the network, blocking all traffic except its connection to the management console, containing the threat while leaving the endpoint reachable for live remote investigation.$$),
('cy-f-412','cysa','core',3,'3.2',$$What does account-based containment cover beyond a password reset?$$,$$Disabling the compromised account, revoking active sessions and issued tokens, and forcing re-authentication everywhere - a password reset alone leaves existing sessions and tokens valid.$$),
('cy-f-413','cysa','core',3,'3.2',$$What does cloud-specific containment typically require?$$,$$Revoking exposed API keys and temporary IAM credentials, and snapshotting the affected volume/instance for forensic preservation BEFORE terminating it - termination without a snapshot destroys evidence.$$),
('cy-f-414','cysa','core',3,'3.2',$$Why reimage from a known-good gold image rather than just deleting the malware files found?$$,$$Rootkits and other persistence mechanisms can hide additional footholds a manual cleanup misses; reimaging from a trusted baseline guarantees a clean state instead of trusting incomplete detection.$$),
('cy-f-415','cysa','core',3,'3.2',$$How does patching fit into eradication?$$,$$Removing the malware addresses the immediate infection; patching the vulnerability it exploited closes the entry point so the SAME technique can't be reused against the same host during this incident.$$),
('cy-f-416','cysa','core',3,'3.2',$$What persistence mechanisms must eradication specifically remove?$$,$$Attacker-created scheduled tasks/cron jobs, registry Run keys, rogue services, and unauthorized accounts - artifacts that let an attacker regain access even after the original malware is deleted.$$),
('cy-f-417','cysa','core',3,'3.2',$$What is sinkholing used for during containment?$$,$$Redirecting a malicious domain's DNS resolution to a controlled server, cutting off a botnet's or malware's command-and-control while optionally letting defenders observe which internal hosts still try to reach it.$$),
('cy-f-418','cysa','core',3,'3.2',$$What is the "backup poisoning" risk during recovery?$$,$$If the attacker had a foothold before the incident was detected, backups taken during that window may already contain the compromise; restoring from a poisoned backup reintroduces the threat instead of recovering from it.$$),
('cy-f-419','cysa','core',3,'3.2',$$What is a hyper-care monitoring period after recovery?$$,$$A period of heightened, focused monitoring on recently restored systems immediately after they return to production, watching for any sign of reinfection before declaring the incident fully closed.$$),
('cy-f-420','cysa','core',3,'3.2',$$What is phased/staged recovery?$$,$$Restoring the most business-critical systems first, under heightened monitoring, before bringing back lower-priority systems - balancing the need to resume operations against the risk of an incomplete eradication.$$),
('cy-f-421','cysa','core',3,'3.2',$$When is segment-wide (VLAN-wide) isolation preferred over isolating individual hosts?$$,$$When the full scope of compromise across a network segment is still unknown - isolating the whole segment prevents further lateral spread while scoping continues, rather than isolating hosts one at a time as they're found.$$),
('cy-f-422','cysa','core',3,'3.2',$$Why might responders delay fully containing a compromised host?$$,$$To observe the attacker's behavior a little longer, via monitoring or deception, and gather intelligence on scope, tools, and objectives - a deliberate, risk-weighed trade-off against tipping them off, not neglect.$$),
('cy-f-423','cysa','core',3,'3.2',$$When is a Continuity of Operations Plan (COOP) invoked during incident response?$$,$$When containment actions, such as isolating or taking down a system, will disrupt critical business operations - COOP defines how essential functions continue on alternate means while the primary system is contained.$$),
('cy-f-424','cysa','core',3,'3.2',$$What containment options exist for an active DDoS attack?$$,$$Rate limiting, blackhole/null routing of attack traffic, and traffic scrubbing via an upstream provider or CDN - absorbing or filtering the flood rather than patching a vulnerability, since a DDoS isn't an exploit-based intrusion.$$),
('cy-f-425','cysa','core',3,'3.2',$$Why is a compromised third-party/supply-chain component especially hard to eradicate?$$,$$The organization can't simply patch code it doesn't own; until the vendor ships a fix, containment may require disabling or isolating the affected component's functionality entirely rather than eradicating in place.$$),
('cy-f-426','cysa','core',3,'3.2',$$How do responders validate that eradication was actually complete?$$,$$Re-scanning and monitoring previously affected systems for the same indicators of compromise before recovery - confirming no reinfection or missed foothold rather than assuming the cleanup worked.$$),
('cy-f-427','cysa','core',3,'3.2',$$Why does eradicating multiple compromised systems require careful sequencing?$$,$$If footholds are removed one at a time over a long window, an attacker who notices can re-establish access on already-cleaned systems or shift to remaining ones - simultaneous/coordinated eradication denies them that chance.$$),
-- ===================== 3.3 core (5) =====================
('cy-f-428','cysa','core',3,'3.3',$$What is an incident-response jump kit (go bag)?$$,$$A pre-staged, ready-to-grab kit of forensic tools - write blockers, clean storage media, a forensic laptop, cabling, chain-of-custody forms - prepared in advance so responders aren't scrambling to gather equipment once an incident starts.$$),
('cy-f-429','cysa','core',3,'3.3',$$What events should trigger a review of the IR plan outside its normal schedule?$$,$$Major organizational changes - mergers/acquisitions, new critical systems or cloud migrations, significant staff turnover, regulatory changes - and immediately after any real incident: anything that could invalidate assumptions the plan was built on.$$),
('cy-f-430','cysa','core',3,'3.3',$$What are the three broad root-cause categories investigators sort findings into?$$,$$Technical (a missing or misconfigured control), process (a procedure that was never defined or wasn't followed), and human factor (a mistake or a susceptibility like falling for phishing) - naming which one narrows what actually needs to change.$$),
('cy-f-431','cysa','core',3,'3.3',$$What must happen before a legal hold is released?$$,$$Legal counsel signs off that the litigation or investigatory need has passed; only then can preserved evidence return to the normal retention/deletion schedule - releasing it early risks spoliation if the need resurfaces.$$),
('cy-f-432','cysa','core',3,'3.3',$$Why do organizations share sanitized findings from their own incidents with an ISAC or the wider threat-intel community post-incident?$$,$$New IOCs, TTPs, and lessons discovered during the response can help peer organizations detect or block the same campaign - post-incident sharing turns one victim's response into industry-wide defense.$$),
-- ===================== acronyms (7) =====================
('cy-a-140','cysa','acronym',3,'3.1',$$OSSTMM$$,$$Open Source Security Testing Methodology Manual - a peer-reviewed methodology for consistent, measurable security testing, scored via Risk Assessment Values (RAV).$$),
('cy-a-141','cysa','acronym',3,'3.1',$$ISAC$$,$$Information Sharing and Analysis Center - an industry-specific community where organizations share threat intelligence and best practices with peers facing similar risks.$$),
('cy-a-142','cysa','acronym',3,'3.1',$$MSSP$$,$$Managed Security Service Provider - a third party contracted to perform ongoing security monitoring and/or incident response on an organization's behalf under a service agreement.$$),
('cy-a-143','cysa','acronym',3,'3.1',$$TTX$$,$$Tabletop Exercise - a discussion-based walkthrough of an incident scenario used to test an IR plan and roles without touching production systems.$$),
('cy-a-144','cysa','acronym',3,'3.2',$$COOP$$,$$Continuity of Operations Plan - defines how essential business functions keep running on alternate means while a primary system is contained or offline during incident response.$$),
('cy-a-145','cysa','acronym',3,'3.3',$$CAPA$$,$$Corrective And Preventive Action - a tracking framework distinguishing fixes for what already went wrong (corrective) from steps that reduce similar risk elsewhere (preventive).$$),
('cy-a-146','cysa','acronym',3,'3.3',$$AAR$$,$$After-Action Report - the written record of a lessons-learned review documenting what happened, what worked, and the concrete improvements to carry back into preparation.$$),
-- ===================== feynman (3) =====================
('cy-y-070','cysa','feynman',3,'3.1',$$Explain how the Unified Kill Chain fixes a real gap in the original Cyber Kill Chain.$$,$$Model answer: The original Kill Chain is a straight line that ends at "Actions on Objectives," as if the attack were over. Real intrusions don't stop there - attackers pivot, escalate, move laterally, and re-establish footholds for weeks. The Unified Kill Chain borrows ATT&CK's granular techniques and turns the process into loop-friendly phases covering that whole "in the network" persistence and lateral-movement stage the original chain waves past in one box - so it actually matches what a long-running breach looks like, not just how the attacker got in the door.$$),
('cy-y-071','cysa','feynman',3,'3.2',$$Explain why a responder might deliberately NOT contain a compromised host the moment it's found.$$,$$Model answer: Slamming the door shut instantly tips the attacker off - they see their access die and may destroy evidence, deploy a wiper, or scatter to footholds you haven't found yet. Sometimes it's worth watching quietly a little longer, isolated from anything sensitive, to see what they're after, what tools they use, and how many other systems they touch - then containing everything at once. It's a deliberate risk trade against tipping your hand too early, not carelessness.$$),
('cy-y-072','cysa','feynman',3,'3.3',$$Explain the "five whys" technique using a simple example, then apply it to a phishing incident.$$,$$Model answer: Ask "why" repeatedly past the first answer. Simple case: the car won't start - why? Battery's dead - why? Alternator failed - why? Belt snapped - why? Belt was never inspected - why? No maintenance schedule existed. THAT'S the fixable root cause. Applied to phishing: a user clicked a malicious link - why? The email passed spam filtering - why? It spoofed a trusted domain the filter allowlisted - why? The allowlist was never reviewed - why? No process owns allowlist review. The real fix isn't "train that user," it's "assign someone to audit the allowlist."$$);
