-- Core flashcards, Domain 2: Threats, Vulnerabilities & Mitigations (22%)
insert into public.flashcards (id, deck, domain, objective, front, back) values
('f2-001','core',2,'2.1',$$Name the major threat actor types.$$,$$Nation-state, organized crime, hacktivist, insider threat, unskilled attacker (script kiddie), shadow IT.$$),
('f2-002','core',2,'2.1',$$Which threat actor is best resourced and most sophisticated?$$,$$Nation-state actors - funding, custom tooling (APTs), long-term espionage or disruption motives.$$),
('f2-003','core',2,'2.1',$$Primary motivation of organized crime actors?$$,$$Financial gain - ransomware, fraud, data theft for sale.$$),
('f2-004','core',2,'2.1',$$What motivates hacktivists?$$,$$Ideology/philosophical or political beliefs - defacement, leaks, DDoS to make a statement.$$),
('f2-005','core',2,'2.1',$$Why are insider threats especially dangerous?$$,$$They already have legitimate access and knowledge of systems; motivations include revenge or financial gain, and they bypass perimeter defenses.$$),
('f2-006','core',2,'2.1',$$What is shadow IT?$$,$$Technology deployed without IT approval (unsanctioned SaaS, personal devices) - creates unmanaged, unprotected attack surface.$$),
('f2-007','core',2,'2.1',$$List common threat actor motivations (exam list).$$,$$Data exfiltration, espionage, service disruption, blackmail, financial gain, philosophical/political beliefs, ethical, revenge, disruption/chaos, war.$$),
('f2-008','core',2,'2.2',$$Message-based attack vectors - name three.$$,$$Email (phishing), SMS (smishing), instant messaging - deliver malicious links/attachments or social engineering.$$),
('f2-009','core',2,'2.2',$$What is a supply chain attack? Give an example vector.$$,$$Compromising a target through its suppliers: managed service providers (MSPs), hardware vendors, or software dependencies/updates.$$),
('f2-010','core',2,'2.2',$$Phishing vs spear phishing vs whaling?$$,$$Phishing: mass generic lure. Spear phishing: tailored to a specific person/org. Whaling: spear phishing aimed at executives.$$),
('f2-011','core',2,'2.2',$$What is vishing? Smishing?$$,$$Vishing: voice-call phishing. Smishing: SMS text phishing.$$),
('f2-012','core',2,'2.2',$$What is pretexting?$$,$$Inventing a believable scenario/identity (the pretext) to manipulate a victim into disclosing info or acting.$$),
('f2-013','core',2,'2.2',$$What is Business Email Compromise (BEC)?$$,$$Attacker impersonates or hijacks a trusted business email account (often an executive or vendor) to redirect payments or extract data.$$),
('f2-014','core',2,'2.2',$$What is a watering hole attack?$$,$$Compromising a website that a target group is known to visit, so the targets infect themselves.$$),
('f2-015','core',2,'2.2',$$What is typosquatting?$$,$$Registering look-alike domains (gooogle.com) to catch mistyped traffic for phishing or malware delivery.$$),
('f2-016','core',2,'2.2',$$What is brand impersonation?$$,$$Attacker mimics a trusted brand's emails/sites/logos to gain victim trust.$$),
('f2-017','core',2,'2.2',$$What is disinformation/misinformation as an attack?$$,$$Deliberately spreading false narratives (influence campaigns) to manipulate opinion or create confusion - often nation-state.$$),
('f2-018','core',2,'2.3',$$What is a zero-day vulnerability?$$,$$A flaw unknown to the vendor (no patch exists) being exploited - defenses rely on compensating controls and behavior detection.$$),
('f2-019','core',2,'2.3',$$Buffer overflow - what is it?$$,$$Writing more data than a memory buffer holds, overwriting adjacent memory - can crash a program or execute attacker code.$$),
('f2-020','core',2,'2.3',$$Race condition / TOC-TOU vulnerability?$$,$$Outcome depends on operation timing; time-of-check to time-of-use flaws let attackers change a resource between validation and use.$$),
('f2-021','core',2,'2.3',$$What is a memory injection attack?$$,$$Inserting malicious code into a running process's memory (e.g., DLL injection) to execute with that process's privileges and evade disk-based AV.$$),
('f2-022','core',2,'2.3',$$Name three common cloud-specific vulnerabilities.$$,$$Misconfiguration (open storage buckets, permissive IAM), insecure APIs, shared-tenancy risks - plus lack of visibility into provider infrastructure.$$),
('f2-023','core',2,'2.3',$$What is VM escape? VM sprawl?$$,$$Escape: breaking out of a guest VM to attack the hypervisor/other VMs. Sprawl: unmanaged proliferation of VMs leading to unpatched, forgotten systems.$$),
('f2-024','core',2,'2.3',$$Why are end-of-life/legacy systems a vulnerability?$$,$$No vendor patches for new flaws; mitigate with isolation/segmentation, compensating controls, or replacement.$$),
('f2-025','core',2,'2.3',$$Common mobile device vulnerabilities (exam view)?$$,$$Sideloading (installing apps outside official stores) and jailbreaking/rooting (removing OS protections) - both bypass platform security.$$),
('f2-026','core',2,'2.3',$$What is a firmware vulnerability and why is it serious?$$,$$Flaws in low-level device code (below the OS); compromise persists across reinstalls and evades most endpoint tools.$$),
('f2-027','core',2,'2.3',$$What is a supply-chain vulnerability in software?$$,$$Malicious or vulnerable third-party components (libraries, build tools, update channels) inherited by your software.$$),
('f2-028','core',2,'2.4',$$Ransomware - behavior and best defense?$$,$$Encrypts data and demands payment; defenses: offline/immutable backups, EDR, patching, least privilege, user training.$$),
('f2-029','core',2,'2.4',$$Trojan vs worm vs virus?$$,$$Trojan: malware disguised as legitimate software (user runs it). Worm: self-propagates across networks without user action. Virus: attaches to files/programs and needs execution to spread.$$),
('f2-030','core',2,'2.4',$$What is a logic bomb?$$,$$Malicious code that triggers on a condition (date, event, account deletion) - classic insider threat move.$$),
('f2-031','core',2,'2.4',$$What is a rootkit?$$,$$Malware embedding into the OS kernel/low level to hide itself and other malware; survives reboots, evades AV.$$),
('f2-032','core',2,'2.4',$$Spyware vs keylogger vs bloatware?$$,$$Spyware: covertly collects user data/activity. Keylogger: records keystrokes (credentials). Bloatware: unwanted preinstalled software expanding attack surface.$$),
('f2-033','core',2,'2.4',$$What is fileless malware and how is it detected?$$,$$Runs in memory using legitimate tools (PowerShell, WMI), leaving little on disk; detected via behavior monitoring/EDR, script logging.$$),
('f2-034','core',2,'2.4',$$Physical brute-force attacks (exam list)?$$,$$Forcible entry, RFID cloning of badges, environmental attacks (e.g., cutting power/HVAC) - physical indicators of malicious activity.$$),
('f2-035','core',2,'2.4',$$DDoS: amplified vs reflected?$$,$$Reflected: attacker spoofs victim's IP so third-party servers reply to the victim. Amplified: small queries yield huge responses (DNS, NTP) multiplying traffic. Often combined.$$),
('f2-036','core',2,'2.4',$$DNS attacks - name three.$$,$$DNS/cache poisoning (fake records), domain hijacking (stealing registrar control), DNS tunneling/exfiltration (data hidden in DNS queries).$$),
('f2-037','core',2,'2.4',$$What is an on-path (man-in-the-middle) attack?$$,$$Attacker positions between two parties to intercept/modify traffic (ARP poisoning, rogue AP); mitigated by encryption and mutual authentication.$$),
('f2-038','core',2,'2.4',$$What is credential replay?$$,$$Capturing authentication material (hashes, tokens, cookies) and re-sending it to authenticate as the victim - mitigated by session expiry, TLS, nonce/timestamps.$$),
('f2-039','core',2,'2.4',$$What is a downgrade attack?$$,$$Forcing communication to an older, weaker protocol/cipher (e.g., TLS to SSL) to break it; mitigate by disabling legacy versions.$$),
('f2-040','core',2,'2.4',$$What is a birthday attack?$$,$$Exploiting hash collision probability (two inputs, same hash) - probability rises much faster than intuition suggests; mitigated by longer, stronger hashes.$$),
('f2-041','core',2,'2.4',$$Spraying vs brute-force password attacks?$$,$$Brute force: many passwords against one account (triggers lockout). Spraying: one common password against many accounts - avoids lockouts and detection.$$),
('f2-042','core',2,'2.4',$$Privilege escalation - vertical vs horizontal?$$,$$Vertical: gaining higher privileges (user to admin). Horizontal: accessing another user's resources at the same privilege level.$$),
('f2-043','core',2,'2.4',$$Directory traversal attack?$$,$$Using ../ sequences in input to reach files outside the web root (e.g., /etc/passwd); mitigate with input validation and least-privilege file permissions.$$),
('f2-044','core',2,'2.4',$$What is SQL injection and its top mitigation?$$,$$Malicious SQL in user input alters queries (' OR 1=1--); mitigate with parameterized queries/prepared statements plus input validation.$$),
('f2-045','core',2,'2.4',$$Stored vs reflected XSS?$$,$$Stored: malicious script saved on the server (comment field) and served to every visitor. Reflected: script echoed back from a crafted link only to whoever clicks it.$$),
('f2-046','core',2,'2.4',$$Common indicators of compromise (exam list)?$$,$$Account lockout, concurrent session usage, impossible travel, blocked content, resource consumption spikes, resource inaccessibility, out-of-cycle logging, missing logs, published stolen data.$$),
('f2-047','core',2,'2.4',$$What does "impossible travel" indicate?$$,$$Logins from geographically distant locations within an impossible timeframe - strong signal of compromised credentials.$$),
('f2-048','core',2,'2.4',$$Why are MISSING logs an indicator of attack?$$,$$Attackers clear or disable logging to cover tracks; gaps in logs are themselves an alert-worthy anomaly.$$),
('f2-049','core',2,'2.5',$$What is network segmentation as a mitigation?$$,$$Dividing the network into zones (VLANs, subnets, DMZ) so compromise of one zone cannot reach others; essential for legacy/IoT/OT isolation.$$),
('f2-050','core',2,'2.5',$$What are ACLs?$$,$$Access control lists - ordered permit/deny rules applied to network traffic (routers/firewalls) or file permissions.$$),
('f2-051','core',2,'2.5',$$Application allow list vs deny list as endpoint mitigation?$$,$$Allow list permits only approved executables (default deny, strongest); deny list blocks known-bad only.$$),
('f2-052','core',2,'2.5',$$What is patching cadence and emergency patching?$$,$$Regular scheduled updates (e.g., monthly) plus out-of-band emergency patches for actively exploited critical flaws.$$),
('f2-053','core',2,'2.5',$$Key host hardening techniques (exam list)?$$,$$Encryption, endpoint protection (EDR/HIPS), host firewall, disabling unneeded ports/services, default password changes, removing unnecessary software, patching.$$),
('f2-054','core',2,'2.5',$$What is decommissioning as a mitigation?$$,$$Formally retiring systems: remove from network, sanitize/destroy data, revoke credentials/certificates - prevents forgotten systems becoming footholds.$$),
('f2-055','core',2,'2.5',$$Isolation vs containment in mitigation?$$,$$Isolation: separating a system/network preemptively (air gap, segment). Containment: restricting an ACTIVE compromise from spreading (quarantine host, disable account).$$);
