-- A+ Core 1 (220-1101) Domain 4 expansion: Virtualization & Cloud Computing.
-- Tops objective 4.1 (cloud-computing concepts) and 4.2 (client-side
-- virtualization) up to 33 items each.
--   questions   a1-q-700 .. a1-q-721  (22: 15 mcq, 5 multi, 1 matching, 1 ordering)
--   flashcards  a1-f-700 .. a1-f-726  (27: 22 core, 5 acronym)
-- Objective tags follow the 220-1101 blueprint as corrected in
-- 20260715000101_review_fixes_aplus1.sql: 4.1 = cloud, 4.2 = client-side
-- virtualization. Text uses dollar-quoting, matching every other seed file.

insert into public.questions (id, cert, domain, objective, qtype, difficulty, stem, choices, answer, explanation) values

-- ---------- 4.1 Cloud computing concepts (10) ----------

('a1-q-700','aplus1',4,'4.1','mcq',2,$q$A development team wants to deploy a web application to the cloud. They want to write and control the application code, but they do not want to install, size, or patch the operating system or the web server runtime it needs. Which cloud service model fits this requirement?$q$,$q$["IaaS","PaaS","SaaS","Community cloud"]$q$::jsonb,'1'::jsonb,$q$PaaS supplies a managed operating system and runtime stack, so the customer deploys only application code and data. IaaS is the tempting answer because the team also controls the application there, but IaaS delivers a bare virtual machine and leaves the guest OS and runtime installation, sizing and patching to the customer - exactly the work they want to avoid. SaaS would hand them a finished application with no code of their own, and community cloud is a deployment model, not a service model.$q$),

('a1-q-701','aplus1',4,'4.1','mcq',3,$q$An organization runs its accounting virtual machines on a public-cloud IaaS platform. A critical security update is released for the operating system inside those VMs. Who is responsible for applying it?$q$,$q$["The cloud provider, because it owns the physical hosts the VMs run on","The customer, because the guest operating system sits above the IaaS boundary","Neither party - IaaS instances patch their guest operating systems automatically","The provider, but only if the customer has purchased a high-availability tier"]$q$::jsonb,'1'::jsonb,$q$In IaaS the provider's responsibility stops at the physical hardware, the hypervisor and the virtual network; everything from the guest OS upward belongs to the customer. Blaming the provider is the classic error - the provider genuinely does patch the hosts and hypervisor, but that never reaches inside a customer's VM. Had the workload been PaaS or SaaS, OS patching would have been the provider's job.$q$),

('a1-q-702','aplus1',4,'4.1','mcq',2,$q$Four independent county hospital systems jointly fund and share a single cloud environment purpose-built to satisfy the healthcare regulations all four fall under. No outside organization can use it. Which deployment model is this?$q$,$q$["Public cloud","Private cloud","Community cloud","Hybrid cloud"]$q$::jsonb,'2'::jsonb,$q$A community cloud is shared by several organizations with common regulatory, security or mission requirements, who also share its cost, and it stays closed to the general public. Private cloud is the tempting choice because the environment is not public, but a private cloud is dedicated to exactly one organization - here four separate organizations share and fund the same platform.$q$),

('a1-q-703','aplus1',4,'4.1','mcq',1,$q$A company's cloud invoice changes every month: last month it covered 412 vCPU-hours and 1.2 TB of storage, this month 1,180 vCPU-hours and 1.9 TB. Which cloud characteristic does this billing arrangement demonstrate?$q$,$q$["Metered utilization","Rapid elasticity","High availability","File synchronization"]$q$::jsonb,'0'::jsonb,$q$Metered utilization means consumption is measured per unit - vCPU-hours, GB stored, GB transferred - and billed accordingly, so the invoice tracks real usage. Rapid elasticity is the natural distractor because it explains why the usage moved, but elasticity is the technical ability to scale capacity while metering is the measurement and billing of what was consumed.$q$),

('a1-q-704','aplus1',4,'4.1','mcq',3,$q$In a public cloud, a customer's virtual machines run on physical hosts that simultaneously run virtual machines belonging to other, unrelated customers. Separation between them is enforced logically by the hypervisor and virtual networking rather than by separate hardware. Which cloud characteristic is being described?$q$,$q$["Rapid elasticity","Shared resources (multi-tenant resource pooling)","High availability","Metered utilization"]$q$::jsonb,'1'::jsonb,$q$Shared resources, also called resource pooling, is precisely this multi-tenant arrangement, and it is the reason some regulated workloads are moved to a private cloud or to dedicated hosts. Rapid elasticity is the usual wrong pick, but it describes how quickly capacity can grow and shrink - a property the customer would still enjoy even if it had the physical host entirely to itself.$q$),

('a1-q-705','aplus1',4,'4.1','mcq',1,$q$A user edits a document stored in a cloud storage folder on a work laptop. Minutes later the updated version is already present in the same folder on the user's phone and home desktop, with no manual upload. Which cloud characteristic is at work?$q$,$q$["File synchronization","Rapid elasticity","Metered utilization","Resource pooling"]$q$::jsonb,'0'::jsonb,$q$File synchronization keeps the local copy on each device consistent with the cloud copy, uploading changes and pushing them to the user's other devices automatically. Rapid elasticity is about scaling compute or storage capacity to match demand, not about replicating one file across a person's devices.$q$),

('a1-q-706','aplus1',4,'4.1','mcq',3,$q$A retailer hires 300 seasonal remote workers for a ten-week period each year. IT must give each one a managed corporate desktop without purchasing server hardware, and must release the capacity when the season ends. Which approach best meets the requirement?$q$,$q$["Cloud-hosted VDI (desktop as a service)","On-premises VDI on newly purchased host servers","Ship each worker a corporate laptop with the standard image","Give each worker a Type 2 hypervisor licence to run a corporate VM on their personal PC"]$q$::jsonb,'0'::jsonb,$q$Cloud-hosted VDI provisions virtual desktops on the provider's infrastructure and releases them when the season ends, so the elasticity and metered billing match a ten-week workload with no capital purchase. On-premises VDI delivers an identical desktop experience and is the tempting answer, but it requires buying host servers that would sit idle for the other 42 weeks - the exact cost the requirement rules out.$q$),

('a1-q-707','aplus1',4,'4.1','multi',2,$q$A company runs virtual machines on a public-cloud IaaS platform. Select the TWO responsibilities that remain with the company rather than the provider. (Choose two.)$q$,$q$["Installing security patches on the guest operating systems","Replacing failed physical disks in the provider's data center","Configuring the virtual firewall rules that protect its own instances","Maintaining and patching the hypervisor the instances run on","Supplying power and cooling to the physical racks"]$q$::jsonb,'[0,2]'::jsonb,$q$Under IaaS the customer owns the guest operating system and everything above it, which includes OS patching and the security rules applied to its own instances. Physical disk replacement, hypervisor maintenance and facility power and cooling all sit below the IaaS boundary and belong to the provider. Hypervisor maintenance is the most tempting distractor because the customer's VMs depend on it completely, but the customer has no access to that layer at all.$q$),

('a1-q-708','aplus1',4,'4.1','multi',3,$q$Select the TWO statements that correctly distinguish a private cloud from a public cloud. (Choose two.)$q$,$q$["A private cloud's pooled resources are dedicated to a single organization","A private cloud gives the organization direct control over where its data physically resides","A private cloud cannot offer self-service provisioning or elasticity","A private cloud removes the organization's responsibility for capacity planning","A private cloud is always less expensive than public cloud at any scale"]$q$::jsonb,'[0,1]'::jsonb,$q$Single-tenant dedicated resources and control over data location are the defining advantages of a private cloud. The claim that a private cloud cannot do self-service or elasticity is wrong - it provides both, just within capacity the organization already owns, and that finite capacity is why the fourth option is backwards: capacity planning and hardware purchasing stay firmly with the organization, which is the main trade-off against public cloud.$q$),

('a1-q-709','aplus1',4,'4.1','matching',2,$q$Match each hosting model to the division of management responsibility it creates.$q$,$q${"left":["IaaS","PaaS","SaaS","Traditional on-premises data center"],"right":["Provider runs everything up to the finished application; the customer manages only its users, data and configuration settings","The organization manages everything itself, including facility, power, hardware and hypervisor","Provider manages the hardware, hypervisor and virtual network; the customer installs and patches the guest OS and everything above it","Provider manages the operating system and runtime; the customer deploys and manages only application code and its data"]}$q$::jsonb,'[2,3,0,1]'::jsonb,$q$The responsibility line moves upward from IaaS to PaaS to SaaS: with IaaS the customer's ownership begins at the guest OS, with PaaS it begins at the application code, and with SaaS it shrinks to data, users and settings. The on-premises data center is the baseline where nothing is delegated. The usual mistake is handing guest-OS patching to the provider under IaaS, which is the boundary the exam tests most often.$q$),

-- ---------- 4.2 Client-side virtualization (12) ----------

('a1-q-710','aplus1',4,'4.2','mcq',2,$q$A technician installs a Type 2 hypervisor on a new workstation and tries to power on a 64-bit guest. The VM fails immediately with a message that hardware-assisted virtualization is not available. The workstation has a current 64-bit processor, ample free RAM and plenty of free disk space. What is the most likely cause?$q$,$q$["Intel VT-x / AMD-V is disabled in the workstation's UEFI firmware","The host does not have enough free disk space for the virtual disk","The VM's virtual network adapter is set to host-only mode","Type 2 hypervisors cannot run 64-bit guest operating systems"]$q$::jsonb,'0'::jsonb,$q$Virtualization extensions ship disabled in UEFI on many systems; without VT-x or AMD-V the hypervisor cannot run a 64-bit guest and refuses to start it. The fix is to enter firmware setup, enable the extension, save and reboot. Free disk space is the plausible-sounding resource distractor, but a storage shortage produces a disk or datastore error rather than a hardware-virtualization message - and the stem already states disk is plentiful.$q$),

('a1-q-711','aplus1',4,'4.2','mcq',3,$q$A workstation with 8 GB of physical RAM runs a Type 2 hypervisor. A technician assigns 6 GB of RAM to a single VM. The VM starts and runs, but both the guest and the host become extremely sluggish and the host's disk activity light stays on almost constantly. What is the most likely cause?$q$,$q$["The host is over-committed on memory and is paging heavily to disk","CPU virtualization extensions are disabled in the UEFI firmware","The virtual disk is thin-provisioned rather than thick-provisioned","The guest operating system has not been activated"]$q$::jsonb,'0'::jsonb,$q$Handing 6 GB of 8 GB to the guest leaves the host OS roughly 2 GB, forcing constant paging to disk - which is exactly why both sides crawl and disk activity never stops. Reduce the VM's assigned RAM or add physical memory. Disabled virtualization extensions are the reflex answer for VM problems, but they stop a VM from starting at all; this VM started, so the symptom is a resource shortage, not a missing CPU feature.$q$),

('a1-q-712','aplus1',4,'4.2','mcq',2,$q$A test VM must receive an IP address from the physical LAN's DHCP server and be reachable by other physical computers on that LAN. At present the VM can communicate only with its host machine. Which virtual network adapter mode should the technician select?$q$,$q$["Bridged","NAT","Host-only","Internal (isolated) network"]$q$::jsonb,'0'::jsonb,$q$Bridged mode attaches the virtual NIC to the physical network as a peer, so the VM leases its own address from the LAN DHCP server and other LAN hosts can initiate connections to it. NAT is the tempting alternative because it does give the guest outbound connectivity, but the VM hides behind the host's address and is not directly reachable inbound, and it does not get a LAN DHCP lease. Host-only is the current setting that produced the symptom.$q$),

('a1-q-713','aplus1',4,'4.2','mcq',1,$q$A manufacturing plant depends on a control application that runs only on an operating system whose vendor ended support years ago, and the software vendor is out of business. The original physical PC has now failed. What is the standard virtualization answer?$q$,$q$["Run the legacy operating system and its application inside a VM with restricted network access","Install the current operating system and run the application in compatibility mode","Have the application rewritten for a currently supported operating system","Buy replacement hardware of the same vintage and keep it as a cold spare"]$q$::jsonb,'0'::jsonb,$q$Legacy software and OS support is a named purpose of client-side virtualization: the VM reproduces the obsolete environment on modern hardware, exists as a file that can be backed up and snapshotted, and can be network-restricted because the unsupported OS no longer receives security patches. Compatibility mode is worth trying for an ordinary application and is the strongest distractor, but it cannot help when the software depends on the legacy operating system itself.$q$),

('a1-q-714','aplus1',4,'4.2','mcq',2,$q$A developer working on a macOS workstation must build and test the same product on Windows and on Linux, and needs all three environments running at the same time so behavior can be compared side by side. Which solution meets the requirement?$q$,$q$["Cross-platform virtualization: Windows and Linux guest VMs on a hypervisor running on the macOS host","Configure the workstation to triple-boot macOS, Windows and Linux","Keep a separate physical Windows PC and Linux PC and remote into each for testing","Application virtualization of the Windows build tools onto macOS"]$q$::jsonb,'0'::jsonb,$q$Cross-platform virtualization runs guests from different OS families concurrently on one host, which is what comparing all three at once demands. Multi-boot is the tempting alternative because it also provides all three operating systems on one machine, but only one runs at a time and every switch costs a reboot, so side-by-side comparison is impossible.$q$),

('a1-q-715','aplus1',4,'4.2','mcq',3,$q$A company must deliver one specialized application to 40 users. The application conflicts with software already installed on their PCs. IT does not want to change the standard desktop image and does not want to give each user an entire second operating system to license and maintain. Which approach fits?$q$,$q$["Application virtualization, delivering the app in its own isolated container","A full VDI deployment giving each user a virtual desktop","Install a Type 2 hypervisor and a guest OS VM on each of the 40 PCs","Reimage all 40 PCs with a build that includes the application"]$q$::jsonb,'0'::jsonb,$q$Application virtualization packages a single application with its dependencies and runs it isolated from the local operating system, which resolves the conflict without touching the desktop image. VDI or a per-user VM would isolate the application just as effectively and is the tempting answer, but each one supplies a whole additional operating system to license, patch and support - explicitly ruled out by the requirement.$q$),

('a1-q-716','aplus1',4,'4.2','mcq',3,$q$A security analyst will detonate a suspicious executable inside a VM running on a workstation attached to the corporate LAN. Which configuration best limits the risk to the rest of the organization?$q$,$q$["Place the VM on a host-only or isolated virtual network, disable shared folders and clipboard sharing, and snapshot it before detonation","Bridge the VM to the corporate LAN so the network IDS can inspect the malware's traffic","Give the VM a NAT adapter so it reaches the internet through the host's address only","Rely on the hypervisor's built-in isolation and leave the default VM settings in place"]$q$::jsonb,'0'::jsonb,$q$Isolating the virtual network and closing the host-to-guest channels - shared folders, clipboard, drag-and-drop - removes the paths malware would use to reach the host or the LAN, and the pre-detonation snapshot lets the analyst discard the infected state afterwards. Bridging for IDS visibility is the seductive wrong answer: it places a live sample directly on the production network, which is the precise outcome the isolation is meant to prevent.$q$),

('a1-q-717','aplus1',4,'4.2','mcq',3,$q$Six VMs share a host whose single 1 TB SSD holds all of their thin-provisioned virtual disks; those disks are configured with a combined maximum size of 1.8 TB. After months of normal use, several VMs suddenly suspend themselves and their disks go read-only. What happened?$q$,$q$["The thin-provisioned disks grew with use until the host's physical storage was exhausted","Each guest operating system filled its own system partition at the same moment","The host CPU no longer has enough cores to schedule six VMs","The virtual disks silently reverted from thin to thick provisioning"]$q$::jsonb,'0'::jsonb,$q$Thin provisioning permits the sum of the virtual disks to exceed the physical volume; the files grow as data is written, and when the host volume fills, running VMs suspend or their disks are forced read-only. Guests filling their own partitions is individually plausible and is the strongest distractor, but that fails one VM at a time and would never suspend several simultaneously - the shared host volume is what makes the failure collective.$q$),

('a1-q-718','aplus1',4,'4.2','multi',2,$q$A new VM will not power on and the hypervisor reports that hardware-assisted virtualization is unavailable. Select the TWO items the technician should check. (Choose two.)$q$,$q$["Whether Intel VT-x / AMD-V is enabled in the host's UEFI/BIOS setup","Whether the host CPU model actually supports virtualization extensions","Whether the virtual disk has enough free space for the guest OS installation","Whether the virtual network adapter is set to bridged mode","Whether the guest operating system has a valid product key"]$q$::jsonb,'[0,1]'::jsonb,$q$The error names the CPU feature, so the two checks are whether the processor supports the extensions at all and whether they are switched on in firmware. Disk space is the most tempting distractor because free storage is a genuine VM prerequisite, but a storage shortage raises a disk error and never reports missing hardware-assisted virtualization. Adapter mode and licensing affect a VM that is already running, not one that refuses to power on.$q$),

('a1-q-719','aplus1',4,'4.2','multi',2,$q$Select the TWO statements that correctly describe security requirements for running guest VMs on a client workstation. (Choose two.)$q$,$q$["Each guest OS must be licensed, patched and protected with antimalware in its own right","A guest VM automatically inherits the host's patch level and antimalware protection","Host-to-guest features such as shared folders, clipboard sharing and drag-and-drop should be disabled for untrusted guests","Malware cannot infect a VM because the VM is not running on real hardware","Taking a snapshot removes the need to secure the guest at all"]$q$::jsonb,'[0,2]'::jsonb,$q$A guest is a complete, separate operating system installation, so it needs its own licence, patching and antimalware, and the integration features that bridge host and guest are the routes malware uses to escape - they are switched off for untrusted guests. The inheritance claim is the most common misconception on this objective: nothing about the host's patches or antimalware extends inside the guest, and a snapshot only helps you recover after a compromise, it does not prevent one.$q$),

('a1-q-720','aplus1',4,'4.2','multi',2,$q$A technician is specifying a workstation that must run three VMs concurrently. Select the TWO correct statements about the host's resource requirements. (Choose two.)$q$,$q$["Physical RAM must cover the memory assigned to all running guests plus what the host OS needs for itself","Each virtual disk consumes real capacity on the host's physical storage","A single CPU core can be shared among any number of VMs with no effect on performance","Guests need no network configuration of their own as long as the host is already online","Consolidating workloads onto VMs reduces the total storage the machine needs"]$q$::jsonb,'[0,1]'::jsonb,$q$Memory and storage are hard physical limits: the guests plus the host must fit in installed RAM, and every virtual disk is a real file occupying real capacity. The CPU option is the appealing half-truth - cores are time-sliced so VMs can oversubscribe them and still boot, but the result is contention and sluggish guests, not free capacity. Guests also need their own IP configuration, and virtualization adds storage overhead rather than removing it.$q$),

('a1-q-721','aplus1',4,'4.2','ordering',3,$q$Place the steps for standing up a new test VM on a client workstation in the correct order.$q$,$q$["Create the VM and allocate vCPUs, RAM, a virtual disk and a virtual NIC","Confirm the CPU supports virtualization extensions and enable Intel VT-x / AMD-V in UEFI","Patch the guest, install antimalware, and take a baseline snapshot","Install the Type 2 hypervisor onto the host operating system","Install the guest operating system from the ISO","Verify the guest reaches the network through its virtual adapter"]$q$::jsonb,'[1,3,0,4,5,2]'::jsonb,$q$Firmware comes first: without VT-x or AMD-V enabled the hypervisor cannot run 64-bit guests, so the extension is confirmed before the hypervisor is installed. The hypervisor must exist before a VM can be defined, the VM shell must exist before an OS can be installed into it, and connectivity is verified while the guest is still simple to troubleshoot. The baseline snapshot is taken last, after the guest is patched, protected and confirmed working, so any later rollback returns to a known-good secured state rather than a bare installation.$q$);

insert into public.flashcards (id, cert, deck, domain, objective, front, back) values

-- ---------- 4.1 Cloud computing concepts (13: 5 acronym, 8 core) ----------

('a1-f-700','aplus1','acronym',4,'4.1',$$IaaS$$,$$Infrastructure as a Service - the provider rents out virtualized compute, storage and networking. Purpose: you receive a bare virtual machine and stay responsible for the guest OS, its patching and everything above it.$$),
('a1-f-701','aplus1','acronym',4,'4.1',$$PaaS$$,$$Platform as a Service - the provider supplies a managed operating system, runtime and development stack. Purpose: deploy application code and data without installing, sizing or patching servers.$$),
('a1-f-702','aplus1','acronym',4,'4.1',$$DaaS$$,$$Desktop as a Service - virtual desktops hosted and maintained by a provider and consumed on subscription. Purpose: VDI without owning, sizing or patching the host servers.$$),
('a1-f-703','aplus1','acronym',4,'4.1',$$VDI$$,$$Virtual Desktop Infrastructure - desktop operating system instances run on centralized servers and are streamed to thin clients or ordinary endpoints. Purpose: centralizes imaging and patching and keeps corporate data off the endpoint.$$),
('a1-f-704','aplus1','acronym',4,'4.1',$$HA$$,$$High Availability - designing a service with redundancy and automatic failover so it keeps serving through the loss of a component. Purpose: cloud providers commit to it as an uptime percentage (for example 99.9%) in the SLA.$$),
('a1-f-705','aplus1','core',4,'4.1',$$The provider patches the operating system and runtime, but you still write and deploy the application. Which service model is that, and how do its neighbours differ?$$,$$PaaS. With IaaS you would also own the guest OS and runtime and have to patch them yourself; with SaaS you would write no application at all and would only configure a finished one, manage your users and control your data.$$),
('a1-f-706','aplus1','core',4,'4.1',$$How do you tell a community cloud from a private cloud?$$,$$A private cloud's pooled resources are dedicated to one organization. A community cloud is shared by several organizations that have the same regulatory, security or mission requirements, and they share its cost - but it is still closed to the general public, which is what separates it from public cloud.$$),
('a1-f-707','aplus1','core',4,'4.1',$$What does metered utilization mean, and how does it change IT budgeting?$$,$$Consumption is measured and billed per unit used - vCPU-hours, GB stored, GB transferred - so the invoice tracks actual usage. It converts a large up-front capital purchase into a variable operating expense that must be watched, because forgotten or idle resources keep billing.$$),
('a1-f-708','aplus1','core',4,'4.1',$$What does high availability mean for a cloud service, and how is it delivered?$$,$$The service keeps responding through the failure of a component. It is delivered with redundant instances spread across separate hosts or availability zones, load balancing and automatic failover. It is not a backup - replication faithfully copies deletions and corruption too.$$),
('a1-f-709','aplus1','core',4,'4.1',$$What problem does file synchronization solve?$$,$$It keeps the local copy on each device consistent with the cloud copy: an edit made on one device is uploaded and pushed out to the others, files stay usable offline, and queued changes upload automatically when the device reconnects.$$),
('a1-f-710','aplus1','core',4,'4.1',$$When would an organization choose cloud-hosted VDI over on-premises VDI?$$,$$When it does not want to buy and maintain host servers, or when the desktop count swings sharply (seasonal staff, contractors, project teams) so it needs to add and release desktops quickly and pay only while they exist. On-premises VDI wins when data must physically stay in-house or when dependence on the WAN link is unacceptable.$$),
('a1-f-711','aplus1','core',4,'4.1',$$In a public cloud, what does "shared resources" actually mean for your workload?$$,$$Your VMs run on physical hosts that also run other customers' VMs. Separation is logical - enforced by the hypervisor and virtual networking - not physical. Organizations that cannot accept that arrangement move to a private cloud or pay a premium for dedicated hosts.$$),
('a1-f-712','aplus1','core',4,'4.1',$$Rapid elasticity and metered utilization get confused constantly - what is the difference?$$,$$Elasticity is the capability: capacity scales up and back down automatically as demand changes. Metering is the accounting: consumption is measured per unit and billed. Elasticity is why the bill moves; metering is what moves it.$$),

-- ---------- 4.2 Client-side virtualization (14 core) ----------

('a1-f-713','aplus1','core',4,'4.2',$$A VM will not power on and the hypervisor reports that hardware-assisted virtualization is unavailable. What is the cause and the fix?$$,$$The CPU's virtualization extensions (Intel VT-x or AMD-V) are disabled in UEFI/BIOS, or the processor genuinely lacks them. Enter firmware setup, enable the extension, save and reboot. Without it the hypervisor cannot run 64-bit guests at all - this stops the VM from starting rather than making it slow.$$),
('a1-f-714','aplus1','core',4,'4.2',$$How much RAM can you safely assign to guest VMs on a workstation?$$,$$The memory assigned to all running guests plus the host OS's own requirement must fit within physical RAM. Over-allocating leaves the host paging to disk, so host and guest both crawl with constant disk activity. The fix is to lower the VM's assigned RAM or install more physical memory.$$),
('a1-f-715','aplus1','core',4,'4.2',$$Bridged, NAT and host-only virtual NIC modes - what does each one do?$$,$$Bridged: the VM is a peer on the physical LAN, leases its own address from the LAN DHCP server and is reachable inbound. NAT: the VM shares the host's address for outbound traffic and is not directly reachable from the LAN. Host-only: the VM talks only to the host and other host-only VMs, with no external network at all.$$),
('a1-f-716','aplus1','core',4,'4.2',$$How should a VM used to detonate suspicious software be configured?$$,$$Put it on a host-only or isolated virtual network, disable shared folders, clipboard sharing and drag-and-drop, take a clean snapshot before detonation and revert to it afterwards. Bridging it to the production LAN for monitoring would hand the sample a live path to every other machine.$$),
('a1-f-717','aplus1','core',4,'4.2',$$Thin versus thick provisioned virtual disks - what is the trade-off?$$,$$Thick reserves the full disk size on host storage immediately. Thin allocates only what is actually written and grows over time, so the combined maximum size of the virtual disks can exceed the physical volume. Thin saves space but demands monitoring: when the host volume fills, running VMs suspend or their disks go read-only.$$),
('a1-f-718','aplus1','core',4,'4.2',$$What is application virtualization, and how does it differ from running a VM?$$,$$It packages a single application with its dependencies so the app runs isolated from the local OS - often streamed to the client - without being installed on it. A VM instead virtualizes hardware and runs a whole guest operating system that must be separately licensed, patched and supported; application virtualization avoids that entire second OS.$$),
('a1-f-719','aplus1','core',4,'4.2',$$Why keep a legacy application in a VM rather than on its original physical PC?$$,$$The original hardware and its drivers eventually fail and cannot be replaced. A VM reproduces the obsolete environment on current hardware, exists as a file that can be backed up and snapshotted, and can have its network access restricted - which matters because the unsupported OS receives no more security patches.$$),
('a1-f-720','aplus1','core',4,'4.2',$$What does cross-platform virtualization let you do that multi-boot does not?$$,$$Run guests from a different OS family than the host - Windows and Linux guests on a macOS workstation, for instance - concurrently, switching between them instantly and moving data between them. Multi-boot also provides several operating systems, but only one runs at a time and every switch costs a reboot.$$),
('a1-f-721','aplus1','core',4,'4.2',$$Does a guest VM need its own licence, patches and antimalware?$$,$$Yes. Each guest is a complete, separate OS installation, so it must be licensed, patched and protected independently. Nothing about the host's patch level or antimalware reaches inside the guest, and an unpatched guest on a bridged adapter is exposed on the network exactly like a physical machine.$$),
('a1-f-722','aplus1','core',4,'4.2',$$What is a VM escape, and how is the risk reduced?$$,$$An exploit that breaks the hypervisor's isolation so code running in a guest reaches the host or another guest. Reduce it by keeping the hypervisor patched, disabling unnecessary host-guest integration (shared folders, clipboard, drag-and-drop), and running untrusted guests on isolated virtual networks.$$),
('a1-f-723','aplus1','core',4,'4.2',$$One guest VM is very slow while the host and the other guests perform normally. What do you check?$$,$$That guest's own allocation: too few vCPUs or too little assigned RAM, a virtual disk sitting on a slow or nearly full volume, and whether the hypervisor's guest tools/drivers are installed - without them the guest falls back to generic emulated video and disk drivers and feels sluggish. A host-wide shortage would slow everything, not one guest.$$),
('a1-f-724','aplus1','core',4,'4.2',$$What is a VM snapshot good for, and what is it not?$$,$$It captures the VM's state at a point in time so you can roll back instantly after a bad patch or a failed test. It is not a backup: it lives on the same host storage as the VM, is lost if that host is lost, and long snapshot chains consume space and degrade the VM's disk performance.$$),
('a1-f-725','aplus1','core',4,'4.2',$$Besides the virtual disk file, what else consumes host storage for each VM?$$,$$Snapshot delta files, the suspend/saved-state file (roughly the size of the RAM assigned to that guest), the guest's own paging file inside its disk, and any ISO images retained for installs. A VM with a 60 GB virtual disk can occupy far more than 60 GB on the host once snapshots exist.$$),
('a1-f-726','aplus1','core',4,'4.2',$$A VM has no network connectivity at all. What is the checklist?$$,$$Confirm the virtual NIC is present, enabled and marked connected in the VM settings; confirm the network mode matches the need (host-only cannot reach the LAN); confirm the guest holds a valid IP rather than an APIPA 169.254.x.x address; and confirm the host's physical adapter used for bridging is up. Then test from inside the guest with ipconfig/ifconfig and ping.$$);
