-- CISSP Domain 1 (Security and Risk Management) expansion, part A of 4 (siblings d1b/d1c/d1d
-- cover the rest of the domain). Adds objectives 1.1 (ethics), 1.2 (CIA triad/foundational
-- concepts), 1.3 (security governance), and a genuinely new 1.4 lane (compliance and regulatory
-- framework alignment: determining applicable requirements, compliance program structure, audit
-- readiness) distinct from the 5 legacy 1.4 rows (ci-f-072, ci-f-077, ci-q-006, ci-q-060,
-- ci-q-066), which are known BIA/BCP/vendor-risk mistags left untouched pending a separate review.
--   questions:   ci-q-200 .. ci-q-243 (44 items: 1.1=12, 1.2=12, 1.3=7, 1.4=13)
--   flashcards:  ci-f-200 .. ci-f-238 (39 core), ci-a-100 .. ci-a-105 (6 acronym),
--                ci-y-050 .. ci-y-057 (8 feynman) = 53 items (1.1=14, 1.2=15, 1.3=9, 1.4=15)

-- ============================================================================
-- QUESTIONS
-- ============================================================================

insert into public.questions (id, cert, domain, objective, qtype, difficulty, stem, choices, answer, explanation) values

-- ---------------------------------------------------------------- 1.1 (12) --
('ci-q-200','cissp',1,'1.1','mcq',1,$q$What is the correct order of precedence for the four canons of the ISC2 Code of Ethics when they conflict?$q$,$q$["Protect society, the common good, public trust, and infrastructure; then act honorably, honestly, justly, responsibly, and legally; then provide diligent and competent service to principals; then advance and protect the profession","Advance and protect the profession; then provide diligent and competent service to principals; then act honorably, honestly, justly, responsibly, and legally; then protect society, the common good, public trust, and infrastructure","Provide diligent and competent service to principals; then protect society, the common good, public trust, and infrastructure; then act honorably, honestly, justly, responsibly, and legally; then advance and protect the profession","All four canons carry equal weight and are balanced case by case with no fixed order"]$q$::jsonb,'0'::jsonb,$q$The canons are a strict hierarchy, not a balancing test: protecting society and the public trust always outranks duty to principals, which outranks the profession's collective standing. A lower canon can never justify violating a higher one, which is precisely why the order exists - to give practitioners a clear tiebreaker instead of weighing competing duties equally.$q$),

('ci-q-201','cissp',1,'1.1','mcq',2,$q$A security consultant's client asks them to overstate the maturity of the client's security posture in a report intended for the client's board, specifically to help secure additional budget approval next quarter. Complying with this request most directly violates which canon?$q$,$q$["Act honorably, honestly, justly, responsibly, and legally","Advance and protect the profession","Provide diligent and competent service to principals","Protect society, the common good, public trust, and infrastructure"]$q$::jsonb,'0'::jsonb,$q$Deliberately misrepresenting findings in a report is dishonesty in the practitioner's own conduct - a direct breach of acting honorably and honestly. It is not primarily a Canon I issue (no harm to society or infrastructure is described), and it does not injure the profession's broader reputation (Canon IV) or fail the client's interests (Canon III) the way it corrupts the practitioner's personal integrity.$q$),

('ci-q-202','cissp',1,'1.1','mcq',1,$q$A security consultant discovers unrelated evidence of a colleague's ISC2 Code of Ethics violation during an unrelated engagement. Under ISC2 policy, who is eligible to file a complaint about it?$q$,$q$["Only another ISC2 certified member may file the complaint","Only the colleague's direct manager may file the complaint","Any person, certified or not, who believes a violation occurred may file a complaint","Only ISC2 staff may initiate a complaint"]$q$::jsonb,'2'::jsonb,$q$Ethics complaints are not restricted to fellow certified members - any person who believes an ISC2 certified or associate member has violated the Code may submit a written complaint to ISC2 for review. Restricting complaints to managers, peers, or staff only would let violations affecting non-members go unreported.$q$),

('ci-q-203','cissp',1,'1.1','mcq',1,$q$Which of the following is NOT a possible outcome of a substantiated ISC2 ethics complaint against a certified member?$q$,$q$["A private reprimand","Suspension of certification","Automatic criminal prosecution initiated directly by ISC2","Revocation of certification and membership"]$q$::jsonb,'2'::jsonb,$q$ISC2 is a certifying body, not a law enforcement or prosecutorial authority - it can sanction the credential itself (reprimand, suspension, revocation) but cannot itself bring criminal charges. Criminal prosecution, if warranted, is a matter for courts and law enforcement, not an automatic consequence of an ISC2 ethics finding.$q$),

('ci-q-204','cissp',1,'1.1','mcq',2,$q$A CISSP's employer maintains an internal code of conduct that is silent on a situation where following the employer's direct instruction would violate Canon I of the ISC2 Code of Ethics. What should the CISSP do?$q$,$q$["Follow the employer's instruction since no internal policy explicitly forbids it","Follow the ISC2 Code of Ethics, since adherence to it is a condition of certification regardless of what the employer's internal policy does or does not say","Do nothing until the employer updates its code of conduct to address the situation","Resign immediately without attempting to escalate or resolve the conflict"]$q$::jsonb,'1'::jsonb,$q$Strict adherence to the ISC2 Code of Ethics is a condition of holding the certification; it is not contingent on, or overridden by, silence or gaps in an employer's own internal policy. The CISSP must follow the Code regardless, though escalation before resignation is generally the more constructive first step.$q$),

('ci-q-205','cissp',1,'1.1','multi',2,$q$Select the TWO scenarios that most directly violate Canon IV of the ISC2 Code of Ethics ("advance and protect the profession").$q$,$q$["Submitting a plagiarized case study under your own name to claim Continuing Professional Education (CPE) credit","Publicly asserting, without evidence, that all industry security certifications including CISSP are worthless in order to promote a competing credential","Declining a client engagement that falls outside your area of competence","Encouraging a junior analyst to pursue an ISC2 certification"]$q$::jsonb,$q$[0,1]$q$::jsonb,$q$Plagiarizing for CPE credit corrupts the integrity of the certification body's own continuing-education system, and baselessly disparaging the entire certification field damages public confidence in the profession - both directly injure the profession's standing, which Canon IV protects. Declining out-of-scope work is actually the diligent, competent choice (Canon III), and encouraging certification pursuit strengthens the profession rather than harming it.$q$),

('ci-q-206','cissp',1,'1.1','ordering',2,$q$Order these steps of the ISC2 ethics complaint process from first to last.$q$,$q$["A written complaint alleging a Code of Ethics violation is submitted to ISC2","The complaint is reviewed for sufficiency and the accused member is notified","The accused member is given an opportunity to respond","A determination is made and, if substantiated, a sanction up to revocation may be applied"]$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$The process begins with a written complaint, moves to an initial sufficiency review with notice to the accused, then affords the accused an opportunity to respond before any determination, and only then concludes with a decision and, if warranted, a sanction. Skipping notice or the chance to respond would deny the accused member due process.$q$),

('ci-q-207','cissp',1,'1.1','matching',2,$q$Match each ISC2 Code of Ethics canon to the situation that best exemplifies a violation of it.$q$,$q${"left":["Canon I - Protect society, the common good, public trust, and infrastructure","Canon II - Act honorably, honestly, justly, responsibly, and legally","Canon III - Provide diligent and competent service to principals","Canon IV - Advance and protect the profession"],"right":["Fabricating test results in a report to make a colleague's contribution look inadequate","Falsely advertising an expired CISSP certification as currently active to win new clients","Concealing a vulnerability that endangers public safety to avoid delaying a product launch","Accepting an assessment engagement in a specialized ICS environment with no relevant experience and no attempt to gain it"]}$q$::jsonb,$q$[2,0,3,1]$q$::jsonb,$q$Canon I is violated by concealing a public-safety risk to protect a launch date. Canon II is violated by fabricating results - dishonest personal conduct. Canon III is violated by taking on work outside one's competence, since it fails the duty of diligent, competent service to the principal. Canon IV is violated by falsely advertising an expired certification, which deceives clients and erodes trust in the certification itself.$q$),

('ci-q-208','cissp',1,'1.1','mcq',3,$q$A CISSP consultant is halfway through a paid penetration test when the client instructs them to stop testing the production billing system immediately, because a critical unpatched vulnerability was just discovered there and the client fears further testing could cause an outage during a peak sales period. The vulnerability poses no immediate risk to the public. What should the CISSP do?$q$,$q$["Continue testing the billing system regardless of the client's instruction, since Canon III always requires completing the full agreed scope","Honor the client's instruction to pause testing on that system, since doing so does not conflict with Canon I and reasonably serving the client's legitimate operational concern is consistent with diligent, competent service under Canon III","File an ISC2 ethics complaint against the client for interfering with the engagement","Continue testing but do not tell the client, to avoid an uncomfortable conversation"]$q$::jsonb,'1'::jsonb,$q$Honoring a reasonable, availability-motivated client instruction that creates no risk to the public or infrastructure is fully consistent with diligent service to the principal under Canon III - nothing here triggers Canon I, since no one outside the client is endangered. Insisting on completing scope over the client's legitimate objection, filing a baseless ethics complaint, or secretly continuing against instructions (itself a Canon II honesty violation) are all worse choices.$q$),

('ci-q-209','cissp',1,'1.1','mcq',1,$q$Which of the following is explicitly emphasized in the ISC2 Code of Ethics Preamble as an obligation of certified professionals, in addition to strict adherence to the Code itself?$q$,$q$["Being seen to adhere to the highest ethical standards of behavior, not merely adhering to them privately","Achieving a minimum number of billable hours per year","Publishing at least one security research paper annually","Working exclusively for principals located in the practitioner's home country"]$q$::jsonb,'0'::jsonb,$q$The preamble ties the obligation specifically to being seen to adhere to high ethical standards, not only to privately complying with them - visible, demonstrable ethical conduct is part of maintaining public trust in the profession, not just an internal state of mind.$q$),

('ci-q-210','cissp',1,'1.1','mcq',2,$q$An ISC2 member's employer maintains its own organizational code of ethics that conflicts with the ISC2 Code of Ethics on a matter directly implicating Canon I (protecting the public). Which statement correctly describes the relationship between the two codes in this situation?$q$,$q$["The organizational code always controls because it governs day-to-day employment","The ISC2 Code of Ethics still governs the member's certification standing, and adherence to it cannot be waived by an employer's conflicting internal policy","Neither code applies once any conflict exists between them","The member may simply choose whichever code they personally find more convenient"]$q$::jsonb,'1'::jsonb,$q$The ISC2 Code of Ethics is a condition of certification and takes precedence over an employer's internal code where the two genuinely conflict, especially where Canon I (protecting society and the public) is implicated - an organization cannot contractually waive a certified individual's ethical obligations to the certifying body.$q$),

('ci-q-211','cissp',1,'1.1','mcq',3,$q$A CISSP publicly and truthfully discloses, through appropriate channels, that a former employer knowingly shipped software with a critical unpatched vulnerability that endangered customer safety, after internal escalation was ignored. The disclosure damages the former employer's reputation. Under the ISC2 Code of Ethics, how should this disclosure be characterized?$q$,$q$["A violation of Canon III, because it harms a former principal","Consistent with Canon I, since protecting society, the common good, and public trust and confidence takes precedence over the interests of any single principal once internal escalation has failed","A violation of Canon IV, because it embarrasses the security profession","Prohibited in all cases regardless of circumstances, since practitioners must never discuss a former employer publicly"]$q$::jsonb,'1'::jsonb,$q$Canon I outranks Canon III: when protecting the public from real, unaddressed harm conflicts with the interests of a principal (even a former employer), the higher-ranked canon governs. A truthful, appropriately channeled disclosure after failed internal escalation is consistent with, not a violation of, the Code - reputational harm to the entity that created the danger is a consequence of its own conduct, not of the disclosure.$q$),

-- ---------------------------------------------------------------- 1.2 (12) --
('ci-q-212','cissp',1,'1.2','mcq',1,$q$A company encrypts customer records both in its database and while they travel across the network. Which CIA triad goal is this primarily protecting?$q$,$q$["Availability","Confidentiality","Integrity","Non-repudiation"]$q$::jsonb,'1'::jsonb,$q$Encryption at rest and in transit restricts who can read the data's contents even if it is intercepted or accessed without authorization - that is the definition of confidentiality. It does not by itself keep the system reachable (availability) or detect unauthorized changes (integrity).$q$),

('ci-q-213','cissp',1,'1.2','mcq',1,$q$A file transfer system computes and compares a SHA-256 checksum before and after transmission to detect any corruption or tampering. Which CIA triad goal does this primarily support?$q$,$q$["Confidentiality","Availability","Integrity","Authenticity"]$q$::jsonb,'2'::jsonb,$q$Comparing checksums detects whether the data changed in transit, which is exactly what integrity protects - accuracy and completeness of the data. A hash alone says nothing about who could read the file (confidentiality) or whether it reached its destination on time (availability), and it does not by itself prove who sent it (authenticity).$q$),

('ci-q-214','cissp',1,'1.2','mcq',2,$q$An e-commerce site adds redundant database replicas across two data centers and auto-scaling web servers so the site stays reachable during a traffic surge. Which CIA triad goal is this primarily addressing?$q$,$q$["Integrity","Confidentiality","Availability","Non-repudiation"]$q$::jsonb,'2'::jsonb,$q$Redundancy and auto-scaling exist to keep the system reachable and responsive to authorized users under load - the definition of availability. Neither measure changes who can read the data (confidentiality) or whether the data itself is accurate (integrity).$q$),

('ci-q-215','cissp',1,'1.2','mcq',2,$q$A ransomware attack encrypts a hospital's patient record database, making it completely inaccessible to clinical staff, though no data is exfiltrated or altered. In DAD terms, what failure mode does this represent?$q$,$q$["Disclosure","Alteration","Denial","All three equally"]$q$::jsonb,'2'::jsonb,$q$Nothing was viewed by an unauthorized party (no disclosure) and nothing was changed in a way the attacker profits from directly (limited alteration relevance here since the data itself is unread, just locked); the defining harm is that authorized users can no longer access the data at all - a denial, the direct opposite of availability.$q$),

('ci-q-216','cissp',1,'1.2','mcq',2,$q$An employee receives a contract that appears to be digitally signed by the CFO and later disputes ever approving it, but the signature can be cryptographically verified as having been created with the CFO's private key at the claimed time. Which security property is being demonstrated?$q$,$q$["Confidentiality","Availability","Non-repudiation","Least privilege"]$q$::jsonb,'2'::jsonb,$q$Non-repudiation means a party cannot credibly deny having performed an action; a verifiable digital signature tied to the CFO's private key provides strong evidence attributing the approval to that specific individual, defeating the later denial. Confidentiality and availability are unrelated to proving who took an action, and least privilege concerns access scope, not attribution.$q$),

('ci-q-217','cissp',1,'1.2','mcq',3,$q$A message is intercepted and its digest is recomputed by the recipient, matching the digest sent with the message. However, the message was never actually sent by the claimed originator - an attacker fabricated both the message and a valid digest for it. What does this scenario demonstrate?$q$,$q$["Integrity was preserved and authenticity was also achieved","Integrity was preserved, but authenticity was NOT achieved, since a matching hash alone does not prove who created the message","Neither integrity nor authenticity applies to hashed messages","This scenario is impossible because a hash always proves who sent a message"]$q$::jsonb,'1'::jsonb,$q$A hash only proves internal consistency - that the message received matches what the hash was computed over. Anyone, including an attacker, can compute a valid hash for content they fabricated. Authenticity requires binding the hash (or the message) to a verified identity, typically via a digital signature using the true sender's private key, which is absent here.$q$),

('ci-q-218','cissp',1,'1.2','multi',2,$q$Select the TWO controls that primarily support the AVAILABILITY leg of the CIA triad.$q$,$q$["Full-disk encryption of laptop hard drives","RAID 10 storage with automatic failover","Load-balanced, auto-scaling web server clusters","Role-based access control restricting who can view a file"]$q$::jsonb,$q$[1,2]$q$::jsonb,$q$RAID with automatic failover and load-balanced auto-scaling clusters both exist to keep a resource reachable and responsive under normal and adverse conditions - the definition of availability. Full-disk encryption protects confidentiality, and role-based access control primarily protects confidentiality (and indirectly integrity) by restricting who can view or change data, not by keeping systems reachable.$q$),

('ci-q-219','cissp',1,'1.2','ordering',2,$q$A public-facing web server is targeted by a volumetric flood of junk traffic. Order the following stages of the resulting incident from first to last.$q$,$q$["An attacker directs a botnet to flood the server with traffic far exceeding its capacity","Legitimate user requests are queued or dropped because the server's resources are exhausted","Customers are unable to reach the website during checkout","The business experiences lost sales and reports the incident as an availability failure"]$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$The chain runs from cause to business impact: the flood consumes server capacity, which crowds out legitimate requests, which prevents customers from completing checkout, which ultimately produces the measurable business loss that gets classified and reported as an availability failure.$q$),

('ci-q-220','cissp',1,'1.2','mcq',1,$q$Which of the following best distinguishes "privacy" from "confidentiality" as security concepts?$q$,$q$["They are identical concepts with different names","Confidentiality restricts disclosure of information generally; privacy specifically concerns an individual's rights over their own personal data, including how it may be used, not just who can see it","Privacy only applies to government data, while confidentiality applies to corporate data","Confidentiality is a legal concept and privacy is a technical control"]$q$::jsonb,'1'::jsonb,$q$Confidentiality is a general security objective about limiting disclosure of any information to unauthorized parties. Privacy is narrower and specifically about an individual's rights over their own personal data - collection, use, sharing, and retention - and can be violated even when confidentiality is technically intact, such as when data is used for a purpose the individual never consented to.$q$),

('ci-q-221','cissp',1,'1.2','matching',2,$q$Match each foundational security concept to the scenario that best illustrates it.$q$,$q${"left":["Confidentiality","Integrity","Availability","Non-repudiation"],"right":["A geographically distributed CDN keeps a news site loading quickly even during a traffic spike","A signed audit log entry proves a specific administrator, and no one else, executed a given command","A database field is protected so that only encrypted, authorized queries can read its contents","A financial ledger uses cryptographic hash chaining so any retroactive edit to a past entry is immediately detectable"]}$q$::jsonb,$q$[2,3,0,1]$q$::jsonb,$q$Confidentiality is illustrated by restricting who can read the database field. Integrity is illustrated by the hash-chained ledger, which reveals retroactive tampering. Availability is illustrated by the CDN keeping the site reachable under load. Non-repudiation is illustrated by the signed log entry, which attributes an action to one specific administrator beyond credible denial.$q$),

('ci-q-222','cissp',1,'1.2','mcq',3,$q$A hospital's infusion pump is compromised, causing it to deliver an incorrect medication dose to a patient without triggering any alarm. Beyond the direct integrity failure of the corrupted dosage data, which additional foundational security concept introduced in the ISC2 2024 outline is most directly implicated?$q$,$q$["Non-repudiation","Safety","Availability","Accountability"]$q$::jsonb,'1'::jsonb,$q$Safety is implicated because the compromise causes physical harm to a person, not just a data-integrity problem - a category of impact the 2024 outline explicitly calls out alongside confidentiality, integrity, and availability, particularly relevant to OT, medical devices, and industrial control systems.$q$),

('ci-q-223','cissp',1,'1.2','mcq',2,$q$A company requires every privileged administrator to log in through named individual accounts rather than a shared "admin" account, and every action taken under that account is recorded with a timestamp and user ID. What security property does this primarily enable?$q$,$q$["Availability of the administrative interface","Accountability - actions can be traced back to a specific individual","Confidentiality of the administrator's credentials","Physical safety of hospital patients"]$q$::jsonb,'1'::jsonb,$q$Eliminating shared accounts and logging per-user actions is exactly what accountability requires: tying every action to a specific identity so responsibility can be assigned. It does not primarily concern uptime, password secrecy, or physical harm; it may also support non-repudiation as a byproduct, but the property directly demonstrated here is accountability.$q$),

-- ---------------------------------------------------------------- 1.3 (7) --
('ci-q-224','cissp',1,'1.3','mcq',1,$q$What is the primary purpose of a security governance (steering) committee?$q$,$q$["To perform hands-on penetration testing of production systems","To set security strategy, approve major risk and policy decisions, and keep the security program aligned with business priorities","To write all technical firewall rules directly","To replace the need for a CISO"]$q$::jsonb,'1'::jsonb,$q$A governance committee is a cross-functional, executive-level body that sets direction, approves policy and major risk decisions, and ensures the security program stays resourced and aligned with the business - not a hands-on technical team performing testing or writing firewall rules, and not a substitute for the CISO's operational leadership.$q$),

('ci-q-225','cissp',1,'1.3','mcq',2,$q$A newly appointed CISO wants security investment decisions to be driven by the organization's actual revenue-generating processes and strategic goals, rather than by whichever technology happens to be trending. Which governance principle is the CISO applying?$q$,$q$["Least privilege","Separation of duties","Alignment of the security function with business strategy and objectives","Defense in depth"]$q$::jsonb,'2'::jsonb,$q$Tying security investment to the organization's actual mission and revenue-critical processes, rather than to trends, is the definition of aligning the security function with business strategy and objectives - a core governance principle distinct from access-control concepts like least privilege and separation of duties, or the architectural concept of defense in depth.$q$),

('ci-q-226','cissp',1,'1.3','mcq',2,$q$During due diligence for an acquisition, the security team discovers the target company has an undisclosed history of a prior data breach and several systems that have never been patched. What is the MOST direct governance value of surfacing this before the deal closes?$q$,$q$["It allows the acquiring company to factor undisclosed risk and remediation cost into deal valuation, negotiate terms, or walk away, rather than inheriting unknown liability after close","It guarantees the target company will be fined by regulators","It has no effect on the transaction since IT issues are unrelated to deal value","It obligates the acquiring company to publicly disclose the finding immediately"]$q$::jsonb,'0'::jsonb,$q$Security due diligence in M&A exists precisely so undisclosed risk becomes known before the deal closes, letting the acquirer price it into the valuation, negotiate indemnification, or reconsider the deal - rather than silently inheriting the liability, remediation cost, and reputational exposure the moment the acquisition completes.$q$),

('ci-q-227','cissp',1,'1.3','mcq',1,$q$In a well-governed organization, who is typically accountable for classifying a given dataset and deciding which roles should be granted access to it?$q$,$q$["The security operations center analyst on duty","The data owner, typically a business-unit leader accountable for that data","The network engineer who manages the firewall","Whichever employee created the data most recently, regardless of role"]$q$::jsonb,'1'::jsonb,$q$The data owner - usually a business-unit leader who understands the data's business value and sensitivity - is accountable for classification and access decisions, while the security team implements the technical controls that carry those decisions out. Classification decisions are not delegated to whoever happens to be on shift or created the file.$q$),

('ci-q-228','cissp',1,'1.3','multi',2,$q$Select the TWO statements that correctly describe the board of directors' role in security governance.$q$,$q$["The board is responsible for personally configuring technical security controls","The board sets overall risk appetite and provides oversight of whether management has an effective security program","The board delegates day-to-day security execution to management (e.g., the CISO) while retaining ultimate accountability","The board has no legal or reputational exposure related to cybersecurity oversight"]$q$::jsonb,$q$[1,2]$q$::jsonb,$q$The board's role is oversight and accountability, not hands-on technical work: it sets risk appetite and monitors whether management runs an effective program, while delegating execution to management. Boards increasingly do carry legal and reputational exposure for cybersecurity oversight failures, contrary to the claim that they have none.$q$),

('ci-q-229','cissp',1,'1.3','ordering',3,$q$Order these steps of building an organization's security governance program from first to last, starting with the foundational step.$q$,$q$["Obtain executive/board sponsorship and establish a governance committee","Define security strategy and objectives aligned with business goals","Select and adopt a control framework (e.g., ISO 27001, NIST CSF) to structure the program","Assign accountable roles (data owners, control owners) and begin implementing and auditing against the framework"]$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$Governance starts with sponsorship and a committee empowered to make decisions, which then defines strategy aligned to the business, which is structured using a recognized control framework, and is finally operationalized by assigning accountable owners and beginning implementation and audit. Skipping sponsorship or strategy and jumping straight to a framework produces a program with no direction or authority behind it.$q$),

('ci-q-230','cissp',1,'1.3','mcq',3,$q$A company's security program has strong technical controls, but no executive sponsorship, no documented risk appetite, and security decisions are made independently by whichever engineer happens to be available that day, with no consistent framework. An external auditor is MOST likely to characterize this as a deficiency in which area?$q$,$q$["Encryption strength","Security governance - the program lacks structured oversight, accountability, and alignment with a recognized framework, regardless of individual technical control quality","Network segmentation","Password complexity requirements"]$q$::jsonb,'1'::jsonb,$q$Strong individual technical controls do not compensate for the absence of oversight, documented risk appetite, and consistent decision-making structure - that gap is a governance deficiency, not a technical one, and it is exactly what security governance frameworks exist to prevent.$q$),

-- ---------------------------------------------------------------- 1.4 (13) --
('ci-q-231','cissp',1,'1.4','mcq',1,$q$A retail company begins accepting credit card payments online for the first time. Which compliance obligation does this action most directly and immediately trigger?$q$,$q$["HIPAA","PCI DSS","FedRAMP","SOX"]$q$::jsonb,'1'::jsonb,$q$Storing, processing, or transmitting cardholder data triggers PCI DSS obligations regardless of industry or company size. HIPAA applies to health information, FedRAMP to cloud services sold to federal agencies, and SOX to internal controls over financial reporting at public companies - none of which is triggered simply by accepting card payments.$q$),

('ci-q-232','cissp',1,'1.4','mcq',2,$q$A cloud hosting company signs a contract to process protected health information on behalf of a hospital system. Under HIPAA, what document must the hosting company sign to formally accept its resulting compliance obligations?$q$,$q$["A Data Processing Addendum specific to GDPR","A Business Associate Agreement (BAA)","A Service Level Agreement covering only uptime","A PCI DSS Attestation of Compliance"]$q$::jsonb,'1'::jsonb,$q$A Business Associate Agreement is the HIPAA-specific contract that binds a third party handling protected health information on a covered entity's behalf to HIPAA's safeguard and breach-notification obligations. A GDPR DPA, an uptime SLA, and a PCI DSS attestation each address a different regulatory regime entirely.$q$),

('ci-q-233','cissp',1,'1.4','mcq',2,$q$An organization implements one encryption-at-rest control and documents that it simultaneously satisfies relevant requirements from PCI DSS, HIPAA, and an internal ISO 27001-aligned control catalog. What compliance practice does this represent?$q$,$q$["Risk avoidance","A control framework crosswalk/harmonization mapping one control to multiple obligations","Risk transference via insurance","Segregation of duties"]$q$::jsonb,'1'::jsonb,$q$Mapping a single implemented control to the equivalent requirements in several different frameworks or regulations - so it only has to be built, operated, and evidenced once - is a control crosswalk or harmonization exercise, a core compliance-program efficiency practice distinct from risk treatment concepts like avoidance or transference.$q$),

('ci-q-234','cissp',1,'1.4','mcq',2,$q$An organization's second line of defense (risk/compliance function) sets a policy requiring quarterly access reviews, and the first line (IT operations) performs those reviews. Whose job is it to independently verify that the reviews are actually being performed effectively?$q$,$q$["The first line, since they already perform the reviews","The second line, since they wrote the policy","The third line (internal audit), which independently assures that both the first and second lines are functioning as intended","No independent verification is required once a policy exists"]$q$::jsonb,'2'::jsonb,$q$The Three Lines model exists so each line is checked by the one after it: the first line owns and executes controls, the second line sets policy and monitors, and the third line - internal audit - independently assures the board that both prior lines are actually functioning, rather than any line grading its own work.$q$),

('ci-q-235','cissp',1,'1.4','mcq',1,$q$Which of the following is the best description of "audit readiness"?$q$,$q$["Waiting until an audit is scheduled before gathering any evidence of compliance","Maintaining an ongoing, organized inventory of controls, evidence, and control owners so compliance can be demonstrated to an auditor at any time","Hiring an external auditor to write the organization's policies for it","Passing every audit with zero findings, regardless of remediation status"]$q$::jsonb,'1'::jsonb,$q$Audit readiness means the organization can demonstrate its compliance posture at any time without a last-minute scramble - a current control inventory, organized evidence, and named control owners maintained continuously. It is not about achieving a perfect zero-finding audit or letting the auditor author policy.$q$),

('ci-q-236','cissp',1,'1.4','mcq',3,$q$A cloud service provider wants to sell its product to multiple U.S. federal agencies without each agency independently re-assessing its security controls from scratch. Which program is designed to solve exactly this problem?$q$,$q$["SOC 2 Type II","FedRAMP","PCI DSS","COBIT"]$q$::jsonb,'1'::jsonb,$q$FedRAMP standardizes the security assessment, authorization, and continuous monitoring of cloud services for the U.S. federal government, so a single FedRAMP authorization can be reused across agencies instead of each one repeating a full independent assessment. SOC 2, PCI DSS, and COBIT each serve different audiences and purposes and were not built to solve federal cross-agency reuse.$q$),

('ci-q-237','cissp',1,'1.4','mcq',2,$q$A publicly traded company's compliance team requires documented change-management approvals and periodic access reviews specifically over systems that feed the general ledger and financial reporting process. Which regulatory driver is most directly responsible for this requirement?$q$,$q$["GDPR","PCI DSS","Sarbanes-Oxley (SOX) internal controls over financial reporting","FedRAMP"]$q$::jsonb,'2'::jsonb,$q$SOX requires public companies to maintain effective internal controls over financial reporting, including IT general controls like change management and access review specifically for systems that affect financial statement integrity. GDPR, PCI DSS, and FedRAMP each address different data types or customer bases and do not drive this particular financial-reporting control requirement.$q$),

('ci-q-238','cissp',1,'1.4','multi',2,$q$Select the TWO facts that correctly describe PCI DSS.$q$,$q$["It is a government-enacted law with criminal penalties for violation","It is a contractual security standard imposed by the payment card brands and acquiring banks","It applies to any organization that stores, processes, or transmits cardholder data, regardless of industry","It only applies to banks and payment processors, never to merchants"]$q$::jsonb,$q$[1,2]$q$::jsonb,$q$PCI DSS is contractual, not statutory - imposed by the card brands and acquiring banks through merchant agreements - and it applies broadly to any organization touching cardholder data, including ordinary merchants, not just banks or processors. It carries contractual penalties (fines, loss of card-acceptance privileges) rather than criminal ones.$q$),

('ci-q-239','cissp',1,'1.4','ordering',3,$q$Order these steps an organization follows to determine and operationalize its applicable compliance requirements, from first to last.$q$,$q$["Inventory the business's data types, industry sector, customer geography, and contractual relationships","Identify which specific laws, regulations, and contractual standards are triggered by that inventory","Map the resulting requirements onto a common control framework to identify overlaps and gaps","Assign control owners, remediate gaps, and establish ongoing monitoring and audit-readiness evidence collection"]$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$Determining compliance scope starts with an honest inventory of the business itself, which reveals which specific obligations actually apply, which are then mapped onto a common control framework to spot overlap and gaps, and finally operationalized through ownership, remediation, and ongoing monitoring. Selecting a framework before knowing what applies would build structure around the wrong requirements.$q$),

('ci-q-240','cissp',1,'1.4','mcq',1,$q$A compliance risk register lists a finding: "Quarterly privileged-access review required by SOX has not been performed for two consecutive quarters." What best describes this entry?$q$,$q$["An unrelated technical vulnerability with no compliance relevance","A tracked gap against a specific external obligation, with an implied need for a remediation owner and deadline","Evidence that SOX no longer applies to the organization","A finding that should be removed from the register once documented, with no further action needed"]$q$::jsonb,'1'::jsonb,$q$This is exactly what a compliance risk register exists to capture - a specific, named gap against an external obligation (SOX's access-review requirement), which needs an assigned owner and a remediation deadline until it is closed. Missing a control requirement does not mean the underlying regulation stopped applying, and documenting a gap is the start of remediation tracking, not the end of it.$q$),

('ci-q-241','cissp',1,'1.4','mcq',3,$q$A startup currently serves only domestic customers and handles no payment card or health data, so its compliance team determined no major sector-specific regulatory frameworks applied beyond baseline data-protection law. Six months later, the company begins accepting credit card payments and signs its first customers in the European Union. What is the MOST appropriate governance response?$q$,$q$["No action is needed since the original compliance determination was correct at the time it was made","Re-scope the compliance program now, since the new payment processing and EU customer base newly trigger PCI DSS and GDPR obligations that did not previously apply","Wait until the next scheduled annual compliance review, since interim changes do not require immediate action","Assume PCI DSS and GDPR do not apply until a regulator formally notifies the company"]$q$::jsonb,'1'::jsonb,$q$Compliance scoping is an ongoing exercise, not a one-time decision: material changes to the business - here, accepting cards and gaining EU customers - immediately change which obligations apply, and the program must be re-scoped as soon as the change happens rather than waiting for a scheduled review or a regulator's notice, which is not how applicability works.$q$),

('ci-q-242','cissp',1,'1.4','mcq',2,$q$What is the primary distinction between the responsibilities of a Chief Compliance Officer's function and a security team, even though both work closely together?$q$,$q$["The compliance function is exclusively responsible for firewall configuration","There is no meaningful distinction; the two terms describe the same role","The compliance function tracks adherence to external obligations across the whole business (legal, financial, privacy, operational), while security implements and operates the technical and procedural controls addressing the security-relevant subset of those obligations","Security teams have no role in supporting compliance objectives"]$q$::jsonb,'2'::jsonb,$q$Compliance has a business-wide scope - tracking legal, financial, privacy, and operational obligations, not just technical ones - while security is responsible for building and running the controls that satisfy the security-relevant portion of those obligations. The two functions coordinate closely, but neither is simply a duplicate of the other or excluded from the effort.$q$),

('ci-q-243','cissp',1,'1.4','mcq',2,$q$An organization completes a SOC 2 Type II audit covering the prior twelve months and receives a clean report with no exceptions. Two months later, a misconfigured cloud storage bucket exposes customer data. Which statement best explains why this is possible despite the clean audit?$q$,$q$["SOC 2 reports guarantee no future security incidents can occur","A point-in-time or period audit report reflects control effectiveness for the period reviewed; it does not guarantee controls remain effective indefinitely afterward, which is why continuous compliance monitoring is used to catch drift between audits","The auditor must have committed fraud if an incident occurred afterward","SOC 2 Type II reports do not evaluate operating effectiveness at all"]$q$::jsonb,'1'::jsonb,$q$A SOC 2 Type II report attests to control operating effectiveness during the period examined - it is a snapshot, not a forward-looking guarantee. Conditions and configurations can drift after the audit period closes, which is exactly the gap continuous compliance monitoring is meant to catch between formal audits rather than waiting for the next annual cycle to discover it.$q$);

-- ============================================================================
-- FLASHCARDS
-- ============================================================================

insert into public.flashcards (id, cert, deck, domain, objective, front, back) values

-- ---------------------------------------------------------------- 1.1 core (11) --
('ci-f-200','cissp','core',1,'1.1',$$What is the purpose of the ISC2 Code of Ethics Preamble?$$,$$It frames ethics as both a personal obligation and a visible, public commitment: the safety and welfare of society and the common good, and duty to principals and to each other, requires strict adherence - and being seen to adhere - to the highest ethical standards, making that adherence a condition of certification.$$),
('ci-f-201','cissp','core',1,'1.1',$$What does Canon II of the ISC2 Code of Ethics require, and what makes it distinct from Canon I?$$,$$Canon II: act honorably, honestly, justly, responsibly, and legally. It governs personal integrity in professional conduct - truthfulness, fairness, and legal compliance - whereas Canon I is specifically about protecting society, the public trust, and infrastructure from harm. A lie to a colleague breaches Canon II; concealing a threat to public safety breaches Canon I.$$),
('ci-f-202','cissp','core',1,'1.1',$$Who are the "principals" referenced in Canon III of the ISC2 Code of Ethics, and what must a CISSP provide them?$$,$$Principals are employers, clients, and the individuals and organizations that rely on the practitioner's professional judgment - broadly, anyone the practitioner serves. Canon III requires providing diligent and competent service to them: staying current, working within one's competence, and not overstating one's expertise.$$),
('ci-f-203','cissp','core',1,'1.1',$$What does Canon IV, "advance and protect the profession," obligate a CISSP to do or avoid?$$,$$Avoid actions that injure the reputation of the profession, such as misrepresenting certification status or unauthorized practice claims, and actively contribute to it through mentoring, sharing knowledge, and maintaining public confidence in the security profession as a whole.$$),
('ci-f-204','cissp','core',1,'1.1',$$If a CISSP's employer directs them to do something that breaches the ISC2 Code of Ethics, what should the CISSP do?$$,$$Refuse to comply and, if necessary, escalate or resign rather than violate the Code. Adherence to the Code is a condition of certification; an employer's instruction does not override it, and Canon I (protect society and the public trust) takes precedence over any internal directive that conflicts with it.$$),
('ci-f-205','cissp','core',1,'1.1',$$Who may file an ISC2 ethics complaint against a certified professional, and against whom?$$,$$Any person - not only other ISC2 members - may file a written complaint against any ISC2 certified or associate member believed to have violated the Code of Ethics. Complaints are submitted to ISC2 for review.$$),
('ci-f-206','cissp','core',1,'1.1',$$What is the general process ISC2 follows once an ethics complaint is filed?$$,$$The complaint is reviewed for sufficiency, the accused member is notified and given an opportunity to respond, and an ISC2 ethics review process determines whether the Code was violated and what action, if any, is warranted.$$),
('ci-f-207','cissp','core',1,'1.1',$$What sanctions can result from a substantiated ISC2 ethics violation?$$,$$Outcomes range from a private reprimand, to suspension, up to permanent revocation of certification and ISC2 membership - the certification is the practitioner's credential, and it can be withdrawn for a proven Code violation.$$),
('ci-f-208','cissp','core',1,'1.1',$$How does an organizational code of ethics relate to the ISC2 Code of Ethics when a CISSP's employer has its own code?$$,$$Both apply, but they are not equals: the ISC2 Code is a condition of certification and cannot be overridden by an employer's internal code. A CISSP follows the organization's code of conduct for day-to-day workplace behavior, but if the two ever conflict, adherence to the ISC2 Code - especially Canon I - still governs professional certification standing.$$),
('ci-f-209','cissp','core',1,'1.1',$$Why does claiming a CISSP certification you have not earned, or letting one lapse without disclosure, violate the ISC2 Code of Ethics?$$,$$It breaches Canon II (dishonesty) and Canon IV (advancing/protecting the profession) simultaneously - misrepresenting credentials deceives clients and employers about your competence and damages public trust in the certification itself, which is exactly the trust the Code exists to protect.$$),
('ci-f-210','cissp','core',1,'1.1',$$Does the ISC2 Code of Ethics apply only to actions taken in a professional capacity?$$,$$No - Canon I ties personal conduct to protecting the common good and public trust, so conduct seriously inconsistent with the Code, even outside a specific work engagement, can still be grounds for an ethics complaint.$$),

-- ---------------------------------------------------------------- 1.1 feynman (3) --
('ci-y-050','cissp','feynman',1,'1.1',$$Explain, with a concrete workplace example, how the four ISC2 Code of Ethics canons are meant to be applied in strict priority order rather than balanced against each other.$$,$$Model answer: The canons aren't weighed like a balancing test - they're a strict hierarchy: Canon I always outranks II, which outranks III, which outranks IV. Example: a CISSP discovers their employer is shipping a product with a known critical vulnerability that could harm end users' safety, and the employer (a principal, protected under Canon III) orders silence to protect the launch date. Canon III would say "serve the principal diligently," but Canon I - protect society, the common good, and public trust - sits above it. So the practitioner must escalate or disclose the risk even though it means disappointing or defying the employer, because a lower canon can never justify violating a higher one. The ranking exists specifically so a practitioner has a clear tiebreaker instead of being torn between conflicting duties.$$),
('ci-y-051','cissp','feynman',1,'1.1',$$Explain why the ISC2 ethics complaint process matters to the value of the CISSP credential itself, using an analogy.$$,$$Model answer: think of the CISSP credential like a professional license - a doctor's license means little if incompetent or fraudulent doctors keep it forever regardless of proven misconduct. The ethics complaint process is the enforcement mechanism that keeps the credential meaningful: anyone can file a complaint, the accused gets due process (notice and a chance to respond), and proven violations can lead to suspension or revocation. Without this enforcement, "CISSP" would just be a line on a resume with no guarantee behind it. The process protects the value of the certification for every other CISSP holder by keeping bad actors from carrying the same credential unchallenged.$$),
('ci-y-052','cissp','feynman',1,'1.1',$$Explain the difference between violating Canon II and violating Canon IV using two distinct examples.$$,$$Model answer: Canon II ("act honorably, honestly, justly, responsibly, and legally") is about how you personally conduct yourself - for example, falsifying a penetration test report to hide that you ran out of time is a Canon II violation: it's dishonest conduct in your own work. Canon IV ("advance and protect the profession") is about the reputation and standing of the security profession as a whole - for example, publicly and baselessly mocking the value of certifications to encourage clients to distrust all credentialed security professionals undermines the profession's credibility and is a Canon IV concern rather than a personal-honesty one. The two can overlap in a single act - a publicized fraud conviction hurts both your integrity (II) and the profession's image (IV) - but conceptually II is inward-facing conduct and IV is outward-facing stewardship of the field.$$),

-- ---------------------------------------------------------------- 1.2 core (11) --
('ci-f-211','cissp','core',1,'1.2',$$What does "confidentiality" mean in the CIA triad, and what is a primary mechanism used to enforce it?$$,$$Confidentiality means information is disclosed only to authorized parties. Enforced primarily through encryption (at rest and in transit) plus access controls that restrict who can view the data in the first place.$$),
('ci-f-212','cissp','core',1,'1.2',$$What does "integrity" mean in the CIA triad, and what is a primary mechanism used to enforce it?$$,$$Integrity means data is accurate, complete, and has not been altered in an unauthorized or undetected way. Enforced through hashing/checksums to detect changes, access controls to prevent unauthorized modification, and version control/change logs to track legitimate changes.$$),
('ci-f-213','cissp','core',1,'1.2',$$What does "availability" mean in the CIA triad, and what is a primary mechanism used to enforce it?$$,$$Availability means authorized users can access information and systems when needed. Enforced through redundancy (RAID, clustering), fault tolerance, capacity planning, and DDoS mitigation - anything that keeps a resource reachable and responsive under normal and adverse conditions.$$),
('ci-f-214','cissp','core',1,'1.2',$$What is the "DAD" triad, and how does it relate to CIA?$$,$$Disclosure, Alteration, and Denial - the direct opposites of Confidentiality, Integrity, and Availability. Where CIA describes the security goals, DAD describes the corresponding failure modes: a confidentiality breach is a disclosure, an integrity breach is an unauthorized alteration, and an availability breach is a denial.$$),
('ci-f-215','cissp','core',1,'1.2',$$What is non-repudiation, and why is it distinct from authentication?$$,$$Non-repudiation means a party cannot credibly deny having performed an action, such as sending a message or approving a transaction, typically proven with digital signatures and audit trails. Authentication proves who you are at login; non-repudiation proves, after the fact and often to a third party, that a specific action is attributable to that identity.$$),
('ci-f-216','cissp','core',1,'1.2',$$What is authenticity in the context of the extended CIA model, and how does it differ from integrity?$$,$$Authenticity means data or a message genuinely originates from the claimed source. Integrity means the content hasn't changed. A message can be unaltered (intact integrity) yet forged (fake origin, no authenticity) - digital signatures typically prove both together.$$),
('ci-f-217','cissp','core',1,'1.2',$$How does accountability complement the CIA triad?$$,$$Accountability ties actions back to individual identities through logging, auditing, and unique user IDs, so specific users can be held responsible for specific actions. It underpins non-repudiation and depends on strong authentication - without accountability, you can detect that something happened but not who did it.$$),
('ci-f-218','cissp','core',1,'1.2',$$Give an example of a trade-off between confidentiality and availability.$$,$$Requiring strong multi-step re-authentication or encryption key entry every time a user accesses a system improves confidentiality but can slow down or block legitimate access during time-critical situations, reducing availability - security decisions often balance these competing goals rather than maximizing all three simultaneously.$$),
('ci-f-219','cissp','core',1,'1.2',$$Why is "privacy" not simply a synonym for "confidentiality," even though both restrict who can see data?$$,$$Confidentiality is a security control objective about restricting disclosure generally. Privacy is specifically about an individual's rights over their own personal data - how it is collected, used, shared, and retained - and is often driven by law or regulation rather than by a security policy alone. Data can be kept perfectly confidential yet still be used in a way that violates privacy expectations.$$),
('ci-f-220','cissp','core',1,'1.2',$$What foundational concept did the ISC2 2024 CISSP outline add alongside confidentiality, integrity, and availability?$$,$$Safety - recognizing that some security failures, particularly in operational technology, medical devices, and industrial control systems, can cause physical harm to people, not just data loss. Security concepts now explicitly extend beyond information protection to protecting human life and physical well-being.$$),
('ci-f-221','cissp','core',1,'1.2',$$Why can a hash alone prove integrity but not authenticity?$$,$$A hash detects whether data changed, because any modification changes the digest - but anyone can compute a hash of any message, including an attacker who altered it. Without binding the hash to a verified identity (e.g., via a digital signature using the sender's private key), a matching hash only shows the data is internally consistent, not that it truly came from the claimed sender.$$),

-- ---------------------------------------------------------------- 1.2 acronym (2) --
('ci-a-100','cissp','acronym',1,'1.2',$$CIA (security)$$,$$Confidentiality, Integrity, Availability - the three foundational security objectives every control ultimately protects, often complemented by authenticity and non-repudiation.$$),
('ci-a-101','cissp','acronym',1,'1.2',$$DAD$$,$$Disclosure, Alteration, Denial - the triad of security failure modes, each the direct opposite of one CIA triad goal (confidentiality, integrity, and availability respectively).$$),

-- ---------------------------------------------------------------- 1.2 feynman (2) --
('ci-y-053','cissp','feynman',1,'1.2',$$Explain the difference between integrity and authenticity using a concrete scenario, and why you need both to fully trust a message.$$,$$Model answer: Imagine you receive an email that says "Wire $50,000 to this account" with a hash attached that matches the message exactly - integrity checks out, the message wasn't altered in transit. But the email was actually sent by an attacker who spoofed your CFO's address, not the CFO. Integrity only tells you the message you received is the same message that was sent - it says nothing about who sent it. Authenticity is the missing piece: it verifies the claimed sender is the real sender, typically through a digital signature that can only have been produced with the sender's private key. You need both together, because a perfectly intact, high-integrity message from a forged sender is just as dangerous as a genuine message that's been tampered with - a digital signature is popular precisely because it proves both properties at once.$$),
('ci-y-054','cissp','feynman',1,'1.2',$$Explain why "availability" is a security concern and not just an IT operations concern, using the DAD failure-mode framing.$$,$$Model answer: It's tempting to think denial-of-service and outages are purely reliability or ops problems, separate from confidentiality breaches or data tampering. But the DAD triad frames all three the same way: disclosure, alteration, and denial are simply the three ways an adversary or an accident can defeat a security objective. A ransomware attack that encrypts and withholds access to files is a denial - an availability failure - caused by a deliberate attacker, just as surely as data theft is a disclosure failure. Because an adversary can achieve the same business damage by blocking access instead of stealing or altering data, availability has to sit inside the security program, with its own risk assessments, controls, and incident response, rather than being treated as someone else's uptime problem.$$),

-- ---------------------------------------------------------------- 1.3 core (6) --
('ci-f-222','cissp','core',1,'1.3',$$What does it mean to align the security function with business strategy, goals, mission, and objectives?$$,$$Security decisions and investments are driven by what the business is trying to achieve, not treated as a stand-alone technical program. A security program aligned with strategy prioritizes controls that protect the organization's actual mission-critical processes and revenue drivers, and speaks to leadership in terms of business risk and objectives rather than pure technology.$$),
('ci-f-223','cissp','core',1,'1.3',$$What is a security governance (steering) committee, and what does it do?$$,$$A cross-functional body - typically including executives from IT, legal, HR, finance, and business units, chaired by or reporting to senior leadership - that sets security strategy, approves policy and major risk decisions, and ensures the security program stays aligned with business priorities and receives adequate resources.$$),
('ci-f-224','cissp','core',1,'1.3',$$What role does the board of directors typically play in security governance?$$,$$Ultimate oversight and accountability: the board sets risk appetite at the highest level, ensures management has an effective security program, and is increasingly held legally and reputationally accountable for cybersecurity oversight failures - even though day-to-day execution is delegated to management such as the CISO.$$),
('ci-f-225','cissp','core',1,'1.3',$$Why do security control frameworks such as COBIT, ISO/IEC 27001, and NIST CSF matter for governance, beyond providing a checklist of controls?$$,$$They give an organization a structured, repeatable, and defensible way to design, operate, and demonstrate its security program - enabling consistent decision-making, comparability across audits and assessments, and a common language between security, business leadership, regulators, and auditors, rather than an ad hoc, undocumented approach.$$),
('ci-f-226','cissp','core',1,'1.3',$$Why does a merger or acquisition require security due diligence before the deal closes?$$,$$The acquiring organization inherits the target's security posture, existing breaches and liabilities, technical debt, and compliance gaps along with its assets - security due diligence during M&A identifies undisclosed risks, such as a prior undetected breach or non-compliant systems, that could materially affect the deal's value or create post-acquisition liability.$$),
('ci-f-227','cissp','core',1,'1.3',$$What is the difference between a data owner and the security team in a governance model, and why does that separation matter?$$,$$The data owner, typically a business-unit leader, is accountable for classifying data and deciding who should have access to it, based on business need; the security team implements and enforces the technical controls that carry out those decisions. Separating the two ensures access decisions are made by people who understand the business value and risk of the data, while technical enforcement stays consistent and centrally managed.$$),

-- ---------------------------------------------------------------- 1.3 acronym (1) --
('ci-a-102','cissp','acronym',1,'1.3',$$COBIT$$,$$Control Objectives for Information and Related Technologies - an ISACA governance and management framework that helps align IT and security processes and controls to enterprise goals, widely used as a governance framework rather than a purely technical control catalog.$$),

-- ---------------------------------------------------------------- 1.3 feynman (2) --
('ci-y-055','cissp','feynman',1,'1.3',$$Explain why a CISO reporting directly to the CEO or board, rather than to the CIO, is often considered a governance best practice.$$,$$Model answer: If the CISO reports to the CIO, the person responsible for security is organizationally subordinate to the person responsible for IT operations and delivery speed - the same executive whose performance is often judged on uptime, project timelines, and cost, which can create pressure to deprioritize security findings that slow things down or cost money. There's an inherent conflict of interest: the CIO might be reluctant to escalate a security risk that reflects poorly on their own IT organization. Reporting directly to the CEO or board removes that filter - security risk gets escalated and discussed at the level where genuine business trade-offs are made, and the CISO's independence and authority to say "no" or "not yet" isn't subject to a boss whose incentives can point the other way.$$),
('ci-y-056','cissp','feynman',1,'1.3',$$Explain, using an example, why a security control framework provides more governance value than simply implementing whatever individual controls a security team thinks are good ideas.$$,$$Model answer: Imagine two companies both deploy firewalls, MFA, and encryption - but one did it by picking controls ad hoc based on what the security team read about, and the other mapped its program to a framework like NIST CSF or ISO 27001. When an auditor, regulator, cyber-insurance underwriter, or acquiring company asks how they know the security program is complete and appropriate, the ad hoc company can only say "trust us, we thought about it." The framework-aligned company can show exactly which framework categories are covered, which are partially covered, and which are accepted gaps with documented risk decisions - it's structured, comparable across time and against peers, and defensible to a third party. The value isn't that the framework's controls are technically superior; it's that governance requires demonstrating and justifying decisions to people who weren't in the room, and a framework is what makes that demonstration possible.$$),

-- ---------------------------------------------------------------- 1.4 core (11) --
('ci-f-228','cissp','core',1,'1.4',$$What does it mean for an organization to "determine" its compliance requirements, as distinct from simply knowing that laws and standards exist?$$,$$It means actively identifying which specific contractual, legal, regulatory, and industry-standard obligations actually apply to the organization, based on factors like industry sector, the type of data handled, customer base, and geographic footprint - rather than assuming a generic set of requirements. An organization that never processes payment cards has no PCI DSS obligation regardless of how well known that standard is.$$),
('ci-f-229','cissp','core',1,'1.4',$$What is the Three Lines (of Defense) model in compliance and risk governance?$$,$$First line: business and operational units that own and manage risk day-to-day, such as IT operating controls. Second line: risk management and compliance functions that set policy, monitor, and provide oversight independent of operations. Third line: internal audit, which independently assures the board that the first two lines are actually working. Each line checks the one before it.$$),
('ci-f-230','cissp','core',1,'1.4',$$What is a control framework crosswalk (or harmonization), and why do compliance programs use one?$$,$$A mapping that shows how a single set of implemented controls satisfies requirements from multiple regulations or standards simultaneously, such as one encryption-at-rest control mapped to relevant requirements in both PCI DSS and HIPAA. It lets an organization implement and evidence one control once instead of duplicating effort for every applicable framework separately.$$),
('ci-f-231','cissp','core',1,'1.4',$$What is the difference between continuous compliance monitoring and a point-in-time compliance audit?$$,$$A point-in-time audit or certification, such as an annual SOC 2 report, verifies controls were operating effectively during a specific period, then ages as conditions change. Continuous compliance monitoring uses automated checks and dashboards to verify controls are operating correctly on an ongoing basis, catching drift between formal audits rather than only discovering a gap once a year.$$),
('ci-f-232','cissp','core',1,'1.4',$$What does "audit readiness" mean for a compliance program, and what does it typically require maintaining?$$,$$Being able to demonstrate compliance to an auditor at any time without a scramble - typically requires a current control inventory mapped to requirements, an organized evidence repository (screenshots, logs, configuration exports, policy documents), named control owners, and a tracked remediation process for known gaps.$$),
('ci-f-233','cissp','core',1,'1.4',$$What triggers PCI DSS applicability for an organization?$$,$$Storing, processing, or transmitting cardholder data (payment card numbers), regardless of company size or industry. It is a contractual obligation imposed by the payment card brands and acquiring banks, not a government law, but non-compliance can mean losing the ability to accept card payments and incurring contractual fines.$$),
('ci-f-234','cissp','core',1,'1.4',$$What distinguishes a HIPAA covered entity from a business associate?$$,$$A covered entity (health plan, healthcare provider, healthcare clearinghouse) directly handles protected health information as part of delivering care or billing. A business associate is a third party that performs a function involving protected health information on the covered entity's behalf, such as a cloud hosting provider or billing vendor, and must sign a Business Associate Agreement accepting HIPAA obligations.$$),
('ci-f-235','cissp','core',1,'1.4',$$What is FedRAMP, and what compliance need does it address?$$,$$The Federal Risk and Authorization Management Program standardizes security assessment, authorization, and continuous monitoring for cloud service providers selling to U.S. federal agencies, so agencies can reuse a single FedRAMP authorization instead of every agency separately auditing the same cloud provider.$$),
('ci-f-236','cissp','core',1,'1.4',$$What does a compliance risk register track, and how does it differ from a general security risk register?$$,$$A compliance risk register tracks known gaps against specific regulatory, contractual, or industry-standard obligations, such as a missing quarterly access review required by SOX, including a remediation owner and deadline. A general security risk register is broader and includes any risk to confidentiality, integrity, or availability regardless of whether a specific external requirement mandates addressing it.$$),
('ci-f-237','cissp','core',1,'1.4',$$Why might mapping business requirements to applicable regulatory frameworks be described as an ongoing scoping exercise rather than a one-time decision?$$,$$As a business launches new products, enters new markets or geographies, adopts new data types, or acquires companies, its compliance obligations change - a company that starts accepting payment cards newly triggers PCI DSS, and one that starts serving EU residents newly triggers GDPR. Compliance scoping must be revisited whenever the business changes, not decided once at founding.$$),
('ci-f-238','cissp','core',1,'1.4',$$What is the role of a Chief Compliance Officer (or compliance function) relative to the security team?$$,$$The compliance function identifies which external obligations apply and tracks the organization's adherence to them across the whole business, including legal, financial, privacy, and operational compliance, not just IT. Security implements and operates the technical and procedural controls that help satisfy the security-relevant subset of those obligations; the two functions coordinate closely, but compliance's scope is broader than security's.$$),

-- ---------------------------------------------------------------- 1.4 acronym (3) --
('ci-a-103','cissp','acronym',1,'1.4',$$PCI DSS$$,$$Payment Card Industry Data Security Standard - a contractual security standard imposed by payment card brands on any entity that stores, processes, or transmits cardholder data.$$),
('ci-a-104','cissp','acronym',1,'1.4',$$FedRAMP$$,$$Federal Risk and Authorization Management Program - standardized security assessment and continuous monitoring for cloud services used by U.S. federal agencies, allowing reuse of a single authorization across agencies.$$),
('ci-a-105','cissp','acronym',1,'1.4',$$SOX$$,$$Sarbanes-Oxley Act - U.S. law requiring public companies to maintain effective internal controls over financial reporting, including IT general controls such as access management and change management that support the integrity of financial data.$$),

-- ---------------------------------------------------------------- 1.4 feynman (1) --
('ci-y-057','cissp','feynman',1,'1.4',$$Explain, with an example, why one organization might be subject to PCI DSS, HIPAA, and GDPR all at the same time, and how a compliance program handles that overlap without tripling its workload.$$,$$Model answer: Picture a healthcare telehealth company based in the US that also serves patients in the EU and lets patients pay their co-pay by credit card in the app. It's now a HIPAA covered entity because it handles protected health information, it's in PCI DSS scope because it processes cardholder data for the co-pay, and it's subject to GDPR because it processes personal data of EU residents - three completely different regimes triggered by three different facts about the same business. A mature compliance program doesn't build three separate parallel control sets; instead, it maps all three sets of requirements onto one underlying control framework - for example, its encryption-at-rest control satisfies a HIPAA safeguard, a PCI DSS requirement, and a GDPR Article 32 security obligation simultaneously, and that mapping (a crosswalk) is documented once. The workload isn't tripled because the compliance program is organized around controls that happen to satisfy multiple obligations, not around each regulation as a separate silo built from scratch.$$);
