-- Network+ (N10-009) Domain 1 (Networking Concepts) expansion, part A.
-- Tops up objectives 1.1, 1.2, 1.3 and 1.4 to 33 items each.
--   questions:   n-q-400 .. n-q-448  (49 items)
--   flashcards:  n-f-400 .. n-f-459  (60 items)
-- Objective split: 1.1 = 11q/14f, 1.2 = 13q/16f, 1.3 = 14q/16f, 1.4 = 11q/14f.
-- Objective 1.2 previously had flashcards only and no questions at all; it now
-- receives a full question set so it can be drawn by quiz and exam forms.

-- ============================================================================
-- QUESTIONS
-- ============================================================================

insert into public.questions (id, cert, domain, objective, qtype, difficulty, stem, choices, answer, explanation) values

-- ---------------------------------------------------------------- 1.1 (11) --
('n-q-400','netplus',1,'1.1','mcq',1,$q$A packet capture is opened and a technician points at a unit of data that already carries a source and destination IP address, but has not yet had any MAC addressing applied. What is the correct name for the protocol data unit at that layer?$q$,$q$["Frame","Packet","Segment","Bit"]$q$::jsonb,$q$1$q$::jsonb,$q$Layer 3 wraps the transport payload in an IP header containing source and destination logical addresses, and the resulting PDU is called a packet. Frame is the tempting answer because a capture on the wire usually shows Ethernet as well, but a frame is what Layer 2 produces when it adds the MAC header and the FCS trailer - which has explicitly not happened yet.$q$),

('n-q-401','netplus',1,'1.1','ordering',2,$q$Order these protocol data units as they are produced during encapsulation, starting with what the application hands down and finishing with what leaves the network interface.$q$,$q$["Frame","Segment","Bits","Data","Packet"]$q$::jsonb,$q$[3,1,4,0,2]$q$::jsonb,$q$Encapsulation runs top down: the upper layers produce data, Layer 4 adds port numbers to create a segment, Layer 3 adds IP addressing to create a packet, Layer 2 adds the MAC header and FCS trailer to create a frame, and Layer 1 encodes the frame as bits on the medium. Reversing this order describes de-encapsulation at the receiver, not encapsulation at the sender.$q$),

('n-q-402','netplus',1,'1.1','matching',2,$q$Match each OSI layer to the device or addressing artifact that belongs to it.$q$,$q${"left":["Layer 1 - Physical","Layer 2 - Data Link","Layer 3 - Network","Layer 4 - Transport"],"right":["Router","Hub or media converter","TCP or UDP port number","Switch and MAC address"]}$q$::jsonb,$q$[1,3,0,2]$q$::jsonb,$q$Hubs and media converters only repeat or convert signalling, so they sit at Layer 1. Switches forward using MAC addresses at Layer 2. Routers forward using IP addresses at Layer 3. Port numbers identify the endpoint application and belong to Layer 4. A multilayer switch blurs the picture in practice, but on the exam the device is classified by the address it makes its forwarding decision on.$q$),

('n-q-403','netplus',1,'1.1','mcq',2,$q$A workstation has a link light, the switch shows the port up with the correct MAC address learned, and the user can reach other hosts in the same subnet. Nothing on any other subnet is reachable. Which OSI layer should the technician concentrate on?$q$,$q$["Layer 1 - Physical","Layer 2 - Data Link","Layer 3 - Network","Layer 7 - Application"]$q$::jsonb,$q$2$q$::jsonb,$q$Same subnet traffic working proves the cabling, the switch port and MAC forwarding are healthy, so Layers 1 and 2 are already validated. Only traffic that must be routed fails, which points at Layer 3 - a missing or wrong default gateway, a bad subnet mask, or a routing problem upstream. Layer 2 is the tempting pick because the fault involves a switch port, but a Layer 2 fault would break local communication too.$q$),

('n-q-404','netplus',1,'1.1','mcq',3,$q$Users report that https://intranet fails in the browser, but browsing directly to the server IP address over HTTPS loads the site normally. Where does this fault sit?$q$,$q$["Layer 3, because routing to the web server is broken","Layer 4, because TCP 443 is being filtered","Layer 2, because the ARP cache is stale","Layer 7, because name resolution is an Application layer service"]$q$::jsonb,$q$3$q$::jsonb,$q$Reaching the site by IP proves routing, transport and the web service itself are all fine; the only thing that failed is turning a name into an address, and DNS is an Application layer service in the OSI model. The claim that TCP 443 is filtered is the tempting distractor, but if 443 were blocked the connection by IP address would have failed as well.$q$),

('n-q-405','netplus',1,'1.1','multi',2,$q$Select the TWO functions that are performed at the Transport layer of the OSI model.$q$,$q$["Segmentation of a large data stream and reassembly in the correct order at the destination","Assigning a logical IP address to an interface","Identifying the destination application with a port number","Encoding bits as electrical or optical signals on the medium","Resolving an IP address to a MAC address"]$q$::jsonb,$q$[0,2]$q$::jsonb,$q$Layer 4 breaks the data stream into segments, sequences them for reassembly, and uses port numbers to identify which application on the host the data belongs to. Assigning an IP address and resolving one to a MAC address are Layer 3 and Layer 2 activities respectively, and signal encoding is Layer 1.$q$),

('n-q-406','netplus',1,'1.1','mcq',2,$q$Application data is compressed and converted from an application-specific format into a common format that the receiving system can interpret. Which OSI layer describes this work?$q$,$q$["Session (Layer 5)","Presentation (Layer 6)","Application (Layer 7)","Transport (Layer 4)"]$q$::jsonb,$q$1$q$::jsonb,$q$The Presentation layer handles format translation, character encoding, compression and encryption so that the two ends agree on how the payload is represented. The Session layer is the classic confusion, but it deals with establishing, maintaining and tearing down the dialogue between the endpoints rather than with the shape of the data itself.$q$),

('n-q-407','netplus',1,'1.1','mcq',3,$q$A switch receives a unicast frame and sends it out of every port except the one it arrived on. Which condition explains this behaviour?$q$,$q$["The destination MAC address is not present in the switch MAC address table","The TTL value in the frame has expired","The destination IP address is outside the local subnet","The switch has no route to the destination network"]$q$::jsonb,$q$0$q$::jsonb,$q$This is unknown unicast flooding: when a switch has not yet learned which port owns a destination MAC address, it floods the frame to every other port in the VLAN and learns from the reply. Routing tables and TTL are Layer 3 constructs - a Layer 2 switch neither maintains routes nor decrements a TTL, so any answer built on those cannot explain switch behaviour.$q$),

('n-q-408','netplus',1,'1.1','mcq',1,$q$A technician replaces a failed SFP transceiver and reterminates a fiber patch cord to restore a dead uplink. At which OSI layer is this work being performed?$q$,$q$["Layer 2 - Data Link","Layer 3 - Network","Layer 1 - Physical","Layer 4 - Transport"]$q$::jsonb,$q$2$q$::jsonb,$q$Cabling, connectors, transceivers and the signalling they carry are all Layer 1. The Data Link layer is tempting because the link will only come up as a usable Ethernet link once the optics work, but Layer 2 concerns framing and MAC addressing, not the physical media carrying the signal.$q$),

('n-q-409','netplus',1,'1.1','multi',3,$q$Select the THREE statements that correctly describe what happens as a frame is de-encapsulated at a receiving host.$q$,$q$["The Layer 2 header and trailer are stripped before the packet is handed up to Layer 3","A new source IP address is written into the packet by every router along the path","The Layer 3 header is removed before the segment is handed to the Transport layer","Port numbers are rewritten by every intermediate switch","The FCS trailer is checked at Layer 2 and a frame that fails the check is discarded"]$q$::jsonb,$q$[0,2,4]$q$::jsonb,$q$De-encapsulation peels one header per layer on the way up, and Layer 2 validates the FCS first so corrupt frames never reach Layer 3. The idea that routers rewrite the source IP at each hop is the classic misconception - routers rewrite the Layer 2 header for each new segment but leave the Layer 3 source and destination addresses intact (barring NAT), and switches never touch Layer 4 port numbers at all.$q$),

('n-q-410','netplus',1,'1.1','ordering',3,$q$A technician is using a bottom-up troubleshooting methodology. Order these checks from the lowest OSI layer to the highest.$q$,$q$["Confirm the user can load the web page in a browser","Verify the patch cable is seated and the link light is lit","Check that the host has a valid default gateway and can ping a remote IP address","Confirm the switchport is in the correct VLAN and the host MAC is being learned","Verify the firewall permits TCP 443 through to the server"]$q$::jsonb,$q$[1,3,2,4,0]$q$::jsonb,$q$Bottom up means starting at Layer 1: cable and link light, then Layer 2 VLAN membership and MAC learning, then Layer 3 gateway and IP reachability, then Layer 4 port filtering, and finally the Layer 7 application itself. Working in this order means each check stands on ground already proven good, so a failure identifies the layer immediately.$q$),

-- ---------------------------------------------------------------- 1.2 (13) --
('n-q-411','netplus',1,'1.2','mcq',2,$q$A public web application runs on six identical servers. Incoming client sessions must be spread across them, and any server that stops responding to a health check must be taken out of rotation automatically. Which appliance provides this?$q$,$q$["Forward proxy","VPN concentrator","Load balancer","Intrusion detection system"]$q$::jsonb,$q$2$q$::jsonb,$q$A load balancer distributes inbound sessions across a pool of servers using an algorithm such as round robin or least connections, and it removes members that fail its health checks. A forward proxy is the tempting alternative because it also sits in the traffic path, but it faces outbound from internal clients toward the internet - it does not front a server farm or track backend health.$q$),

('n-q-412','netplus',1,'1.2','mcq',2,$q$Security requires that traffic matching a known exploit signature be dropped before it reaches the target server, not merely recorded. Which deployment meets the requirement?$q$,$q$["An IDS connected to a switch SPAN port","A syslog collector receiving switch logs","A protocol analyzer capturing on the server NIC","An IPS deployed inline in the traffic path"]$q$::jsonb,$q$3$q$::jsonb,$q$Only an inline IPS sits in the forwarding path and can discard a matching packet before delivery. An IDS on a SPAN port receives copies of traffic after it has already been forwarded, so it can alert but cannot prevent - which is exactly why the distinction between detection and prevention is tested by asking whether the device must block or merely notice.$q$),

('n-q-413','netplus',1,'1.2','mcq',1,$q$Laptops using 802.11 need to reach servers on the wired 802.3 network. Which device performs the conversion between the two frame formats for those clients?$q$,$q$["Wireless access point","Wireless LAN controller","Wireless range extender","Media converter"]$q$::jsonb,$q$0$q$::jsonb,$q$An access point is the bridge between the wireless and wired media: clients associate to it and it moves their traffic onto the Ethernet segment. A wireless LAN controller is the tempting answer in an enterprise design, but its job is to configure, monitor and coordinate a fleet of APs - clients never associate directly with the controller.$q$),

('n-q-414','netplus',1,'1.2','mcq',2,$q$Sixty access points are being deployed across four floors. The design calls for one consistent SSID and security policy, coordinated channel and power assignment, and seamless roaming between APs. What should be added?$q$,$q$["A stand-alone autonomous AP configured individually in each area","A wireless range extender between coverage zones","A wireless LAN controller","A captive portal on the edge firewall"]$q$::jsonb,$q$2$q$::jsonb,$q$A wireless LAN controller pushes one configuration to all lightweight APs, manages radio resources centrally, and coordinates client roaming. Configuring autonomous APs individually is the tempting alternative at small scale, but at sixty radios it produces configuration drift and no central radio management, and it does not coordinate roaming.$q$),

('n-q-415','netplus',1,'1.2','mcq',3,$q$Database servers must be presented with raw block storage over a dedicated storage fabric so that each server formats the volume with its own file system. Which storage design is required?$q$,$q$["A NAS exporting SMB shares over the user LAN","A NAS exporting NFS mounts over the user LAN","A SAN presenting block-level LUNs","A cloud object storage bucket accessed over HTTPS"]$q$::jsonb,$q$2$q$::jsonb,$q$A SAN presents block-level LUNs over a dedicated fabric such as Fibre Channel or iSCSI, and the server treats the LUN like a local disk it can format itself. A NAS is the classic confusion: it is also shared network storage, but it serves at file level over the regular LAN using SMB or NFS, and the file system is owned by the NAS rather than by the server.$q$),

('n-q-416','netplus',1,'1.2','mcq',2,$q$Management wants all outbound employee web requests to pass through a device that caches popular content, enforces category-based filtering, and logs the requesting user. Browsers will be configured to point at it. Which appliance is this?$q$,$q$["Reverse proxy","Load balancer","Intrusion prevention system","Forward proxy"]$q$::jsonb,$q$3$q$::jsonb,$q$A forward proxy sits between internal clients and the internet, so it can cache, filter by URL category and attribute requests to users. A reverse proxy is the tempting mirror image, but it faces the other direction - it accepts inbound requests on behalf of published servers rather than brokering internal users outbound.$q$),

('n-q-417','netplus',1,'1.2','mcq',2,$q$A retailer with customers on three continents finds that images and scripts load slowly for users far from its single data centre. Which solution addresses the root cause?$q$,$q$["A content delivery network","A second load balancer in the existing data centre","Link aggregation on the data centre uplink","An increase in the DNS record TTL"]$q$::jsonb,$q$0$q$::jsonb,$q$A CDN caches static content at edge locations worldwide, so the round-trip distance between user and content shrinks. Adding a load balancer is the tempting answer because it sounds like a performance fix, but it only spreads load among servers that are all still in the same distant site - it cannot reduce the propagation delay that is actually causing the slowness.$q$),

('n-q-418','netplus',1,'1.2','mcq',3,$q$A policy must permit a specific cloud storage application for one group of users while blocking all other cloud storage applications, regardless of which ports or IP addresses they use. Which appliance can enforce this?$q$,$q$["A stateless packet-filtering ACL on the border router","A Layer 2 switch with port security enabled","A next-generation firewall","An IDS sensor on a network tap"]$q$::jsonb,$q$2$q$::jsonb,$q$A next-generation firewall inspects traffic at the application layer and can bind a rule to an identified application and a user identity rather than to a port number. A stateless ACL is the tempting choice because it also permits and denies traffic, but it can only match addresses, protocols and port numbers - and modern cloud applications all share TCP 443, so an ACL cannot tell them apart.$q$),

('n-q-419','netplus',1,'1.2','mcq',1,$q$Several hundred remote employees need encrypted tunnels from their laptops back into the corporate network, all terminating on one hardened device at the network edge. Which appliance terminates those tunnels?$q$,$q$["VPN concentrator","RADIUS server","Load balancer","Network-attached storage appliance"]$q$::jsonb,$q$0$q$::jsonb,$q$A VPN concentrator (also called a VPN headend) is purpose-built to terminate large numbers of client tunnels, handling the cryptographic load and applying access policy. A RADIUS server is the tempting supporting cast: it authenticates the users, but the tunnel itself still has to terminate somewhere, and that somewhere is the concentrator.$q$),

('n-q-420','netplus',1,'1.2','mcq',2,$q$VoIP calls break up every evening at the moment the nightly backup job starts saturating the WAN link. Which function should be applied?$q$,$q$["Enable jumbo frames on the WAN interface","Increase the DHCP lease time for the phones","Enable port mirroring on the voice VLAN","Apply QoS to classify and prioritize the voice traffic"]$q$::jsonb,$q$3$q$::jsonb,$q$QoS classifies and marks voice traffic and gives it priority treatment in the queue, so latency-sensitive packets are serviced ahead of bulk backup data during congestion. Enabling jumbo frames is the tempting performance-sounding option, but larger frames raise serialisation delay and do nothing to establish priority between two traffic classes competing for the same link.$q$),

('n-q-421','netplus',1,'1.2','mcq',3,$q$A misconfiguration has produced a routing loop. Which field prevents the looping packets from circulating on the network indefinitely?$q$,$q$["The IPv4 header checksum","The TTL field, which every router decrements and discards at zero","The Ethernet FCS trailer","The TCP receive window size"]$q$::jsonb,$q$1$q$::jsonb,$q$Each router decrements the IPv4 TTL (the hop limit in IPv6) by one, and when it reaches zero the packet is dropped and an ICMP time-exceeded message is returned - which is also the mechanism traceroute exploits. The header checksum is the tempting distractor, but it only detects corruption of the header in transit; a looping packet is perfectly valid and would pass every checksum forever.$q$),

('n-q-422','netplus',1,'1.2','multi',2,$q$Select the TWO statements that correctly distinguish an IDS from an IPS.$q$,$q$["An IDS is typically deployed out of band, receiving copies of traffic from a SPAN port or a tap","An IPS is deployed inline and can drop matching traffic before it reaches the target","An IDS decrypts TLS by default whereas an IPS cannot","An IPS only generates alerts and never blocks traffic","An IDS is required in order to route traffic between VLANs"]$q$::jsonb,$q$[0,1]$q$::jsonb,$q$The whole distinction is placement and authority: detection systems watch a copy of the traffic and raise alerts, prevention systems sit in the path and can discard. Saying that an IPS only alerts inverts the definition, and neither device performs inter-VLAN routing - that is the job of a router or a Layer 3 switch.$q$),

('n-q-423','netplus',1,'1.2','multi',3,$q$Select the THREE statements that are true about NAS and SAN storage.$q$,$q$["A NAS provides file-level access over the existing Ethernet LAN using protocols such as SMB and NFS","A SAN provides block-level access, commonly over Fibre Channel or iSCSI","A NAS presents raw LUNs that the client formats with its own file system","A SAN is always slower than a NAS because both share the same user LAN links","A SAN is typically built on a dedicated storage fabric kept separate from the user LAN"]$q$::jsonb,$q$[0,1,4]$q$::jsonb,$q$NAS is file level over the ordinary LAN; SAN is block level over a fabric built for storage, which is why SAN designs usually isolate the storage network from user traffic. The claim that a NAS presents raw LUNs describes a SAN, and the assertion that a SAN shares the user LAN contradicts the dedicated-fabric design that gives a SAN its performance profile.$q$),

-- ---------------------------------------------------------------- 1.3 (14) --
('n-q-424','netplus',1,'1.3','mcq',1,$q$A development team uploads application code to a hosted platform. The provider supplies and patches the operating system, the runtime and the middleware; the team never touches a virtual machine. Which service model is in use?$q$,$q$["IaaS","PaaS","SaaS","Colocation"]$q$::jsonb,$q$1$q$::jsonb,$q$Platform as a Service delivers a managed runtime environment so the customer is responsible only for the code and its data. IaaS is the tempting alternative, but under IaaS the customer would receive virtual machines and would be the one patching the guest operating system.$q$),

('n-q-425','netplus',1,'1.3','mcq',2,$q$In a cloud deployment the customer patches the guest operating systems, defines subnets and route tables, and manages the virtual firewall rules. The provider maintains the hypervisor, the physical servers and the data centre. Which service model is this?$q$,$q$["SaaS","PaaS","IaaS","Function as a Service"]$q$::jsonb,$q$2$q$::jsonb,$q$Infrastructure as a Service hands the customer virtual compute, storage and networking, and everything from the guest OS upward stays the customer responsibility. PaaS is the tempting near-miss, but PaaS removes guest OS patching from the customer entirely, which is explicitly described here as the customer job.$q$),

('n-q-426','netplus',1,'1.3','mcq',2,$q$A regulated workload must run on infrastructure dedicated to the organisation, but seasonal overflow capacity is drawn from a public provider across a private connection, with workloads moving between the two. Which deployment model is described?$q$,$q$["Public cloud","Private cloud","Community cloud","Hybrid cloud"]$q$::jsonb,$q$3$q$::jsonb,$q$A hybrid cloud combines a private environment with public cloud resources and keeps them linked so workloads and data can move between them - the overflow behaviour described is cloud bursting. Private cloud alone is the tempting answer because the regulated portion is dedicated, but a purely private deployment has no public component to burst into.$q$),

('n-q-427','netplus',1,'1.3','mcq',2,$q$Five regional hospitals jointly fund and share a single cloud environment built to the specific privacy controls their sector requires. No other organisations use it. Which deployment model is this?$q$,$q$["Public cloud","Community cloud","Hybrid cloud","Private cloud"]$q$::jsonb,$q$1$q$::jsonb,$q$A community cloud is shared by several organisations with common regulatory or mission requirements, splitting the cost while keeping outsiders out. Private cloud is the tempting choice because access is restricted, but a private cloud serves exactly one organisation - here the tenancy is deliberately shared among peers.$q$),

('n-q-428','netplus',1,'1.3','mcq',3,$q$A platform automatically adds instances when weekday traffic triples at 09:00 and removes them again when traffic falls at 18:00, so the invoice tracks actual demand. Which cloud characteristic does this describe?$q$,$q$["Elasticity","Vertical scalability","High availability","Multitenancy"]$q$::jsonb,$q$0$q$::jsonb,$q$Elasticity is the automatic, demand-driven addition and removal of resources in both directions, which is what ties consumption to cost. Scalability is the tempting answer and is genuinely related, but scalability only describes the capacity to grow when required - it says nothing about releasing resources automatically once demand drops.$q$),

('n-q-429','netplus',1,'1.3','mcq',1,$q$An application is given more capacity by launching four additional identical web server instances behind the existing load balancer. What is this called?$q$,$q$["Scaling up (vertical scaling)","Rapid provisioning","Scaling out (horizontal scaling)","Failover clustering"]$q$::jsonb,$q$2$q$::jsonb,$q$Adding more instances of the same size is scaling out, or horizontal scaling, and it requires a load balancer in front to spread the work. Scaling up is the tempting opposite: it means giving a single instance more CPU or memory, which usually requires a restart and is bounded by the largest instance type available.$q$),

('n-q-430','netplus',1,'1.3','mcq',2,$q$A customer is allocated a logically isolated section of the provider cloud in which it defines its own private IP address ranges, subnets, route tables and gateways. What is this construct called?$q$,$q$["An availability zone","A virtual private cloud (VPC)","A site-to-site VPN","A network security group"]$q$::jsonb,$q$1$q$::jsonb,$q$A VPC is the customer-defined virtual network inside the provider cloud, complete with its own address space and routing. A site-to-site VPN is the tempting confusion because both involve the word private, but a VPN is an encrypted tunnel connecting networks - it is a way to reach the VPC, not the VPC itself.$q$),

('n-q-431','netplus',1,'1.3','mcq',3,$q$A cloud filtering control is applied to individual instance network interfaces, and when an allowed outbound request is made the corresponding return traffic is permitted automatically without a matching inbound rule. Which control is described?$q$,$q$["A stateless network access list applied at the subnet boundary","A stateful network security group applied to the instance interface","A route table entry in the VPC","An internet gateway attached to the VPC"]$q$::jsonb,$q$1$q$::jsonb,$q$Security groups are stateful and are attached to instance interfaces, so the return path of an allowed session is tracked and permitted implicitly. Network access lists are the tempting sibling because they also permit and deny traffic, but they are stateless and evaluated at the subnet boundary, which means the return direction needs its own explicit rule.$q$),

('n-q-432','netplus',1,'1.3','mcq',3,$q$A finance application replicating to the cloud needs predictable latency and committed bandwidth, and its traffic must not traverse the public internet at all. Which connectivity option should be chosen?$q$,$q$["An IPSec site-to-site VPN over the existing internet circuit","A client-to-site SSL VPN installed on each server","A dedicated direct connection provisioned to the provider","A NAT gateway placed in a public subnet"]$q$::jsonb,$q$2$q$::jsonb,$q$A direct connection is a private circuit between the customer site and the provider edge, so it delivers committed bandwidth and consistent latency and never rides the public internet. A site-to-site VPN is the tempting choice because it is encrypted and quick to build, but it still crosses the internet, so its latency and throughput remain at the mercy of whatever the path is doing that day.$q$),

('n-q-433','netplus',1,'1.3','multi',2,$q$Instances in a private cloud subnet must be able to download operating system patches from the internet, but must never be reachable from the internet. Select the THREE components required.$q$,$q$["A NAT gateway placed in a public subnet","An internet gateway attached to the VPC","A public IP address assigned to every instance","An inbound security group rule allowing 0.0.0.0/0 on TCP 443","A default route in the private subnet route table pointing at the NAT gateway"]$q$::jsonb,$q$[0,1,4]$q$::jsonb,$q$Outbound-only internet access is built from a NAT gateway in a public subnet, an internet gateway giving that public subnet a path out, and a default route in the private subnet aimed at the NAT gateway. Assigning public IP addresses to the instances would defeat the whole design by making them directly addressable, and an inbound allow rule from 0.0.0.0/0 would do the same.$q$),

('n-q-434','netplus',1,'1.3','mcq',2,$q$A team needs a new firewall and load balancer for a branch site within the hour, with no hardware shipment and no rack space. They launch software instances that perform those roles on commodity servers. Which concept does this illustrate?$q$,$q$["Software-defined WAN link bonding","Infrastructure as code templating","Network segmentation","Network functions virtualization"]$q$::jsonb,$q$3$q$::jsonb,$q$NFV moves network functions such as routing, firewalling and load balancing off purpose-built appliances and onto software instances running on general-purpose compute, so capacity is provisioned in minutes. Infrastructure as code is the tempting distractor because it also speeds up delivery, but it describes declaring and deploying configuration from templates - the point here is that the appliance itself has become software.$q$),

('n-q-435','netplus',1,'1.3','multi',2,$q$Select the TWO statements that correctly distinguish public cloud from private cloud.$q$,$q$["Public cloud resources are multitenant, shared with other customers on the provider infrastructure","Private cloud infrastructure is dedicated to a single organisation, whether it is hosted internally or by a third party","A private cloud cannot make use of virtualization","Public cloud is cheaper than private cloud at every possible scale","Moving to public cloud transfers all security responsibility to the provider"]$q$::jsonb,$q$[0,1]$q$::jsonb,$q$The defining difference is tenancy: public cloud pools infrastructure across many customers, private cloud dedicates it to one - and a private cloud can be hosted by a third party and still be private. The idea that the provider assumes all security responsibility is the most dangerous misconception here; the shared responsibility model always leaves data, identity and configuration with the customer.$q$),

('n-q-436','netplus',1,'1.3','multi',3,$q$In an IaaS deployment, select the THREE tasks that remain the customer responsibility.$q$,$q$["Patching the guest operating system on the virtual machines","Replacing failed physical disks in the provider data centre","Configuring security group rules","Maintaining and patching the hypervisor","Defining subnets and route tables inside the VPC"]$q$::jsonb,$q$[0,2,4]$q$::jsonb,$q$Under IaaS the provider owns everything up to and including the hypervisor and the physical plant, while the customer owns the guest OS, the virtual network design and the access controls. Hypervisor maintenance is the most commonly mis-assigned item on this list - customers never see it, which is precisely why it belongs to the provider.$q$),

('n-q-437','netplus',1,'1.3','matching',2,$q$Match each cloud networking component to its description.$q$,$q${"left":["Virtual private cloud","Network security group","Direct connection","NAT gateway"],"right":["A private dedicated circuit between the customer site and the provider, bypassing the internet","Allows private instances to start outbound internet sessions without being reachable inbound","A logically isolated network inside the provider where the customer defines its own addressing","A stateful rule set attached to instance network interfaces"]}$q$::jsonb,$q$[2,3,0,1]$q$::jsonb,$q$The VPC is the customer-defined virtual network, the security group is the stateful per-interface filter, the direct connection is the private circuit that avoids the internet, and the NAT gateway gives private instances outbound-only reachability. Confusing the VPC with the direct connection is common: one is where the resources live, the other is how you reach it privately.$q$),

-- ---------------------------------------------------------------- 1.4 (11) --
('n-q-438','netplus',1,'1.4','matching',2,$q$Match each protocol to its default port number.$q$,$q${"left":["SMTP","LDAP","Syslog","SIP signalling without TLS"],"right":["514","5060","25","389"]}$q$::jsonb,$q$[2,3,0,1]$q$::jsonb,$q$SMTP uses TCP 25 for server-to-server mail transfer, LDAP uses 389 for directory queries, syslog collectors listen on UDP 514, and SIP call signalling uses 5060 in the clear or 5061 with TLS. Syslog on 514 and SIP on 5060 are the pair most often swapped under time pressure, so anchor syslog to logging and 5060 to voice signalling.$q$),

('n-q-439','netplus',1,'1.4','mcq',2,$q$A switch must pull its configuration file from a server during a zero-touch boot. The switch bootloader supports only a minimal UDP-based transfer with no authentication and no directory listing. Which protocol and port is it using?$q$,$q$["FTP on TCP 21","TFTP on UDP 69","SFTP on TCP 22","SMB on TCP 445"]$q$::jsonb,$q$1$q$::jsonb,$q$TFTP is the trivial file transfer protocol on UDP 69: no authentication, no directory browsing, small enough to live in firmware, which is why network devices use it for config and image transfers. FTP on TCP 21 is the tempting answer because it is also a file transfer protocol, but FTP is TCP-based, authenticates users and supports directory listings - none of which the described bootloader can do.$q$),

('n-q-440','netplus',1,'1.4','mcq',1,$q$A client with no IP address broadcasts a request for network configuration and a server replies with an offer. Which ports carry this IPv4 exchange?$q$,$q$["TCP 67 and TCP 68","UDP 69 and UDP 70","UDP 67 and UDP 68","TCP 546 and TCP 547"]$q$::jsonb,$q$2$q$::jsonb,$q$DHCP for IPv4 uses UDP 67 on the server and UDP 68 on the client - it must be UDP because the client has no address yet and cannot complete a TCP handshake. Ports 546 and 547 are the tempting near-miss: those are DHCPv6, and they are UDP rather than TCP as well.$q$),

('n-q-441','netplus',1,'1.4','mcq',3,$q$A secondary DNS server is failing to pull the zone from the primary, although normal name lookups against both servers succeed. Which transport does a zone transfer require?$q$,$q$["UDP 53, exactly as ordinary queries do","TCP 853 only","UDP 953","TCP 53, because the transfer is too large for reliable single-datagram delivery"]$q$::jsonb,$q$3$q$::jsonb,$q$Ordinary DNS lookups use UDP 53 for speed, but a zone transfer moves the whole zone and needs the reliability and sequencing of a TCP session, so it uses TCP 53. Assuming that DNS is UDP-only is the classic trap, and it is exactly why a firewall rule permitting only UDP 53 breaks replication while leaving lookups working.$q$),

('n-q-442','netplus',1,'1.4','mcq',2,$q$A monitored switch sends an unsolicited notification to the management station the moment an interface goes down. Which port does the management station listen on to receive it?$q$,$q$["UDP 162","UDP 161","TCP 162","UDP 514"]$q$::jsonb,$q$0$q$::jsonb,$q$SNMP traps and informs are sent to the manager on UDP 162. UDP 161 is the tempting sibling, but that is the port the agent listens on for the manager to poll it - the direction of the conversation is what decides which of the two numbers applies.$q$),

('n-q-443','netplus',1,'1.4','mcq',3,$q$A single IP address is advertised into the routing system from data centres on several continents, and each client is served by whichever instance is closest in routing terms. Which traffic type is this?$q$,$q$["Broadcast","Multicast","Anycast","Unicast"]$q$::jsonb,$q$2$q$::jsonb,$q$Anycast is one-to-nearest: many hosts share the same address and routing steers each client to the closest one, which is how public DNS resolvers and CDN edges are commonly built. Multicast is the tempting alternative because it also involves many destinations, but multicast is one-to-many - every subscribed receiver gets a copy, rather than one chosen receiver answering.$q$),

('n-q-444','netplus',1,'1.4','mcq',2,$q$An IPTV feed must be delivered only to the hosts that have subscribed to it, without being flooded to every host in the VLAN and without opening a separate stream per viewer. Which traffic type meets this?$q$,$q$["Broadcast to 255.255.255.255","A separate unicast stream for each viewer","Anycast from the nearest available source","Multicast to a group address in 224.0.0.0/4"]$q$::jsonb,$q$3$q$::jsonb,$q$Multicast sends one stream that the network replicates only toward the hosts that joined the group, using addresses in 224.0.0.0/4. Broadcast is the tempting alternative because it also reaches many hosts with one transmission, but it reaches every host in the broadcast domain - including those that never asked for the feed - and it does not cross a router.$q$),

('n-q-445','netplus',1,'1.4','mcq',3,$q$Two sites need a tunnel that can carry a dynamic routing protocol and multicast traffic between them. The encapsulation itself is expected to provide no confidentiality. Which protocol provides the tunnel?$q$,$q$["IPSec ESP","GRE","TLS","IPSec AH"]$q$::jsonb,$q$1$q$::jsonb,$q$GRE (IP protocol 47) encapsulates arbitrary payloads, including multicast and routing protocol traffic, but adds no encryption at all - which is why GRE is so often paired with IPSec when confidentiality is also required. ESP is the tempting pick because it is the usual site-to-site choice, but ESP encrypts and native IPSec tunnels do not carry multicast, which is exactly the gap GRE fills.$q$),

('n-q-446','netplus',1,'1.4','multi',2,$q$An audit requires that cleartext administrative and file transfer access to network devices be eliminated. Select the THREE ports that should therefore be closed on the management interfaces.$q$,$q$["TCP 23","TCP 22","TCP 21","TCP 443","TCP 80"]$q$::jsonb,$q$[0,2,4]$q$::jsonb,$q$Telnet on TCP 23, FTP control on TCP 21 and HTTP on TCP 80 all carry credentials and data in the clear, so each has an encrypted replacement that should be used instead. SSH on TCP 22 and HTTPS on TCP 443 are the encrypted replacements themselves and are exactly what should remain open.$q$),

('n-q-447','netplus',1,'1.4','multi',3,$q$Select the THREE correct statements about the components of an IPSec deployment.$q$,$q$["AH, IP protocol 51, provides integrity and authentication but no encryption","ESP, IP protocol 50, provides confidentiality in addition to integrity","ICMP, IP protocol 1, negotiates the IPSec security association","GRE, IP protocol 47, encrypts the tunnel payload","IKE, on UDP 500, negotiates the security association and keys"]$q$::jsonb,$q$[0,1,4]$q$::jsonb,$q$IPSec is built from IKE for negotiation on UDP 500, plus AH for authentication and integrity and ESP when confidentiality is needed as well. The claim that GRE encrypts is the trap worth remembering: GRE only encapsulates, and ICMP has nothing to do with key exchange - it carries error and diagnostic messages.$q$),

('n-q-448','netplus',1,'1.4','ordering',2,$q$Place these services in ascending order of their default port number.$q$,$q$["HTTPS","SSH","DNS","NTP","LDAP"]$q$::jsonb,$q$[1,2,3,4,0]$q$::jsonb,$q$Ascending order is SSH 22, DNS 53, NTP 123, LDAP 389, HTTPS 443. Anchoring the low numbers (22, 53) against the higher directory and web ports (389, 443) makes it much harder to confuse LDAP with LDAPS on 636 or NTP on 123 with syslog on 514.$q$);

-- ============================================================================
-- FLASHCARDS
-- ============================================================================

insert into public.flashcards (id, cert, domain, objective, deck, front, back) values

-- ---------------------------------------------------------------- 1.1 (14) --
('n-f-400','netplus',1,'1.1','core',$q$A capture shows one unit of data carrying an Ethernet header, an IP header and a TCP header. What is that unit called at Layers 2, 3 and 4?$q$,$q$Frame at Layer 2, packet at Layer 3, segment at Layer 4. The name always refers to the outermost header that the layer in question is responsible for - the same bytes on the wire are a frame to the switch and a packet to the router.$q$),
('n-f-401','netplus',1,'1.1','acronym',$q$PDU$q$,$q$Protocol Data Unit - the generic name for the unit of data at a given OSI layer (data, segment or datagram, packet, frame, bits). Naming the PDU tells you which layer you are reasoning about.$q$),
('n-f-402','netplus',1,'1.1','core',$q$What belongs to OSI Layer 1, and what symptom points there?$q$,$q$Cabling, connectors, transceivers, patch panels, repeaters, hubs, and the signalling and encoding on the medium. The symptom is no link light, high error or CRC counters, or a port that will not come up at all - Layer 1 faults break everything above them.$q$),
('n-f-403','netplus',1,'1.1','core',$q$What does OSI Layer 2 do, and what are its two sublayers?$q$,$q$Frames data for delivery across one link, using MAC addressing, and detects corrupt frames with the FCS trailer. Its sublayers are LLC (interfaces with the upper layers) and MAC (controls access to the medium). Switches, 802.1Q VLAN tagging and ARP responses live here.$q$),
('n-f-404','netplus',1,'1.1','core',$q$What does OSI Layer 3 add, and which devices and protocols operate there?$q$,$q$Logical IP addressing, routing between different networks, TTL-based loop prevention and fragmentation. Routers and Layer 3 switches forward here; IPv4, IPv6 and ICMP are Layer 3 protocols. If local traffic works but remote traffic does not, start here.$q$),
('n-f-405','netplus',1,'1.1','core',$q$What are the four jobs of OSI Layer 4?$q$,$q$Segmentation of the data stream and reassembly in order, identifying the endpoint application by port number, flow control (TCP windowing), and choosing reliability (TCP) or speed (UDP). A blocked port number is a Layer 4 fault, not a Layer 3 one.$q$),
('n-f-406','netplus',1,'1.1','core',$q$What is OSI Layer 5 responsible for?$q$,$q$Establishing, maintaining, synchronising and tearing down the dialogue between two applications - session setup, session identifiers and orderly termination. Remote procedure calls and session tokens are typical examples; it manages the conversation, not the formatting of the data.$q$),
('n-f-407','netplus',1,'1.1','core',$q$What does OSI Layer 6 do?$q$,$q$Translates data between the application format and a common transmission format: character encoding, file format representation, compression, and encryption or decryption. TLS is conventionally placed here on the exam, and format mismatches (a file that arrives but cannot be read) are the classic Layer 6 symptom.$q$),
('n-f-408','netplus',1,'1.1','core',$q$What actually lives at OSI Layer 7?$q$,$q$The network-facing services that applications call - HTTP and HTTPS, DNS, SMTP, FTP, SNMP, LDAP. Layer 7 is not the application itself: the browser is software on the host, while the HTTP exchange it generates is the Layer 7 protocol.$q$),
('n-f-409','netplus',1,'1.1','core',$q$What is the difference between encapsulation and de-encapsulation?$q$,$q$Encapsulation happens on the way down at the sender: each layer wraps the payload from above in its own header (and at Layer 2 a trailer). De-encapsulation happens on the way up at the receiver: each layer strips its own header, checks it, and hands the remainder to the layer above.$q$),
('n-f-410','netplus',1,'1.1','core',$q$As a packet crosses several routers, which headers change and which stay the same?$q$,$q$The Layer 2 header is rewritten at every hop, because each link has different MAC addresses. The Layer 3 source and destination IP addresses stay the same end to end (unless NAT is applied), while the TTL is decremented by one at each router. Layer 4 port numbers are untouched by routers.$q$),
('n-f-411','netplus',1,'1.1','core',$q$What are the three OSI-based troubleshooting approaches, and when do you use each?$q$,$q$Bottom-up starts at Layer 1 and is best for suspected physical problems. Top-down starts at Layer 7 and suits a single application failing while everything else works. Divide and conquer starts in the middle, usually with a ping at Layer 3, and halves the search space with one test.$q$),
('n-f-412','netplus',1,'1.1','core',$q$How do you tell a Layer 1 fault from a Layer 2 fault?$q$,$q$No link light, dead port or a physically damaged cable is Layer 1. Link up but no usable traffic is Layer 2: wrong VLAN, duplex mismatch, port security shutting the port, a spanning tree block, or a MAC address not being learned. Layer 1 asks whether there is a signal; Layer 2 asks whether the frames are valid and allowed.$q$),
('n-f-413','netplus',1,'1.1','core',$q$Ping to a server succeeds but the application will not connect. Which layer is implicated and why?$q$,$q$Layer 4 or above. A successful ping proves Layers 1 to 3 all the way to the host, so the remaining suspects are a blocked TCP or UDP port, a service that is not listening, or an application-layer fault. Check the port with a port scan or a telnet-to-port test before touching the routing.$q$),

-- ---------------------------------------------------------------- 1.2 (16) --
('n-f-414','netplus',1,'1.2','core',$q$When do you need a router rather than a Layer 3 switch?$q$,$q$Both route between subnets, but a router terminates WAN circuits, supports diverse interface types, performs NAT and richer policy, and generally has more advanced routing features. A Layer 3 switch routes between VLANs inside the campus at wire speed with many copper ports and is the cheaper choice per port for pure inter-VLAN routing.$q$),
('n-f-415','netplus',1,'1.2','core',$q$How do an IDS and an IPS differ in placement and effect?$q$,$q$An IDS sits out of band on a SPAN port or a tap and receives copies of traffic, so it can only alert after the fact but cannot break production if it fails. An IPS sits inline in the forwarding path and can drop or reset matching traffic - the price being that a false positive blocks legitimate traffic and a failure can interrupt the link.$q$),
('n-f-416','netplus',1,'1.2','core',$q$What does a load balancer do beyond spreading traffic?$q$,$q$Distributes sessions across a server pool (round robin, least connections, weighted), removes members that fail health checks, keeps a client pinned to one backend with session persistence, and often terminates TLS on behalf of the servers (SSL offload). It also hides the number and identity of the backend servers.$q$),
('n-f-417','netplus',1,'1.2','core',$q$What is the difference between a forward proxy and a reverse proxy?$q$,$q$A forward proxy sits in front of internal clients heading out: caching, URL and category filtering, user attribution and anonymity. A reverse proxy sits in front of published servers facing inbound clients: it hides the server topology, terminates TLS and can cache or load balance. Same technology, opposite direction of travel.$q$),
('n-f-418','netplus',1,'1.2','core',$q$NAS or SAN - how do you choose?$q$,$q$NAS is file-level storage served over the normal Ethernet LAN with SMB or NFS; simple, cheap, and the NAS owns the file system. SAN is block-level storage over a dedicated fabric (Fibre Channel or iSCSI) that appears to the server as a raw local disk it formats itself; it is what databases and virtualization hosts expect.$q$),
('n-f-419','netplus',1,'1.2','core',$q$What is the difference between an autonomous access point and a controller-based (lightweight) AP?$q$,$q$An autonomous AP holds its own full configuration and is managed individually - fine for a handful of radios. A lightweight AP receives its configuration from a wireless LAN controller, which also handles channel and power assignment, roaming coordination and central monitoring across the whole fleet.$q$),
('n-f-420','netplus',1,'1.2','acronym',$q$CDN$q$,$q$Content Delivery Network - a geographically distributed set of caching servers that serves static content from an edge location near the user, cutting latency and offloading the origin.$q$),
('n-f-421','netplus',1,'1.2','core',$q$What problem does a CDN solve, and what does it not solve?$q$,$q$It solves distance: static assets are cached at edge locations near users, so round-trip latency drops and origin bandwidth is offloaded, and the distributed footprint helps absorb volumetric attacks. It does not accelerate uncacheable, per-user dynamic responses - those still have to be generated at the origin.$q$),
('n-f-422','netplus',1,'1.2','core',$q$What is the difference between a stateless packet filter, a stateful firewall and a next-generation firewall?$q$,$q$A stateless filter (a router ACL) evaluates each packet alone against addresses, protocols and ports. A stateful firewall tracks connections, so the return traffic of an allowed session is permitted automatically. A next-generation firewall adds application awareness, user identity and integrated IPS, so it can distinguish two applications that both use TCP 443.$q$),
('n-f-423','netplus',1,'1.2','core',$q$What does a VPN concentrator do, and how do site-to-site and client-to-site VPNs differ?$q$,$q$A VPN concentrator (headend) terminates many encrypted tunnels at the network edge and applies access policy to them. Site-to-site joins two networks permanently through gateways, so users never install anything. Client-to-site (remote access) puts a client on each endpoint device and connects individual users from anywhere.$q$),
('n-f-424','netplus',1,'1.2','core',$q$What does QoS actually do to fix choppy voice on a congested link?$q$,$q$Classifies traffic, marks it (DSCP EF is the usual marking for voice), and then queues and schedules so marked traffic is serviced first and shaped or policed traffic is held back. QoS only matters where there is congestion - it reallocates a scarce link, it does not create extra bandwidth.$q$),
('n-f-425','netplus',1,'1.2','core',$q$TTL means two different things on the exam - what are they?$q$,$q$In an IP header, TTL is a hop counter that every router decrements and drops at zero, preventing loops and enabling traceroute. In DNS, TTL is the number of seconds a resolver may cache a record - lower it before a planned cutover so clients pick up the new address quickly.$q$),
('n-f-426','netplus',1,'1.2','core',$q$What is the difference between an explicit proxy and a transparent proxy?$q$,$q$An explicit proxy requires the client to be configured (manually or by PAC file) to send requests to it, so an unconfigured client bypasses it entirely. A transparent proxy intercepts traffic in the path with no client configuration, which is harder to evade but can break applications that do certificate pinning.$q$),
('n-f-427','netplus',1,'1.2','core',$q$What problem does session persistence (sticky sessions) solve on a load balancer?$q$,$q$It keeps a given client returning to the same backend server for the life of a session, so server-held state such as a shopping cart or an unshared login session is not lost. Without it, a pure round-robin distribution can land each request on a different server and appear to log the user out at random.$q$),
('n-f-428','netplus',1,'1.2','core',$q$What is the difference between Layer 4 and Layer 7 load balancing?$q$,$q$Layer 4 balances on IP address and port alone, which is fast and protocol-agnostic but blind to content. Layer 7 reads the application data, so it can route by URL path, hostname or cookie, insert headers and terminate TLS - at the cost of more processing per request.$q$),
('n-f-429','netplus',1,'1.2','core',$q$Why prefer another access point over a wireless range extender?$q$,$q$A repeater or extender receives and retransmits on the same radio, roughly halving the throughput for clients behind it and adding latency. An additional AP with its own wired uplink keeps full throughput, and with a controller it also participates in coordinated channel planning and roaming.$q$),

-- ---------------------------------------------------------------- 1.3 (16) --
('n-f-430','netplus',1,'1.3','core',$q$IaaS, PaaS, SaaS - who manages what?$q$,$q$IaaS: provider gives virtual compute, storage and networking; customer owns the guest OS upward. PaaS: provider also owns the OS, runtime and middleware; customer owns only code and data. SaaS: provider runs the whole application; customer owns only its data, users and configuration. The line moves up the stack as you move from IaaS to SaaS.$q$),
('n-f-431','netplus',1,'1.3','core',$q$What are the four cloud deployment models?$q$,$q$Public: multitenant infrastructure shared on a provider platform. Private: dedicated to one organisation, hosted internally or by a third party. Community: shared by several organisations with common compliance needs. Hybrid: private and public linked so workloads and data can move, which is what enables cloud bursting.$q$),
('n-f-432','netplus',1,'1.3','acronym',$q$NFV$q$,$q$Network Functions Virtualization - delivering routing, firewall, load balancing and similar network functions as software instances on general-purpose compute rather than as dedicated hardware appliances.$q$),
('n-f-433','netplus',1,'1.3','acronym',$q$VPC$q$,$q$Virtual Private Cloud - a logically isolated network inside a provider cloud where the customer defines its own IP address ranges, subnets, route tables and gateways.$q$),
('n-f-434','netplus',1,'1.3','core',$q$What is the exact difference between scalability and elasticity?$q$,$q$Scalability is the capacity to grow to meet a larger load, typically a planned change. Elasticity is automatic expansion and contraction tracking demand in real time, in both directions, so cost follows usage. Every elastic system is scalable, but a system that can only be grown by hand is not elastic.$q$),
('n-f-435','netplus',1,'1.3','core',$q$Horizontal or vertical scaling - what is the trade-off?$q$,$q$Vertical (scaling up) means giving one instance more CPU or memory: simple, no application change, but bounded by the largest instance available and usually requires downtime. Horizontal (scaling out) means adding more instances behind a load balancer: effectively unbounded and tolerant of node failure, but the application must be able to run stateless or share state.$q$),
('n-f-436','netplus',1,'1.3','core',$q$How does a network security group differ from a network access list in the cloud?$q$,$q$A security group is stateful and attaches to instance interfaces, so return traffic for an allowed session is permitted automatically and rules are usually allow-only. A network access list is stateless and evaluated at the subnet boundary, supports both allow and deny entries in order, and requires an explicit rule for each direction.$q$),
('n-f-437','netplus',1,'1.3','core',$q$What are the common cloud gateway types and what does each do?$q$,$q$Internet gateway: gives a subnet a bidirectional path to the internet. NAT gateway: lets private instances reach out without being reachable inbound. VPN gateway: terminates encrypted tunnels from on-premises sites. Storage gateway: presents cloud storage to on-premises systems using familiar file or block protocols.$q$),
('n-f-438','netplus',1,'1.3','core',$q$Site-to-site VPN or a direct connection to the cloud - how do you choose?$q$,$q$A VPN rides the existing internet circuit: fast to deploy, cheap, encrypted, but latency and throughput vary with internet conditions. A direct connection is a provisioned private circuit: consistent latency, committed bandwidth and no internet exposure, but it costs more and takes weeks to install. Many designs keep a VPN as the backup for the direct connection.$q$),
('n-f-439','netplus',1,'1.3','core',$q$What is multitenancy and what risk does it introduce?$q$,$q$Multiple customers share the same underlying physical infrastructure, with logical isolation keeping their data and traffic apart - it is what makes public cloud economics work. The risk is that a flaw in the isolation, or a noisy neighbour consuming shared resources, can affect a tenant who did nothing wrong.$q$),
('n-f-440','netplus',1,'1.3','core',$q$What does the shared responsibility model always leave with the customer?$q$,$q$Regardless of service model: the data itself, identity and access management, and the customer configuration of the service. The provider is always responsible for the physical facility and the underlying platform. The boundary between them moves up the stack from IaaS to SaaS, but it never reaches the customer data.$q$),
('n-f-441','netplus',1,'1.3','core',$q$What is the difference between a cloud region and an availability zone?$q$,$q$A region is a geographic area, chosen for latency to users and for data residency requirements. An availability zone is one or more discrete data centres within a region with independent power and cooling. Spreading instances across zones survives a single data centre failure; spreading across regions survives a regional event but adds latency and cost.$q$),
('n-f-442','netplus',1,'1.3','core',$q$How can two VPCs communicate privately, and what breaks it?$q$,$q$By peering them directly, or by connecting both to a central transit hub when many networks are involved. The traffic stays on the provider backbone rather than the internet. Overlapping CIDR ranges break it outright - address planning has to be done before the VPCs are built, not after.$q$),
('n-f-443','netplus',1,'1.3','core',$q$How do SDN and NFV differ?$q$,$q$SDN separates the control plane from the data plane and centralises forwarding decisions in a controller - it changes how the network is controlled. NFV replaces dedicated appliances with software instances of the same functions - it changes what the network device is. They are complementary and often deployed together, but neither implies the other.$q$),
('n-f-444','netplus',1,'1.3','core',$q$What makes a cloud subnet public rather than private?$q$,$q$Its route table. A public subnet has a default route pointing at an internet gateway, so resources with a public address are reachable from and can reach the internet. A private subnet has no such route; if its instances need outbound access they get a default route to a NAT gateway instead, which permits outbound only.$q$),
('n-f-445','netplus',1,'1.3','core',$q$What are the five essential characteristics of cloud computing?$q$,$q$On-demand self-service, broad network access, resource pooling, rapid elasticity, and measured service (metered, pay-per-use billing). If an offering is missing one - for example a hosted server you must phone someone to resize - it is hosting rather than true cloud.$q$),

-- ---------------------------------------------------------------- 1.4 (14) --
('n-f-446','netplus',1,'1.4','core',$q$FTP, TFTP, SFTP, FTPS - ports and differences?$q$,$q$FTP: TCP 21 control and TCP 20 data, cleartext. TFTP: UDP 69, no authentication, used by network devices for config and firmware. SFTP: file transfer inside an SSH session on TCP 22. FTPS: FTP wrapped in TLS. SFTP and FTPS both encrypt but are different protocols, not different names for one thing.$q$),
('n-f-447','netplus',1,'1.4','core',$q$What rides on TCP 22, and why did it replace Telnet on TCP 23?$q$,$q$SSH carries encrypted remote shell, and SFTP and SCP file transfer, all on TCP 22. Telnet on TCP 23 sends the session - including the credentials - in cleartext, so anyone capturing the traffic reads the password. Any device still offering Telnet on a management interface is an audit finding.$q$),
('n-f-448','netplus',1,'1.4','acronym',$q$SIP$q$,$q$Session Initiation Protocol - sets up, modifies and tears down voice and video calls on TCP or UDP 5060 in the clear, or 5061 with TLS. It carries only the signalling; RTP carries the actual media stream.$q$),
('n-f-449','netplus',1,'1.4','core',$q$Which ports do the mail protocols use?$q$,$q$SMTP TCP 25 for server-to-server relay, TCP 587 for authenticated client submission and TCP 465 for implicit TLS submission. POP3 TCP 110, or 995 with TLS. IMAP TCP 143, or 993 with TLS. POP3 typically downloads and removes; IMAP keeps mail on the server and syncs across devices.$q$),
('n-f-450','netplus',1,'1.4','core',$q$DNS uses port 53 - but over which transport?$q$,$q$UDP 53 for ordinary queries and responses, because a single small exchange does not justify a handshake. TCP 53 for zone transfers and for responses too large to fit reliably in one datagram. A firewall rule permitting only UDP 53 lets lookups work while silently breaking zone replication.$q$),
('n-f-451','netplus',1,'1.4','core',$q$Which ports does DHCP use, for IPv4 and for IPv6?$q$,$q$IPv4 DHCP uses UDP 67 on the server and UDP 68 on the client. DHCPv6 uses UDP 547 on the server and UDP 546 on the client. It has to be UDP and broadcast for the first exchange, because the client has no address yet - which is also why a relay agent is needed when the server is on another subnet.$q$),
('n-f-452','netplus',1,'1.4','core',$q$HTTP 80 and HTTPS 443 - what exactly does the difference buy?$q$,$q$HTTPS is HTTP carried inside a TLS session on TCP 443, adding confidentiality, integrity and server authentication through the certificate. HTTP on TCP 80 provides none of those, so credentials, cookies and page content are readable and modifiable by anything on the path.$q$),
('n-f-453','netplus',1,'1.4','core',$q$Which port does NTP use, and why does accurate time matter so much?$q$,$q$UDP 123. Without synchronised clocks, log correlation across devices becomes unreliable, Kerberos authentication fails once the skew exceeds its tolerance (five minutes by default), and certificate validity checks can wrongly succeed or fail. Time is a dependency for security, not a convenience.$q$),
('n-f-454','netplus',1,'1.4','core',$q$What are the SNMP ports, and what changed in SNMPv3?$q$,$q$UDP 161 is where the agent listens for the manager to poll it; UDP 162 is where the manager receives traps and informs sent by agents. SNMPv1 and v2c authenticate with a cleartext community string; v3 adds per-user authentication, message integrity and encryption, and is the only version that should be used on production networks.$q$),
('n-f-455','netplus',1,'1.4','core',$q$What are LDAP and LDAPS used for, and on which ports?$q$,$q$LDAP on TCP 389 queries and modifies a directory service - looking up users, groups and their attributes for authentication and authorisation. LDAPS on TCP 636 is the same thing over TLS. Directory binds carry credentials, so plain 389 without StartTLS exposes them on the wire.$q$),
('n-f-456','netplus',1,'1.4','core',$q$Which ports serve SMB, RDP, syslog and the common databases?$q$,$q$SMB TCP 445 for Windows file and printer sharing. RDP TCP 3389 for remote desktop. Syslog UDP 514 to a collector. Microsoft SQL Server TCP 1433 and MySQL TCP 3306. None of 445, 3389, 1433 or 3306 belongs open to the internet - each is a routine target for scanning and brute force.$q$),
('n-f-457','netplus',1,'1.4','core',$q$Unicast, multicast, broadcast, anycast - one line each?$q$,$q$Unicast is one to one. Multicast is one to a subscribed group (IPv4 224.0.0.0/4) and can be routed where configured. Broadcast is one to every host in the broadcast domain (255.255.255.255) and is stopped by routers. Anycast is one to nearest: many hosts share one address and routing picks the closest.$q$),
('n-f-458','netplus',1,'1.4','core',$q$Which IP protocol numbers should you recognise?$q$,$q$ICMP is 1, TCP is 6, UDP is 17, GRE is 47, ESP is 50 and AH is 51. These sit in the protocol field of the IP header, not in a port field - which is why an ACL permitting only TCP and UDP silently blocks a GRE tunnel or an ESP-protected IPSec session.$q$),
('n-f-459','netplus',1,'1.4','acronym',$q$GRE$q$,$q$Generic Routing Encapsulation - IP protocol 47, a tunnelling protocol that encapsulates almost any payload, including multicast and routing protocol traffic, but provides no encryption and so is often paired with IPSec.$q$);
