-- AWS SAA-C03 Domain 2 (Design Resilient Architectures) expansion: 2.1 scalable
-- & loosely coupled architectures (SQS/SNS, decoupling, auto scaling, load
-- balancers) gets 18 new items (8 questions + 10 flashcards); 2.2 highly
-- available / fault-tolerant architectures (already near target depth) gets
-- 6 small, genuinely non-duplicate new items (3 questions + 3 flashcards).
-- New topics not previously covered in the awssaa bank: SQS FIFO vs Standard,
-- SQS dead-letter queues/redrive policy, SNS fan-out, Gateway Load Balancer,
-- Auto Scaling policy types (target tracking/step/scheduled/predictive),
-- queue-depth-based scaling, cross-zone load balancing, Amazon MQ, SQS long
-- vs short polling, RDS automated backups/point-in-time recovery, AWS
-- Elastic Disaster Recovery (DRS), and AWS Backup centralized policies.
-- Adds questions sa-q-300..sa-q-310 (11) and flashcards sa-f-300..sa-f-308
-- (core, 9), sa-a-120..sa-a-121 (acronym, 2), sa-y-060..sa-y-061 (feynman, 2).
-- Purely additive: no existing rows are modified or deleted.

insert into public.questions (id, cert, domain, objective, qtype, difficulty, stem, choices, answer, explanation) values
('sa-q-300','awssaa',2,'2.1','mcq',1,$q$A payment-processing pipeline must ensure that each transaction message is processed exactly once and in the exact order it was submitted, even under high throughput. Which Amazon SQS queue type meets this requirement?$q$,$q$["A FIFO queue with content-based deduplication enabled","A Standard queue with a longer visibility timeout","A Standard queue with increased maximum message size","A FIFO queue with visibility timeout disabled"]$q$::jsonb,'0'::jsonb,$q$FIFO queues guarantee exactly-once processing and preserve the exact order in which messages are sent within a message group - exactly what strict ordering plus deduplication needs. Standard queues offer higher throughput but only best-effort ordering and at-least-once delivery, so duplicates and reordering remain possible regardless of visibility timeout or message size settings; disabling a FIFO queue's visibility timeout wouldn't address ordering or deduplication either.$q$),
('sa-q-301','awssaa',2,'2.1','mcq',2,$q$A worker fleet consumes messages from an SQS queue, but a small number of malformed messages keep failing processing and being returned to the queue, where they are retried indefinitely and slow down processing of valid messages. What should be configured to isolate these messages?$q$,$q$["A redrive policy that moves messages to a dead-letter queue after a maximum receive count is reached","A shorter message retention period on the queue","A FIFO queue instead of a Standard queue","A larger visibility timeout on the queue"]$q$::jsonb,'0'::jsonb,$q$A redrive policy with a maxReceiveCount sends a message to a dead-letter queue once it has failed processing that many times, pulling poison-pill messages out of the main queue so they stop consuming worker capacity and can be inspected separately. Shortening retention would eventually delete messages outright, including good ones; switching queue type doesn't fix repeated processing failures; and a longer visibility timeout only delays retries rather than isolating bad messages.$q$),
('sa-q-302','awssaa',2,'2.1','mcq',2,$q$When a new file is uploaded, the system must simultaneously trigger a Lambda function for thumbnail generation, place a message on an SQS queue for a separate audit-logging service, and send an email notification - all from a single publish action, without the publisher knowing about any of the subscribers. Which design achieves this?$q$,$q$["Publish once to an SNS topic that fans out to the Lambda function, the SQS queue, and an email subscription","Have the uploader call each of the three downstream services directly","Use a single SQS Standard queue that all three services poll simultaneously","Use a Multi-AZ RDS database as an intermediary"]$q$::jsonb,'0'::jsonb,$q$SNS fan-out lets one publish operation deliver a copy of the message to every subscriber - Lambda, SQS, email, and more - independently and in parallel, keeping the publisher decoupled from how many consumers exist or what they do. Direct calls couple the publisher to every consumer; a single queue that three unrelated services all poll would mean whichever consumer reads a message first removes it from the others; and a database isn't a pub/sub mechanism.$q$),
('sa-q-303','awssaa',2,'2.1','mcq',1,$q$A company runs a fleet of third-party virtual firewall appliances in front of its VPC traffic and needs those appliances to scale transparently with traffic volume while keeping all traffic for a given connection flowing through the same appliance instance. Which load balancer type is purpose-built for this?$q$,$q$["Gateway Load Balancer","Application Load Balancer","Classic Load Balancer","A NAT Gateway"]$q$::jsonb,'0'::jsonb,$q$Gateway Load Balancer operates at Layer 3/4 and is designed specifically to distribute traffic across a scalable fleet of third-party virtual appliances (firewalls, intrusion detection/prevention systems), using GENEVE encapsulation and flow stickiness so a given connection consistently reaches the same appliance instance. ALB works at Layer 7 for HTTP(S) applications, the Classic Load Balancer is a legacy general-purpose balancer, and a NAT Gateway only provides outbound internet access, not appliance load distribution.$q$),
('sa-q-304','awssaa',2,'2.1','matching',2,$q$Match each Auto Scaling policy type to how it decides when to add or remove capacity.$q$,$q${"left":["Target tracking scaling","Step scaling","Scheduled scaling","Predictive scaling"],"right":["Automatically adjusts capacity to keep a chosen metric, such as average CPU utilization, at a specified target value","Adds or removes different amounts of capacity in increments based on how far the alarm has been breached","Scales capacity at specific dates and times to match a known, recurring traffic pattern","Uses machine learning on historical load data to scale ahead of an anticipated demand change"]}$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$Target tracking works like a thermostat, continuously adjusting capacity to hold a metric near a target. Step scaling reacts to alarm breaches with different-sized adjustments depending on how far past the threshold the metric is. Scheduled scaling handles predictable, calendar-based patterns such as business hours. Predictive scaling forecasts future load from historical trends and provisions capacity ahead of it arriving, reducing the lag of purely reactive policies.$q$),
('sa-q-305','awssaa',2,'2.1','ordering',3,$q$Order the sequence of events when an SQS-backed worker tier is configured to scale out based on queue backlog during a sudden traffic burst.$q$,$q$["Producers publish a burst of messages faster than consumers can drain them, and the queue backlog grows","A CloudWatch alarm on the backlog-per-instance metric breaches its scale-out threshold","The Auto Scaling Group launches additional worker instances to increase consumption capacity","The larger worker fleet drains the backlog until the metric falls and the group scales back in"]$q$::jsonb,$q$[0,1,2,3]$q$::jsonb,$q$The backlog only grows once inflow outpaces existing consumer capacity; that rising backlog-per-instance metric is what trips the CloudWatch alarm; the alarm triggers the Auto Scaling Group to add workers; and once the enlarged fleet has caught up, the metric drops back below the scale-in threshold and capacity is released. Scaling on the queue itself, rather than a proxy metric like CPU, ties capacity directly to the actual amount of unprocessed work.$q$),
('sa-q-306','awssaa',2,'2.1','mcq',1,$q$An Application Load Balancer has two Availability Zones registered, with 8 healthy targets in AZ-a and 2 healthy targets in AZ-b. With cross-zone load balancing enabled, how is incoming traffic distributed?$q$,$q$["Evenly across all 10 healthy targets regardless of which AZ they are in","Evenly split 50/50 between AZ-a and AZ-b regardless of target count","All traffic goes to AZ-a because it has more targets","Traffic is rejected because the AZs are unbalanced"]$q$::jsonb,'0'::jsonb,$q$Cross-zone load balancing spreads each load balancer node's traffic evenly across all registered healthy targets in all enabled AZs, so with it enabled here, all 10 targets receive a roughly even share regardless of the 8/2 split between AZs. Without cross-zone load balancing, each AZ's traffic would instead be spread only among the targets in that AZ, giving AZ-b's 2 targets a disproportionately larger share per target.$q$),
('sa-q-307','awssaa',2,'2.1','multi',3,$q$An enterprise is migrating an on-premises application that communicates over JMS and depends on an existing ActiveMQ broker's queues and topics, and wants to lift-and-shift the messaging layer with minimal application changes. Which TWO characteristics make Amazon MQ a better fit here than building the messaging layer on SQS and SNS?$q$,$q$["Amazon MQ supports industry-standard protocols like JMS, AMQP, and MQTT that the existing application already speaks","Amazon MQ is a managed, broker-based service compatible with ActiveMQ and RabbitMQ APIs, unlike the AWS-proprietary SQS/SNS APIs","Amazon MQ has unlimited message throughput with no scaling limits of any kind","Amazon MQ eliminates the need for any application code changes when moving from any messaging system whatsoever"]$q$::jsonb,$q$[0,1]$q$::jsonb,$q$Amazon MQ is a managed message broker that speaks standard protocols (JMS, AMQP, MQTT, STOMP) and is compatible with ActiveMQ and RabbitMQ, so an application already coded against those APIs/protocols can move with minimal rework - exactly the lift-and-shift scenario described. SQS and SNS use AWS-specific APIs and would require rewriting the messaging integration. Amazon MQ is not limitless in throughput or scaling since it runs on sized broker instances, unlike the effectively unlimited horizontal scaling of SQS/SNS, and no messaging migration is entirely change-free.$q$),
('sa-q-308','awssaa',2,'2.2','mcq',1,$q$Besides a Multi-AZ standby and manually created snapshots, what does Amazon RDS provide by default to let you restore a database to any point within its backup retention window, down to the second?$q$,$q$["Automated backups with point-in-time recovery, using a daily snapshot plus continuous transaction logs","A second read replica in another region","An Application Load Balancer health check","S3 Same-Region Replication"]$q$::jsonb,'0'::jsonb,$q$RDS automated backups take a daily snapshot and continuously capture transaction logs, letting you restore to any second within the retention period (up to 35 days). This is distinct from Multi-AZ, which is about failover rather than point-in-time restore, and from manual snapshots, which only capture the single moment you explicitly took one. Read replicas serve reads or DR promotion but aren't a point-in-time-recovery mechanism, an ALB health check is unrelated to backups, and S3 SRR replicates S3 objects, not RDS databases.$q$),
('sa-q-309','awssaa',2,'2.2','mcq',2,$q$A company wants a managed service that continuously replicates its on-premises servers' disks at the block level into AWS, so that during a disaster it can launch fully provisioned, up-to-date recovery instances within minutes rather than rebuilding from periodic backups. Which service is purpose-built for this?$q$,$q$["AWS Elastic Disaster Recovery (AWS DRS)","Amazon S3 Cross-Region Replication","AWS Backup","Amazon RDS Multi-AZ"]$q$::jsonb,'0'::jsonb,$q$AWS Elastic Disaster Recovery performs continuous, block-level replication of source servers, whether on-premises or in another cloud, into a low-cost staging area in AWS, and can launch fully provisioned recovery instances within minutes during a failover, automating a pilot-light-to-warm-standby style DR pattern with low RTO/RPO. S3 CRR only replicates S3 objects, AWS Backup takes scheduled backups rather than continuous replication, and RDS Multi-AZ is a single-region database failover feature, not a general-purpose server DR replication tool.$q$),
('sa-q-310','awssaa',2,'2.2','multi',3,$q$A company currently protects its data with separate, hand-rolled scripts: one for EBS snapshots, another for RDS snapshots, and a third for DynamoDB backups, each on a different schedule and with no consistent retention or off-site copy. Which TWO benefits would migrating to a single AWS Backup policy provide?$q$,$q$["One centralized, auditable backup policy that defines schedule and retention consistently across EBS, RDS, DynamoDB, EFS, and other supported services","Built-in cross-region (and cross-account) copy of backups from a single policy, without writing separate copy scripts per service","Automatic Multi-AZ synchronous failover for every protected resource","Elimination of the need for any Recovery Time Objective or Recovery Point Objective planning"]$q$::jsonb,$q$[0,1]$q$::jsonb,$q$AWS Backup centralizes backup policy, meaning schedule, lifecycle, and retention, across many AWS services from one place, replacing per-service scripts with consistent, auditable rules, and it can automatically copy backups to another region or account for DR and compliance without custom tooling. It does not provide Multi-AZ failover, which is a separate, service-specific availability feature, and it doesn't remove the need to plan RTO/RPO - it's a tool for meeting whatever targets you set, not a substitute for setting them.$q$);

insert into public.flashcards (id, cert, deck, domain, objective, front, back) values
('sa-f-300','awssaa','core',2,'2.1',$$SQS FIFO queue vs Standard queue - when do you need each?$$,$$FIFO: exactly-once processing and strict message-group ordering, at the cost of lower throughput (up to 3,000 msg/sec with batching). Standard: nearly unlimited throughput with at-least-once delivery and best-effort ordering. Use FIFO when order or duplicate-prevention is a correctness requirement, such as financial transactions; use Standard for high-volume workloads that can tolerate occasional duplicates or reordering.$$),
('sa-f-301','awssaa','core',2,'2.1',$$What does an SQS redrive policy with a dead-letter queue (DLQ) do?$$,$$After a message fails processing (is received but not deleted) maxReceiveCount times, SQS automatically moves it to a separate dead-letter queue instead of retrying it forever. This isolates poison-pill messages so they stop consuming worker capacity and can be inspected or reprocessed separately.$$),
('sa-f-302','awssaa','core',2,'2.1',$$What is the SNS fan-out pattern?$$,$$Publishing a single message to an SNS topic that delivers a copy to every subscriber - SQS queues, Lambda functions, HTTP endpoints, email, and more - in parallel. The publisher stays decoupled from how many consumers exist or what each one does with the message.$$),
('sa-f-303','awssaa','core',2,'2.1',$$What are the four Auto Scaling policy types and how do they differ?$$,$$Target tracking keeps a chosen metric near a set value, like a thermostat. Step scaling adds or removes varying capacity based on how far an alarm is breached. Scheduled scaling changes capacity at set times for known patterns. Predictive scaling uses machine learning on historical data to provision ahead of forecasted demand, reducing reactive lag.$$),
('sa-f-304','awssaa','core',2,'2.1',$$What does enabling cross-zone load balancing change about traffic distribution?$$,$$Without it, each load balancer node only distributes traffic among targets in its own AZ, so an AZ with fewer targets gives each target a disproportionate share. With cross-zone load balancing enabled, traffic is spread evenly across all healthy targets in all enabled AZs, regardless of how many targets are in each AZ.$$),
('sa-f-305','awssaa','core',2,'2.1',$$When should you choose Amazon MQ over SQS/SNS for messaging?$$,$$Amazon MQ is a managed broker supporting standard protocols (JMS, AMQP, MQTT, STOMP) and is API-compatible with ActiveMQ/RabbitMQ, making it the better fit when migrating an existing application that already depends on those protocols or APIs. SQS/SNS use AWS-proprietary APIs and scale further, so they're preferred for new, cloud-native decoupled designs.$$),
('sa-f-306','awssaa','core',2,'2.1',$$SQS short polling vs long polling - what's the difference?$$,$$Short polling returns immediately even if the queue is empty, and may not check every server, so it can miss messages and burns more requests. Long polling waits, up to 20 seconds, for a message to arrive before returning, reducing empty responses, API calls and cost, and false-empty results - long polling is the recommended default.$$),
('sa-f-307','awssaa','core',2,'2.2',$$How do RDS automated backups differ from a Multi-AZ standby and from manual snapshots?$$,$$Automated backups take a daily snapshot plus continuous transaction logs, enabling point-in-time recovery to any second within the retention window (up to 35 days). Multi-AZ is a live synchronous standby for fast failover, not a point-in-time restore mechanism. Manual snapshots capture only the single moment you took them and are retained until you delete them.$$),
('sa-f-308','awssaa','core',2,'2.2',$$What does AWS Elastic Disaster Recovery (AWS DRS) do?$$,$$Continuously replicates source servers, whether on-premises, other clouds, or other AWS regions, at the block level into a low-cost staging area in AWS, then can launch fully provisioned recovery instances within minutes during a failover - automating a pilot-light or warm-standby style DR strategy with low RTO/RPO.$$),
('sa-a-120','awssaa','acronym',2,'2.1',$$DLQ$$,$$Dead-Letter Queue - holds messages that repeatedly fail processing so they stop blocking the main queue and can be investigated separately.$$),
('sa-a-121','awssaa','acronym',2,'2.1',$$GWLB$$,$$Gateway Load Balancer - Layer 3/4 load balancer for transparently scaling third-party virtual appliances such as firewalls and intrusion detection systems.$$),
('sa-y-060','awssaa','feynman',2,'2.1',$$Explain why scaling a worker fleet on SQS queue backlog is a better loose-coupling practice than scaling only on CPU utilization.$$,$$Model answer: CPU utilization tells you how busy the workers you already have are, but it says nothing about how much unprocessed work is waiting - a fleet could be at low CPU because it's starved for messages, or work could be piling up in the queue while CPU looks moderate because each message is I/O-bound. Scaling on the queue's backlog-per-instance metric ties capacity directly to the actual amount of undone work: as producers publish faster than consumers drain, the backlog rises, an alarm fires, and the Auto Scaling Group adds exactly the consumers needed to catch up. That keeps producers and consumers genuinely decoupled, because producers never need to know or care how many consumers exist - the queue depth itself is the signal that governs consumer capacity.$$),
('sa-y-061','awssaa','feynman',2,'2.2',$$Explain why centralizing backups under a single AWS Backup policy reduces disaster-recovery risk compared to separate per-service snapshot scripts.$$,$$Model answer: When EBS, RDS, and DynamoDB each have their own hand-written backup script, you end up with different schedules, different retention periods, and no single place to verify that everything is actually protected - it's easy for one script to silently break while the others keep running, and nobody notices until a restore is needed. A single AWS Backup policy defines schedule, lifecycle, and retention once, applies it consistently across every supported resource, and gives one auditable place to confirm coverage and add cross-region copy for off-site protection. It doesn't change the underlying RTO/RPO math, but it removes the operational risk of inconsistent, unmonitored, hand-rolled backup tooling.$$);
